# Generated by Django 2.0.12 on 2019-06-26 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import w3.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0018_country_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('programme_type', enumfields.fields.EnumIntegerField(enum=w3.models.ProgrammeTypes)),
                ('sector', enumfields.fields.EnumIntegerField(enum=w3.models.Sectors)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget_amount', models.IntegerField()),
                ('budget_currency', enumfields.fields.EnumField(enum=w3.models.Currencies, max_length=4)),
                ('status', enumfields.fields.EnumIntegerField(enum=w3.models.Statuses)),
                ('project_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.District')),
                ('reporting_ns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
