# Generated by Django 2.2.25 on 2022-01-11 11:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import informal_update.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0138_auto_20220105_0543'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformalAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='name')),
                ('organizations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NTLS', 'National Society'), ('PNS', 'Foreign Society'), ('FDRN', 'Federation'), ('GOV', 'Government')], max_length=4), blank=True, default=list, size=None, verbose_name='organizations')),
                ('informal_update_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EVT', 'Event'), ('EW', 'Early Warning'), ('EPI', 'Epidemic'), ('COVID', 'COVID-19')], max_length=16), default=list, size=None, verbose_name='informal update types')),
                ('category', models.CharField(choices=[('General', 'General'), ('Health', 'Health'), ('NS Institutional Strengthening', 'NS Institutional Strengthening'), ('Socioeconomic Interventions', 'Socioeconomic Interventions')], default='General', max_length=255, verbose_name='category')),
                ('is_disabled', models.BooleanField(default=False, help_text='Disable in form', verbose_name='is disabled?')),
                ('tooltip_text', models.TextField(blank='true', null=True, verbose_name='tooltip text')),
            ],
            options={
                'verbose_name': 'informal action',
                'verbose_name_plural': 'informal actions',
            },
        ),
        migrations.CreateModel(
            name='InformalGraphicMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='informal_update/images/', verbose_name='file')),
                ('caption', models.CharField(blank=True, max_length=225, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
            ],
            options={
                'verbose_name': 'informal graphic map',
                'verbose_name_plural': 'informal graphic maps',
            },
        ),
        migrations.CreateModel(
            name='InformalReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, verbose_name='date')),
                ('source_description', models.CharField(blank=True, max_length=225, verbose_name='Name or Source Description')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informal_document', to='informal_update.InformalGraphicMap', verbose_name='document')),
            ],
            options={
                'verbose_name': 'informal reference',
                'verbose_name_plural': 'informal references',
            },
        ),
        migrations.CreateModel(
            name='ReferenceUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='InformalUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=300)),
                ('situational_overview', models.TextField(verbose_name='Situational Overview')),
                ('originator_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='originator_name')),
                ('originator_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='originator_title')),
                ('originator_email', models.CharField(blank=True, max_length=300, null=True, verbose_name='originator_email')),
                ('originator_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='originator_phone')),
                ('ifrc_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ifrc_name')),
                ('ifrc_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='ifrc_title')),
                ('ifrc_email', models.CharField(blank=True, max_length=300, null=True, verbose_name='ifrc_email')),
                ('ifrc_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='ifrc_phone')),
                ('share_with', models.CharField(choices=[('ifrc_secretariat', 'IFRC Secretariat'), ('rcrc_network', 'RCRC Network'), ('rcrc_network_and_donors', 'RCRC Network and Donors')], default=informal_update.models.InformalUpdate.InformalShareWith('ifrc_secretariat'), max_length=50, verbose_name='share with')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informal_update_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('graphics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informal_graphics', to='informal_update.InformalGraphicMap', verbose_name='graphics')),
                ('hazard_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informal_update_hazard_type', to='api.DisasterType', verbose_name='hazard type')),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informal_map', to='informal_update.InformalGraphicMap', verbose_name='map')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informal_update_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('references', models.ManyToManyField(blank=True, to='informal_update.InformalReferences', verbose_name='references')),
            ],
            options={
                'verbose_name': 'Informal update',
                'verbose_name_plural': 'Informal updates',
            },
        ),
        migrations.AddField(
            model_name='informalreferences',
            name='url',
            field=models.ManyToManyField(blank=True, to='informal_update.ReferenceUrls', verbose_name='Add url'),
        ),
        migrations.CreateModel(
            name='InformalActionsTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(choices=[('NTLS', 'National Society'), ('PNS', 'Foreign Society'), ('FDRN', 'Federation'), ('GOV', 'Government')], max_length=16, verbose_name='organization')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('actions', models.ManyToManyField(blank=True, to='informal_update.InformalAction', verbose_name='actions')),
                ('informal_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_taken_informal', to='informal_update.InformalUpdate', verbose_name='informal update')),
            ],
            options={
                'verbose_name': 'actions taken informal',
                'verbose_name_plural': 'all actions taken informal',
            },
        ),
        migrations.CreateModel(
            name='InformalCountryDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informal_country', to='api.Country', verbose_name='country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informal_district', to='api.District', verbose_name='district')),
                ('informal_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informal_update.InformalUpdate', verbose_name='informal update')),
            ],
            options={
                'verbose_name': 'informal country district',
                'verbose_name_plural': 'informal countries districts',
                'unique_together': {('informal_update', 'country')},
            },
        ),
    ]
