# Generated by Django 2.2.25 on 2022-01-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informalupdate',
            name='situational_overview_ar',
            field=models.TextField(null=True, verbose_name='Situational Overview'),
        ),
        migrations.AddField(
            model_name='informalupdate',
            name='situational_overview_en',
            field=models.TextField(null=True, verbose_name='Situational Overview'),
        ),
        migrations.AddField(
            model_name='informalupdate',
            name='situational_overview_es',
            field=models.TextField(null=True, verbose_name='Situational Overview'),
        ),
        migrations.AddField(
            model_name='informalupdate',
            name='situational_overview_fr',
            field=models.TextField(null=True, verbose_name='Situational Overview'),
        ),
        migrations.AddField(
            model_name='informalupdate',
            name='title_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='informalupdate',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='informalupdate',
            name='title_es',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='informalupdate',
            name='title_fr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.RemoveField(
            model_name='informalupdate',
            name='graphics',
        ),
        migrations.AddField(
            model_name='informalupdate',
            name='graphics',
            field=models.ManyToManyField(blank=True, related_name='informal_graphics', to='informal_update.InformalGraphicMap', verbose_name='graphics'),
        ),
        migrations.RemoveField(
            model_name='informalupdate',
            name='map',
        ),
        migrations.AddField(
            model_name='informalupdate',
            name='map',
            field=models.ManyToManyField(blank=True, related_name='informal_map', to='informal_update.InformalGraphicMap', verbose_name='map'),
        ),
    ]
