# Generated by Django 2.2.25 on 2021-12-29 05:57

from django.db import migrations, models
import informal_update.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informalupdate',
            name='share_with',
            field=models.CharField(choices=[('ifrc_secretariat', 'IFRC Secretariat'), ('rcrc_network', 'RCRC Network'), ('rcrc_network_and_donors', 'RCRC Network and Donors')], default=informal_update.models.InformalUpdate.InformalShareWith('ifrc_secretariat'), max_length=50, verbose_name='share with'),
        ),
    ]
