# Generated by Django 2.2.25 on 2022-01-05 05:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informalaction',
            name='organizations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NTLS', 'National Society'), ('PNS', 'Foreign Society'), ('FDRN', 'Federation'), ('GOV', 'Government')], max_length=4), blank=True, default=list, size=None, verbose_name='organizations'),
        ),
        migrations.AlterField(
            model_name='informalactionstaken',
            name='organization',
            field=models.CharField(choices=[('NTLS', 'National Society'), ('PNS', 'Foreign Society'), ('FDRN', 'Federation'), ('GOV', 'Government')], max_length=16, verbose_name='organization'),
        ),
    ]
