# Generated by Django 2.2.25 on 2022-02-08 11:18

from django.db import migrations, models
import django.utils.timezone
import informal_update.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_update', '0005_auto_20220126_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informalemailsubscriptions',
            name='share_with',
            field=models.CharField(choices=[('ifrc_secretariat', 'IFRC Secretariat'), ('rcrc_network', 'RCRC Network'), ('rcrc_network_and_donors', 'RCRC Network and Donors')], default=informal_update.models.InformalUpdate.InformalShareWith('ifrc_secretariat'), max_length=50, verbose_name='share with'),
        ),
        migrations.AlterField(
            model_name='informalgraphicmap',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='informal_update/images/', verbose_name='file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informalupdate',
            name='share_with',
            field=models.CharField(blank=True, choices=[('ifrc_secretariat', 'IFRC Secretariat'), ('rcrc_network', 'RCRC Network'), ('rcrc_network_and_donors', 'RCRC Network and Donors')], max_length=50, null=True, verbose_name='share with'),
        ),
    ]
