# Generated by Django 2.2.26 on 2022-02-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informal_update', '0007_auto_20220216_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informalemailsubscriptions',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informal_email_subscription', to='auth.Group'),
        ),
    ]
