default_language_version:
  python: python3

# NOTE: Update in .flake8 pyproject.toml as well
exclude: |
    (?x)^(
      \.git|
      __pycache__|
      .+\/.+\/migrations\/.*|
      legacy|
      \.venv
    )

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff
