# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

resources:
  repositories:
  - repository: go-api
    type: github
    endpoint: developmentseed
    name: developmentseed/go-api
    ref: azure-pipelines

pool:
  vmImage: ubuntu-latest

jobs:
- job: 'helloWorld'
  steps:
  - bash: echo "Hello World"

- job: 'Build'
  steps:
  - checkout: go-api
    path: go-api

  - bash: pip install -v chartpress
  - task: Docker@2
    inputs:
      containerRegistry: 'ifrcgotestacr'
      command: 'login'

  - bash: $(Pipeline.Workspace)/go-api/deploy/scripts/cipublish
