version: '2'

services:
  
  base:
    build: .
    image: developmentseed/ifrc-go-api:latest
    entrypoint: /bin/bash
    #env_file: .env
    volumes:
      - '.:/home/ifrc/work'

  test:
    image: developmentseed/ifrc-go-api:latest
    working_dir: /home/ifrc/work
    entrypoint: bash -c './manage.py migrate; ./manage.py test'
    #env_file: .env
    volumes:
      - '.:/home/ifrc/work'
