class Sectors:
    people_targeted = 'peopleTargeted'
    people_reached = 'peopleReached'
    male = 'male'
    female = 'female'
    requirements = 'requirements'


class MetaFields:
    operation_num = 'operationNumber'
    appeal_num = 'appealNumber'
    glide_num = 'glideNumber'
    date_of_issue = 'dateOfIssue'
    appeal_launch_date = 'appealLaunchDate'
    expected_time_frame = 'expectedTimeFrame'
    expected_end_date = 'expectedEndDate'
    category_allocated = 'categoryAllocated'
    dref_allocated = 'drefAllocated'
    total_num_of_people_affected = 'totalNumberOfPeopleAffected'
    num_of_people_to_be_assisted = 'numOfPeopleToBeAssisted'
    epoa_update_num = 'epoaUpdateNumber'
    time_frame_covered_by_update = 'timeFrameCoveredByUpdate'
    operation_start_date = 'operationStartDate'
    operation_end_date = 'operationEndDate'
    operation_timeframe = 'operationTimeframe'
    date_of_disaster = 'dateOfDisaster'
    operation_budget = 'operationBudget'
    num_of_people_being_affected = 'numOfPeopleBeingAffected'
    num_of_people_being_assisted = 'numOfPeopleBeingAssisted'
    num_of_partner_ns_involved = 'numOfPartnerNsInvolved'
    num_of_other_partner_involved = 'numOfOtherPartnerInvolved'
    current_appeal_budget = 'currentAppealBudget'
    appeal_launch = 'appealLaunch'
    appeal_end = 'appealEnd'
    revision_number = 'revisionNumber'
    extended_months = 'extendedMonths'
