# Generated by Django 3.2.16 on 2022-11-23 08:51

import country_plan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_plan', '0002_alter_strategicpriority_sp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryplan',
            name='role_of_national_society',
        ),
        migrations.RemoveField(
            model_name='countryplan',
            name='situation_analysis',
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='file',
            field=models.FileField(upload_to=country_plan.models.file_upload_to, verbose_name='EXCEL file'),
        ),
        migrations.AlterField(
            model_name='membershipcoordination',
            name='strategic_priority',
            field=models.CharField(blank=True, choices=[('climate', 'Climate'), ('crisis', 'Crisis'), ('health', 'Health'), ('migration', 'Migration'), ('inclusion', 'Inclusion'), ('engaged', 'Engaged'), ('accountable', 'Accountable'), ('trusted', 'Trusted')], max_length=100, null=True, verbose_name='Strategic Priority'),
        ),
    ]
