# Generated by Django 3.2.16 on 2022-11-23 09:31

import country_plan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_plan', '0003_auto_20221123_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryplan',
            name='internal_plan_file',
            field=models.FileField(blank=True, null=True, upload_to=country_plan.models.pdf_upload_to, verbose_name='Internal Plan'),
        ),
        migrations.AlterField(
            model_name='countryplan',
            name='public_plan_file',
            field=models.FileField(blank=True, null=True, upload_to=country_plan.models.pdf_upload_to, verbose_name='Country Plan'),
        ),
    ]
