{{- range $i, $job := .Values.cronjobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "ifrcgo-helm.fullname" $ }}-{{ $job.command | trunc 8 | nospace | lower | replace "_" "-" }}-{{ $i }}
  labels:
    component: api-jobs
    environment: {{ $.Values.environment }}
    release: {{ $.Release.Name }}
spec:
  schedule: {{ $job.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: {{ template "ifrcgo-helm.fullname" $ }}-{{ $job.command | trunc 8 | nospace | lower | replace "_" "-" }}-{{ $i }}
              image: "{{ $.Values.api.image.name }}:{{ $.Values.api.image.tag }}"
              command: ["python", "/home/ifrc/go-api/manage.py", "{{ $job.command }}"]
              #FIXME: add resources
              envFrom:
                - secretRef:
                    name: {{ template "ifrcgo-helm.fullname" $ }}-api-secret
                - configMapRef:
                    name: {{ template "ifrcgo-helm.fullname" $ }}-api-configmap
              #FIXME: Add onFailure policy, retries, etc.
{{- end }}