# Generated by Django 3.2.16 on 2022-12-22 15:12

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0160_merge_0159_auto_20221022_1542_0159_auto_20221028_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=6, verbose_name='Unique ID')),
                ('national_society_name', models.CharField(max_length=255, verbose_name='National Society Name')),
                ('local_branch_name', models.CharField(max_length=255, verbose_name='Branch name in local language')),
                ('english_branch_name', models.CharField(max_length=255, verbose_name='Branch name in English')),
                ('branch_level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Branch Level')),
                ('branch_type_name', models.CharField(max_length=100, verbose_name='Branch type name')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('draft', models.BooleanField(default=False, verbose_name='Draft')),
                ('validated', models.BooleanField(default=True, verbose_name='Validated')),
                ('source', models.CharField(max_length=255, verbose_name='Source')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('post_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('phone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('link', models.CharField(max_length=255, verbose_name='Social link')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_unit_country', to='api.country', verbose_name='Country')),
            ],
        ),
    ]
