# Generated by Django 3.2.17 on 2023-02-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localunit',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Validated'),
        ),
    ]
