# Generated by Django 3.2.25 on 2024-04-16 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_units', '0007_auto_20240330_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localunit',
            name='data_source_id',
        ),
        migrations.AlterModelOptions(
            name='localunitlevel',
            options={'verbose_name': 'Local unit coverage', 'verbose_name_plural': 'Local unit coverages'},
        ),
    ]
