# Generated by Django 3.2.25 on 2024-05-06 06:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('local_units', '0010_alter_localunit_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localunit',
            name='date_of_data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of data collection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localunit',
            name='english_branch_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch name in English'),
        ),
        migrations.AlterField(
            model_name='localunit',
            name='health',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_data', to='local_units.healthdata', verbose_name='Health Data'),
        ),
        migrations.AlterField(
            model_name='localunit',
            name='local_branch_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch name in local language'),
        ),
        migrations.AlterField(
            model_name='localunit',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='localunit',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='local_unit_type', to='local_units.localunittype', verbose_name='Type'),
            preserve_default=False,
        ),
    ]
