# Generated by Django 3.2.25 on 2024-05-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_units', '0011_auto_20240506_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='affiliation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='health_affiliation', to='local_units.affiliation', verbose_name='Affiliation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='functionality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='health_functionality', to='local_units.functionality', verbose_name='Functionality'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='health_facility_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='health_facility_type', to='local_units.facilitytype', verbose_name='Health facility type'),
            preserve_default=False,
        ),
    ]
