# Generated by Django 4.2.16 on 2024-11-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local_units", "0018_localunit_is_deprecated_localunit_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="localunitchangerequest",
            name="depricated_reason",
            field=models.IntegerField(
                choices=[
                    (1, "Non-existent local unit"),
                    (2, "Incorrectly added local unit"),
                    (3, "Security concerns"),
                    (4, "Other"),
                ],
                default=4,
                verbose_name="Depricated reason",
            ),
        ),
    ]
