# Generated by Django 4.2.17 on 2024-12-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local_units", "0018_localunit_deprecated_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="localunit",
            name="last_sent_validator_type",
            field=models.IntegerField(
                choices=[(1, "Local"), (2, "Regional"), (3, "Global")], default=1, verbose_name="Last email sent validator type"
            ),
        ),
    ]
