# Generated by Django 4.2.19 on 2025-08-12 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import main.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0220_event_ifrc_severity_level_update_date_and_more"),
        ("local_units", "0020_alter_localunit_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="localunit",
            name="is_new_local_unit",
            field=models.BooleanField(default=False, verbose_name="Is New Local Unit?"),
        ),
        migrations.AddField(
            model_name="localunit",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Validated"), (2, "Unvalidated"), (3, "Pending Edit Validation")],
                default=2,
                verbose_name="Validation Status",
            ),
        ),
        migrations.AddField(
            model_name="localunit",
            name="update_reason_overview",
            field=models.TextField(blank=True, null=True, verbose_name="Explain the reason why the local unit is being updated"),
        ),
        migrations.CreateModel(
            name="LocalUnitBulkUpload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("success_count", models.PositiveIntegerField(default=0, verbose_name="Success Count")),
                ("failed_count", models.PositiveIntegerField(default=0, verbose_name="Failed Count")),
                ("file_size", models.PositiveIntegerField(default=0, verbose_name="File Size")),
                ("status", models.IntegerField(choices=[(1, "Success"), (2, "Failed"), (3, "Pending")], verbose_name="Status")),
                ("triggered_at", models.DateTimeField(auto_now_add=True, verbose_name="Triggered At")),
                ("file", main.fields.SecureFileField(upload_to="local_unit/bulk_uploads/", verbose_name="Uploaded File")),
                (
                    "error_file",
                    main.fields.SecureFileField(
                        blank=True, null=True, upload_to="local_unit/bulk_upload_errors/", verbose_name="Error File"
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="Error Message")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_upload_local_unit_country",
                        to="api.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "local_unit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_upload_local_unit_type",
                        to="local_units.localunittype",
                        verbose_name="Local Unit Type",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_by_bulk_upload",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Triggered By",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternallyManagedLocalUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="externally_managed_local_unit_country",
                        to="api.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_external_local_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "local_unit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="externally_managed_local_unit_type",
                        to="local_units.localunittype",
                        verbose_name="Type",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_external_local_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="localunit",
            name="bulk_upload",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulk_upload_local_unit",
                to="local_units.localunitbulkupload",
                verbose_name="Bulk Upload Local Unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="externallymanagedlocalunit",
            constraint=models.UniqueConstraint(fields=("country", "local_unit_type"), name="unique_country_local_unit_type"),
        ),
    ]
