# Generated by Django 4.2.19 on 2025-08-12 21:39

from django.db import migrations


def migrate_validated_to_status(apps, schema_editor):
    """
    Update all validated field values to corresponding status values
    """
    LocalUnit = apps.get_model("local_units", "LocalUnit")
    LocalUnit.objects.filter(validated=True).update(status=1)  # 1 for Validated
    LocalUnit.objects.filter(validated=False).update(status=2)  # 2 for Unvalidated


class Migration(migrations.Migration):

    dependencies = [
        ("local_units", "0021_localunit_is_new_local_unit_localunit_status_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_validated_to_status,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
