# Generated by Django 4.2.19 on 2025-07-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("local_units", "0021_localunit_update_reason_overview_and_more"),
        ("local_units", "0021_localunitbulkupload_localunit_bulk_upload"),
    ]

    operations = []
