# Generated by Django 4.2.19 on 2025-08-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local_units", "0022_localunit_is_new_local_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="localunit",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Validated"), (2, "Unvalidated"), (3, "Pending Edit Validation")],
                default=2,
                verbose_name="Validation Status",
            ),
        ),
    ]
