# Generated by Django 4.2.19 on 2025-09-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local_units", "0022_localunit_status_migrate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localunit",
            name="is_locked",
        ),
        migrations.RemoveField(
            model_name="localunit",
            name="is_new_local_unit",
        ),
        migrations.RemoveField(
            model_name="localunit",
            name="validated",
        ),
        migrations.AlterField(
            model_name="localunit",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Validated"), (2, "Unvalidated"), (3, "Pending Edit Validation"), (4, "Externally Managed")],
                default=2,
                verbose_name="Validation Status",
            ),
        ),
    ]
