# Generated by Django 4.2.19 on 2025-08-07 06:23

from django.db import migrations, models


def migrate_validated_to_status(apps, schema_editor):
    """
    Update all validated field values to corresponding status values
    """
    LocalUnit = apps.get_model("local_units", "LocalUnit")
    LocalUnit.objects.filter(validated=True).update(status=1)
    LocalUnit.objects.filter(validated=False).update(status=2)


class Migration(migrations.Migration):

    dependencies = [
        ("local_units", "0022_localunit_is_new_local_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="localunit",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Validated"), (2, "Unvalidated"), (3, "Pending Edit Validation")],
                default=2,
                verbose_name="Validation Status",
            ),
        ),
        migrations.RunPython(
            migrate_validated_to_status,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
