# Generated by Django 4.2.19 on 2025-10-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_units', '0023_remove_localunit_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(verbose_name='Position')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
            ],
            options={
                'verbose_name': 'Other Profile',
                'verbose_name_plural': 'Other Profiles',
            },
        ),
        migrations.AddField(
            model_name='healthdata',
            name='other_training_facilities',
            field=models.TextField(blank=True, null=True, verbose_name='Other Training Facilities'),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='pharmacists',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pharmacists'),
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='other_profiles',
        ),
        migrations.AddField(
            model_name='healthdata',
            name='other_profiles',
            field=models.ManyToManyField(blank=True, related_name='health_data_other_profile', to='local_units.otherprofile', verbose_name='Other Profiles'),
        ),
    ]
