# Generated by Django 4.2.19 on 2025-08-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local_units", "0023_merge_20250727_0858"),
    ]

    operations = [
        migrations.AddField(
            model_name="localunitbulkupload",
            name="error_message",
            field=models.TextField(blank=True, null=True, verbose_name="Error Message"),
        ),
    ]
