# Generated by Django 4.2.19 on 2025-11-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(100, 'GDACS Flood'), (200, 'GDACS Cyclone'), (300, 'USGS Earthquake')], help_text='Type of disaster data connector', unique=True, verbose_name='Connector Type')),
                ('status', models.IntegerField(choices=[(10, 'Initialized'), (20, 'Success'), (30, 'Failed'), (40, 'Running')], default=10, help_text='Current status of the connector', verbose_name='Status')),
                ('source_url', models.URLField(help_text='Base URL for the STAC API endpoint', verbose_name='Source URL')),
                ('last_success_run', models.DateTimeField(blank=True, help_text='Timestamp of the last successful data fetch', null=True, verbose_name='Last Successful Run')),
                ('filter_hazard', models.JSONField(blank=True, default=dict, help_text='JSON filters to apply when fetching hazard data', verbose_name='Hazard Filter')),
                ('filter_impact', models.JSONField(blank=True, default=dict, help_text='JSON filters to apply when fetching impact data', verbose_name='Impact Filter')),
                ('filter_event', models.JSONField(blank=True, default=dict, help_text='JSON filters to apply when fetching event data', verbose_name='Event Filter')),
            ],
            options={
                'verbose_name': 'Connector',
                'verbose_name_plural': 'Connectors',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='StacItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stac_id', models.CharField(db_index=True, help_text='Unique identifier for the event item', max_length=255, unique=True, verbose_name='Event ID')),
                ('collection', models.IntegerField(choices=[(100, 'Impacts'), (200, 'Hazard'), (300, 'Impact')], help_text='Collection type of the item', verbose_name='Collection')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('resp_data', models.JSONField(blank=True, help_text='Raw JSON response from the STAC API', null=True, verbose_name='Response Data')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for internal use', verbose_name='Metadata')),
                ('correlation_id', models.CharField(help_text='Correlation identifier linking all models', max_length=255, verbose_name='Correlation ID')),
                ('cluster', models.CharField(blank=True, help_text='Cluster classification of the hazard', max_length=255, null=True, verbose_name='Cluster')),
                ('estimate_type', models.CharField(blank=True, help_text='Type of severity estimate (e.g., preliminary, confirmed)', max_length=255, null=True, verbose_name='Estimate Type')),
                ('severity_unit', models.CharField(blank=True, help_text='Unit of measurement for severity', max_length=100, null=True, verbose_name='Severity Unit')),
                ('severity_label', models.CharField(blank=True, help_text='Human-readable severity label (e.g., Red, Orange, Green)', max_length=255, null=True, verbose_name='Severity Label')),
                ('severity_value', models.IntegerField(blank=True, help_text='Human-readable severity value', null=True, verbose_name='Severity Value')),
                ('category', models.CharField(blank=True, help_text='The category of the impact', max_length=255, null=True, verbose_name='Category')),
                ('type', models.CharField(blank=True, help_text='The type of the impact', max_length=255, null=True, verbose_name='type')),
                ('value', models.IntegerField(blank=True, help_text='Value of the associated type', null=True, verbose_name='Value')),
                ('processed', models.BooleanField(default=False)),
                ('connector', models.ForeignKey(help_text='Data source connector', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='alert_system.connector', verbose_name='Connector')),
            ],
            options={
                'verbose_name': 'Stac Item',
                'verbose_name_plural': 'Stac Items',
            },
        ),
        migrations.CreateModel(
            name='EligibleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stac_id', models.CharField(db_index=True, help_text='Unique identifier for the event item', max_length=255, unique=True, verbose_name='Event ID')),
                ('collection', models.IntegerField(choices=[(100, 'Impacts'), (200, 'Hazard'), (300, 'Impact')], help_text='Collection type of the item', verbose_name='Collection')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('resp_data', models.JSONField(blank=True, help_text='Raw JSON response from the STAC API', null=True, verbose_name='Response Data')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for internal use', verbose_name='Metadata')),
                ('correlation_id', models.CharField(help_text='Correlation identifier linking all models', max_length=255, verbose_name='Correlation ID')),
                ('cluster', models.CharField(blank=True, help_text='Cluster classification of the hazard', max_length=255, null=True, verbose_name='Cluster')),
                ('estimate_type', models.CharField(blank=True, help_text='Type of severity estimate (e.g., preliminary, confirmed)', max_length=255, null=True, verbose_name='Estimate Type')),
                ('severity_unit', models.CharField(blank=True, help_text='Unit of measurement for severity', max_length=100, null=True, verbose_name='Severity Unit')),
                ('severity_label', models.CharField(blank=True, help_text='Human-readable severity label (e.g., Red, Orange, Green)', max_length=255, null=True, verbose_name='Severity Label')),
                ('severity_value', models.IntegerField(blank=True, help_text='Human-readable severity value', null=True, verbose_name='Severity Value')),
                ('category', models.CharField(blank=True, help_text='The category of the impact', max_length=255, null=True, verbose_name='Category')),
                ('type', models.CharField(blank=True, help_text='The type of the impact', max_length=255, null=True, verbose_name='type')),
                ('value', models.IntegerField(blank=True, help_text='Value of the associated type', null=True, verbose_name='Value')),
                ('connector', models.ForeignKey(help_text='Data source connector', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='alert_system.connector', verbose_name='Connector')),
            ],
            options={
                'verbose_name': 'Eligible Item',
                'verbose_name_plural': 'Eligible Items',
            },
        ),
    ]
