# Generated by Django 4.2.26 on 2025-11-28 06:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(100, 'GDACS Flood'), (200, 'GDACS Cyclone'), (300, 'USGS Earthquake')], help_text='Type of disaster data connector', unique=True, verbose_name='Connector Type')),
                ('status', models.IntegerField(choices=[(10, 'Initialized'), (20, 'Success'), (30, 'Failed'), (40, 'Running')], default=10, help_text='Current status of the connector', verbose_name='Status')),
                ('source_url', models.URLField(help_text='Base URL for the STAC API endpoint', verbose_name='Source URL')),
                ('last_success_run', models.DateTimeField(blank=True, help_text='Timestamp of the last successful data fetch', null=True, verbose_name='Last Successful Run')),
            ],
            options={
                'verbose_name': 'Connector',
                'verbose_name_plural': 'Connectors',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='LoadItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('correlation_id', models.CharField(help_text='Correlation identifier linking all models', max_length=255, verbose_name='Correlation ID')),
                ('event_title', models.CharField(help_text='Title of the event', max_length=255, verbose_name='Event Title')),
                ('event_description', models.TextField(help_text='Description of the event', verbose_name='Event Description')),
                ('country', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), help_text='Country of the item', null=True, size=None)),
                ('severity_unit', models.CharField(blank=True, help_text='Unit of measurement for severity', max_length=100, null=True, verbose_name='Severity Unit')),
                ('severity_label', models.CharField(blank=True, help_text='Human-readable severity label (e.g., Red, Orange, Green)', max_length=255, null=True, verbose_name='Severity Label')),
                ('severity_value', models.IntegerField(blank=True, help_text='Human-readable severity value', null=True, verbose_name='Severity Value')),
                ('total_people_exposed', models.IntegerField(help_text='Total number of people exposed to event', verbose_name='Total People Exposed')),
                ('total_buildings_exposed', models.IntegerField(help_text='Total number of buildings exposed to event', verbose_name='Total Buildings Exposed')),
                ('impact_metadata', models.JSONField(help_text='Metadata constructed from all events associated', verbose_name='Impact Metadata')),
                ('item_eligible', models.BooleanField(help_text='Is the item eligible for alerting')),
                ('connector', models.ForeignKey(help_text='Data source connector', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='alert_system.connector', verbose_name='Connector')),
            ],
            options={
                'verbose_name': 'Eligible Item',
                'verbose_name_plural': 'Eligible Items',
            },
        ),
        migrations.CreateModel(
            name='ExtractionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('correlation_id', models.CharField(help_text='Correlation identifier linking all models', max_length=255, verbose_name='Correlation ID')),
                ('collection', models.IntegerField(choices=[(100, 'Impacts'), (200, 'Hazard'), (300, 'Impact')], help_text='Collection type of the item', verbose_name='Collection')),
                ('stac_id', models.CharField(db_index=True, help_text='Unique identifier for the event item', max_length=255, unique=True, verbose_name='Event ID')),
                ('resp_data', models.JSONField(blank=True, help_text='Raw JSON response from the STAC API', null=True, verbose_name='Response Data')),
                ('connector', models.ForeignKey(help_text='Data source connector', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='alert_system.connector', verbose_name='Connector')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
