# Generated by Django 4.2.26 on 2026-02-09 08:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0227_alter_eventseveritylevelhistory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0016_alertsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(100, 'GDACS Flood'), (200, 'GDACS Cyclone'), (300, 'USGS Earthquake')], help_text='Type of disaster data connector', unique=True, verbose_name='Connector Type')),
                ('status', models.IntegerField(choices=[(10, 'Initialized'), (20, 'Success'), (30, 'Failed'), (40, 'Running')], default=10, help_text='Current status of the connector', verbose_name='Status')),
                ('polling_start_datetime', models.DateTimeField(blank=True, help_text='Polling start date-time', null=True, verbose_name='Polling Start DateTime')),
                ('lookback_weeks', models.IntegerField(blank=True, default=520, help_text='Lookback weeks for fetching past events.', verbose_name='Lookback Weeks')),
                ('source_url', models.URLField(help_text='Base URL for the STAC API endpoint', verbose_name='Source URL')),
                ('last_success_run', models.DateTimeField(blank=True, help_text='Timestamp of the last successful data fetch', null=True, verbose_name='Last Successful Run')),
                ('dtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disastertype', verbose_name='disaster type')),
            ],
            options={
                'verbose_name': 'Connector',
                'verbose_name_plural': 'Connectors',
                'ordering': ['id', 'type'],
            },
        ),
        migrations.CreateModel(
            name='LoadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_run_id', models.UUIDField(blank=True, db_index=True, help_text='UUID field for tracking the extraction run through ETL pipeline', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('correlation_id', models.CharField(help_text='Correlation identifier linking all models', max_length=255, verbose_name='Correlation ID')),
                ('guid', models.CharField(help_text='Globally unique ID for events', verbose_name='GUID')),
                ('parent_guid', models.CharField(help_text='GUID without the episode number.', verbose_name='Parent GUID')),
                ('event_title', models.CharField(help_text='Title of the event', max_length=255, verbose_name='Event Title')),
                ('event_description', models.TextField(help_text='Description of the event', verbose_name='Event Description')),
                ('start_datetime', models.DateTimeField(help_text='Start datetime of the event')),
                ('end_datetime', models.DateTimeField(help_text='End datetime of the event', null=True)),
                ('country_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), help_text='List of country codes(ISO3) of afffected countries', null=True, size=None)),
                ('severity_unit', models.CharField(blank=True, help_text='Unit of measurement for severity', max_length=100, null=True, verbose_name='Severity Unit')),
                ('severity_label', models.CharField(blank=True, help_text='Human-readable severity label (e.g., Red, Orange, Green)', max_length=255, null=True, verbose_name='Severity Label')),
                ('severity_value', models.IntegerField(blank=True, help_text='Human-readable severity value', null=True, verbose_name='Severity Value')),
                ('total_people_exposed', models.IntegerField(help_text='Total number of people exposed to event', null=True, verbose_name='Total People Exposed')),
                ('total_buildings_exposed', models.IntegerField(help_text='Total number of buildings exposed to event', null=True, verbose_name='Total Buildings Exposed')),
                ('impact_metadata', models.JSONField(help_text='Metadata constructed from all events associated', verbose_name='Impact Metadata')),
                ('item_eligible', models.BooleanField(help_text='Is the item eligible for alerting')),
                ('is_past_event', models.BooleanField(default=False, help_text='Is the item in load table a past event')),
                ('connector', models.ForeignKey(help_text='Data source connector', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='alert_system.connector', verbose_name='Connector')),
                ('related_go_events', models.ManyToManyField(blank=True, to='api.event', verbose_name='Related GO Events')),
                ('related_montandon_events', models.ManyToManyField(blank=True, related_name='related_to', to='alert_system.loaditem')),
            ],
            options={
                'verbose_name': 'Eligible Item',
                'verbose_name_plural': 'Eligible Items',
            },
        ),
        migrations.CreateModel(
            name='ExtractionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_run_id', models.UUIDField(blank=True, db_index=True, help_text='UUID field for tracking the extraction run through ETL pipeline', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('correlation_id', models.CharField(help_text='Correlation identifier linking all models', max_length=255, verbose_name='Correlation ID')),
                ('guid', models.CharField(help_text='Globally unique ID for events', verbose_name='GUID')),
                ('collection', models.IntegerField(choices=[(100, 'event'), (200, 'Hazard'), (300, 'Impacts')], help_text='Collection type of the item', verbose_name='Collection')),
                ('stac_id', models.CharField(db_index=True, help_text='Unique identifier for the event item', max_length=255, unique=True, verbose_name='Event ID')),
                ('resp_data', models.JSONField(blank=True, help_text='Raw JSON response from the STAC API', null=True, verbose_name='Response Data')),
                ('connector', models.ForeignKey(help_text='Data source connector', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='alert_system.connector', verbose_name='Connector')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertEmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_guid', models.CharField(help_text='Identifier linking related LoadItems into the same email thread.')),
                ('root_email_message_id', models.CharField(help_text='Message-ID of the first email in this thread.', max_length=255, unique=True)),
                ('root_message_sent_at', models.DateTimeField(help_text='Timestamp when the root email was sent.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_email_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Thread',
                'verbose_name_plural': 'Email Threads',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AlertEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Unique Message-ID of email for tracking and threading.', max_length=255, unique=True, verbose_name='Message ID')),
                ('status', models.IntegerField(choices=[(100, 'Pending'), (200, 'Processing'), (300, 'Sent'), (400, 'Failed')], db_index=True, default=100, verbose_name='Email Status')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='Timestamp when email was successfully sent.', null=True, verbose_name='Sent At')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_alert_load_item', to='alert_system.loaditem', verbose_name='Load Item')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_alert_subscription', to='notifications.alertsubscription', verbose_name='Alert Subscription')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_alert_thread', to='alert_system.alertemailthread', verbose_name='Email Thread')),
                ('user', models.ForeignKey(help_text='The recipient of this alert email.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Alert Log',
                'verbose_name_plural': 'Email Alert Logs',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='loaditem',
            constraint=models.UniqueConstraint(fields=('guid',), name='unique_guid'),
        ),
        migrations.AddIndex(
            model_name='alertemailthread',
            index=models.Index(fields=['parent_guid', 'user'], name='alert_syste_parent__737a31_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertemailthread',
            constraint=models.UniqueConstraint(fields=('parent_guid', 'user'), name='unique_user_guid'),
        ),
        migrations.AddIndex(
            model_name='alertemaillog',
            index=models.Index(fields=['user', 'subscription', 'email_sent_at'], name='alert_syste_user_id_06a2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='alertemaillog',
            index=models.Index(fields=['user', 'item', 'status'], name='alert_syste_user_id_e51594_idx'),
        ),
    ]
