# Generated by Django 4.2.26 on 2025-12-22 15:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaditem',
            name='related_go_events',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, help_text='List of IDs of the events in GO.', size=None),
        ),
        migrations.CreateModel(
            name='EmailAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Email Message-ID', max_length=255, unique=True)),
                ('status', models.IntegerField(choices=[(100, 'Pending'), (200, 'Processing'), (300, 'Sent'), (400, 'Failed')], default=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_emails', to='alert_system.loaditem')),
            ],
            options={
                'verbose_name': 'EmailAlertLog',
                'verbose_name_plural': 'EmailAlertLogs',
                'ordering': ['-id'],
            },
        ),
    ]
