# Generated by Django 4.2.26 on 2025-12-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaditems',
            name='is_past_event',
            field=models.BooleanField(default=False, help_text='Is the item in load table a past event'),
        ),
        migrations.AddField(
            model_name='loaditems',
            name='related_events',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='alert_system.loaditems'),
        ),
    ]
