# Generated by Django 4.2.26 on 2025-12-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaditem',
            name='end_datetime',
            field=models.DateTimeField(help_text='End datetime of the event', null=True),
        ),
    ]
