# Generated by Django 4.2.26 on 2026-01-09 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_alertsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alert_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(help_text='Identifier linking related LoadItems into the same email thread.', max_length=255)),
                ('root_email_message_id', models.CharField(help_text='Message-ID of the first email in this thread.', max_length=255, unique=True)),
                ('root_message_sent_at', models.DateTimeField(help_text='Timestamp when the root email was sent.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_email_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Thread',
                'verbose_name_plural': 'Email Threads',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AlertEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Unique Message-ID of email for tracking and threading.', max_length=255, unique=True, verbose_name='Message ID')),
                ('status', models.IntegerField(choices=[(100, 'Pending'), (200, 'Processing'), (300, 'Sent'), (400, 'Failed')], db_index=True, default=100, verbose_name='Email Status')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='Timestamp when email was successfully sent.', null=True, verbose_name='Sent At')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_alert_load_item', to='alert_system.loaditem', verbose_name='Load Item')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_alert_subscription', to='notifications.alertsubscription', verbose_name='Alert Subscription')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_alert_thread', to='alert_system.alertemailthread', verbose_name='Email Thread')),
                ('user', models.ForeignKey(help_text='The recipient of this alert email.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Alert Log',
                'verbose_name_plural': 'Email Alert Logs',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='alertemailthread',
            index=models.Index(fields=['correlation_id', 'user'], name='alert_syste_correla_2e9c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='alertemaillog',
            index=models.Index(fields=['user', 'subscription', 'email_sent_at'], name='alert_syste_user_id_06a2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='alertemaillog',
            index=models.Index(fields=['user', 'item', 'status'], name='alert_syste_user_id_e51594_idx'),
        ),
    ]
