# Generated by Django 4.2.26 on 2026-01-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connector',
            options={'ordering': ['id', 'type'], 'verbose_name': 'Connector', 'verbose_name_plural': 'Connectors'},
        ),
    ]
