# Generated by Django 4.2.30 on 2026-05-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alertemailthread',
            name='unique_user_guid',
        ),
        migrations.RemoveIndex(
            model_name='alertemailthread',
            name='alert_syste_parent__737a31_idx',
        ),
        migrations.RenameField(
            model_name='alertemailthread',
            old_name='parent_guid',
            new_name='parent_event_id',
        ),
        migrations.AddIndex(
            model_name='alertemailthread',
            index=models.Index(fields=['parent_event_id', 'user'], name='alert_syste_parent__7efaa4_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertemailthread',
            constraint=models.UniqueConstraint(fields=('parent_event_id', 'user'), name='unique_user_parent_event'),
        ),
    ]
