# Generated by Django 4.2.26 on 2025-12-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0002_loaditems_is_past_event_loaditems_related_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionitem',
            name='collection',
            field=models.IntegerField(choices=[(100, 'event'), (200, 'Hazard'), (300, 'Impacts')], help_text='Collection type of the item', verbose_name='Collection'),
        ),
    ]
