# Generated by Django 4.2.26 on 2025-12-22 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0002_alter_loaditem_related_go_events_emailalertlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0016_alertsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailalertlog',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_logs', to='notifications.alertsubscription'),
        ),
        migrations.AddField(
            model_name='emailalertlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_email', to=settings.AUTH_USER_MODEL),
        ),
    ]
