# Generated by Django 4.2.26 on 2025-12-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0226_nsdinitiativescategory_and_more'),
        ('alert_system', '0002_alter_loaditem_end_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaditem',
            name='related_go_events',
        ),
        migrations.AddField(
            model_name='loaditem',
            name='related_go_events',
            field=models.ManyToManyField(blank=True, to='api.event', verbose_name='Related GO Events'),
        ),
    ]
