# Generated by Django 4.2.30 on 2026-05-26 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0002_remove_alertemailthread_unique_user_guid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alertemailthread',
            name='unique_user_parent_event',
        ),
    ]
