# Generated by Django 4.2.26 on 2025-12-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0003_alter_extractionitem_collection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoadItems',
            new_name='LoadItem',
        ),
    ]
