# Generated by Django 5.2.14 on 2026-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0003_remove_alertemailthread_unique_user_parent_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertemailthread',
            name='root_email_message_id',
            field=models.CharField(blank=True, help_text='Message-ID of the first email in this thread.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alertemailthread',
            name='root_message_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the root email was sent.', null=True),
        ),
    ]
