# Generated by Django 4.2.26 on 2026-01-04 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0016_alertsubscription'),
        ('alert_system', '0003_remove_loaditem_related_go_events_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(db_index=True, help_text='Identifier linking related LoadItems into the same email thread.', max_length=255)),
                ('root_email_message_id', models.CharField(help_text='Message-ID of the first email in this thread.', max_length=255, unique=True)),
                ('root_message_sent_at', models.DateTimeField(help_text='Timestamp when the root email was sent.')),
                ('reply_until', models.DateTimeField(help_text='Replies allowed until this timestamp (root email send date + 30 days).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_email_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Unique Message-ID of email for tracking and threading.', max_length=255, unique=True, verbose_name='Message ID')),
                ('in_reply_to', models.CharField(blank=True, help_text='Message-ID of the root email this message replies to. Null if this is the root.', max_length=255, null=True, verbose_name='In-Reply-To')),
                ('status', models.IntegerField(choices=[(100, 'Pending'), (200, 'Processing'), (300, 'Sent'), (400, 'Failed')], default=100, verbose_name='Email Status')),
                ('email_type', models.IntegerField(choices=[(100, 'New email'), (200, 'Reply email')], help_text='Indicates if the email is a new root email or a reply in a thread.', verbose_name='Email Type')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when the email was successfully sent.', null=True, verbose_name='Sent At')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_alert_load_item', to='alert_system.loaditem', verbose_name='Load Item')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_alert_subscription', to='notifications.alertsubscription', verbose_name='Alert Subscription')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_alert_thread', to='alert_system.alertemailthread', verbose_name='Email Thread')),
                ('user', models.ForeignKey(help_text='The recipient of this alert email.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Alert Log',
                'verbose_name_plural': 'Email Alert Logs',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='alertemailthread',
            constraint=models.UniqueConstraint(fields=('user', 'correlation_id'), name='unique_user_correlation_thread'),
        ),
    ]
