# Generated by Django 4.2.26 on 2025-12-10 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0004_rename_loaditems_loaditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaditem',
            old_name='country',
            new_name='country_codes',
        ),
    ]
