# Generated by Django 4.2.26 on 2025-12-12 05:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0005_rename_country_loaditem_country_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaditem',
            name='country_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), help_text='List of country codes(ISO3) of afffected countries', null=True, size=None),
        ),
    ]
