# Generated by Django 4.2.26 on 2025-12-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0006_alter_loaditem_country_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionitem',
            name='extraction_run_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID field for tracking the extraction run through ETL pipeline', null=True),
        ),
        migrations.AddField(
            model_name='loaditem',
            name='extraction_run_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID field for tracking the extraction run through ETL pipeline', null=True),
        ),
    ]
