# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso', models.CharField(max_length=2, null=True)),
                ('society_name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DisasterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uri', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(default=0)),
                ('request_assistance', models.BooleanField(default=False)),
                ('num_injured', models.IntegerField(null=True)),
                ('num_dead', models.IntegerField(null=True)),
                ('num_missing', models.IntegerField(null=True)),
                ('num_affected', models.IntegerField(null=True)),
                ('num_displaced', models.IntegerField(null=True)),
                ('num_assisted_gov', models.IntegerField(null=True)),
                ('num_assisted_rc', models.IntegerField(null=True)),
                ('num_localstaff', models.IntegerField(null=True)),
                ('num_volunteers', models.IntegerField(null=True)),
                ('num_expats_delegates', models.IntegerField(null=True)),
                ('action', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('countries', models.ManyToManyField(to='api.Country')),
                ('dtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DisasterType')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployed', models.BooleanField(default=False)),
                ('location', models.TextField()),
            ],
        ),
    ]
