# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='source',
            name='stype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SourceType'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='sources',
            field=models.ManyToManyField(to='api.Source'),
        ),
    ]
