# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 23:20
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171201_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='actions_others',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='appeal',
            field=enumfields.fields.EnumIntegerField(default=0, enum=api.models.RequestChoices),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='appeal_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='bulletin',
            field=enumfields.fields.EnumIntegerField(default=0, enum=api.models.RequestChoices),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='dref',
            field=enumfields.fields.EnumIntegerField(default=0, enum=api.models.RequestChoices),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='dref_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='eru',
            field=enumfields.fields.EnumIntegerField(default=0, enum=api.models.RequestChoices),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='fact',
            field=enumfields.fields.EnumIntegerField(default=0, enum=api.models.RequestChoices),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='ifrc_staff',
            field=enumfields.fields.EnumIntegerField(default=0, enum=api.models.RequestChoices),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='num_fact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='num_ifrc_staff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='num_rdrt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='rdrt',
            field=enumfields.fields.EnumIntegerField(default=0, enum=api.models.RequestChoices),
        ),
    ]
