# Generated by Django 2.0.5 on 2018-06-07 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20180410_1445"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionstaken",
            name="field_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="actions_taken", to="api.FieldReport"
            ),
        ),
        migrations.AlterField(
            model_name="eventcontact",
            name="event",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contacts", to="api.Event"),
        ),
        migrations.AlterField(
            model_name="fieldreportcontact",
            name="field_report",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contacts", to="api.FieldReport"),
        ),
        migrations.AlterField(
            model_name="keyfigure",
            name="event",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="key_figures", to="api.Event"),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="event",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="snippets", to="api.Event"),
        ),
        migrations.AlterField(
            model_name="source",
            name="field_report",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sources", to="api.FieldReport"),
        ),
    ]
