# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_disastertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='society_name',
            field=models.TextField(default=''),
        ),
    ]
