# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171207_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDACSEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=12)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.URLField(null=True)),
                ('report', models.URLField(null=True)),
                ('publication_date', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('event_type', models.CharField(max_length=12)),
                ('alert_level', models.CharField(max_length=12)),
                ('severity', models.TextField()),
                ('severity_unit', models.CharField(max_length=12)),
                ('severity_value', models.CharField(max_length=12)),
                ('population_unit', models.CharField(max_length=12)),
                ('population_value', models.CharField(max_length=12)),
                ('vulnerability', models.IntegerField()),
                ('country', models.TextField()),
            ],
        ),
    ]
