# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 17:17
from __future__ import unicode_literals

import api.models
import api.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171219_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('document', models.FileField(blank=True, null=True, storage=api.storage.AzureStorage(), upload_to=api.models.appeal_document_path)),
                ('document_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctype', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FieldReportContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctype', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='fieldreport',
            name='contacts',
        ),
        migrations.AlterField(
            model_name='appeal',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='api.Event'),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_reports', to='api.Event'),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='rid',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='field_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FieldReport'),
        ),
        migrations.AddField(
            model_name='eventcontact',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event'),
        ),
        migrations.AddField(
            model_name='appealdocument',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Appeal'),
        ),
    ]
