# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171207_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='countries',
            field=models.ManyToManyField(to='api.Country'),
        ),
    ]
