# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180111_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldreport',
            name='regions',
            field=models.ManyToManyField(blank=True, to='api.Region'),
        ),
    ]
