# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171221_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=32, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
                ('linked_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Event')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Region')),
            ],
        ),
    ]
