# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171201_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldreport',
            name='eru',
        ),
    ]
