# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 07:33
from __future__ import unicode_literals

import api.models
import api.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180116_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('document', models.FileField(blank=True, null=True, storage=api.storage.AzureStorage(), upload_to=api.models.sitrep_document_path)),
                ('document_url', models.URLField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
            ],
        ),
    ]
