# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171209_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contacts',
            field=models.ManyToManyField(to='api.Contact'),
        ),
        migrations.AddField(
            model_name='event',
            name='embed_snippet',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='dtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.DisasterType'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='api.Event'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Region'),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Region'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.DisasterType'),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='dtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.DisasterType'),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_reports', to='api.Event'),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='originator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country'),
        ),
        migrations.AlterField(
            model_name='source',
            name='stype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SourceType'),
        ),
    ]
