# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171122_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='summary',
        ),
        migrations.AddField(
            model_name='appeal',
            name='amount_funded',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appeal',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appeal',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Country'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Event'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='num_beneficiaries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appeal',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appeal',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='dtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DisasterType'),
        ),
        migrations.AddField(
            model_name='event',
            name='eid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='aid',
            field=models.CharField(max_length=20),
        ),
    ]
