# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171211_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='regions',
            field=models.ManyToManyField(to='api.Region'),
        ),
    ]
