# Generated by Django 2.0.5 on 2018-06-14 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180610_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('country_iso', models.CharField(max_length=3, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ('-start_date', '-end_date')},
        ),
        migrations.AddField(
            model_name='appeal',
            name='needs_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_generated_source',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='auto_generated',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='districts',
            field=models.ManyToManyField(blank=True, to='api.District'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='districts',
            field=models.ManyToManyField(blank=True, to='api.District'),
        ),
    ]
