# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_heop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heop',
            name='linked_event',
        ),
        migrations.AddField(
            model_name='heop',
            name='dtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.DisasterType'),
        ),
        migrations.AlterField(
            model_name='heop',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Event'),
        ),
    ]
