# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171122_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='amount_funded',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
