# Generated by Django 2.0.5 on 2018-06-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180614_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='report_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
