# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_glide'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='alert_level',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
