# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:39
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171123_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldreport',
            old_name='num_assisted_gov',
            new_name='gov_num_assisted',
        ),
        migrations.RenameField(
            model_name='fieldreport',
            old_name='num_assisted_rc',
            new_name='num_assisted',
        ),
        migrations.AddField(
            model_name='appeal',
            name='atype',
            field=enumfields.fields.EnumIntegerField(default=0, enum=api.models.AppealType),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='gov_num_affected',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='gov_num_dead',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='gov_num_displaced',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='gov_num_expats_delegates',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='gov_num_injured',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='gov_num_localstaff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='gov_num_missing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='gov_num_volunteers',
            field=models.IntegerField(null=True),
        ),
    ]
