# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 17:29
from __future__ import unicode_literals

import api.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180122_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='alert_level',
            field=enumfields.fields.EnumIntegerField(default=0, enum=api.models.AlertLevel),
        ),
        migrations.AlterField(
            model_name='gdacsevent',
            name='alert_level',
            field=enumfields.fields.EnumIntegerField(default=0, enum=api.models.AlertLevel),
        ),
    ]
