# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171128_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActionsTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('actions', models.ManyToManyField(to='api.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='fieldreport',
            name='action_federation',
        ),
        migrations.RemoveField(
            model_name='fieldreport',
            name='action_foreign',
        ),
        migrations.RemoveField(
            model_name='fieldreport',
            name='action_national',
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='actions',
            field=models.ManyToManyField(to='api.ActionsTaken'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='contacts',
            field=models.ManyToManyField(to='api.Contact'),
        ),
    ]
