# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171212_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldreport',
            old_name='originator',
            new_name='user',
        ),
    ]
