# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171212_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='num_affected',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
