# Generated by Django 2.0.5 on 2018-07-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180703_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentTypes',
            new_name='DocumentType',
        ),
    ]
