# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 22:40
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_event_num_affected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country')),
            ],
        ),
        migrations.CreateModel(
            name='ERU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', enumfields.fields.EnumIntegerField(default=0, enum=api.models.ERUType)),
                ('units', models.IntegerField(default=0)),
                ('countries', models.ManyToManyField(to='api.Country')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Deployment')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
