# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 22:44
from __future__ import unicode_literals

import api.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171213_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='visibility',
            field=enumfields.fields.EnumIntegerField(default=1, enum=api.models.VisibilityChoices),
        ),
    ]
