# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_fieldreport_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eru',
            name='countries',
            field=models.ManyToManyField(blank=True, to='api.Country'),
        ),
    ]
