# Generated by Django 2.0.12 on 2019-02-25 17:07

import api.models
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181120_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('position', 'id')},
        ),
        migrations.AlterModelOptions(
            name='countrysnippet',
            options={'ordering': ('position', 'id')},
        ),
        migrations.AlterModelOptions(
            name='regionsnippet',
            options={'ordering': ('position', 'id')},
        ),
        migrations.AddField(
            model_name='snippet',
            name='position',
            field=models.IntegerField(default=3, choices=api.models.PositionType).choices,
        ),
        migrations.AddField(
            model_name='countrysnippet',
            name='position',
            field=models.IntegerField(default=3, choices=api.models.PositionType).choices,
        ),
        migrations.AddField(
            model_name='regionsnippet',
            name='position',
            field=models.IntegerField(default=3, choices=api.models.PositionType).choices,
        ),
    ]
