# Generated by Django 2.0.12 on 2019-03-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_snippet_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDeployments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_deployed_to', models.IntegerField(blank=True, null=True)),
                ('deployments', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=4)),
            ],
        ),
    ]
