# Generated by Django 2.0.12 on 2019-04-09 15:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_snippet_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
