# Generated by Django 2.0.12 on 2019-03-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_eventdeployments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventDeployments',
        ),
    ]
