# Generated by Django 2.0.12 on 2019-04-24 15:08

import api.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190424_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ifrc_severity_level',
            field=enumfields.fields.EnumIntegerField(default=0, enum=api.models.AlertLevel, verbose_name='IFRC Severity level'),
        ),
    ]
