# Generated by Django 2.0.12 on 2019-04-24 15:08

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_auto_20190424_1224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ifrc_severity_level",
            field=models.IntegerField(default=0, choices=api.models.AlertLevel.choices, verbose_name="IFRC Severity level"),
        ),
    ]
