# Generated by Django 2.0.12 on 2019-06-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190424_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='logo',
            field=models.FileField(blank=True, null=True, storage=api.storage.AzureStorage(), upload_to=api.models.logo_document_path)
        ),
    ]
