# Generated by Django 2.0.12 on 2019-07-03 06:14

import api.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190626_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='record_type',
            field=enumfields.fields.EnumIntegerField(default=1, enum=api.models.CountryType, help_text='Type of entity'),
        ),
        migrations.AddField(
            model_name='district',
            name='is_enclave',
            field=models.BooleanField(default=False, help_text='Is it an enclave away from parent country?'),
        ),
    ]
