# Generated by Django 2.0.12 on 2019-07-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190724_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
