# Generated by Django 2.0.12 on 2019-11-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20191125_0939'),
        ('api', '0027_auto_20191120_1223'),
    ]

    operations = [
    ]
