# Generated by Django 2.0.12 on 2019-11-25 09:49

import api.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20191125_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='forecast_based_action',
            field=enumfields.fields.EnumIntegerField(default=0, enum=api.models.RequestChoices),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='forecast_based_action_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='imminent_dref',
            field=enumfields.fields.EnumIntegerField(default=0, enum=api.models.RequestChoices),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='imminent_dref_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
