# Generated by Django 2.0.12 on 2019-11-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20191127_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured on Home Page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_featured_region',
            field=models.BooleanField(default=False, verbose_name='Is Featured on Region Page'),
        ),
    ]
