# Generated by Django 2.2.9 on 2020-01-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_cronjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='backend_side',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='num_result',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='storing_days',
            field=models.IntegerField(default=3),
        ),
    ]
