# Generated by Django 2.2.9 on 2020-02-11 15:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_authlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReversionDifferenceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=256, null=True)),
                ('object_id', models.CharField(blank=True, max_length=191)),
                ('object_type', models.CharField(blank=True, max_length=191)),
                ('changed_from', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('changed_to', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
            ],
        ),
    ]
