# Generated by Django 2.2.10 on 2020-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20200318_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='situationreport',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin this report at the top'),
        ),
        migrations.AddField(
            model_name='situationreporttype',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Ensure this type gets precedence over others that are empty'),
        ),
    ]
