# Generated by Django 2.2.9 on 2020-03-25 09:05

import api.utils
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20200318_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='url_ifrc',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, default=None, help_text='Optional string for a clean URL. For example, go.ifrc.org/emergencies/hurricane-katrina-2019. The string cannot start with a number and is forced to be lowercase. Recommend using hyphens over underscores. Special characters like # is not allowed.', max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), api.utils.validate_slug_number]),
        ),
    ]
