# Generated by Django 2.2.10 on 2020-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20200320_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situationreporttype',
            name='is_primary',
            field=models.BooleanField(default=False, editable=False, help_text='Ensure this type gets precedence over others that are empty'),
        ),
    ]
