# Generated by Django 2.2.9 on 2020-03-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20200325_0905'),
        ('api', '0045_auto_20200320_1121'),
    ]

    operations = [
    ]
