# Generated by Django 2.2.10 on 2020-03-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_merge_20200325_1016'),
        ('api', '0045_auto_20200212_1354'),
    ]

    operations = [
    ]
