# Generated by Django 2.2.10 on 2020-04-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20200401_1249'),
        ('api', '0048_merge_20200401_1310'),
    ]

    operations = [
    ]
