# Generated by Django 2.2.10 on 2020-04-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_fieldreport_sit_fields_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldreport',
            name='sit_fields_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
