# Generated by Django 2.2.10 on 2020-04-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_merge_20200406_1026'),
        ('api', '0052_auto_20200406_0623'),
    ]

    operations = [
    ]
