# Generated by Django 2.2.10 on 2020-04-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20200407_0939'),
        ('api', '0054_merge_20200407_1212'),
    ]

    operations = [
    ]
