# Generated by Django 2.2.10 on 2020-04-13 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_merge_20200407_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, help_text="If needed, you have to change the connected Appeals', Field Reports', etc to point to the parent Emergency manually.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Event', verbose_name='Parent Emergency'),
        ),
    ]
