# Generated by Django 2.2.10 on 2020-04-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20200415_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='is_covid_report',
            field=models.BooleanField(default=False, help_text='Is this a Field Report specific to the COVID-19 emergency?'),
        ),
        migrations.AlterField(
            model_name='action',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Health', 'Health'), ('NS Institutional Strengthening', 'NS Institutional Strengthening'), ('Socio-economic Impacts', 'Socio-economic Impacts')], default='General', max_length=12),
        ),
    ]
