# Generated by Django 2.2.10 on 2020-05-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20200430_0852'),
        ('api', '0059_auto_20200430_0801'),
    ]

    operations = [
    ]
