# Generated by Django 2.2.10 on 2020-05-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20200501_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='epi_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='epi_confirmed_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='epi_num_dead',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='epi_probable_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='epi_suspected_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
