# Generated by Django 2.2.10 on 2020-05-04 13:15

import api.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20200504_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='epi_figures_source',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=api.models.EPISourceChoices, null=True),
        ),
    ]
