# Generated by Django 2.2.10 on 2020-05-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20200504_1438'),
        ('api', '0065_fieldreport_epi_figures_source'),
    ]

    operations = [
    ]
