# Generated by Django 2.2.10 on 2020-05-28 08:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_merge_20200508_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionstaken',
            name='actions',
            field=models.ManyToManyField(blank=True, to='api.Action'),
        ),
        migrations.AlterField(
            model_name='countrysnippet',
            name='snippet',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regionsnippet',
            name='snippet',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='snippet',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
