# Generated by Django 2.2.10 on 2020-06-03 07:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20200603_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='description_ar',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='description_es',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='description_fr',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='summary_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='summary_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='summary_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
