# Generated by Django 2.2.13 on 2020-06-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_notificationguid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationGUID',
        ),
    ]
