# Generated by Django 2.2.13 on 2020-06-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20200603_0743'),
        ('api', '0067_auto_20200528_0840'),
        ('api', '0067_auto_20200603_0613'),
    ]

    operations = [
    ]
