# Generated by Django 2.2.13 on 2020-06-24 15:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20200623_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrysnippet',
            name='snippet',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AlterField(
            model_name='regionsnippet',
            name='snippet',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='snippet',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
    ]
