# Generated by Django 2.2.13 on 2020-08-04 06:10

import api.utils
import django.core.validators
from django.db import migrations, models
import re
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_merge_20200730_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='action',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='action',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='action',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='actionstaken',
            name='summary_ar',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='actionstaken',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='actionstaken',
            name='summary_es',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='actionstaken',
            name='summary_fr',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='appealdocument',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='appealdocument',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='appealdocument',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='appealdocument',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='overview_ar',
            field=models.TextField(blank=True, null=True, verbose_name='overview'),
        ),
        migrations.AddField(
            model_name='country',
            name='overview_en',
            field=models.TextField(blank=True, null=True, verbose_name='overview'),
        ),
        migrations.AddField(
            model_name='country',
            name='overview_es',
            field=models.TextField(blank=True, null=True, verbose_name='overview'),
        ),
        migrations.AddField(
            model_name='country',
            name='overview_fr',
            field=models.TextField(blank=True, null=True, verbose_name='overview'),
        ),
        migrations.AddField(
            model_name='countrysnippet',
            name='snippet_ar',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AddField(
            model_name='countrysnippet',
            name='snippet_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AddField(
            model_name='countrysnippet',
            name='snippet_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AddField(
            model_name='countrysnippet',
            name='snippet_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AddField(
            model_name='disastertype',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='disastertype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='disastertype',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='disastertype',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='disastertype',
            name='summary_ar',
            field=models.TextField(null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='disastertype',
            name='summary_en',
            field=models.TextField(null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='disastertype',
            name='summary_es',
            field=models.TextField(null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='disastertype',
            name='summary_fr',
            field=models.TextField(null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug_ar',
            field=models.CharField(blank=True, default=None, editable=False, help_text='Optional string for a clean URL. For example, go.ifrc.org/emergencies/hurricane-katrina-2019. The string cannot start with a number and is forced to be lowercase. Recommend using hyphens over underscores. Special characters like # is not allowed.', max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), api.utils.validate_slug_number], verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug_en',
            field=models.CharField(blank=True, default=None, editable=False, help_text='Optional string for a clean URL. For example, go.ifrc.org/emergencies/hurricane-katrina-2019. The string cannot start with a number and is forced to be lowercase. Recommend using hyphens over underscores. Special characters like # is not allowed.', max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), api.utils.validate_slug_number], verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug_es',
            field=models.CharField(blank=True, default=None, editable=False, help_text='Optional string for a clean URL. For example, go.ifrc.org/emergencies/hurricane-katrina-2019. The string cannot start with a number and is forced to be lowercase. Recommend using hyphens over underscores. Special characters like # is not allowed.', max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), api.utils.validate_slug_number], verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug_fr',
            field=models.CharField(blank=True, default=None, editable=False, help_text='Optional string for a clean URL. For example, go.ifrc.org/emergencies/hurricane-katrina-2019. The string cannot start with a number and is forced to be lowercase. Recommend using hyphens over underscores. Special characters like # is not allowed.', max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), api.utils.validate_slug_number], verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='actions_others_ar',
            field=models.TextField(blank=True, null=True, verbose_name='actions taken (others)'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='actions_others_en',
            field=models.TextField(blank=True, null=True, verbose_name='actions taken (others)'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='actions_others_es',
            field=models.TextField(blank=True, null=True, verbose_name='actions taken (others)'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='actions_others_fr',
            field=models.TextField(blank=True, null=True, verbose_name='actions taken (others)'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='description_ar',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='description_es',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='description_fr',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='other_sources_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='sources (other)'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='other_sources_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='sources (other)'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='other_sources_es',
            field=models.TextField(blank=True, default='', null=True, verbose_name='sources (other)'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='other_sources_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='sources (other)'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='summary_ar',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='summary_es',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='summary_fr',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='gdacsevent',
            name='country_text_ar',
            field=models.TextField(null=True, verbose_name='country text'),
        ),
        migrations.AddField(
            model_name='gdacsevent',
            name='country_text_en',
            field=models.TextField(null=True, verbose_name='country text'),
        ),
        migrations.AddField(
            model_name='gdacsevent',
            name='country_text_es',
            field=models.TextField(null=True, verbose_name='country text'),
        ),
        migrations.AddField(
            model_name='gdacsevent',
            name='country_text_fr',
            field=models.TextField(null=True, verbose_name='country text'),
        ),
        migrations.AddField(
            model_name='gdacsevent',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='gdacsevent',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='gdacsevent',
            name='description_es',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='gdacsevent',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='gdacsevent',
            name='title_ar',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='gdacsevent',
            name='title_en',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='gdacsevent',
            name='title_es',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='gdacsevent',
            name='title_fr',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='regionsnippet',
            name='snippet_ar',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AddField(
            model_name='regionsnippet',
            name='snippet_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AddField(
            model_name='regionsnippet',
            name='snippet_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AddField(
            model_name='regionsnippet',
            name='snippet_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AddField(
            model_name='situationreport',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='situationreport',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='situationreport',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='situationreport',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='snippet_ar',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='snippet_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='snippet_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='snippet_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AlterField(
            model_name='countrysnippet',
            name='snippet',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AlterField(
            model_name='regionsnippet',
            name='snippet',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='snippet',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='snippet'),
        ),
    ]
