# Generated by Django 2.2.13 on 2020-09-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20200916_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=400, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name_ar',
            field=models.CharField(max_length=400, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name_en',
            field=models.CharField(max_length=400, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name_es',
            field=models.CharField(max_length=400, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name_fr',
            field=models.CharField(max_length=400, null=True, verbose_name='name'),
        ),
    ]
