# Generated by Django 2.2.13 on 2020-11-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20200918_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='fdrs',
            field=models.CharField(max_length=6, null=True, verbose_name='FDRS'),
        ),
        # migrations.AlterField(
        #     model_name='event',
        #     name='num_displaced',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='number of displaced'),
        # ),
    ]
