# Generated by Django 2.2.13 on 2020-10-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20200918_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='num_displaced',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of displaced'),
        ),
    ]
