# Generated by Django 2.2.13 on 2020-11-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20201119_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionlink',
            name='show_in_go',
            field=models.BooleanField(default=False, help_text='Show link contents within GO'),
        ),
        migrations.DeleteModel(
            name='RegionAdditionalLink',
        ),
    ]
