# Generated by Django 2.2.13 on 2020-11-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20201123_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='nsi_annual_fdrs_reporting',
            field=models.NullBooleanField(verbose_name='Annual Reporting to FDRS'),
        ),
        migrations.AddField(
            model_name='country',
            name='nsi_branches',
            field=models.IntegerField(blank=True, null=True, verbose_name='Branches'),
        ),
        migrations.AddField(
            model_name='country',
            name='nsi_cmc_dashboard_compliance',
            field=models.NullBooleanField(verbose_name='Complying with CMC Dashboard'),
        ),
        migrations.AddField(
            model_name='country',
            name='nsi_domestically_generated_income',
            field=models.NullBooleanField(verbose_name='>50% Domestically Generated Income'),
        ),
        migrations.AddField(
            model_name='country',
            name='nsi_expenditures',
            field=models.IntegerField(blank=True, null=True, verbose_name='Expenditures (CHF)'),
        ),
        migrations.AddField(
            model_name='country',
            name='nsi_gov_financial_support',
            field=models.NullBooleanField(verbose_name='Gov Financial Support'),
        ),
        migrations.AddField(
            model_name='country',
            name='nsi_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Income (CHF)'),
        ),
        migrations.AddField(
            model_name='country',
            name='nsi_policy_implementation',
            field=models.NullBooleanField(verbose_name='Your Policy / Programme Implementation'),
        ),
        migrations.AddField(
            model_name='country',
            name='nsi_risk_management_framework',
            field=models.NullBooleanField(verbose_name='Risk Management Framework'),
        ),
        migrations.AddField(
            model_name='country',
            name='nsi_staff',
            field=models.IntegerField(blank=True, null=True, verbose_name='Staff'),
        ),
        migrations.AddField(
            model_name='country',
            name='nsi_trained_in_first_aid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trained in First Aid'),
        ),
        migrations.AddField(
            model_name='country',
            name='nsi_volunteers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volunteers'),
        ),
        migrations.AddField(
            model_name='country',
            name='nsi_youth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Youth - 6-19 Yrs'),
        ),
    ]
