# Generated by Django 2.2.13 on 2020-11-27 10:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_auto_20201127_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='summary_ar',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='event',
            name='summary_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='event',
            name='summary_es',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='event',
            name='summary_fr',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='summary'),
        ),
    ]
