# Generated by Django 2.2.13 on 2020-12-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20201130_0954'),
        ('api', '0088_auto_20201118_1144'),
    ]

    operations = [
    ]
