# Generated by Django 2.2.13 on 2021-02-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20201211_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldreport',
            name='ns_request_assistance',
            field=models.NullBooleanField(verbose_name='NS request assistance'),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='request_assistance',
            field=models.NullBooleanField(verbose_name='request assistance'),
        ),
    ]
