# Generated by Django 2.2.13 on 2020-12-14 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20201211_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='disputed',
            field=models.BooleanField(default=False, help_text='Is this country disputed?'),
        ),
        migrations.AddField(
            model_name='country',
            name='sovereign_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country', verbose_name='Country ID of the Sovereign State'),
        ),
    ]
