# Generated by Django 2.2.13 on 2021-01-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20201211_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='epi_cases_since_last_fr',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of new cases since the last field report'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='epi_deaths_since_last_fr',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of new deaths since last field report'),
        ),
    ]
