# Generated by Django 2.2.13 on 2021-01-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_auto_20210126_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='tooltip_text',
            field=models.TextField(blank='true', null=True, verbose_name='tooltip text'),
        ),
    ]
