# Generated by Django 2.2.13 on 2021-02-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_fieldreport_epi_notes_since_last_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='notes_health',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='notes_ns',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
