# Generated by Django 2.2.13 on 2021-02-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_externalpartner_externalpartnercategory_fieldreportexternalpartner_fieldreportexternalpartnercategor'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpartner',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='externalpartner',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='externalpartner',
            name='name_es',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='externalpartner',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='externalpartnercategory',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='externalpartnercategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='externalpartnercategory',
            name='name_es',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='externalpartnercategory',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='supportedactivity',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='supportedactivity',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='supportedactivity',
            name='name_es',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='supportedactivity',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
    ]
