# Generated by Django 2.2.13 on 2021-02-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_merge_20210204_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldreport',
            name='external_partner_categories',
        ),
        migrations.DeleteModel(
            name='ExternalPartnerCategory',
        ),
    ]
