# Generated by Django 2.2.13 on 2021-02-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20210205_1443'),
        ('api', '0116_auto_20210205_0905'),
    ]

    operations = [
    ]
