# Generated by Django 2.2.13 on 2021-02-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_merge_20210205_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='in_search',
            field=models.BooleanField(default=True, verbose_name='Include in Search?'),
        ),
    ]
