# Generated by Django 2.2.13 on 2021-02-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_country_in_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='in_search',
            field=models.BooleanField(default=True, verbose_name='Include in Search'),
        ),
    ]
