# Generated by Django 2.2.13 on 2021-03-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_auto_20210219_0908'),
        ('api', '0121_geccode'),
    ]

    operations = [
    ]
