# Generated by Django 2.2.13 on 2021-03-08 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_geccode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='country_iso',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'ISO must be uppercase')], verbose_name='country ISO2'),
        ),
    ]
