# Generated by Django 2.2.13 on 2021-03-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20210308_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='country_iso',
        ),
        migrations.RemoveField(
            model_name='district',
            name='country_name',
        ),
    ]
