# Generated by Django 2.2.13 on 2021-04-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20210318_1520'),
        ('api', '0123_auto_20210301_1014'),
    ]

    operations = [
    ]
