# Generated by Django 2.2.20 on 2021-04-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_erpguid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpguid',
            name='field_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FieldReport', verbose_name='field report'),
        ),
        migrations.AlterField(
            model_name='geccode',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country', verbose_name='country'),
        ),
    ]
