# Generated by Django 2.2.20 on 2021-07-29 16:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_auto_20210701_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealhistory',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='eventfeatureddocument',
            name='thumbnail',
            field=models.ImageField(help_text='Image should be portrait (3:4 aspect ratio) and scaled down to as close to 96x128 as the image size', storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to='event-featured-documents/thumbnail/', verbose_name='thumbnail'),
        ),
    ]
