# Generated by Django 2.2.20 on 2021-07-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0132_auto_20210701_0635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appealhistory",
            name="code",
            field=models.CharField(max_length=20, null=True, verbose_name="code"),
        ),
    ]
