# Generated by Django 2.2.20 on 2021-10-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_auto_20210729_1609'),
        ('api', '0133_auto_20210922_1327'),
    ]

    operations = [
    ]
