# Generated by Django 2.2.24 on 2021-11-17 15:29

import api.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_usercountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=enumfields.fields.EnumIntegerField(default=1, enum=api.models.VisibilityChoices, verbose_name='visibility'),
        ),
    ]
