# Generated by Django 2.2.24 on 2022-01-04 08:45

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_event_visibility'),
        ('api', '0134_merge_20211020_0622'),
    ]

    operations = [
    ]
