# Generated by Django 2.2.24 on 2022-01-04 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0138_auto_20220105_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Region', verbose_name='region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userRegionName', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Regional Admin',
                'verbose_name_plural': 'Regional Admins',
            },
        ),
    ]
