# Generated by Django 2.2.24 on 2022-01-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_userregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='triggering_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='triggering_amount'),
        ),
        migrations.AddField(
            model_name='appealhistory',
            name='triggering_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='triggering_amount'),
        ),
    ]
