# Generated by Django 2.2.27 on 2022-03-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0150_event_emergency_response_contact_email"),
        ("api", "0150_admin2_admin2geoms"),
    ]

    operations = []
