# Generated by Django 2.2.27 on 2022-04-12 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0151_merge_20220325_1027"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryOfFieldReportToReview",
            fields=[
                (
                    "country",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="api.Country",
                        verbose_name="country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country of Field Report to review",
                "verbose_name_plural": "Countries of Field Report to review",
            },
        ),
    ]
