# Generated by Django 2.2.27 on 2022-05-13 09:34

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_auto_20220513_0633'),
        ('api', '0153_auto_20220510_0730'),
    ]

    operations = [
    ]
