# Generated by Django 2.2.27 on 2022-06-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0155_auto_20220523_0824"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldreport",
            name="health_min_num_assisted",
            field=models.IntegerField(
                blank=True, help_text="not used any more", null=True, verbose_name="number of assisted (ministry of health)"
            ),
        ),
        migrations.AlterField(
            model_name="fieldreport",
            name="who_num_assisted",
            field=models.IntegerField(
                blank=True, help_text="not used any more", null=True, verbose_name="number of assisted (who)"
            ),
        ),
    ]
