# Generated by Django 2.2.27 on 2022-09-06 09:46

import api.models
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_appealfilter_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.snippet_image_path, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='event',
            name='summary_ar',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='event',
            name='summary_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='event',
            name='summary_es',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='event',
            name='summary_fr',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='summary'),
        ),
    ]
