# Generated by Django 2.2.28 on 2022-07-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_appealfilter_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldreport',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Two'), (3, 'Three'), (8, 'Early Warning'), (9, 'Event-related'), (10, 'Ten'), (11, 'EAP Activation')], default=0, verbose_name='type'),
        ),
    ]
