# Generated by Django 3.2.18 on 2023-03-31 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin2',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
