# Generated by Django 3.2.18 on 2023-04-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_admin2_is_deprecated'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('public_site_or_fednet', models.BooleanField(default=False, verbose_name='Sourced by FedNet?')),
            ],
            options={
                'verbose_name': 'appeal document type',
                'verbose_name_plural': 'appeal document types',
                'ordering': ('name',),
            },
        ),
    ]
