# Generated by Django 3.2.18 on 2023-04-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_admin2_is_deprecated'),
        ('api', '0163_auto_20230410_0720'),
    ]

    operations = [
    ]
