# Generated by Django 3.2.18 on 2023-04-25 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_alter_appealdocument_iso3'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[("update api_country set iso=null where iso='';")],
            reverse_sql=[("update api_country set iso=null where iso='';")],
        ),
        migrations.AlterField(
            model_name='country',
            name='iso',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'ISO must be uppercase')], verbose_name='ISO'),
        ),
    ]
