# Generated by Django 3.2.18 on 2023-06-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0163_auto_20230410_0720"),
        ("api", "0169_auto_20230425_1120"),
    ]

    operations = []
