# Generated by Django 3.2.18 on 2023-06-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_merge_20230419_0524'),
        ('api', '0170_merge_0163_auto_20230410_0720_0169_auto_20230425_1120'),
    ]

    operations = [
    ]
