# Generated by Django 3.2.20 on 2023-08-29 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_alter_fieldreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='Url')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Requested At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Errored')], default=0, verbose_name='Status')),
                ('pdf_file', models.FileField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Pdf File')),
            ],
        ),
    ]
