# Generated by Django 3.2.20 on 2023-08-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='pdf-export/', verbose_name='Pdf File'),
        ),
    ]
