# Generated by Django 3.2.20 on 2023-08-30 06:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0174_alter_export_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="export",
            name="selector",
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name="Selector"),
            preserve_default=False,
        ),
    ]
