# Generated by Django 3.2.20 on 2023-09-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_auto_20230906_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='selector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Selector'),
        ),
    ]
