# Generated by Django 3.2.20 on 2023-09-11 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0177_alter_export_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='export_id',
            field=models.IntegerField(default=1, verbose_name='Export Id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='export',
            name='export_type',
            field=models.CharField(choices=[('dref-applications', 'Dref Applications')], default=django.utils.timezone.now, max_length=255, verbose_name='Export Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='export',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='export',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Url'),
        ),
    ]
