# Generated by Django 3.2.20 on 2023-09-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0179_alter_export_export_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appealhistory",
            name="amount_funded",
            field=models.FloatField(default=0.0, verbose_name="amount funded"),
        ),
        migrations.AlterField(
            model_name="appealhistory",
            name="amount_requested",
            field=models.FloatField(default=0.0, verbose_name="amount requested"),
        ),
    ]
