# Generated by Django 3.2.20 on 2023-09-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_alter_export_export_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreportcontact',
            name='ctype_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='ctype_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='ctype_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='ctype_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='email_ar',
            field=models.CharField(max_length=300, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='email_en',
            field=models.CharField(max_length=300, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='email_es',
            field=models.CharField(max_length=300, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='email_fr',
            field=models.CharField(max_length=300, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='phone_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='phone_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='phone_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='phone_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='title_ar',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='title_es',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='title_fr',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='fieldreportcontact',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='source',
            name='spec_ar',
            field=models.TextField(blank=True, null=True, verbose_name='spec'),
        ),
        migrations.AddField(
            model_name='source',
            name='spec_en',
            field=models.TextField(blank=True, null=True, verbose_name='spec'),
        ),
        migrations.AddField(
            model_name='source',
            name='spec_es',
            field=models.TextField(blank=True, null=True, verbose_name='spec'),
        ),
        migrations.AddField(
            model_name='source',
            name='spec_fr',
            field=models.TextField(blank=True, null=True, verbose_name='spec'),
        ),
        migrations.AddField(
            model_name='source',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='source',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
    ]
