# Generated by Django 3.2.23 on 2023-12-18 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0186_auto_20231103_0904"),
    ]

    # NOTE: Default value `0` as expected
    # If migration error, to be fixed manually
    operations = [
        migrations.AlterField(
            model_name="appeal",
            name="country",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="api.country", verbose_name="country"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appealhistory",
            name="country",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="api.country", verbose_name="country"
            ),
            preserve_default=False,
        ),
    ]
