# Generated by Django 3.2.23 on 2023-11-30 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_auto_20231103_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdacsevent',
            name='disaster_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.disastertype', verbose_name='disaster type'),
        ),
    ]
