# Generated by Django 3.2.23 on 2024-01-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_alter_export_export_type'),
        ('api', '0188_auto_20240109_0508'),
    ]

    operations = [
    ]
