# Generated by Django 3.2.23 on 2024-01-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_auto_20240109_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted_montandon_license_terms',
            field=models.BooleanField(default=False, verbose_name='has accepted montandon license terms?'),
        ),
    ]
