# Generated by Django 3.2.23 on 2023-12-13 05:19

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0191_countrykeydocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSDInitiatives",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("fund_type", models.CharField(max_length=255, verbose_name="Fund Type")),
                ("allocation", models.IntegerField(verbose_name="Allocation in CHF")),
                ("year", models.CharField(max_length=20, verbose_name="Year")),
                ("funding_period", models.IntegerField(verbose_name="Funding Period in Month")),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="Funding categories",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.country", verbose_name="Country"),
                ),
            ],
        ),
    ]
