# Generated by Django 3.2.23 on 2023-12-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0192_nsdinitiatives"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryCapacityStrengthening",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assessment_code", models.CharField(max_length=255, verbose_name="Assessment Code")),
                ("year", models.CharField(max_length=25, verbose_name="Year of Assessment")),
                ("submission_date", models.DateTimeField(verbose_name="Submission Date")),
                ("url", models.CharField(max_length=255, verbose_name="Url")),
                (
                    "assessment_type",
                    models.IntegerField(choices=[(0, "Ocac"), (1, "Boca")], verbose_name="Country Assessment Type"),
                ),
                ("branch_name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Branch Name")),
                (
                    "country",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.country", verbose_name="Country"),
                ),
            ],
        ),
    ]
