# Generated by Django 3.2.23 on 2024-01-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0200_countryicrcpresence"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="disaster_law_url",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Disaster law url"),
        ),
    ]
