# Generated by Django 3.2.23 on 2024-01-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0202_alter_countryorganizationalcapacity_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countryicrcpresence",
            name="country",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="api.country", verbose_name="Country"),
        ),
    ]
