# Generated by Django 3.2.23 on 2024-01-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0188_auto_20240109_0508"),
        ("api", "0203_alter_countryicrcpresence_country"),
    ]

    operations = []
