# Generated by Django 3.2.23 on 2024-02-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0190_auto_20240220_0510"),
        ("api", "0190_remove_export_selector"),
        ("api", "0204_merge_20240129_0639"),
    ]

    operations = []
