# Generated by Django 3.2.24 on 2024-03-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0206_alter_export_export_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="export",
            name="per_country",
            field=models.IntegerField(blank=True, null=True, verbose_name="Per Country Id"),
        ),
        migrations.AlterField(
            model_name="export",
            name="export_type",
            field=models.CharField(
                choices=[
                    ("dref-applications", "DREF Application"),
                    ("dref-operational-updates", "DREF Operational Update"),
                    ("dref-final-reports", "DREF Final Report"),
                    ("old-dref-final-reports", "Old DREF Final Report"),
                    ("per", "Per"),
                ],
                max_length=255,
                verbose_name="Export Type",
            ),
        ),
    ]
