# Generated by Django 3.2.25 on 2024-04-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0209_auto_20240423_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted_montandon_license_terms',
            field=models.BooleanField(default=False, verbose_name='has accepted montandon license terms?'),
        ),
    ]
