# Generated by Django 4.2.13 on 2024-07-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0210_profile_accepted_montandon_license_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="limit_access_to_guest",
            field=models.BooleanField(
                default=False,
                help_text="User having this value as true explictly is treated as guest user.Despite of having all the         permission, if this value is set to true, the user is deprived of all the non-guest user permission.",
                verbose_name="limit access to guest user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="limit_access_to_guest",
            field=models.BooleanField(
                default=True,
                help_text="User having this value as true explictly is treated as guest user.Despite of having all the         permission, if this value is set to true, the user is deprived of all the non-guest user permission.",
                verbose_name="limit access to guest user permissions",
            ),
        ),
    ]
