# Generated by Django 4.2.15 on 2024-09-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0213_merge_20240807_1001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="limit_access_to_guest",
            field=models.BooleanField(
                default=False,
                help_text="If this value is set to true, the user is treated as a guest user regardless of any other permissions they may have, thereby depriving them of all non-guest user permissions.",
                verbose_name="limit access to guest user permissions",
            ),
        ),
    ]
