# Generated by Django 4.2.15 on 2024-09-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0213_merge_20240807_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='title_ar',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='title_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='title_es',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='title_fr',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
