# Generated by Django 4.2.16 on 2024-10-29 08:51

from django.db import migrations

import api.models
import main.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0214_alter_profile_limit_access_to_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generaldocument",
            name="document",
            field=main.fields.SecureFileField(
                blank=True, null=True, upload_to=api.models.general_document_path, verbose_name="document"
            ),
        ),
        migrations.AlterField(
            model_name="situationreport",
            name="document",
            field=main.fields.SecureFileField(
                blank=True, null=True, upload_to=api.models.sitrep_document_path, verbose_name="document"
            ),
        ),
    ]
