# Generated by Django 4.2.16 on 2024-11-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0215_alter_generaldocument_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="emma_id",
            field=models.CharField(blank=True, help_text="Meteoalarm EMMA_ID", max_length=10, null=True, verbose_name="emma_id"),
        ),
        migrations.AddField(
            model_name="district",
            name="fips_code",
            field=models.PositiveIntegerField(blank=True, help_text="USA FIPS Code", null=True, verbose_name="fips_code"),
        ),
        migrations.AddField(
            model_name="district",
            name="nuts1",
            field=models.CharField(
                blank=True,
                help_text="Nomenclature of Territorial Units for Statistics 1",
                max_length=3,
                null=True,
                verbose_name="nuts1",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="nuts2",
            field=models.CharField(
                blank=True,
                help_text="Nomenclature of Territorial Units for Statistics 2",
                max_length=4,
                null=True,
                verbose_name="nuts2",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="nuts3",
            field=models.CharField(
                blank=True,
                help_text="Nomenclature of Territorial Units for Statistics 3",
                max_length=5,
                null=True,
                verbose_name="nuts3",
            ),
        ),
    ]
