# Generated by Django 4.2.17 on 2025-02-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0217_merge_20250107_1019"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="title",
        ),
        migrations.RemoveField(
            model_name="event",
            name="title_ar",
        ),
        migrations.RemoveField(
            model_name="event",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="event",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="event",
            name="title_fr",
        ),
        migrations.AlterField(
            model_name="fieldreport",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Title is used to generate the summary/name of the Field Report. </br>The summary is constructed as: <b><i>Country IS03: Disaster Type - Start Date - Title - Field Report Number - (date)</b><i>",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="fieldreport",
            name="title_ar",
            field=models.CharField(
                blank=True,
                help_text="Title is used to generate the summary/name of the Field Report. </br>The summary is constructed as: <b><i>Country IS03: Disaster Type - Start Date - Title - Field Report Number - (date)</b><i>",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fieldreport",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Title is used to generate the summary/name of the Field Report. </br>The summary is constructed as: <b><i>Country IS03: Disaster Type - Start Date - Title - Field Report Number - (date)</b><i>",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fieldreport",
            name="title_es",
            field=models.CharField(
                blank=True,
                help_text="Title is used to generate the summary/name of the Field Report. </br>The summary is constructed as: <b><i>Country IS03: Disaster Type - Start Date - Title - Field Report Number - (date)</b><i>",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fieldreport",
            name="title_fr",
            field=models.CharField(
                blank=True,
                help_text="Title is used to generate the summary/name of the Field Report. </br>The summary is constructed as: <b><i>Country IS03: Disaster Type - Start Date - Title - Field Report Number - (date)</b><i>",
                max_length=256,
                null=True,
            ),
        ),
    ]
