# Generated by Django 4.2.17 on 2025-02-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0218_remove_event_title_remove_event_title_ar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="skip_auto_generate_name",
            field=models.BooleanField(
                default=False, help_text="<b>If checked, the name of the Emergency will not be auto-generated. </b>"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Title is used to generate the name of the Emergency. </br>The name is constructed as: <b><i>Country IS03 or Name: Disaster Type - Start Date - Title</b><i>",
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_ar",
            field=models.CharField(
                blank=True,
                help_text="Title is used to generate the name of the Emergency. </br>The name is constructed as: <b><i>Country IS03 or Name: Disaster Type - Start Date - Title</b><i>",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Title is used to generate the name of the Emergency. </br>The name is constructed as: <b><i>Country IS03 or Name: Disaster Type - Start Date - Title</b><i>",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_es",
            field=models.CharField(
                blank=True,
                help_text="Title is used to generate the name of the Emergency. </br>The name is constructed as: <b><i>Country IS03 or Name: Disaster Type - Start Date - Title</b><i>",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_fr",
            field=models.CharField(
                blank=True,
                help_text="Title is used to generate the name of the Emergency. </br>The name is constructed as: <b><i>Country IS03 or Name: Disaster Type - Start Date - Title</b><i>",
                max_length=256,
                null=True,
            ),
        ),
    ]
