# Generated by Django 4.2.19 on 2025-08-01 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0219_alter_appealfilter_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ifrc_severity_level_update_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="ifrc severity level update date"),
        ),
        migrations.CreateModel(
            name="EventSeverityLevelHistory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ifrc_severity_level",
                    models.IntegerField(
                        choices=[(0, "Yellow"), (1, "Orange"), (2, "Red")], default=0, verbose_name="IFRC Severity level"
                    ),
                ),
                (
                    "ifrc_severity_level_update_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="ifrc severity level update date"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_by_ifrc_severity_level",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.event", verbose_name="event")),
            ],
        ),
    ]
