# Generated by Django 4.2.19 on 2025-09-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0220_event_ifrc_severity_level_update_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nsdinitiatives",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="nsdinitiatives",
            name="remote_id",
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="nsdinitiatives",
            name="title_ar",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="nsdinitiatives",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="nsdinitiatives",
            name="title_es",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="nsdinitiatives",
            name="title_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="nsdinitiatives",
            name="translation_module_original_language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Spanish"), ("fr", "French"), ("ar", "Arabic")],
                default="en",
                help_text="Language used to create this entity",
                max_length=2,
                verbose_name="Entity Original language",
            ),
        ),
        migrations.AddField(
            model_name="nsdinitiatives",
            name="translation_module_skip_auto_translation",
            field=models.BooleanField(
                default=False, help_text="Skip auto translation operation for this entity?", verbose_name="Skip auto translation"
            ),
        ),
    ]
