# Generated by Django 4.2.19 on 2025-08-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0220_event_ifrc_severity_level_update_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="export",
            name="export_type",
            field=models.CharField(
                choices=[
                    ("dref-applications", "DREF Applications"),
                    ("dref-operational-updates", "DREF Operational Updates"),
                    ("dref-final-reports", "DREF Final Reports"),
                    ("old-dref-final-reports", "Old DREF Final Reports"),
                    ("per", "Per"),
                ],
                max_length=255,
                verbose_name="Export Type",
            ),
        ),
    ]
