# Generated by Django 4.2.19 on 2025-08-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0222_rename_ifrc_staff_fieldreport_emergency_response_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldreport",
            name="emergency_response_unit",
            field=models.IntegerField(
                choices=[(0, "No"), (1, "Requested"), (2, "Planned"), (3, "Completed")],
                default=0,
                null=True,
                verbose_name="Emergency Response Unit",
            ),
        ),
        migrations.AlterField(
            model_name="fieldreport",
            name="num_emergency_response_unit",
            field=models.IntegerField(blank=True, null=True, verbose_name="Number of Emergency Response Units"),
        ),
    ]
