# Generated by Django 4.2.19 on 2025-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0223_alter_fieldreport_emergency_response_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsdinitiatives",
            name="nsia_risk",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="NSIA Risk"),
        ),
    ]
