# Generated by Django 4.2.19 on 2025-09-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0224_nsdinitiatives_nsia_risk"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsdinitiatives",
            name="nsia_risk_ar",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="NSIA Risk"),
        ),
        migrations.AddField(
            model_name="nsdinitiatives",
            name="nsia_risk_en",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="NSIA Risk"),
        ),
        migrations.AddField(
            model_name="nsdinitiatives",
            name="nsia_risk_es",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="NSIA Risk"),
        ),
        migrations.AddField(
            model_name="nsdinitiatives",
            name="nsia_risk_fr",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="NSIA Risk"),
        ),
    ]
