# Generated by Django 4.2.19 on 2025-09-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0225_nsdinitiatives_nsia_risk_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSDInitiativesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'NSD initiative category',
                'verbose_name_plural': 'NSD initiative categories',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='nsdinitiatives',
            name='categories',
        ),
        migrations.AddField(
            model_name='nsdinitiatives',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='initiatives', to='api.nsdinitiativescategory', verbose_name='Funding categories'),
        ),
        migrations.AddField(
            model_name='nsdinitiativescategory',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], db_index=True, default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='nsdinitiativescategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='nsdinitiativescategory',
            unique_together={('name', 'lang')},
        ),
    ]
