# Generated by Django 4.2.26 on 2026-01-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0226_nsdinitiativescategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="export",
            name="export_type",
            field=models.CharField(
                choices=[
                    ("dref-applications", "DREF Application"),
                    ("dref-operational-updates", "DREF Operational Update"),
                    ("dref-final-reports", "DREF Final Report"),
                    ("old-dref-final-reports", "Old DREF Final Report"),
                    ("per", "Per"),
                    ("simplified", "Simplified EAP"),
                    ("full", "Full EAP"),
                ],
                max_length=255,
                verbose_name="Export Type",
            ),
        ),
    ]
