# Generated by Django 4.2.26 on 2026-01-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0226_nsdinitiativescategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventseveritylevelhistory',
            options={'verbose_name': 'emergency severity level history', 'verbose_name_plural': 'emergency severity level histories'},
        ),
    ]
