# Generated by Django 4.2.26 on 2025-12-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0227_dimagreementline_dimappeal_dimbuyergroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimappeal',
            options={'managed': False, 'verbose_name': 'Appeal', 'verbose_name_plural': 'Appeals'},
        ),
        migrations.AlterField(
            model_name='diminventorytransactionorigin',
            name='excluded_from_inventory_value',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Excluded From Inventory Value'),
        ),
    ]
