# Generated by Django 4.2.26 on 2026-01-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0227_alter_eventseveritylevelhistory_options'),
        ('api', '0227_alter_export_export_type'),
    ]

    operations = [
    ]
