# Generated by Django 4.2.26 on 2025-12-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0228_alter_dimappeal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimproduct',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterModelTable(
            name='dimappeal',
            table='api_dimappeal',
        ),
    ]