# Generated by Django 4.2.27 on 2026-02-05 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0228_crisiscategorisationbycountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='capacity_and_response_ifrc_international_staff',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='IFRC International staff'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='capacity_and_response_ifrc_national_staff',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='IFRC National staff'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='capacity_and_response_ifrc_total_staff',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='IFRC Total staff'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='capacity_and_response_number_of_dref_ea_last_3_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='# DREF and EA in the last 3 years'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='capacity_and_response_number_of_ns_staff',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Number of NS staff (FDRS) 2025'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='capacity_and_response_number_of_ns_volunteer',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Number of NS volunteer (FDRS)'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='capacity_and_response_ops_capacity_ranking',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Ops capacity Ranking (IFRC Global Risk - 2021)'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='capacity_and_response_ratio_staff_volunteer',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Ratio staff volunteer'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='capacity_and_response_regional_office',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Regional Office'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='crisis_complexity_humanitarian_access_acaps',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Humanitarian access ACAPS (complex crisis)'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='humanitarian_conditions_casualties_injrd_deaths_missing',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='casualties injured + deaths + missing'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='humanitarian_conditions_people_in_need',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='# People in need'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='humanitarian_conditions_severity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='severity'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='pre_crisis_vulnerability_coping_mechanism_intermediate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='coping mechanism (intermediate score)'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='pre_crisis_vulnerability_hazard_exposure_intermediate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='hazard exposure (intermediate score)'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='pre_crisis_vulnerability_vulnerability_intermediate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='vulnerability (intermediate score)'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='scope_and_scale_impact_index_inform',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='impact index INFORM'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='scope_and_scale_number_of_affected_population',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)], verbose_name='# Affected population'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='scope_and_scale_percentage_affected_population',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% of Affected population'),
        ),
        migrations.AlterField(
            model_name='crisiscategorisationbycountry',
            name='scope_and_scale_total_population_of_the_affected_area',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='total population of the affected area *'),
        ),
    ]
