# Generated by Django 4.2.26 on 2025-12-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0229_alter_dimproduct_name_alter_dimappeal_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimsalesorderline',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]