# Generated by Django 4.2.27 on 2026-02-13 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0229_alter_crisiscategorisationbycountry_capacity_and_response_ifrc_international_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtgeoms',
            name='district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.district', verbose_name='district'),
        ),
    ]
