# Generated by Django 4.2.26 on 2026-01-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0228_dimdeliverymode_dimdonor_diminventoryitem_and_more'),
        ('api', '0230_alter_dimsalesorderline_description'),
    ]

    operations = [
    ]
