# Generated by Django 4.2.26 on 2026-01-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0230_alter_dimsalesorderline_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimagreementline',
            name='committed_amount',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=30, null=True, verbose_name='Committed Amount'),
        ),
        migrations.AlterField(
            model_name='dimagreementline',
            name='committed_quantity',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=30, null=True, verbose_name='Committed Quantity'),
        ),
        migrations.AlterField(
            model_name='dimagreementline',
            name='line_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=30, null=True, verbose_name='Line Discount Percent'),
        ),
        migrations.AlterField(
            model_name='dimagreementline',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=30, null=True, verbose_name='Price Per Unit'),
        ),
    ]
