# Generated by Django 4.2.30 on 2026-05-21 04:49

from django.db import migrations, models


def migrate_sources(apps, _):
    """
    Populate the source field for Event records:
    - Non auto generated events are mapped to MANUAL_INPUT.
    - Events that are auto generated and have auto_generated_source are mapped to the corresponding enum value.
    - Events that are auto generated but do not have auto_generated_source are mapped to MANUAL_INPUT.
    - For WHO, the who_guid field is populated with the id extracted from the auto_generated_source field.
    """

    Event = apps.get_model("api", "Event")

    for obj in Event.objects.iterator():
        update_fields = ["source"]

        if not obj.auto_generated:
            source = 100  # MANUAL_INPUT

        else:
            raw_source = (obj.auto_generated_source or "").lower()
            if "gdacs" in raw_source:
                source = 110 # GDACS

            elif "who.int" in raw_source:
                source = 120

                parts = raw_source.strip().split(".")
                who_id = parts[-1].strip()

                try:
                    obj.who_guid = int(who_id)
                    update_fields.append("who_guid")
                except (ValueError, TypeError):
                    pass
            elif "field report dmis ingest" in raw_source:
                source = 130 # FIELD_REPORT_DMIS_INGEST
            elif "field report admin" in raw_source:
                source = 140 # FIELD_REPORT_ADMIN
            elif "appeal" in raw_source:
                source = 150 # APPEAL_ADMIN
            elif "new field report" in raw_source:
                source = 160 # NEW_FIELD_REPORT
            else:
                # Using title for backward compatibility, as some events have auto_generated_source empty but title containing "GDACS"
                if obj.name and obj.name.lower().startswith("gdacs"):
                    source = 110  # GDACS
                else:
                    source = 100  # MANUAL_INPUT
                    obj.auto_generated = False
                    update_fields.append("auto_generated")
        obj.source = source
        obj.save(update_fields=update_fields)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0231_alter_export_export_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="source",
            field=models.IntegerField(
                choices=[
                    (100, "Manual input"),
                    (110, "GDACs scraper"),
                    (120, "WHO scraper"),
                    (130, "Field report DMIS ingest"),
                    (140, "Field report admin"),
                    (150, "Appeal admin"),
                    (160, "New field report"),
                    (170, "DREF"),
                ],
                default=100,
                verbose_name="Event source",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="who_guid",
            field=models.IntegerField(blank=True, null=True, verbose_name="Who guid"),
        ),
        migrations.RunPython(migrate_sources, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="event",
            name="auto_generated_source",
        ),
    ]
