# Generated by Django 5.2.14 on 2026-06-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0231_alter_export_export_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_generated_external_source',
            field=models.CharField(blank=True, help_text='External source or system from which the original event data originated.', max_length=100, null=True, verbose_name='external source'),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_generated_external_source_id',
            field=models.CharField(blank=True, help_text='Unique identifier of the event record in the external source system.', max_length=100, null=True, verbose_name='external source ID'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='external_source',
            field=models.CharField(blank=True, help_text='External source system from which this field report created.', max_length=100, null=True, verbose_name='external source'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='external_source_id',
            field=models.CharField(blank=True, help_text='Unique identifier of this field report in the external source system.', max_length=100, null=True, verbose_name='external source ID'),
        ),
    ]
