# Generated by Django 4.2.26 on 2026-01-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0232_alter_dimappeal_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCodeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Item Code')),
                ('url', models.URLField(max_length=500, verbose_name='Item URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item Code Mapping',
                'verbose_name_plural': 'Item Code Mappings',
                'ordering': ('code',),
            },
        ),
    ]
