# Generated by Django 4.2.26 on 2026-01-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0232_alter_dimappeal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimagreementline',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='Effective Date'),
        ),
        migrations.AlterField(
            model_name='dimagreementline',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
    ]
