# Generated by Django 4.2.26 on 2026-01-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0233_alter_dimagreementline_effective_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diminventorytransactionline',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Date'),
        ),
        migrations.AlterField(
            model_name='diminventorytransactionline',
            name='financial_date',
            field=models.DateField(blank=True, null=True, verbose_name='Financial Date'),
        ),
        migrations.AlterField(
            model_name='diminventorytransactionline',
            name='physical_date',
            field=models.DateField(blank=True, null=True, verbose_name='Physical Date'),
        ),
        migrations.AlterField(
            model_name='diminventorytransactionline',
            name='status_date',
            field=models.DateField(blank=True, null=True, verbose_name='Status Date'),
        ),
        migrations.AlterField(
            model_name='dimitembatch',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='dimitembatch',
            name='vendor_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vendor Expiration Date'),
        ),
        migrations.AlterField(
            model_name='dimpackingslipline',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='dimpurchaseorderline',
            name='confirmed_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Confirmed Delivery Date'),
        ),
        migrations.AlterField(
            model_name='dimpurchaseorderline',
            name='requested_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Requested Delivery Date'),
        ),
        migrations.AlterField(
            model_name='dimsalesorderline',
            name='requested_receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Requested Receipt Date'),
        ),
        migrations.AlterField(
            model_name='dimsalesorderline',
            name='requested_shipping_date',
            field=models.DateField(blank=True, null=True, verbose_name='Requested Shipping Date'),
        ),
        migrations.AlterField(
            model_name='dimvendorphysicaladdress',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='dimvendorphysicaladdress',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='Valid To'),
        ),
    ]
