# Generated by Django 4.2.26 on 2026-01-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0234_alter_diminventorytransactionline_expected_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimconsignment',
            name='delivery_mode',
            field=models.CharField(max_length=100, null=True, verbose_name='Delivery Mode'),
        ),
    ]
