# Generated by Django 4.2.26 on 2026-01-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0236_merge_20260126_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanedFrameworkAgreements',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agreement_id', models.CharField(db_index=True, max_length=100, verbose_name='Agreement ID')),
                ('classification', models.CharField(blank=True, max_length=128, null=True, verbose_name='Classification')),
                ('default_agreement_line_effective_date', models.DateField(blank=True, null=True, verbose_name='Default Agreement Line Effective Date')),
                ('default_agreement_line_expiration_date', models.DateField(blank=True, null=True, verbose_name='Default Agreement Line Expiration Date')),
                ('workflow_status', models.CharField(blank=True, max_length=64, null=True, verbose_name='Workflow Status')),
                ('status', models.CharField(blank=True, max_length=64, null=True, verbose_name='Status')),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True, verbose_name='Price Per Unit')),
                ('pa_line_procurement_category', models.CharField(blank=True, max_length=128, null=True, verbose_name='PA Line Procurement Category')),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vendor Name')),
                ('vendor_country', models.CharField(blank=True, max_length=8, null=True, verbose_name='Vendor Country')),
                ('region_countries_covered', models.CharField(blank=True, max_length=255, null=True, verbose_name='Region / Countries Covered')),
                ('item_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='Item Type')),
                ('item_category', models.CharField(blank=True, max_length=128, null=True, verbose_name='Item Category')),
                ('item_service_short_description', models.TextField(blank=True, null=True, verbose_name='Item / Service Short Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cleaned Framework Agreement',
                'verbose_name_plural': 'Cleaned Framework Agreements',
            },
        ),
        migrations.AlterUniqueTogether(
            name='frameworkagreementcountry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='frameworkagreementcountry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='frameworkagreementcountry',
            name='framework_agreement',
        ),
        migrations.RemoveField(
            model_name='frameworkagreementlineitem',
            name='framework_agreement',
        ),
        migrations.DeleteModel(
            name='FrameworkAgreement',
        ),
        migrations.DeleteModel(
            name='FrameworkAgreementCountry',
        ),
        migrations.DeleteModel(
            name='FrameworkAgreementLineItem',
        ),
    ]
