# Generated by Django 4.2.26 on 2026-01-31 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0237_cleanedframeworkagreements_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CleanedFrameworkAgreements',
            new_name='CleanedFrameworkAgreement',
        ),
    ]
