# Generated by Django 4.2.26 on 2026-02-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0238_rename_cleanedframeworkagreements_cleanedframeworkagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanedframeworkagreement',
            name='owner',
            field=models.CharField(default='', max_length=255, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='cleanedframeworkagreement',
            name='vendor_valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vendor Valid From'),
        ),
        migrations.AddField(
            model_name='cleanedframeworkagreement',
            name='vendor_valid_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vendor Valid To'),
        ),
        migrations.AlterField(
            model_name='cleanedframeworkagreement',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=35, null=True, verbose_name='Price Per Unit'),
        ),
    ]
