# Generated by Django 4.2.26 on 2026-03-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0242_alter_cleanedframeworkagreement_agreement_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.CharField(db_index=True, max_length=100, verbose_name='Warehouse ID')),
                ('warehouse', models.CharField(max_length=255, verbose_name='Warehouse Name')),
                ('warehouse_country', models.CharField(db_index=True, max_length=100, verbose_name='Warehouse Country')),
                ('product_category', models.CharField(max_length=255, verbose_name='Product Category')),
                ('item_name', models.TextField(verbose_name='Item Name')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Aggregated quantity in stock', max_digits=18, verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Stock Inventory',
                'verbose_name_plural': 'Stock Inventories',
                'ordering': ['warehouse', 'product_category', '-quantity'],
                'indexes': [models.Index(fields=['warehouse_id', 'warehouse_country'], name='stock_warehouse_idx'), models.Index(fields=['product_category'], name='stock_category_idx')],
            },
        ),
    ]
