# Generated by Django 4.2.26 on 2026-03-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0242_remove_export_regulations_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycustomssnapshot',
            name='official_doc_title',
            field=models.CharField(blank=True, help_text='Title of the official customs documentation', max_length=500),
        ),
        migrations.AddField(
            model_name='countrycustomssnapshot',
            name='official_doc_url',
            field=models.URLField(blank=True, help_text="URL to the country's official customs documentation", max_length=2048),
        ),
    ]
