# Generated by Django 4.2.26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0243_add_official_doc_to_customs_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycustomssnapshot',
            name='rc_society_url',
            field=models.URLField(blank=True, help_text="URL to the country's Red Cross/Red Crescent society page", max_length=2048),
        ),
        migrations.AddField(
            model_name='countrycustomssnapshot',
            name='rc_society_title',
            field=models.CharField(blank=True, help_text='Title of the Red Cross/Red Crescent society page', max_length=500),
        ),
    ]
