# Generated by Django 4.2.26 on 2026-03-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0243_stockinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinventory',
            name='unit_measurement',
            field=models.CharField(blank=True, help_text='Unit of measure (e.g., ea, kg, m)', max_length=50, null=True, verbose_name='Unit of Measurement'),
        ),
    ]
