# Generated by Django 4.2.26 on 2026-03-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0244_stockinventory_unit_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinventory',
            name='catalogue_link',
            field=models.TextField(blank=True, help_text='URL to item catalogue or product information', null=True, verbose_name='Catalogue Link'),
        ),
        migrations.AddField(
            model_name='stockinventory',
            name='region',
            field=models.CharField(blank=True, help_text='Geographical region (e.g., Asia Pacific, Americas)', max_length=255, null=True, verbose_name='Region'),
        ),
    ]
