# Generated by Django 4.2.26 on 2026-03-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0244_add_rc_society_to_customs_snapshot'),
        ('api', '0245_add_region_and_catalogue_link_to_stockinventory'),
    ]

    operations = [
    ]
