# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2

references:

  container_python36: &container_python36
    docker:
      - image: circleci/python:3.6.2
    working_dir: ~/project

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v0-repo-{{ .Branch }}-{{ .Revision }}
        - v0-repo-{{ .Branch }}
        - v0-repo

jobs:

  checkout_code:
    <<: *container_python36
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v0-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project

  install_and_test:
    <<: *container_python36
    steps:  
      - *restore_repo
      - restore_cache:
          keys: 
            - v0-dependencies36-{{ checksum "requirements.txt"}}
            - v0-dependencies36
      - run: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements.txt
            nosetests -v --with-coverage --cover-package api
      - save_cache:
          key: v0-dependencies36-{{ checksum "requirements.txt"}}
          paths:
            - ~/venv

  deploy:
    <<: *container_python36
    steps:
      - *restore_repo
      - restore_cache:
          keys: 
            - v0-dependencies36-{{ checksum "requirements.txt"}}
            - v0-dependencies36
      - run:
          name: Deploy
          command: |
            . ~/venv/bin/activate
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            VERSION=`awk -F\' '{print $2,$4}' main/__init__.py`
            git tag $VERSION
            git push origin $VERSION


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - checkout_code
      - install_and_test:
          requires:
            - checkout_code
      - deploy:
          requires:
            - install_and_test
          filters:
            branches:
              only: master
