# Python CircleCI 2.1 configuration file
version: 2.1

jobs:
  build:
    machine:
      # Check https://circleci.com/developer/machine/image/ubuntu-2004 for details:
      image: ubuntu-2004:202201-02
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: build docker base image
          command: |
            export DOCKER_BUILDKIT=1
            cp .env-sample .env
            docker-compose build --progress plain serve
            docker-compose pull db redis
      - run:
          name: Validate if there are no pending django migrations.
          command: |
            docker-compose run --rm serve ./manage.py makemigrations --check --dry-run || {
              echo 'There are some changes to be reflected in the migration. Make sure to run makemigrations';
              exit 1;
            }
      - run:
          name: Run tests
          command: |
            docker-compose run --rm serve ./manage.py test --keepdb -v 2 --pattern="test_fake.py" &&
            docker-compose run --rm serve pytest --reuse-db --durations=10
      - run:
          name: Push image to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "develop" ]|| [ "${CIRCLE_BRANCH}" == "remotetest" ]; then
              {
                if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                  LATEST_GIT_TAG=develop &&
                  echo $LATEST_GIT_TAG
                elif [ "${CIRCLE_BRANCH}" == "remotetest" ]; then
                  LATEST_GIT_TAG=remotetest &&
                  echo $LATEST_GIT_TAG
                else
                  LATEST_GIT_TAG=$(git describe --tags --abbrev=0 --match 1.*) &&
                  echo $LATEST_GIT_TAG
                  git checkout tags/$LATEST_GIT_TAG -b latest_git_tag
                fi

                docker-compose build
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                docker tag ifrcgo/go-api:latest ifrcgo/go-api:$LATEST_GIT_TAG
                docker push ifrcgo/go-api:$LATEST_GIT_TAG
              } || {
                echo 'No tag matching the condition found'
              }
            fi
