# Generated by Django 2.2.27 on 2022-07-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eap", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EAPRefrence",
            new_name="EAPReference",
        ),
        migrations.AlterModelOptions(
            name="eapreference",
            options={"verbose_name": "EAP Reference", "verbose_name_plural": "EAP References"},
        ),
    ]
