# Generated by Django 4.2.30 on 2026-04-16 08:35

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0231_alter_export_export_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eap", "0002_auto_20220708_0747"),
    ]

    operations = [
        migrations.CreateModel(
            name="EAPAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(max_length=255, verbose_name="Early Action"),
                ),
                (
                    "previous_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Previous ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Early Action",
                "verbose_name_plural": "Early Actions",
            },
        ),
        migrations.CreateModel(
            name="EAPContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Contact Name")),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="Contact Email"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Contact Title",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Contact Phone Number",
                    ),
                ),
                (
                    "previous_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Previous ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "EAP Contact",
                "verbose_name_plural": "EAP Contacts",
            },
        ),
        migrations.CreateModel(
            name="EAPFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "file",
                    main.fields.SecureFileField(
                        help_text="Upload EAP related file.",
                        upload_to="eap/files/",
                        verbose_name="file",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "eap file",
                "verbose_name_plural": "eap files",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="EAPImpact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impact", models.CharField(max_length=255, verbose_name="Impact")),
                (
                    "previous_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Previous ID"
                    ),
                ),
            ],
            options={
                "verbose_name": " Impact",
                "verbose_name_plural": "Expected Impacts",
            },
        ),
        migrations.CreateModel(
            name="EAPRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "eap_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(10, "Full EAP"), (20, "Simplified EAP")],
                        help_text="Select the type of EAP.",
                        null=True,
                        verbose_name="EAP Type",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (10, "Under Development"),
                            (20, "Under Review"),
                            (30, "NS Addressing Comments"),
                            (40, "Technically Validated"),
                            (50, "Approved(Pending PFA)"),
                            (60, "Approved"),
                        ],
                        default=10,
                        help_text="Select the current status of the EAP development process.",
                        verbose_name="EAP Status",
                    ),
                ),
                (
                    "expected_submission_time",
                    models.DateField(
                        blank=True,
                        help_text="Include the propose time of submission, accounting for the time it will take to deliver the application.Leave blank if not sure.",
                        null=True,
                        verbose_name="Expected submission time",
                    ),
                ),
                (
                    "validated_budget_file",
                    main.fields.SecureFileField(
                        blank=True,
                        help_text="Upload the validated budget file once the EAP is technically validated.",
                        null=True,
                        upload_to="eap/files/validated_budgets/",
                        verbose_name="Validated Budget File",
                    ),
                ),
                (
                    "summary_file",
                    main.fields.SecureFileField(
                        blank=True,
                        null=True,
                        upload_to="eap/files/",
                        verbose_name="EAP Summary PDF",
                    ),
                ),
                (
                    "national_society_contact_name",
                    models.CharField(
                        max_length=255, verbose_name="national society contact name"
                    ),
                ),
                (
                    "national_society_contact_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="national society contact title",
                    ),
                ),
                (
                    "national_society_contact_email",
                    models.CharField(
                        max_length=255, verbose_name="national society contact email"
                    ),
                ),
                (
                    "national_society_contact_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="national society contact phone number",
                    ),
                ),
                (
                    "ifrc_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC contact name ",
                    ),
                ),
                (
                    "ifrc_contact_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC contact email",
                    ),
                ),
                (
                    "ifrc_contact_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC contact title",
                    ),
                ),
                (
                    "ifrc_contact_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="IFRC contact phone number",
                    ),
                ),
                (
                    "dref_focal_point_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="dref focal point name",
                    ),
                ),
                (
                    "dref_focal_point_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Dref focal point email",
                    ),
                ),
                (
                    "dref_focal_point_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Dref focal point title",
                    ),
                ),
                (
                    "dref_focal_point_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Dref focal point phone number",
                    ),
                ),
                (
                    "technically_validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the EAP was technically validated.",
                        null=True,
                        verbose_name="technically validated at",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the EAP was approved.",
                        null=True,
                        verbose_name="approved at",
                    ),
                ),
                (
                    "pending_pfa_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the EAP was marked as pending PFA.",
                        null=True,
                        verbose_name="pending pfa at",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True,
                        help_text="Date by which the EAP submission must be completed.",
                        null=True,
                        verbose_name="deadline",
                    ),
                ),
                (
                    "deadline_remainder_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the deadline reminder email was sent.",
                        null=True,
                        verbose_name="deadline reminder email sent at",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="The country will be pre-populated based on the NS selection, but can be adapted as needed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="development_registration_eap_country",
                        to="api.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "disaster_type",
                    models.ForeignKey(
                        help_text="Select the disaster type for which the EAP is needed",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.disastertype",
                        verbose_name="Disaster Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Development Registration EAP",
                "verbose_name_plural": "Development Registration EAPs",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="EnablingApproach",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approach",
                    models.IntegerField(
                        choices=[
                            (10, "Secretariat Services"),
                            (20, "National Society Strengthening"),
                            (30, "Partnership And Coordination"),
                        ],
                        verbose_name="Approach",
                    ),
                ),
                (
                    "budget_per_approach",
                    models.IntegerField(verbose_name="Budget per approach (CHF)"),
                ),
                (
                    "previous_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Previous ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Enabling Approach",
                "verbose_name_plural": "Enabling Approaches",
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Indicator Title"),
                ),
                ("target", models.IntegerField(verbose_name="Indicator Target")),
                (
                    "previous_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Previous ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicator",
                "verbose_name_plural": "Indicators",
            },
        ),
        migrations.CreateModel(
            name="OperationActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity", models.CharField(max_length=255, verbose_name="Activity")),
                (
                    "timeframe",
                    models.IntegerField(
                        choices=[
                            (10, "Years"),
                            (20, "Months"),
                            (30, "Days"),
                            (40, "Hours"),
                        ],
                        verbose_name="Timeframe",
                    ),
                ),
                (
                    "time_value",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        size=None,
                        verbose_name="Activity time span",
                    ),
                ),
                (
                    "previous_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Previous ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation Activity",
                "verbose_name_plural": "Operation Activities",
            },
        ),
        migrations.CreateModel(
            name="PlannedOperation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sector",
                    models.IntegerField(
                        choices=[
                            (101, "Shelter, Settlement and Housing"),
                            (102, "Livelihoods"),
                            (103, "Protection, Gender and Inclusion"),
                            (104, "Health and Care"),
                            (105, "Risk Reduction, Climate Adaptation and Recovery"),
                            (106, "Multipurpose Cash"),
                            (107, "Water, Sanitation And Hygiene"),
                            (109, "Education"),
                            (110, "Migration"),
                            (111, "Environment Sustainability"),
                            (112, "Community Engagement And Accountability"),
                        ],
                        verbose_name="sector",
                    ),
                ),
                (
                    "people_targeted",
                    models.IntegerField(verbose_name="People Targeted"),
                ),
                (
                    "budget_per_sector",
                    models.IntegerField(verbose_name="Budget per sector (CHF)"),
                ),
                (
                    "previous_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Previous ID"
                    ),
                ),
                (
                    "early_action_activities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="planned_operations_early_action_activities",
                        to="eap.operationactivity",
                        verbose_name="Early Action Activities",
                    ),
                ),
                (
                    "indicators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="planned_operation_indicators",
                        to="eap.indicator",
                        verbose_name="Operation Indicators",
                    ),
                ),
                (
                    "prepositioning_activities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="planned_operations_prepositioning_activities",
                        to="eap.operationactivity",
                        verbose_name="Pre-positioning Activities",
                    ),
                ),
                (
                    "readiness_activities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="planned_operations_readiness_activities",
                        to="eap.operationactivity",
                        verbose_name="Readiness Activities",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planned Operation",
                "verbose_name_plural": "Planned Operations",
            },
        ),
        migrations.CreateModel(
            name="SourceInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(max_length=255, verbose_name="Source Name"),
                ),
                (
                    "source_link",
                    models.URLField(max_length=255, verbose_name="Source Link"),
                ),
                (
                    "previous_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Previous ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Source of Information",
                "verbose_name_plural": "Source of Information",
            },
        ),
        migrations.CreateModel(
            name="SimplifiedEAP",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "people_targeted",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="People Targeted."
                    ),
                ),
                (
                    "national_society_contact_name",
                    models.CharField(
                        max_length=255, verbose_name="national society contact name"
                    ),
                ),
                (
                    "national_society_contact_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="national society contact title",
                    ),
                ),
                (
                    "national_society_contact_email",
                    models.CharField(
                        max_length=255, verbose_name="national society contact email"
                    ),
                ),
                (
                    "national_society_contact_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="national society contact phone number",
                    ),
                ),
                (
                    "ifrc_delegation_focal_point_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC delegation focal point name",
                    ),
                ),
                (
                    "ifrc_delegation_focal_point_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC delegation focal point email",
                    ),
                ),
                (
                    "ifrc_delegation_focal_point_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC delegation focal point title",
                    ),
                ),
                (
                    "ifrc_delegation_focal_point_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="IFRC delegation focal point phone number",
                    ),
                ),
                (
                    "ifrc_head_of_delegation_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC head of delegation name",
                    ),
                ),
                (
                    "ifrc_head_of_delegation_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC head of delegation email",
                    ),
                ),
                (
                    "ifrc_head_of_delegation_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC head of delegation title",
                    ),
                ),
                (
                    "ifrc_head_of_delegation_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="IFRC head of delegation phone number",
                    ),
                ),
                (
                    "dref_focal_point_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="dref focal point name",
                    ),
                ),
                (
                    "dref_focal_point_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Dref focal point email",
                    ),
                ),
                (
                    "dref_focal_point_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Dref focal point title",
                    ),
                ),
                (
                    "dref_focal_point_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Dref focal point phone number",
                    ),
                ),
                (
                    "ifrc_regional_focal_point_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional focal point name",
                    ),
                ),
                (
                    "ifrc_regional_focal_point_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional focal point email",
                    ),
                ),
                (
                    "ifrc_regional_focal_point_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional focal point title",
                    ),
                ),
                (
                    "ifrc_regional_focal_point_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="IFRC regional focal point phone number",
                    ),
                ),
                (
                    "ifrc_regional_ops_manager_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional ops manager name",
                    ),
                ),
                (
                    "ifrc_regional_ops_manager_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional ops manager email",
                    ),
                ),
                (
                    "ifrc_regional_ops_manager_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional ops manager title",
                    ),
                ),
                (
                    "ifrc_regional_ops_manager_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="IFRC regional ops manager phone number",
                    ),
                ),
                (
                    "ifrc_regional_head_dcc_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional head of DCC name",
                    ),
                ),
                (
                    "ifrc_regional_head_dcc_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional head of DCC email",
                    ),
                ),
                (
                    "ifrc_regional_head_dcc_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional head of DCC title",
                    ),
                ),
                (
                    "ifrc_regional_head_dcc_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="IFRC regional head of DCC phone number",
                    ),
                ),
                (
                    "ifrc_global_ops_coordinator_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC global ops coordinator name",
                    ),
                ),
                (
                    "ifrc_global_ops_coordinator_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC global ops coordinator email",
                    ),
                ),
                (
                    "ifrc_global_ops_coordinator_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC global ops coordinator title",
                    ),
                ),
                (
                    "ifrc_global_ops_coordinator_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="IFRC global ops coordinator phone number",
                    ),
                ),
                (
                    "export_file",
                    main.fields.SecureFileField(
                        blank=True,
                        null=True,
                        upload_to="eap/files/exports/",
                        verbose_name="EAP Export File",
                    ),
                ),
                (
                    "diff_file",
                    main.fields.SecureFileField(
                        blank=True,
                        null=True,
                        upload_to="eap/files/",
                        verbose_name="EAP Diff PDF file",
                    ),
                ),
                (
                    "review_checklist_file",
                    main.fields.SecureFileField(
                        blank=True,
                        null=True,
                        upload_to="eap/files/",
                        verbose_name="Review Checklist File",
                    ),
                ),
                (
                    "total_budget",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Budget (CHF)"
                    ),
                ),
                (
                    "readiness_budget",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Readiness Budget (CHF)"
                    ),
                ),
                (
                    "pre_positioning_budget",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Pre-positioning Budget (CHF)",
                    ),
                ),
                (
                    "early_action_budget",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Early Actions Budget (CHF)"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="modified at"
                    ),
                ),
                (
                    "seap_timeframe",
                    models.IntegerField(
                        help_text="Timeframe of the EAP in years.",
                        verbose_name="Timeframe (Years) of the EAP",
                    ),
                ),
                (
                    "prioritized_hazard_and_impact",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Prioritized Hazard and its  historical impact.",
                    ),
                ),
                (
                    "risks_selected_protocols",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Risk selected for the protocols.",
                    ),
                ),
                (
                    "selected_early_actions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Selected Early Actions"
                    ),
                ),
                (
                    "overall_objective_intervention",
                    models.TextField(
                        blank=True,
                        help_text="Provide an objective statement that describe the main of the intervention.",
                        null=True,
                        verbose_name="Overall objective of the intervention",
                    ),
                ),
                (
                    "potential_geographical_high_risk_areas",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Potential geographical high-risk areas",
                    ),
                ),
                (
                    "assisted_through_operation",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Assisted through the operation",
                    ),
                ),
                (
                    "selection_criteria",
                    models.TextField(
                        blank=True,
                        help_text="Explain the selection criteria for who will be targeted",
                        null=True,
                        verbose_name="Selection Criteria.",
                    ),
                ),
                (
                    "trigger_statement",
                    models.TextField(
                        blank=True, null=True, verbose_name="Trigger Statement"
                    ),
                ),
                (
                    "seap_lead_timeframe_unit",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (10, "Years"),
                            (20, "Months"),
                            (30, "Days"),
                            (40, "Hours"),
                        ],
                        null=True,
                        verbose_name="sEAP Lead Timeframe Unit",
                    ),
                ),
                (
                    "seap_lead_time",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="sEAP Lead Time"
                    ),
                ),
                (
                    "operational_timeframe_unit",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (10, "Years"),
                            (20, "Months"),
                            (30, "Days"),
                            (40, "Hours"),
                        ],
                        default=20,
                        null=True,
                        verbose_name="Operational Timeframe Unit",
                    ),
                ),
                (
                    "operational_timeframe",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Operational Time"
                    ),
                ),
                (
                    "trigger_threshold_justification",
                    models.TextField(
                        blank=True,
                        help_text="Explain how the trigger were set and provide information",
                        null=True,
                        verbose_name="Trigger Threshold Justification",
                    ),
                ),
                (
                    "next_step_towards_full_eap",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Next Steps towards Full EAP",
                    ),
                ),
                (
                    "early_action_capability",
                    models.TextField(
                        blank=True,
                        help_text="Assumptions or minimum conditions needed to deliver the early actions.",
                        null=True,
                        verbose_name="Experience or Capacity to implement Early Action.",
                    ),
                ),
                (
                    "rcrc_movement_involvement",
                    models.TextField(
                        blank=True,
                        help_text="RCRC Movement partners, Governmental/other agencies consulted/involved.",
                        null=True,
                        verbose_name="RCRC Movement Involvement.",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Version identifier for the Simplified EAP.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the Simplified EAP is locked for editing.",
                        verbose_name="Is Locked?",
                    ),
                ),
                (
                    "admin2",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="api.admin2",
                        verbose_name="admin",
                    ),
                ),
                (
                    "budget_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eap.eapfile",
                        verbose_name="Budget File",
                    ),
                ),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="eap.eapfile",
                        verbose_name="cover image",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "eap_registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simplified_eaps",
                        to="eap.eapregistration",
                        verbose_name="EAP Development Registration",
                    ),
                ),
                (
                    "enabling_approaches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="simplified_eap_enabling_approaches",
                        to="eap.enablingapproach",
                        verbose_name="Enabling Approaches",
                    ),
                ),
                (
                    "hazard_impact_images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="simplified_eap_hazard_impact_images",
                        to="eap.eapfile",
                        verbose_name="Hazard Impact Images",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to the parent Simplified EAP if this is a snapshot.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="eap.simplifiedeap",
                        verbose_name="Parent Simplified EAP",
                    ),
                ),
                (
                    "partner_contacts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="eap.eapcontact",
                        verbose_name="Partner NS Contacts",
                    ),
                ),
                (
                    "partners",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select any partner NS involved in the EAP development.",
                        related_name="+",
                        to="api.country",
                        verbose_name="Partners",
                    ),
                ),
                (
                    "planned_operations",
                    models.ManyToManyField(
                        blank=True,
                        to="eap.plannedoperation",
                        verbose_name="Planned Operations",
                    ),
                ),
                (
                    "risk_selected_protocols_images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="simplified_eap_risk_selected_protocols_images",
                        to="eap.eapfile",
                        verbose_name="Risk Selected Protocols Images",
                    ),
                ),
                (
                    "selected_early_actions_images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="simplified_eap_selected_early_actions_images",
                        to="eap.eapfile",
                        verbose_name="Selected Early Actions Images",
                    ),
                ),
                (
                    "updated_checklist_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eap.eapfile",
                        verbose_name="Updated Review Checklist File",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simplified EAP",
                "verbose_name_plural": "Simplified EAPs",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="KeyActor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Describe this actor’s involvement.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "previous_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Previous ID"
                    ),
                ),
                (
                    "national_society",
                    models.ForeignKey(
                        help_text="Select the National Society involved in the EAP development.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eap_key_actors",
                        to="api.country",
                        verbose_name="EAP Actors",
                    ),
                ),
            ],
            options={
                "verbose_name": "Key Actor",
                "verbose_name_plural": "Key Actor",
            },
        ),
        migrations.CreateModel(
            name="FullEAP",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "people_targeted",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="People Targeted."
                    ),
                ),
                (
                    "national_society_contact_name",
                    models.CharField(
                        max_length=255, verbose_name="national society contact name"
                    ),
                ),
                (
                    "national_society_contact_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="national society contact title",
                    ),
                ),
                (
                    "national_society_contact_email",
                    models.CharField(
                        max_length=255, verbose_name="national society contact email"
                    ),
                ),
                (
                    "national_society_contact_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="national society contact phone number",
                    ),
                ),
                (
                    "ifrc_delegation_focal_point_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC delegation focal point name",
                    ),
                ),
                (
                    "ifrc_delegation_focal_point_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC delegation focal point email",
                    ),
                ),
                (
                    "ifrc_delegation_focal_point_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC delegation focal point title",
                    ),
                ),
                (
                    "ifrc_delegation_focal_point_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="IFRC delegation focal point phone number",
                    ),
                ),
                (
                    "ifrc_head_of_delegation_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC head of delegation name",
                    ),
                ),
                (
                    "ifrc_head_of_delegation_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC head of delegation email",
                    ),
                ),
                (
                    "ifrc_head_of_delegation_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC head of delegation title",
                    ),
                ),
                (
                    "ifrc_head_of_delegation_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="IFRC head of delegation phone number",
                    ),
                ),
                (
                    "dref_focal_point_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="dref focal point name",
                    ),
                ),
                (
                    "dref_focal_point_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Dref focal point email",
                    ),
                ),
                (
                    "dref_focal_point_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Dref focal point title",
                    ),
                ),
                (
                    "dref_focal_point_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Dref focal point phone number",
                    ),
                ),
                (
                    "ifrc_regional_focal_point_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional focal point name",
                    ),
                ),
                (
                    "ifrc_regional_focal_point_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional focal point email",
                    ),
                ),
                (
                    "ifrc_regional_focal_point_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional focal point title",
                    ),
                ),
                (
                    "ifrc_regional_focal_point_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="IFRC regional focal point phone number",
                    ),
                ),
                (
                    "ifrc_regional_ops_manager_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional ops manager name",
                    ),
                ),
                (
                    "ifrc_regional_ops_manager_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional ops manager email",
                    ),
                ),
                (
                    "ifrc_regional_ops_manager_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional ops manager title",
                    ),
                ),
                (
                    "ifrc_regional_ops_manager_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="IFRC regional ops manager phone number",
                    ),
                ),
                (
                    "ifrc_regional_head_dcc_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional head of DCC name",
                    ),
                ),
                (
                    "ifrc_regional_head_dcc_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional head of DCC email",
                    ),
                ),
                (
                    "ifrc_regional_head_dcc_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC regional head of DCC title",
                    ),
                ),
                (
                    "ifrc_regional_head_dcc_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="IFRC regional head of DCC phone number",
                    ),
                ),
                (
                    "ifrc_global_ops_coordinator_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC global ops coordinator name",
                    ),
                ),
                (
                    "ifrc_global_ops_coordinator_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC global ops coordinator email",
                    ),
                ),
                (
                    "ifrc_global_ops_coordinator_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IFRC global ops coordinator title",
                    ),
                ),
                (
                    "ifrc_global_ops_coordinator_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="IFRC global ops coordinator phone number",
                    ),
                ),
                (
                    "export_file",
                    main.fields.SecureFileField(
                        blank=True,
                        null=True,
                        upload_to="eap/files/exports/",
                        verbose_name="EAP Export File",
                    ),
                ),
                (
                    "diff_file",
                    main.fields.SecureFileField(
                        blank=True,
                        null=True,
                        upload_to="eap/files/",
                        verbose_name="EAP Diff PDF file",
                    ),
                ),
                (
                    "review_checklist_file",
                    main.fields.SecureFileField(
                        blank=True,
                        null=True,
                        upload_to="eap/files/",
                        verbose_name="Review Checklist File",
                    ),
                ),
                (
                    "total_budget",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Budget (CHF)"
                    ),
                ),
                (
                    "readiness_budget",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Readiness Budget (CHF)"
                    ),
                ),
                (
                    "pre_positioning_budget",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Pre-positioning Budget (CHF)",
                    ),
                ),
                (
                    "early_action_budget",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Early Actions Budget (CHF)"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="modified at"
                    ),
                ),
                (
                    "expected_submission_time",
                    models.DateField(
                        help_text="Include the propose time of submission, accounting for the time it will take to deliver the application.",
                        verbose_name="Expected submission time",
                    ),
                ),
                (
                    "objective",
                    models.TextField(
                        help_text="Provide an objective statement that describe the main goal of intervention.",
                        verbose_name="Overall Objective of the EAP.",
                    ),
                ),
                (
                    "is_worked_with_government",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Has Worked with government or other relevant actors.",
                    ),
                ),
                (
                    "worked_with_government_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Government and actors engagement description",
                    ),
                ),
                (
                    "is_technical_working_groups",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Are technical working groups in place",
                    ),
                ),
                (
                    "technically_working_group_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Technical working group title",
                    ),
                ),
                (
                    "technical_working_groups_in_place_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Technical working groups description",
                    ),
                ),
                (
                    "hazard_selection",
                    models.TextField(
                        blank=True,
                        help_text="Provide a brief rationale for selecting this hazard for the FbF system.",
                        null=True,
                        verbose_name="Hazard selection",
                    ),
                ),
                (
                    "exposed_element_and_vulnerability_factor",
                    models.TextField(
                        blank=True,
                        help_text="Explain which people are most likely to experience the impacts of this hazard.",
                        null=True,
                        verbose_name="Exposed elements and vulnerability factors",
                    ),
                ),
                (
                    "prioritized_impact",
                    models.TextField(
                        blank=True,
                        help_text="Describe the impacts that have been prioritized and who is most likely to be affected.",
                        null=True,
                        verbose_name="Prioritized impact",
                    ),
                ),
                (
                    "trigger_statement",
                    models.TextField(
                        blank=True,
                        help_text="Explain in one sentence what exactly the trigger of your EAP will be.",
                        null=True,
                        verbose_name="Trigger Statement",
                    ),
                ),
                (
                    "lead_time",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Lead Time"
                    ),
                ),
                (
                    "lead_timeframe_unit",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (10, "Years"),
                            (20, "Months"),
                            (30, "Days"),
                            (40, "Hours"),
                        ],
                        null=True,
                        verbose_name="Lead Timeframe Unit",
                    ),
                ),
                (
                    "forecast_selection",
                    models.TextField(
                        blank=True,
                        help_text="Explain which forecast's and observations will be used and why they are chosen",
                        null=True,
                        verbose_name="Forecast Selection",
                    ),
                ),
                (
                    "definition_and_justification_impact_level",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Definition and Justification of Impact Level",
                    ),
                ),
                (
                    "identification_of_the_intervention_area",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Identification of Intervention Area",
                    ),
                ),
                (
                    "early_action_selection_process",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Early action selection process",
                    ),
                ),
                (
                    "evidence_base",
                    models.TextField(
                        blank=True,
                        help_text="Explain how the selected actions will reduce the expected disaster impacts.",
                        null=True,
                        verbose_name="Evidence base",
                    ),
                ),
                (
                    "usefulness_of_actions",
                    models.TextField(
                        blank=True,
                        help_text="Describe how actions will still benefit the population if the expected event does not occur.",
                        null=True,
                        verbose_name="Usefulness of actions in case the event does not occur",
                    ),
                ),
                (
                    "feasibility",
                    models.TextField(
                        blank=True,
                        help_text="Explain how feasible it is to implement the proposed early actions in the planned timeframe.",
                        null=True,
                        verbose_name="Feasibility of selected actions",
                    ),
                ),
                (
                    "early_action_implementation_process",
                    models.TextField(
                        blank=True,
                        help_text="Describe the process for implementing early actions.",
                        null=True,
                        verbose_name="Early Action Implementation Process",
                    ),
                ),
                (
                    "trigger_activation_system",
                    models.TextField(
                        blank=True,
                        help_text="Describe the automatic system used to monitor the forecasts.",
                        null=True,
                        verbose_name="Trigger Activation System",
                    ),
                ),
                (
                    "selection_of_target_population",
                    models.TextField(
                        blank=True,
                        help_text="Describe the process used to select the target population for early actions.",
                        null=True,
                        verbose_name="Selection of Target Population",
                    ),
                ),
                (
                    "stop_mechanism",
                    models.TextField(
                        blank=True,
                        help_text="Explain how it would be communicated to communities and stakeholders that the activities are being stopped.",
                        null=True,
                        verbose_name="Stop Mechanism",
                    ),
                ),
                (
                    "meal",
                    models.TextField(
                        blank=True, null=True, verbose_name="MEAL Plan Description"
                    ),
                ),
                (
                    "operational_administrative_capacity",
                    models.TextField(
                        blank=True,
                        help_text="Describe how the NS has operative and administrative capacity to implement the EAPs.",
                        null=True,
                        verbose_name="National Society Operational, thematic and administrative capacity",
                    ),
                ),
                (
                    "strategies_and_plans",
                    models.TextField(
                        blank=True,
                        help_text="Describe how the EAP aligned with disaster risk management strategy of NS.",
                        null=True,
                        verbose_name="National Society Strategies and plans",
                    ),
                ),
                (
                    "advance_financial_capacity",
                    models.TextField(
                        blank=True,
                        help_text="Indicate whether the NS has capacity to advance funds to start early actions.",
                        null=True,
                        verbose_name="National Society Financial capacity to advance funds",
                    ),
                ),
                (
                    "budget_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Full EAP Budget Description",
                    ),
                ),
                (
                    "readiness_cost_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Readiness Cost Description"
                    ),
                ),
                (
                    "prepositioning_cost_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Prepositioning Cost Description",
                    ),
                ),
                (
                    "early_action_cost_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Early Action Cost Description",
                    ),
                ),
                (
                    "eap_endorsement",
                    models.TextField(
                        blank=True,
                        help_text="Describe by whom,how and when the EAP was agreed and endorsed.",
                        null=True,
                        verbose_name="EAP Endorsement Description",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Version identifier for the Full EAP.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the Full EAP is locked for editing.",
                        verbose_name="Is Locked?",
                    ),
                ),
                (
                    "activation_process_relevant_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="activation_process_relevant_files",
                        to="eap.eapfile",
                        verbose_name="Activation Relevant Files",
                    ),
                ),
                (
                    "activation_process_source_of_information",
                    models.ManyToManyField(
                        blank=True,
                        related_name="activation_process_source_of_information",
                        to="eap.sourceinformation",
                        verbose_name="Activation Process Source of Information",
                    ),
                ),
                (
                    "admin2",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="api.admin2",
                        verbose_name="admin",
                    ),
                ),
                (
                    "budget_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eap.eapfile",
                        verbose_name="Budget File",
                    ),
                ),
                (
                    "capacity_relevant_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ns_capacity_relevant_files",
                        to="eap.eapfile",
                        verbose_name="National society capacity relevant files",
                    ),
                ),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="eap.eapfile",
                        verbose_name="cover image",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "definition_and_justification_impact_level_images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="eap.eapfile",
                        verbose_name="Definition and Justification Impact Level Images",
                    ),
                ),
                (
                    "eap_registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="full_eaps",
                        to="eap.eapregistration",
                        verbose_name="EAP Development Registration",
                    ),
                ),
                (
                    "early_action_implementation_images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="early_action_implementation_images",
                        to="eap.eapfile",
                        verbose_name="Early Action Implementation Images",
                    ),
                ),
                (
                    "early_action_selection_process_images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="early_action_selection_process_images",
                        to="eap.eapfile",
                        verbose_name="Early action selection process images",
                    ),
                ),
                (
                    "early_actions",
                    models.ManyToManyField(
                        related_name="full_eap_early_actions",
                        to="eap.eapaction",
                        verbose_name="Early Actions",
                    ),
                ),
                (
                    "enabling_approaches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="full_eap_enabling_approaches",
                        to="eap.enablingapproach",
                        verbose_name="Enabling approaches",
                    ),
                ),
                (
                    "evidence_base_relevant_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="full_eap_evidence_base_relavent_files",
                        to="eap.eapfile",
                        verbose_name="Evidence base files",
                    ),
                ),
                (
                    "evidence_base_source_of_information",
                    models.ManyToManyField(
                        blank=True,
                        related_name="evidence_base_source_of_information",
                        to="eap.sourceinformation",
                        verbose_name="Evidence base source of information",
                    ),
                ),
                (
                    "exposed_element_and_vulnerability_factor_images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="full_eap_vulnerability_factor_images",
                        to="eap.eapfile",
                        verbose_name="Exposed elements and vulnerability factors images",
                    ),
                ),
                (
                    "forecast_selection_images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="eap.eapfile",
                        verbose_name="Forecast Selection Images",
                    ),
                ),
                (
                    "forecast_table_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forecast_table_file",
                        to="eap.eapfile",
                        verbose_name="Forecast Table File",
                    ),
                ),
                (
                    "hazard_selection_images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="full_eap_hazard_selection_images",
                        to="eap.eapfile",
                        verbose_name="Hazard images",
                    ),
                ),
                (
                    "identification_of_the_intervention_area_images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="eap.eapfile",
                        verbose_name="Intervention Area Images",
                    ),
                ),
                (
                    "key_actors",
                    models.ManyToManyField(
                        related_name="full_eap_key_actors",
                        to="eap.keyactor",
                        verbose_name="Key Actors",
                    ),
                ),
                (
                    "meal_relevant_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="full_eap_meal_files",
                        to="eap.eapfile",
                        verbose_name="Meal files",
                    ),
                ),
                (
                    "meal_source_of_information",
                    models.ManyToManyField(
                        blank=True,
                        related_name="meal_source_of_information",
                        to="eap.sourceinformation",
                        verbose_name="meal source of information",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
                (
                    "ns_capacity_source_of_information",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ns_capacity_source_of_information",
                        to="eap.sourceinformation",
                        verbose_name="ns_capacity source of information",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to the parent Full EAP if this is a snapshot.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="eap.fulleap",
                        verbose_name="Parent FUll EAP",
                    ),
                ),
                (
                    "partner_contacts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="eap.eapcontact",
                        verbose_name="Partner NS Contacts",
                    ),
                ),
                (
                    "partners",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select any partner NS involved in the EAP development.",
                        related_name="+",
                        to="api.country",
                        verbose_name="Partners",
                    ),
                ),
                (
                    "planned_operations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="full_eap_planned_operation",
                        to="eap.plannedoperation",
                        verbose_name="Planned operations",
                    ),
                ),
                (
                    "prioritized_impact_images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="full_eap_prioritized_impact_images",
                        to="eap.eapfile",
                        verbose_name="Prioritized impact images",
                    ),
                ),
                (
                    "prioritized_impacts",
                    models.ManyToManyField(
                        related_name="full_eap_prioritized_impacts",
                        to="eap.eapimpact",
                        verbose_name="Prioritized impacts",
                    ),
                ),
                (
                    "risk_analysis_relevant_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="full_eap_risk_analysis_relevant_files",
                        to="eap.eapfile",
                        verbose_name="Risk analysis relevant files",
                    ),
                ),
                (
                    "risk_analysis_source_of_information",
                    models.ManyToManyField(
                        blank=True,
                        related_name="risk_analysis_source_of_information",
                        to="eap.sourceinformation",
                        verbose_name="Risk analysis source of information",
                    ),
                ),
                (
                    "theory_of_change_table_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="theory_of_change_table_file",
                        to="eap.eapfile",
                        verbose_name="Theory of Change Table File",
                    ),
                ),
                (
                    "trigger_activation_system_images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="trigger_activation_system_images",
                        to="eap.eapfile",
                        verbose_name="Trigger Activation System Images",
                    ),
                ),
                (
                    "trigger_model_relevant_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="full_eap_trigger_model_relevant_file",
                        to="eap.eapfile",
                        verbose_name="Trigger Model Relevant File",
                    ),
                ),
                (
                    "trigger_model_source_of_information",
                    models.ManyToManyField(
                        blank=True,
                        related_name="trigger_model_source_of_information",
                        to="eap.sourceinformation",
                        verbose_name="Target Model Source of Information",
                    ),
                ),
                (
                    "trigger_statement_source_of_information",
                    models.ManyToManyField(
                        blank=True,
                        related_name="trigger_statement_source_of_information",
                        to="eap.sourceinformation",
                        verbose_name="Trigger Statement Source of Forecast",
                    ),
                ),
                (
                    "updated_checklist_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eap.eapfile",
                        verbose_name="Updated Review Checklist File",
                    ),
                ),
            ],
            options={
                "verbose_name": "Full EAP",
                "verbose_name_plural": "Full EAPs",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="enablingapproach",
            name="early_action_activities",
            field=models.ManyToManyField(
                blank=True,
                related_name="enabling_approach_early_action_activities",
                to="eap.operationactivity",
                verbose_name="Early Action Activities",
            ),
        ),
        migrations.AddField(
            model_name="enablingapproach",
            name="indicators",
            field=models.ManyToManyField(
                blank=True,
                related_name="enabling_approach_indicators",
                to="eap.indicator",
                verbose_name="Enabling Approach Indicators",
            ),
        ),
        migrations.AddField(
            model_name="enablingapproach",
            name="prepositioning_activities",
            field=models.ManyToManyField(
                blank=True,
                related_name="enabling_approach_prepositioning_activities",
                to="eap.operationactivity",
                verbose_name="Pre-positioning Activities",
            ),
        ),
        migrations.AddField(
            model_name="enablingapproach",
            name="readiness_activities",
            field=models.ManyToManyField(
                blank=True,
                related_name="enabling_approach_readiness_activities",
                to="eap.operationactivity",
                verbose_name="Readiness Activities",
            ),
        ),
        migrations.AddField(
            model_name="eapregistration",
            name="latest_full_eap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="eap.fulleap",
                verbose_name="Latest Full EAP",
            ),
        ),
        migrations.AddField(
            model_name="eapregistration",
            name="latest_simplified_eap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="eap.simplifiedeap",
                verbose_name="Latest Simplified EAP",
            ),
        ),
        migrations.AddField(
            model_name="eapregistration",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_modified_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="modified by",
            ),
        ),
        migrations.AddField(
            model_name="eapregistration",
            name="national_society",
            field=models.ForeignKey(
                help_text="Select National Society that is planning to apply for the EAP",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="development_registration_eap_national_society",
                to="api.country",
                verbose_name="National Society (NS)",
            ),
        ),
        migrations.AddField(
            model_name="eapregistration",
            name="partners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select any partner NS involved in the EAP development.",
                related_name="development_registration_eap_partners",
                to="api.country",
                verbose_name="Partners",
            ),
        ),
        migrations.AddField(
            model_name="eapregistration",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_eap",
                to=settings.AUTH_USER_MODEL,
                verbose_name="users",
            ),
        ),
        migrations.AddConstraint(
            model_name="simplifiedeap",
            constraint=models.UniqueConstraint(
                fields=("eap_registration", "version"),
                name="unique_simplified_eap_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="fulleap",
            constraint=models.UniqueConstraint(
                fields=("eap_registration", "version"), name="unique_full_eap_version"
            ),
        ),
    ]
