# Generated by Django 4.2.19 on 2025-11-04 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0226_nsdinitiativescategory_and_more'),
        ('eap', '0002_auto_20220708_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentRegistrationEAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('eap_type', models.IntegerField(choices=[(10, 'Full application'), (20, 'Simplified application'), (30, 'Not sure')], help_text='Select the type of EAP.', verbose_name='EAP Type')),
                ('expected_submission_time', models.DateField(blank=True, help_text='Include the propose time of submission, accounting for the time it will take to deliver the application.Leave blank if not sure.', null=True, verbose_name='Expected submission time')),
                ('national_society_contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='national society contact name')),
                ('national_society_contact_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='national society contact title')),
                ('national_society_contact_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='national society contact email')),
                ('national_society_contact_phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='national society contact phone number')),
                ('ifrc_contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='IFRC contact name ')),
                ('ifrc_contact_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='IFRC contact email')),
                ('ifrc_contact_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='IFRC contact title')),
                ('ifrc_contact_phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='IFRC contact phone number')),
                ('dref_focal_point_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='dref focal point name')),
                ('dref_focal_point_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dref focal point email')),
                ('dref_focal_point_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dref focal point title')),
                ('dref_focal_point_phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dref focal point phone number')),
                ('country', models.ForeignKey(help_text='The country will be pre-populated based on the NS selection, but can be adapted as needed.', on_delete=django.db.models.deletion.CASCADE, related_name='development_registration_eap_country', to='api.country', verbose_name='Country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('disaster_type', models.ForeignKey(help_text='Select the disaster type for which the EAP is needed', on_delete=django.db.models.deletion.PROTECT, to='api.disastertype', verbose_name='Disaster Type')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('national_society', models.ForeignKey(help_text='Select National Society that is planning to apply for the EAP', on_delete=django.db.models.deletion.CASCADE, related_name='development_registration_eap_national_society', to='api.country', verbose_name='National Society (NS)')),
                ('partners', models.ManyToManyField(blank=True, help_text='Select any partner NS involved in the EAP development.', related_name='development_registration_eap_partners', to='api.country', verbose_name='Partners')),
            ],
            options={
                'verbose_name': 'Development Registration EAP',
                'verbose_name_plural': 'Development Registration EAPs',
            },
        ),
    ]
