# Generated by Django 4.2.19 on 2025-11-11 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eap', '0003_eapfile_eapregistration_enableapproach_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlannedOperations',
            new_name='PlannedOperation',
        ),
    ]
