# Generated by Django 4.2.26 on 2026-01-28 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eap", "0003_eapaction_eapcontact_eapfile_eapimpact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eapregistration",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_eap",
                to=settings.AUTH_USER_MODEL,
                verbose_name="users",
            ),
        ),
    ]
