# Generated by Django 4.2.26 on 2026-02-03 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("eap", "0003_eapaction_eapcontact_eapfile_eapimpact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fulleap",
            name="advance_financial_capacity",
            field=models.TextField(
                blank=True,
                help_text="Indicate whether the NS has capacity to advance funds to start early actions.",
                null=True,
                verbose_name="National Society Financial capacity to advance funds",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="budget_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Full EAP Budget Description"
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="budget_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eap.eapfile",
                verbose_name="Budget File",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="definition_and_justification_impact_level",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Definition and Justification of Impact Level",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="eap_endorsement",
            field=models.TextField(
                blank=True,
                help_text="Describe by whom,how and when the EAP was agreed and endorsed.",
                null=True,
                verbose_name="EAP Endorsement Description",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="early_action_budget",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Early Actions Budget (CHF)"
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="early_action_cost_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Early Action Cost Description"
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="early_action_implementation_process",
            field=models.TextField(
                blank=True,
                help_text="Describe the process for implementing early actions.",
                null=True,
                verbose_name="Early Action Implementation Process",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="early_action_selection_process",
            field=models.TextField(
                blank=True, null=True, verbose_name="Early action selection process"
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="evidence_base",
            field=models.TextField(
                blank=True,
                help_text="Explain how the selected actions will reduce the expected disaster impacts.",
                null=True,
                verbose_name="Evidence base",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="exposed_element_and_vulnerability_factor",
            field=models.TextField(
                blank=True,
                help_text="Explain which people are most likely to experience the impacts of this hazard.",
                null=True,
                verbose_name="Exposed elements and vulnerability factors",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="feasibility",
            field=models.TextField(
                blank=True,
                help_text="Explain how feasible it is to implement the proposed early actions in the planned timeframe.",
                null=True,
                verbose_name="Feasibility of selected actions",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="forecast_selection",
            field=models.TextField(
                blank=True,
                help_text="Explain which forecast's and observations will be used and why they are chosen",
                null=True,
                verbose_name="Forecast Selection",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="hazard_selection",
            field=models.TextField(
                blank=True,
                help_text="Provide a brief rationale for selecting this hazard for the FbF system.",
                null=True,
                verbose_name="Hazard selection",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="identification_of_the_intervention_area",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Identification of Intervention Area",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="ifrc_delegation_focal_point_email",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="IFRC delegation focal point email",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="ifrc_delegation_focal_point_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="IFRC delegation focal point name",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="ifrc_head_of_delegation_email",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="IFRC head of delegation email",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="ifrc_head_of_delegation_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="IFRC head of delegation name",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="key_actors",
            field=models.ManyToManyField(
                related_name="full_eap_key_actors",
                to="eap.keyactor",
                verbose_name="Key Actors",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="lead_time",
            field=models.IntegerField(blank=True, null=True, verbose_name="Lead Time"),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="meal",
            field=models.TextField(
                blank=True, null=True, verbose_name="MEAL Plan Description"
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="modified_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="modified at"
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="operational_administrative_capacity",
            field=models.TextField(
                blank=True,
                help_text="Describe how the NS has operative and administrative capacity to implement the EAPs.",
                null=True,
                verbose_name="National Society Operational, thematic and administrative capacity",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="pre_positioning_budget",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Pre-positioning Budget (CHF)"
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="prepositioning_cost_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Prepositioning Cost Description"
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="prioritized_impact",
            field=models.TextField(
                blank=True,
                help_text="Describe the impacts that have been prioritized and who is most likely to be affected.",
                null=True,
                verbose_name="Prioritized impact",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="readiness_budget",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Readiness Budget (CHF)"
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="readiness_cost_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Readiness Cost Description"
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="selection_of_target_population",
            field=models.TextField(
                blank=True,
                help_text="Describe the process used to select the target population for early actions.",
                null=True,
                verbose_name="Selection of Target Population",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="stop_mechanism",
            field=models.TextField(
                blank=True,
                help_text="Explain how it would be communicated to communities and stakeholders that the activities are being stopped.",
                null=True,
                verbose_name="Stop Mechanism",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="strategies_and_plans",
            field=models.TextField(
                blank=True,
                help_text="Describe how the EAP aligned with disaster risk management strategy of NS.",
                null=True,
                verbose_name="National Society Strategies and plans",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="total_budget",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Total Budget (CHF)"
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="trigger_activation_system",
            field=models.TextField(
                blank=True,
                help_text="Describe the automatic system used to monitor the forecasts.",
                null=True,
                verbose_name="Trigger Activation System",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="trigger_statement",
            field=models.TextField(
                blank=True,
                help_text="Explain in one sentence what exactly the trigger of your EAP will be.",
                null=True,
                verbose_name="Trigger Statement",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="usefulness_of_actions",
            field=models.TextField(
                blank=True,
                help_text="Describe how actions will still benefit the population if the expected event does not occur.",
                null=True,
                verbose_name="Usefulness of actions in case the event does not occur",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="assisted_through_operation",
            field=models.TextField(
                blank=True, null=True, verbose_name="Assisted through the operation"
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="budget_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eap.eapfile",
                verbose_name="Budget File",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="early_action_budget",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Early Actions Budget (CHF)"
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="early_action_capability",
            field=models.TextField(
                blank=True,
                help_text="Assumptions or minimum conditions needed to deliver the early actions.",
                null=True,
                verbose_name="Experience or Capacity to implement Early Action.",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="ifrc_delegation_focal_point_email",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="IFRC delegation focal point email",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="ifrc_delegation_focal_point_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="IFRC delegation focal point name",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="ifrc_head_of_delegation_email",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="IFRC head of delegation email",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="ifrc_head_of_delegation_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="IFRC head of delegation name",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="modified_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="modified at"
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="next_step_towards_full_eap",
            field=models.TextField(
                blank=True, null=True, verbose_name="Next Steps towards Full EAP"
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="operational_timeframe",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Operational Time"
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="operational_timeframe_unit",
            field=models.IntegerField(
                blank=True,
                choices=[(10, "Years"), (20, "Months"), (30, "Days"), (40, "Hours")],
                default=20,
                null=True,
                verbose_name="Operational Timeframe Unit",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="overall_objective_intervention",
            field=models.TextField(
                blank=True,
                help_text="Provide an objective statement that describe the main of the intervention.",
                null=True,
                verbose_name="Overall objective of the intervention",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="potential_geographical_high_risk_areas",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Potential geographical high-risk areas",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="pre_positioning_budget",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Pre-positioning Budget (CHF)"
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="prioritized_hazard_and_impact",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Prioritized Hazard and its  historical impact.",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="rcrc_movement_involvement",
            field=models.TextField(
                blank=True,
                help_text="RCRC Movement partners, Governmental/other agencies consulted/involved.",
                null=True,
                verbose_name="RCRC Movement Involvement.",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="readiness_budget",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Readiness Budget (CHF)"
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="risks_selected_protocols",
            field=models.TextField(
                blank=True, null=True, verbose_name="Risk selected for the protocols."
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="seap_lead_time",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="sEAP Lead Time"
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="seap_lead_timeframe_unit",
            field=models.IntegerField(
                blank=True,
                choices=[(10, "Years"), (20, "Months"), (30, "Days"), (40, "Hours")],
                null=True,
                verbose_name="sEAP Lead Timeframe Unit",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="selected_early_actions",
            field=models.TextField(
                blank=True, null=True, verbose_name="Selected Early Actions"
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="total_budget",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Total Budget (CHF)"
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="trigger_threshold_justification",
            field=models.TextField(
                blank=True,
                help_text="Explain how the trigger were set and provide information",
                null=True,
                verbose_name="Trigger Threshold Justification",
            ),
        ),
    ]
