# Generated by Django 2.2.28 on 2022-07-15 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eap', '0003_auto_20220713_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earlyaction',
            name='prioritized_risk',
        ),
        migrations.AlterField(
            model_name='eap',
            name='eap_number',
            field=models.CharField(max_length=50, verbose_name='EAP Number'),
        ),
        migrations.AlterField(
            model_name='earlyaction',
            name='sector',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter, Housing And Settlements'), ('livelihoods', 'Livelihoods'), ('multi-purpose_cash', 'Multi-purpose Cash'), ('health_and_care', 'Health And Care'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration', 'Migration'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and _accountability', 'Community Engagement And Accountability'), ('environment_sustainability ', 'Environment Sustainability'), ('shelter_cluster_coordination', 'Shelter Cluster Coordination')], max_length=255, verbose_name='sector'),
        ),
        migrations.CreateModel(
            name='PrioritizedRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risks', models.TextField(blank=True, null=True)),
                ('early_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_actions_prioritized_risk', to='eap.EarlyAction', verbose_name='early action')),
            ],
            options={
                'verbose_name': 'Prioritized risk',
                'verbose_name_plural': 'Prioritized risks',
            },
        ),
    ]
