# Generated by Django 4.2.30 on 2026-04-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0231_alter_export_export_type"),
        ("eap", "0003_eapaction_eapcontact_eapfile_eapimpact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailRecipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (10, "DREF Anticipatory Pillar"),
                            (20, "DREF AA Global Team"),
                            (30, "Regional Coordinator"),
                        ],
                        verbose_name="Email Type",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only assign region for Regional Coordinator email type.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Recipient",
                "verbose_name_plural": "Email Recipients",
            },
        ),
        migrations.AddConstraint(
            model_name="emailrecipient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("region__isnull", True)),
                fields=("type", "email"),
                name="unique_email_type_no_region",
                violation_error_message="Email must be unique for the given type when no region is assigned.",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailrecipient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("region__isnull", False)),
                fields=("type", "region", "email"),
                name="unique_email_type_region",
                violation_error_message="Email must be unique for the given type and region.",
            ),
        ),
    ]
