# Generated by Django 2.2.28 on 2022-07-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_appealfilter_comment'),
        ('eap', '0004_auto_20220715_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAPActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('trigger_met_date', models.DateTimeField(verbose_name='Date the trigger was met')),
                ('description', models.TextField(verbose_name='Description of EAP Activation')),
                ('originator_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Originator name')),
                ('originator_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Originator title')),
                ('originator_email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Originator email')),
                ('nsc_name_operational', models.CharField(blank=True, max_length=250, null=True, verbose_name='National Society Contact (Operational)')),
                ('nsc_title_operational', models.CharField(blank=True, max_length=250, null=True, verbose_name='National Society Contact (Operational)')),
                ('nsc_email_operational', models.CharField(blank=True, max_length=250, null=True, verbose_name='National Society Contact (Operational)')),
                ('nsc_name_secretary', models.CharField(blank=True, max_length=250, null=True, verbose_name='National Society Contact (Secretary)')),
                ('nsc_title_secretary', models.CharField(blank=True, max_length=250, null=True, verbose_name='National Society Contact (Secretary)')),
                ('nsc_email_secretary', models.CharField(blank=True, max_length=250, null=True, verbose_name='National Society Contact (Secretary)')),
                ('ifrc_focal_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='IFRC Focal Point Name')),
                ('ifrc_focal_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='IFRC Focal Point Title')),
                ('ifrc_focal_email', models.CharField(blank=True, max_length=250, null=True, verbose_name='IFRC Focal Point Email')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eap_activation_document', to='eap.EAPDocument', verbose_name='EAP Activation Documents')),
                ('eap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eap_activation', to='eap.EAP', verbose_name='eap')),
                ('field_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_report_eap_activation', to='api.FieldReport', verbose_name='field report')),
            ],
        ),
    ]
