# Generated by Django 4.2.30 on 2026-05-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eap", "0004_emailrecipient_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fulleap",
            name="unique_full_eap_version",
        ),
        migrations.RemoveConstraint(
            model_name="simplifiedeap",
            name="unique_simplified_eap_version",
        ),
        migrations.AddConstraint(
            model_name="fulleap",
            constraint=models.UniqueConstraint(
                fields=("eap_registration", "version"),
                name="unique_full_eap_version",
                violation_error_message="A Full EAP for this EAP Registration with this version already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="simplifiedeap",
            constraint=models.UniqueConstraint(
                fields=("eap_registration", "version"),
                name="unique_simplified_eap_version",
                violation_error_message="A Simplified EAP for this EAP Registration with this version already exists.",
            ),
        ),
    ]
