# Generated by Django 4.2.28 on 2026-02-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eap', '0004_alter_fulleap_advance_financial_capacity_and_more'),
        ('eap', '0004_eapregistration_users'),
    ]

    operations = [
    ]
