# Generated by Django 4.2.28 on 2026-02-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eap", "0005_merge_20260213_0909"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulleap",
            name="meal_source_of_information",
            field=models.ManyToManyField(
                blank=True,
                related_name="meal_source_of_information",
                to="eap.sourceinformation",
                verbose_name="meal source of information",
            ),
        ),
        migrations.AddField(
            model_name="fulleap",
            name="ns_capacity_source_of_information",
            field=models.ManyToManyField(
                blank=True,
                related_name="ns_capacity_source_of_information",
                to="eap.sourceinformation",
                verbose_name="ns_capacity source of information",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="is_worked_with_government",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Has Worked with government or other relevant actors.",
            ),
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="people_targeted",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="People Targeted."
            ),
        ),
        migrations.AlterField(
            model_name="plannedoperation",
            name="ap_code",
            field=models.IntegerField(verbose_name="AP Code"),
        ),
        migrations.AlterField(
            model_name="plannedoperation",
            name="sector",
            field=models.IntegerField(
                choices=[
                    (101, "Shelter, Settlement and Housing"),
                    (102, "Livelihoods"),
                    (103, "Protection, Gender and Inclusion"),
                    (104, "Health and Care"),
                    (105, "Risk Reduction, Climate Adaptation and Recovery"),
                    (106, "Multipurpose Cash"),
                    (107, "Water, Sanitation And Hygiene"),
                    (108, "WASH"),
                    (109, "Education"),
                    (110, "Migration"),
                    (111, "Environment Sustainability"),
                    (112, "Community Engagement And Accountability"),
                ],
                verbose_name="sector",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="people_targeted",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="People Targeted."
            ),
        ),
    ]
