# Generated by Django 5.2.14 on 2026-07-24 04:49

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Abs


def backfill_partner_from_national_society(apps, schema_editor):
    """
    Preserve the old FK's name instead of dropping it once national_society is removed.
    """
    KeyActor = apps.get_model("eap", "KeyActor")
    for key_actor in KeyActor.objects.select_related("national_society").iterator():
        key_actor.partner = key_actor.national_society.society_name
        key_actor.save(update_fields=["partner"])


def clamp_negative_values_to_zero(apps, schema_editor):
    """
    PositiveField adds a DB-level `>= 0` CHECK constraint on PostgreSQL;
    existing negative rows would make the AlterField operations in the next
    migration fail.
    """
    PlannedOperation = apps.get_model("eap", "PlannedOperation")
    SimplifiedEAP = apps.get_model("eap", "SimplifiedEAP")
    FullEAP = apps.get_model("eap", "FullEAP")

    PlannedOperation.objects.update(people_targeted=Abs(F("people_targeted")), budget_per_sector=Abs(F("budget_per_sector")))

    for Model in (SimplifiedEAP, FullEAP):
        Model.objects.update(
            people_targeted=Abs(F("people_targeted")),
            total_budget=Abs(F("total_budget")),
            readiness_budget=Abs(F("readiness_budget")),
            pre_positioning_budget=Abs(F("pre_positioning_budget")),
            early_action_budget=Abs(F("early_action_budget")),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('eap', '0005_remove_fulleap_unique_full_eap_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eapregistration',
            old_name='approved_at',
            new_name='project_agreement_signed_at',
        ),
        migrations.RenameField(
            model_name='eapregistration',
            old_name='pending_pfa_at',
            new_name='approved_at',
        ),
        migrations.AlterField(
            model_name='eapregistration',
            name='project_agreement_signed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the project agreement was signed.', null=True, verbose_name='project agreement signed at'),
        ),
        migrations.AlterField(
            model_name='eapregistration',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the EAP was approved.', null=True, verbose_name='approved at'),
        ),
        migrations.AddField(
            model_name='keyactor',
            name='partner',
            field=models.CharField(default='', help_text='Name of the partner organization or entity.', max_length=255, verbose_name='Partner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapregistration',
            name='disaster_sub_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Disaster Sub Type'),
        ),
        migrations.AddField(
            model_name='fulleap',
            name='include_rcrc_climate_center',
            field=models.BooleanField(default=False, verbose_name='Include RCRC Climate Center.'),
        ),
        migrations.AddField(
            model_name='simplifiedeap',
            name='include_rcrc_climate_center',
            field=models.BooleanField(default=False, verbose_name='Include RCRC Climate Center.'),
        ),
        migrations.AlterField(
            model_name='eapregistration',
            name='status',
            field=models.IntegerField(choices=[(10, 'Under Development'), (20, 'Under Review'), (30, 'NS Addressing Comments'), (40, 'Technically validated by VC'), (50, 'Approved'), (60, 'Project Agreement Signed')], default=10, help_text='Select the current status of the EAP development process.', verbose_name='EAP Status'),
        ),
        migrations.AddField(
            model_name='operationactivity',
            name='activation_one',
            field=models.BooleanField(blank=True, null=True, verbose_name='Activation 1'),
        ),
        migrations.AddField(
            model_name='operationactivity',
            name='activation_two',
            field=models.BooleanField(blank=True, null=True, verbose_name='Activation 2'),
        ),
        migrations.RunPython(backfill_partner_from_national_society, migrations.RunPython.noop),
        migrations.RunPython(clamp_negative_values_to_zero, migrations.RunPython.noop),
    ]
