# Generated by Django 2.2.28 on 2022-08-02 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_auto_20220721_0754'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eap', '0005_eapactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAPOperationalPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='Budget per sector (CHF)')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='value')),
                ('no_of_people_reached', models.IntegerField(blank=True, null=True, verbose_name='People Reached')),
                ('readiness_activities_achievements', models.TextField(blank=True, null=True, verbose_name='Readiness Activities Achievements')),
                ('prepo_activities_achievements', models.TextField(blank=True, null=True, verbose_name='Pre-positioning Activities Achievements')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'EAP Operational Plan',
                'verbose_name_plural': 'EAP Operational Plans',
            },
        ),
        migrations.RemoveField(
            model_name='eap',
            name='district',
        ),
        migrations.RemoveField(
            model_name='eap',
            name='document',
        ),
        migrations.RemoveField(
            model_name='eapactivation',
            name='document',
        ),
        migrations.AddField(
            model_name='action',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eap',
            name='districts',
            field=models.ManyToManyField(related_name='eap_district', to='api.District', verbose_name='districts'),
        ),
        migrations.AddField(
            model_name='eap',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='eap_document', to='eap.EAPDocument', verbose_name='EAP Documents'),
        ),
        migrations.AddField(
            model_name='eapactivation',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='eap_activation_document', to='eap.EAPDocument', verbose_name='EAP Activation Documents'),
        ),
        migrations.AddField(
            model_name='eapdocument',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eappartner',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eapreference',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='earlyaction',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='earlyactionindicator',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prioritizedrisk',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='OperationalPlanIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.IntegerField(blank=True, null=True)),
                ('indicator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eap.EarlyActionIndicator')),
                ('operational_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_plan_indicator', to='eap.EAPOperationalPlan', verbose_name='Operational Plan')),
            ],
            options={
                'verbose_name': 'Operational Indicator',
                'verbose_name_plural': 'Operational Indicators',
            },
        ),
        migrations.AddField(
            model_name='eapoperationalplan',
            name='early_action',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eap.EarlyAction'),
        ),
        migrations.CreateModel(
            name='EAPActivationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people_reached', models.IntegerField(verbose_name='Number Of People Reached')),
                ('description', models.TextField(verbose_name='Description of Event & Overview of Implementation')),
                ('overall_objectives', models.TextField(verbose_name='Overall Objective of the Intervention')),
                ('challenges_and_lesson', models.TextField(verbose_name='Challenges & Lesson Learned per Sector')),
                ('general_lesson_and_recomendations', models.TextField(verbose_name='General Lessons Learned and Recomendations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eap_act_report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('documents', models.ManyToManyField(blank=True, related_name='eap_act_reports', to='eap.EAPDocument', verbose_name='EAP Activation Report Document')),
                ('eap_activation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eap_activation_report', to='eap.EAPActivation', verbose_name='EAP Activation Report')),
                ('ifrc_financial_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eap_activation_ifrc_report', to='eap.EAPDocument', verbose_name='IFRC Financial Report')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eap_act_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('operational_plans', models.ManyToManyField(blank=True, to='eap.EAPOperationalPlan', verbose_name='Operational Plans')),
            ],
        ),
        migrations.CreateModel(
            name='ActionAchievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('early_act_achievement', models.TextField(blank=True, null=True, verbose_name='Early Actions Achievements')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eap.Action')),
                ('operational_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_achievement', to='eap.EAPOperationalPlan', verbose_name='Action Achievement')),
            ],
            options={
                'verbose_name': 'Action Achievement',
                'verbose_name_plural': 'Action Achievements',
            },
        ),
    ]
