# Generated by Django 4.2.29 on 2026-03-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eap', '0006_fulleap_meal_source_of_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eapregistration',
            name='activated_at',
        ),
        migrations.AddField(
            model_name='fulleap',
            name='lead_timeframe_unit',
            field=models.IntegerField(blank=True, choices=[(10, 'Years'), (20, 'Months'), (30, 'Days'), (40, 'Hours')], null=True, verbose_name='Lead Timeframe Unit'),
        ),
        migrations.AlterField(
            model_name='eapregistration',
            name='status',
            field=models.IntegerField(choices=[(10, 'Under Development'), (20, 'Under Review'), (30, 'NS Addressing Comments'), (40, 'Technically Validated'), (50, 'Approved(Pending PFA)'), (60, 'Approved')], default=10, help_text='Select the current status of the EAP development process.', verbose_name='EAP Status'),
        ),
        migrations.AlterField(
            model_name='enablingapproach',
            name='ap_code',
            field=models.IntegerField(default=1, verbose_name='AP Code'),
            preserve_default=False,
        ),
    ]
