# Generated by Django 2.2.28 on 2022-08-03 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eap', '0006_auto_20220802_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('early_act_achievement', models.TextField(blank=True, null=True, verbose_name='Early Actions Achievements')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_achievement', to='eap.Action')),
                ('operational_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_achievement', to='eap.EAPOperationalPlan', verbose_name='Action Achievement')),
            ],
            options={
                'verbose_name': 'Action Achievement',
                'verbose_name_plural': 'Action Achievements',
            },
        ),
        migrations.AlterField(
            model_name='operationalplanindicator',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_plan_indicator', to='eap.EarlyActionIndicator'),
        ),
        migrations.DeleteModel(
            name='ActionAchievements',
        ),
    ]
