# Generated by Django 4.2.19 on 2025-11-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eap", "0006_eapregistration_review_checklist_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eapfile",
            options={
                "ordering": ["-id"],
                "verbose_name": "eap file",
                "verbose_name_plural": "eap files",
            },
        ),
        migrations.AlterModelOptions(
            name="eapregistration",
            options={
                "ordering": ["-id"],
                "verbose_name": "Development Registration EAP",
                "verbose_name_plural": "Development Registration EAPs",
            },
        ),
        migrations.AlterModelOptions(
            name="simplifiedeap",
            options={
                "ordering": ["-id"],
                "verbose_name": "Simplified EAP",
                "verbose_name_plural": "Simplified EAPs",
            },
        ),
        migrations.AddField(
            model_name="simplifiedeap",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the Simplified EAP is locked for editing.",
                verbose_name="Is Locked?",
            ),
        ),
        migrations.AddField(
            model_name="simplifiedeap",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the parent Simplified EAP if this is a snapshot.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="snapshots",
                to="eap.simplifiedeap",
                verbose_name="Parent Simplified EAP",
            ),
        ),
        migrations.AddField(
            model_name="simplifiedeap",
            name="version",
            field=models.IntegerField(
                default=1,
                help_text="Version identifier for the Simplified EAP.",
                verbose_name="Version",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="eap_registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simplified_eap",
                to="eap.eapregistration",
                verbose_name="EAP Development Registration",
            ),
        ),
    ]
