# Generated by Django 4.2.28 on 2026-04-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0228_merge_20260123_0806'),
        ('eap', '0007_remove_eapregistration_activated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enablingapproach',
            name='ap_code',
        ),
        migrations.RemoveField(
            model_name='plannedoperation',
            name='ap_code',
        ),
        migrations.AddField(
            model_name='fulleap',
            name='partners',
            field=models.ManyToManyField(blank=True, help_text='Select any partner NS involved in the EAP development.', related_name='+', to='api.country', verbose_name='Partners'),
        ),
        migrations.AddField(
            model_name='simplifiedeap',
            name='partners',
            field=models.ManyToManyField(blank=True, help_text='Select any partner NS involved in the EAP development.', related_name='+', to='api.country', verbose_name='Partners'),
        ),
        migrations.AlterField(
            model_name='plannedoperation',
            name='sector',
            field=models.IntegerField(choices=[(101, 'Shelter, Settlement and Housing'), (102, 'Livelihoods'), (103, 'Protection, Gender and Inclusion'), (104, 'Health and Care'), (105, 'Risk Reduction, Climate Adaptation and Recovery'), (106, 'Multipurpose Cash'), (107, 'Water, Sanitation And Hygiene'), (109, 'Education'), (110, 'Migration'), (111, 'Environment Sustainability'), (112, 'Community Engagement And Accountability')], verbose_name='sector'),
        ),
    ]
