# Generated by Django 5.2.16 on 2026-08-20 11:18

import django.db.models.deletion
import main.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0231_alter_export_export_type'),
        ('eap', '0007_keyactor_partner_positive_integer_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(max_length=255, verbose_name='Potential Risk')),
                ('previous_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Previous ID')),
            ],
            options={
                'verbose_name': 'Potential Risk',
                'verbose_name_plural': 'Potential Risks',
            },
        ),
        migrations.AddField(
            model_name='eapregistration',
            name='appeal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Appeal Code'),
        ),
        migrations.AddField(
            model_name='eapregistration',
            name='final_review_checklist_file',
            field=main.fields.SecureFileField(blank=True, max_length=255, null=True, upload_to='eap/files/', verbose_name='Final Review Checklist File'),
        ),
        migrations.AddField(
            model_name='simplifiedeap',
            name='early_actions',
            field=models.ManyToManyField(blank=True, related_name='seap_early_actions', to='eap.eapaction', verbose_name='Early Actions'),
        ),
        migrations.AlterField(
            model_name='eapfile',
            name='file',
            field=main.fields.SecureFileField(help_text='Upload EAP related file.', max_length=255, upload_to='eap/files/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='eapregistration',
            name='summary_file',
            field=main.fields.SecureFileField(blank=True, max_length=255, null=True, upload_to='eap/files/', verbose_name='EAP Summary PDF'),
        ),
        migrations.AlterField(
            model_name='eapregistration',
            name='validated_budget_file',
            field=main.fields.SecureFileField(blank=True, help_text='Upload the validated budget file once the EAP is technically validated.', max_length=255, null=True, upload_to='eap/files/validated_budgets/', verbose_name='Validated Budget File'),
        ),
        migrations.AlterField(
            model_name='fulleap',
            name='diff_file',
            field=main.fields.SecureFileField(blank=True, max_length=255, null=True, upload_to='eap/files/', verbose_name='EAP Diff PDF file'),
        ),
        migrations.AlterField(
            model_name='fulleap',
            name='export_file',
            field=main.fields.SecureFileField(blank=True, max_length=255, null=True, upload_to='eap/files/exports/', verbose_name='EAP Export File'),
        ),
        migrations.RemoveField(
            model_name='fulleap',
            name='lead_time',
        ),
        migrations.AddField(
            model_name='fulleap',
            name='lead_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lead Time'),
        ),
        migrations.AlterField(
            model_name='fulleap',
            name='review_checklist_file',
            field=main.fields.SecureFileField(blank=True, max_length=255, null=True, upload_to='eap/files/', verbose_name='Review Checklist File'),
        ),
        migrations.AlterField(
            model_name='simplifiedeap',
            name='diff_file',
            field=main.fields.SecureFileField(blank=True, max_length=255, null=True, upload_to='eap/files/', verbose_name='EAP Diff PDF file'),
        ),
        migrations.AlterField(
            model_name='simplifiedeap',
            name='export_file',
            field=main.fields.SecureFileField(blank=True, max_length=255, null=True, upload_to='eap/files/exports/', verbose_name='EAP Export File'),
        ),
        migrations.AlterField(
            model_name='simplifiedeap',
            name='review_checklist_file',
            field=main.fields.SecureFileField(blank=True, max_length=255, null=True, upload_to='eap/files/', verbose_name='Review Checklist File'),
        ),
        migrations.AlterField(
            model_name='sourceinformation',
            name='source_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Source Link'),
        ),
        migrations.CreateModel(
            name='Admin1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('previous_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Previous ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Selected District',
                'verbose_name_plural': 'Selected Districts',
            },
        ),
        migrations.AddField(
            model_name='fulleap',
            name='districts',
            field=models.ManyToManyField(blank=True, related_name='+', to='eap.admin1', verbose_name='districts'),
        ),
        migrations.AddField(
            model_name='simplifiedeap',
            name='districts',
            field=models.ManyToManyField(blank=True, related_name='+', to='eap.admin1', verbose_name='districts'),
        ),
        migrations.AddField(
            model_name='simplifiedeap',
            name='potential_risks',
            field=models.ManyToManyField(blank=True, related_name='simplified_eap_potential_risks', to='eap.potentialrisk', verbose_name='Potential Risks'),
        ),
    ]
