# Generated by Django 2.2.28 on 2022-08-04 05:05

from django.db import migrations, models
import eap.models


class Migration(migrations.Migration):

    dependencies = [
        ('eap', '0007_auto_20220803_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlyactionindicator',
            name='indicator',
            field=models.CharField(blank=True, choices=[('indicator_1', 'Indicator 1'), ('indicator_2', 'Indicator 2')], default=eap.models.EarlyActionIndicator.IndicatorChoices('indicator_1'), max_length=255, null=True),
        ),
    ]
