# Generated by Django 2.2.28 on 2022-08-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eap', '0008_auto_20220804_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='eapdocument',
            name='caption',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='earlyaction',
            name='sector',
            field=models.IntegerField(choices=[(0, 'Shelter, Housing And Settlements'), (1, 'Livelihoods'), (2, 'Multi-purpose Cash'), (3, 'Health And Care'), (4, 'Water, Sanitation And Hygiene'), (5, 'Protection, Gender And Inclusion'), (6, 'Education'), (7, 'Migration'), (8, 'Risk Reduction, Climate Adaptation And Recovery'), (9, 'Community Engagement And Accountability'), (10, 'Environment Sustainability'), (11, 'Shelter Cluster Coordination')], verbose_name='sector'),
        ),
    ]
