# Generated by Django 4.2.26 on 2025-12-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eap", "0009_sourceinformation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EAPAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(max_length=255, verbose_name="Early Action"),
                ),
            ],
            options={
                "verbose_name": "Early Action",
                "verbose_name_plural": "Early Actions",
            },
        ),
        migrations.CreateModel(
            name="EAPImpact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impact", models.CharField(max_length=255, verbose_name="Impact")),
            ],
            options={
                "verbose_name": " Impact",
                "verbose_name_plural": "Expected Impacts",
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Indicator Title"),
                ),
                ("target", models.IntegerField(verbose_name="Indicator Target")),
            ],
            options={
                "verbose_name": "Indicator",
                "verbose_name_plural": "Indicators",
            },
        ),
        migrations.RemoveField(
            model_name="enableapproach",
            name="indicator_target",
        ),
        migrations.AddField(
            model_name="fulleap",
            name="lead_time",
            field=models.IntegerField(default=3, verbose_name="Lead Time"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fulleap",
            name="objective",
            field=models.TextField(
                default="default",
                help_text="Provide an objective statement that describe the main goal of intervention.",
                verbose_name="Overall Objective of the EAP.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="trigger_statement_source_of_information",
            field=models.ManyToManyField(
                blank=True,
                related_name="trigger_statement_source_of_information",
                to="eap.sourceinformation",
                verbose_name="Trigger Statement Source of Forecast",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="assisted_through_operation",
            field=models.TextField(verbose_name="Assisted through the operation"),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="early_action_capability",
            field=models.TextField(
                help_text="Assumptions or minimum conditions needed to deliver the early actions.",
                verbose_name="Experience or Capacity to implement Early Action.",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="overall_objective_intervention",
            field=models.TextField(
                help_text="Provide an objective statement that describe the main of the intervention.",
                verbose_name="Overall objective of the intervention",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="potential_geographical_high_risk_areas",
            field=models.TextField(
                verbose_name="Potential geographical high-risk areas"
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="prioritized_hazard_and_impact",
            field=models.TextField(
                verbose_name="Prioritized Hazard and its  historical impact."
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="rcrc_movement_involvement",
            field=models.TextField(
                help_text="RCRC Movement partners, Governmental/other agencies consulted/involved.",
                verbose_name="RCRC Movement Involvement.",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="risks_selected_protocols",
            field=models.TextField(verbose_name="Risk selected for the protocols."),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="selected_early_actions",
            field=models.TextField(verbose_name="Selected Early Actions"),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="trigger_threshold_justification",
            field=models.TextField(
                help_text="Explain how the trigger were set and provide information",
                verbose_name="Trigger Threshold Justification",
            ),
        ),
        migrations.AddConstraint(
            model_name="fulleap",
            constraint=models.UniqueConstraint(
                fields=("eap_registration", "version"), name="unique_full_eap_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="simplifiedeap",
            constraint=models.UniqueConstraint(
                fields=("eap_registration", "version"),
                name="unique_simplified_eap_version",
            ),
        ),
        migrations.AddField(
            model_name="enableapproach",
            name="indicators",
            field=models.ManyToManyField(
                blank=True,
                related_name="enable_approach_indicators",
                to="eap.indicator",
                verbose_name="Enable Approach Indicators",
            ),
        ),
        migrations.AddField(
            model_name="fulleap",
            name="early_actions",
            field=models.ManyToManyField(
                related_name="full_eap_early_actions",
                to="eap.eapaction",
                verbose_name="Early Actions",
            ),
        ),
        migrations.AddField(
            model_name="fulleap",
            name="prioritized_impacts",
            field=models.ManyToManyField(
                related_name="full_eap_prioritized_impacts",
                to="eap.eapimpact",
                verbose_name="Prioritized impacts",
            ),
        ),
        migrations.AddField(
            model_name="plannedoperation",
            name="indicators",
            field=models.ManyToManyField(
                blank=True,
                related_name="planned_operation_indicators",
                to="eap.indicator",
                verbose_name="Operation Indicators",
            ),
        ),
    ]
