# Generated by Django 4.2.26 on 2025-12-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eap", "0010_eapaction_eapimpact_indicator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fulleap",
            name="updated_checklist_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eap.eapfile",
                verbose_name="Updated Review Checklist File",
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="updated_checklist_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eap.eapfile",
                verbose_name="Updated Review Checklist File",
            ),
        ),
    ]
