# Generated by Django 4.2.26 on 2025-12-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eap", "0011_alter_fulleap_updated_checklist_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fulleap",
            name="seap_timeframe",
        ),
        migrations.RemoveField(
            model_name="fulleap",
            name="selection_area",
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="ifrc_delegation_focal_point_email",
            field=models.CharField(
                default="test@gmail.com",
                max_length=255,
                verbose_name="IFRC delegation focal point email",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="ifrc_delegation_focal_point_name",
            field=models.CharField(
                default="test",
                max_length=255,
                verbose_name="IFRC delegation focal point name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="ifrc_head_of_delegation_email",
            field=models.CharField(
                default="test@gmail.com",
                max_length=255,
                verbose_name="IFRC head of delegation email",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="ifrc_head_of_delegation_name",
            field=models.CharField(
                default="test",
                max_length=255,
                verbose_name="IFRC head of delegation name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="national_society_contact_email",
            field=models.CharField(
                default="test@gmail.com",
                max_length=255,
                verbose_name="national society contact email",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fulleap",
            name="national_society_contact_name",
            field=models.CharField(
                default="test",
                max_length=255,
                verbose_name="national society contact name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="ifrc_delegation_focal_point_email",
            field=models.CharField(
                default="test@gmail.com",
                max_length=255,
                verbose_name="IFRC delegation focal point email",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="ifrc_delegation_focal_point_name",
            field=models.CharField(
                default="test",
                max_length=255,
                verbose_name="IFRC delegation focal point name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="ifrc_head_of_delegation_email",
            field=models.CharField(
                default="test@gmail.com",
                max_length=255,
                verbose_name="IFRC head of delegation email",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="ifrc_head_of_delegation_name",
            field=models.CharField(
                default="test",
                max_length=255,
                verbose_name="IFRC head of delegation name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="national_society_contact_email",
            field=models.CharField(
                default="test@gmail.com",
                max_length=255,
                verbose_name="national society contact email",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="simplifiedeap",
            name="national_society_contact_name",
            field=models.CharField(
                default="test",
                max_length=255,
                verbose_name="national society contact name",
            ),
            preserve_default=False,
        ),
    ]
