# Generated by Django 4.2.26 on 2026-01-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eap', '0014_eapcontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eapregistration',
            name='deadline',
            field=models.DateField(blank=True, help_text='Date by which the EAP submission must be completed.', null=True, verbose_name='deadline'),
        ),
        migrations.AddField(
            model_name='eapregistration',
            name='deadline_remainder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the deadline reminder email was sent.', null=True, verbose_name='deadline reminder email sent at'),
        ),
    ]
