# Generated by Django 4.2.19 on 2026-01-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eap', '0015_eapregistration_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulleap',
            name='technical_working_groups_in_place_description',
            field=models.TextField(blank=True, null=True, verbose_name='Technical working groups description'),
        ),
        migrations.AlterField(
            model_name='fulleap',
            name='worked_with_government_description',
            field=models.TextField(blank=True, null=True, verbose_name='Government and actors engagement description'),
        ),
    ]
