# Generated by Django 5.2.17 on 2026-09-20 05:21

import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import main.fields
import per.models
import tinymce.models
from django.conf import settings
from django.db import migrations, models
from api.logger import logger
from django.core.management import call_command
from django.db import migrations
from main.utils import DjangoReversionDataFixHelper


def _0086__migrate_data(apps, schema_editor):
    Form = apps.get_model('per', 'Form')
    FormData = apps.get_model('per', 'FormData')
    FormComponentQuestionAndAnswer = apps.get_model('per', 'FormComponentQuestionAndAnswer')
    FormComponent = apps.get_model('per', 'FormComponent')
    FormComponentResponse = apps.get_model('per', 'FormComponentResponse')
    AreaResponse = apps.get_model('per', 'AreaResponse')
    PerAssessment = apps.get_model('per', 'PerAssessment')
    PerComponentRating = apps.get_model('per', 'PerComponentRating')
    per_assessments_by_overview = {}
    for form in Form.objects.all():
        overview = form.overview
        per_assessment = per_assessments_by_overview.get(overview.id)
        if not per_assessment:
            per_assessment = PerAssessment.objects.create(overview=overview, user=form.user, is_draft=True)
            per_assessments_by_overview[overview.id] = per_assessment
        area = form.area
        area_response = AreaResponse.objects.create(area=form.area)
        per_assessment.area_responses.add(area_response)
        rating_map = {3: 1, 4: 2, 5: 3, 6: 4, 7: 5, 8: 6}
        for component_response in area.formcomponent_set.all():
            form_component_response = FormComponentResponse.objects.create(component=component_response)
            area_response.component_response.add(form_component_response)
            form_data_entries = FormData.objects.filter(form=form, question__component=component_response)
            for form_data_entry in form_data_entries:
                question = form_data_entry.question.question
                answer = form_data_entry.selected_answer
                notes = form_data_entry.notes_en
                if answer:
                    if question != 'Component performance' and answer.id in [1, 2]:
                        question_and_answer = FormComponentQuestionAndAnswer.objects.create(question=form_data_entry.question, answer=form_data_entry.selected_answer, notes=form_data_entry.notes_en)
                        form_component_response.question_responses.add(question_and_answer)
                question = form_data_entry.question.question
                if question == 'Component performance':
                    answer = form_data_entry.selected_answer
                    if answer:
                        rating = rating_map.get(answer.id)
                        if rating is not None:
                            form_component_response.rating = PerComponentRating.objects.get(id=rating)
                            form_component_response.save(update_fields=['rating'])
                        else:
                            print(f'No rating found for answer {answer}')

def _0087__update_phase(apps, schema_editor):
    Overview = apps.get_model('per', 'Overview')
    FormPrioritization = apps.get_model('per', 'FormPrioritization')
    overviews = Overview.objects.all()
    for overview in overviews:
        overview.phase = 2
        overview.save(update_fields=['phase'])

def _0088__update_overview_assessment_method(apps, schema_editor):
    Overview = apps.get_model('per', 'Overview')
    overviews = Overview.objects.all()
    for overview in overviews:
        if overview.assessment_method == 'PER':
            overview.assessment_method = 'per'
        elif overview.assessment_method == 'DRCE':
            overview.assessment_method = 'drce'
        else:
            overview.assessment_method = 'per'
        overview.save(update_fields=['assessment_method'])

def _0090__update_question_answer(apps, schema_editor):
    FormQuestion = apps.get_model("per", "FormQuestion")
    FormAnswer = apps.get_model("per", "FormAnswer")
    form_questions = FormQuestion.objects.all()
    for form_question in form_questions:
        form_question.answers.add(FormAnswer.objects.get(id=5))  # Hardcoded for now

def _0094__update_suported_by_oragnization_type(apps, schema_editor):
    PerWorkPlanComponent = apps.get_model('per', 'PerWorkPlanComponent')
    PerWorkPlanComponent.objects.update(supported_by_organization_type=3)

def _0096__migrate_formdata_notes(apps, schema_editor):
    pass

def _0098__update_component_description(apps, schema_editor):
    FormComponent = apps.get_model("per", "FormComponent")

    # Update formcomponent `14 A` description to 14 and set 14 to `is_parent`
    form_component_14_A = FormComponent.objects.filter(component_num=14, component_letter="A")
    if form_component_14_A.exists():
        form_component_14_A_first = form_component_14_A.first()
        form_component_14 = FormComponent.objects.filter(component_num=14).first()
        form_component_14.description_en = form_component_14_A_first.description
        form_component_14.is_parent = True
        form_component_14.save(update_fields=["description_en", "is_parent"])

def _0098__modify_per_datetime_data_to_date(self, schema_editor):
    ContentType = self.get_model('contenttypes', 'ContentType')
    Version = self.get_model('reversion', 'Version')
    Overview = self.get_model('per', 'Overview')
    DjangoReversionDataFixHelper.datetime_fields_to_date(ContentType, Version, Overview, ['date_of_assessment'])

def _0098__modify_per_date_data_to_datetime(self, schema_editor):
    ContentType = self.get_model('contenttypes', 'ContentType')
    Version = self.get_model('reversion', 'Version')
    Overview = self.get_model('per', 'Overview')
    DjangoReversionDataFixHelper.date_fields_to_datetime(ContentType, Version, Overview, ['date_of_assessment'])

def _0099__migrate_formdata_notes(apps, schema_editor):
    FormComponentResponse = apps.get_model("per", "FormComponentResponse")
    FormData = apps.get_model("per", "FormData")

    qs = FormComponentResponse.objects.annotate(
        new_notes=models.Subquery(
            # Copy notes from FormData using overview
            FormData.objects.filter(
                form__overview=models.OuterRef("arearesponse__perassessment__overview"),
                question__component=models.OuterRef("component"),
                question=74,
            ).values("notes_en"),
            output_field=models.CharField(),
        ),
    ).filter(new_notes__isnull=False)

    form_component_responses = []
    for form_component_response_id, assessment_id, new_notes in qs.values_list(
        "id",
        models.F("arearesponse__perassessment"),
        "new_notes",
    ):
        print(f"- Copying data for {assessment_id=} {form_component_response_id=}")
        form_component_responses.append(
            FormComponentResponse(
                id=form_component_response_id,
                notes=new_notes,
            )
        )

    print(f"Total form_component_responses notes copied: {len(form_component_responses)}")
    FormComponentResponse.objects.bulk_update(form_component_responses, fields=("notes",))

def _0100__migrate_component_to_question_group(apps, schema_editor):
    FormComponent = apps.get_model("per", "FormComponent")
    FormQuestionGroup = apps.get_model("per", "FormQuestionGroup")
    FormQuestion = apps.get_model("per", "FormQuestion")
    FormComponentResponse = apps.get_model("per", "FormComponentResponse")

    # Fetch components to migrate
    to_migrate_component_ids = [53, 52, 51, 50, 49]
    to_migrate_components = FormComponent.objects.filter(id__in=to_migrate_component_ids)

    # Create question groups
    question_group_count = 0
    for component in to_migrate_components:
        question_group = FormQuestionGroup.objects.create(
            title_en=component.title_en,
            title_es=component.title_es,
            title_ar=component.title_ar,
            title_fr=component.title_fr,
            description_en=component.description_en,
            description_es=component.description_es,
            description_ar=component.description_ar,
            description_fr=component.description_fr,
            component_id=48,
        )
        question_group_count += 1

    logger.info(f"Created QuestionGroup count {question_group_count}")

    # Attach questions to question groups
    form_questions_to_migrate = FormQuestion.objects.filter(component_id__in=to_migrate_component_ids)
    question_count = 0
    for question in form_questions_to_migrate:
        form_question_group = FormQuestionGroup.objects.filter(title_en=question.component.title_en)
        if form_question_group.exists():
            form_question_group_first = form_question_group.first()
            question.question_group = form_question_group_first
            question.save(update_fields=["question_group"])
            question_count += 1

    logger.info(f"Attached Question count {question_count}")

    # Update component responses
    FormComponentResponse.objects.filter(component_id__in=to_migrate_component_ids).update(component_id=48)

    # Update component ID for old data
    form_questions_to_migrate.update(component_id=48)

    # Delete old form components
    deleted_count, _ = to_migrate_components.delete()
    print(f"Deleted {deleted_count} FormComponent instances")

def _0100__migrate_formdata_notes(apps, schema_editor):
    FormComponentResponse = apps.get_model("per", "FormComponentResponse")
    FormData = apps.get_model("per", "FormData")

    qs = FormComponentResponse.objects.annotate(
        new_notes=models.Subquery(
            # Copy notes from FormData using overview
            FormData.objects.filter(
                form__overview=models.OuterRef("arearesponse__perassessment__overview"),
                question__component=models.OuterRef("component"),
                question__question__iexact="Component performance",
            ).values("notes_en"),
            output_field=models.CharField(),
        ),
    ).filter(new_notes__isnull=False)

    form_component_responses = []
    for form_component_response_id, assessment_id, new_notes in qs.values_list(
        "id",
        models.F("arearesponse__perassessment"),
        "new_notes",
    ):
        print(f"- Copying data for {assessment_id=} {form_component_response_id=}")
        form_component_responses.append(
            FormComponentResponse(
                id=form_component_response_id,
                notes=new_notes,
            )
        )

    print(f"Total form_component_responses notes copied: {len(form_component_responses)}")
    FormComponentResponse.objects.bulk_update(form_component_responses, fields=("notes",))

def _0106__update_component_question_group(apps, schema_editor):
    FormComponent = apps.get_model('per', 'FormComponent')
    FormComponent.objects.filter(id=48, formcomponentresponse__rating__isnull=True).update(has_question_group=True)

def _0108__update_suported_by_oragnization_type(apps, schema_editor):
    # Update all the data with supported_by_organization_type=3
    CustomPerWorkPlanComponent = apps.get_model("per", "CustomPerWorkPlanComponent")
    CustomPerWorkPlanComponent.objects.update(supported_by_organization_type=3)

def _0109__update_description_to_null(apps, schema_editor):
    # delete description form component 34 and 14F
    FormComponent = apps.get_model("per", "FormComponent")
    FormComponent.objects.filter(id=48).update(description=None)
    FormComponent.objects.filter(id=20).update(description=None)

def _0110__update_description_to_null(apps, schema_editor):
    FormComponent = apps.get_model('per', 'FormComponent')
    FormComponent.objects.filter(id__in=[48, 20, 15]).update(description=None, description_en=None, description_fr=None, description_es=None, description_ar=None)

def _0112__delete_form_question(apps, schema_editor):
    FormQuestion = apps.get_model('per', 'FormQuestion')
    print(FormQuestion.objects.filter(question__icontains='Component Epidemic Preparedness').delete())
    print(FormQuestion.objects.filter(question__icontains='Component performance').delete())


# Re-added after squashing: these carried elidable=True, so squashmigrations
# dropped them and fresh installs lost their reference data. The flag is
# deliberately omitted so a future squash keeps them.
def _0093__seed_forwards(apps, schema_editor):
    call_command("loaddata", "organizationtypes.json", verbosity=2)


def _0093__seed_reverse(apps, schema_editor):
    apps.get_model("per", "organizationtypes").objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_squashed_0232'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('deployments', '0082_squashed_0097'),
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NSPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField(choices=[(0, 'baseline'), (1, 'orientation'), (2, 'assessment'), (3, 'prioritization'), (4, 'plan of action'), (5, 'action and accountability')], default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'verbose_name': 'NS PER Process Phase',
                'verbose_name_plural': 'NS-es PER Process Phase',
                'ordering': ('updated_at', 'country'),
            },
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioritization', models.IntegerField(choices=[(0, 'low'), (1, 'medium'), (2, 'high')], default=0, verbose_name='prioritization')),
                ('components', models.CharField(blank=True, max_length=900, null=True, verbose_name='components')),
                ('benchmark', models.CharField(blank=True, max_length=900, null=True, verbose_name='benchmark')),
                ('actions', models.CharField(blank=True, max_length=900, null=True, verbose_name='actions')),
                ('comments', models.CharField(blank=True, max_length=900, null=True, verbose_name='comments')),
                ('timeline', models.DateTimeField(verbose_name='timeline')),
                ('status', models.IntegerField(choices=[(0, 'standby'), (1, 'ongoing'), (2, 'cancelled'), (3, 'delayed'), (4, 'pending'), (5, 'need improvements'), (6, 'finished'), (7, 'approved'), (8, 'closed')], default=0, verbose_name='status')),
                ('support_required', models.BooleanField(default=False, verbose_name='support required')),
                ('focal_point', models.CharField(blank=True, max_length=90, null=True, verbose_name='focal point')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='code')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country', verbose_name='country')),
                ('question_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='question id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'PER Work Plan',
                'verbose_name_plural': 'PER Work Plans',
                'ordering': ('prioritization', 'country'),
            },
        ),
        migrations.CreateModel(
            name='NiceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('document', models.FileField(blank=True, null=True, upload_to=per.models.nice_document_path, verbose_name='document')),
                ('document_url', models.URLField(blank=True, verbose_name='document url')),
                ('visibility', models.IntegerField(choices=[(0, 'hidden'), (1, 'visible')], default=1, verbose_name='visibility')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perdoc_country', to='api.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'PER Document',
                'verbose_name_plural': 'PER Documents',
                'ordering': ('visibility', 'country'),
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40, verbose_name='text')),
                ('text_ar', models.CharField(max_length=40, null=True, verbose_name='text')),
                ('text_en', models.CharField(max_length=40, null=True, verbose_name='text')),
                ('text_es', models.CharField(max_length=40, null=True, verbose_name='text')),
                ('text_fr', models.CharField(max_length=40, null=True, verbose_name='text')),
                ('translation_module_original_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language')),
                ('translation_module_skip_auto_translation', models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FormArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('area_num', models.IntegerField(default=1, verbose_name='area number')),
                ('title_ar', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('translation_module_original_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language')),
                ('translation_module_skip_auto_translation', models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation')),
            ],
        ),
        migrations.CreateModel(
            name='FormComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('component_num', models.IntegerField(default=1, verbose_name='component number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='per.formarea', verbose_name='area')),
                ('component_letter', models.CharField(blank=True, max_length=3, null=True, verbose_name='component letter')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('title_ar', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('status', models.CharField(blank=True, choices=[('high_performance', 'High Performance'), ('exists_could_be_strengthened', 'Exits Could be Strengthened'), ('needs_improvement', 'Needs Improvement'), ('partially_exists', 'Partially Exists'), ('does_not_exist', 'Does Not Exist')], max_length=100, null=True, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='question')),
                ('question_num', models.IntegerField(blank=True, null=True, verbose_name='question number')),
                ('answers', models.ManyToManyField(blank=True, to='per.formanswer', verbose_name='answers')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='per.formcomponent', verbose_name='component')),
                ('question_ar', models.CharField(max_length=500, null=True, verbose_name='question')),
                ('question_en', models.CharField(max_length=500, null=True, verbose_name='question')),
                ('question_es', models.CharField(max_length=500, null=True, verbose_name='question')),
                ('question_fr', models.CharField(max_length=500, null=True, verbose_name='question')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='description')),
                ('description_ar', tinymce.models.HTMLField(blank=True, null=True, verbose_name='description')),
                ('description_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='description')),
                ('description_es', tinymce.models.HTMLField(blank=True, null=True, verbose_name='description')),
                ('description_fr', tinymce.models.HTMLField(blank=True, null=True, verbose_name='description')),
                ('translation_module_original_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language')),
                ('translation_module_skip_auto_translation', models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('translation_module_original_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language')),
                ('translation_module_skip_auto_translation', models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation')),
            ],
            options={
                'verbose_name': 'PER Assessment Type',
                'verbose_name_plural': 'PER Assessment Types',
            },
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitator_email', models.CharField(blank=True, max_length=90, null=True, verbose_name='facilitator email')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='per_overviews', to='api.country', verbose_name='country')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('branches_involved', models.CharField(blank=True, max_length=400, null=True, verbose_name='branches involved')),
                ('date_of_assessment', models.DateField(verbose_name='date of assessment')),
                ('facilitator_contact', models.CharField(blank=True, max_length=90, null=True, verbose_name='facilitator other contacts')),
                ('facilitator_name', models.CharField(blank=True, max_length=90, null=True, verbose_name='facilitator name')),
                ('facilitator_phone', models.CharField(blank=True, max_length=90, null=True, verbose_name='facilitator phone')),
                ('method_asmt_used', models.CharField(blank=True, choices=[('per', 'Per'), ('drce', 'Drce'), ('wpns', 'WPNS')], max_length=90, null=True, verbose_name='what method has this assessment used')),
                ('ns_focal_point_email', models.CharField(blank=True, max_length=90, null=True, verbose_name='ns focal point email')),
                ('ns_focal_point_name', models.CharField(blank=True, max_length=90, null=True, verbose_name='ns focal point name')),
                ('ns_focal_point_phone', models.CharField(blank=True, max_length=90, null=True, verbose_name='ns focal point phone')),
                ('partner_focal_point_email', models.CharField(blank=True, max_length=90, null=True, verbose_name='partner focal point email')),
                ('partner_focal_point_name', models.CharField(blank=True, max_length=90, null=True, verbose_name='partner focal point name')),
                ('partner_focal_point_organization', models.CharField(blank=True, max_length=90, null=True, verbose_name='partner focal point organization name')),
                ('partner_focal_point_phone', models.CharField(blank=True, max_length=90, null=True, verbose_name='partner focal point phone')),
                ('type_of_assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_of_assessment', to='per.assessmenttype', verbose_name='type of assessment')),
                ('assessment_number', models.IntegerField(default=1, verbose_name='assessment number')),
                ('assess_climate_environment_of_country', models.BooleanField(blank=True, null=True, verbose_name='Do you want to assess the climate and environment of your National Society?')),
                ('assess_preparedness_of_country', models.BooleanField(blank=True, null=True, verbose_name='Do you want to assess the preparedness of your National Society for epidemics and pandemics?')),
                ('assess_urban_aspect_of_country', models.BooleanField(blank=True, null=True, verbose_name='Do you want to assess the urban aspects of your National Society?')),
                ('date_of_orientation', models.DateField(blank=True, null=True, verbose_name='Date of Orientation')),
                ('date_of_previous_assessment', models.DateField(blank=True, null=True, verbose_name='Date of previous assessment')),
                ('type_of_per_assessment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of Per Asessement')),
                ('workplan_development_date', models.DateField(blank=True, null=True, verbose_name='Workplan Development Date')),
                ('workplan_revision_date', models.DateField(blank=True, null=True, verbose_name='Workplan Revision Date')),
                ('ns_second_focal_point_email', models.CharField(blank=True, max_length=90, null=True, verbose_name='ns second focal point email')),
                ('ns_second_focal_point_name', models.CharField(blank=True, max_length=90, null=True, verbose_name='ns second focal point name')),
                ('ns_second_focal_point_phone', models.CharField(blank=True, max_length=90, null=True, verbose_name='ns second focal point phone')),
                ('phase', models.IntegerField(blank=True, choices=[(1, 'Orientation'), (2, 'Assessment'), (3, 'Prioritisation'), (4, 'WorkPlan'), (5, 'Action And Accoutability')], default=1, null=True, verbose_name='phase')),
                ('is_draft', models.BooleanField(blank=True, null=True, verbose_name='is draft')),
            ],
            options={
                'verbose_name': 'PER General Overview',
                'verbose_name_plural': 'PER General Overviews',
                'ordering': ('country',),
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='per.formarea', verbose_name='area')),
                ('overview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='per.overview', verbose_name='overview')),
            ],
            options={
                'ordering': ('area', 'created_at'),
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='per.form', verbose_name='form')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='per.formquestion', verbose_name='question')),
                ('selected_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='per.formanswer', verbose_name='answer')),
                ('notes_ar', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('notes_en', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('notes_es', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('notes_fr', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('translation_module_original_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language')),
                ('translation_module_skip_auto_translation', models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation')),
            ],
            options={
                'verbose_name': 'Form Data',
                'verbose_name_plural': 'Form Data',
                'ordering': ('form', 'question__question_num'),
            },
        ),
        migrations.CreateModel(
            name='CustomPerWorkPlanComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.TextField(blank=True, max_length=900, null=True, verbose_name='Actions')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'Ongoing'), (2, 'Delayed'), (3, 'Standby'), (4, 'Finished')], default=0, verbose_name='status')),
                ('supported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='FormComponentConsiderations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urban_considerations', models.TextField(blank=True, null=True, verbose_name='Urban Considerations')),
                ('epi_considerations', models.TextField(blank=True, null=True, verbose_name='Epi Considerations')),
                ('climate_environmental_conisderations', models.TextField(blank=True, null=True, verbose_name='Climate Environmental Considerations')),
            ],
        ),
        migrations.CreateModel(
            name='FormComponentQuestionAndAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='per.formanswer', verbose_name='answer')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='per.formquestion', verbose_name='question')),
            ],
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='question_responses',
            field=models.ManyToManyField(blank=True, to='per.formcomponentquestionandanswer', verbose_name='Question responses'),
        ),
        migrations.CreateModel(
            name='FormComponentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='per.formcomponent', verbose_name='Form Component')),
                ('consideration_responses', models.ManyToManyField(blank=True, to='per.formcomponentconsiderations', verbose_name='Consideration responses')),
                ('question_responses', models.ManyToManyField(blank=True, to='per.formcomponentquestionandanswer', verbose_name='Question responses')),
            ],
        ),
        migrations.CreateModel(
            name='AreaResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='per.formarea', verbose_name='Area')),
                ('component_response', models.ManyToManyField(blank=True, to='per.formcomponentresponse', verbose_name='Component Response')),
            ],
        ),
        migrations.CreateModel(
            name='FormPrioritizationComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_prioritized', models.BooleanField(blank=True, null=True, verbose_name='Is prioritized')),
                ('justification_text', models.TextField(blank=True, null=True, verbose_name='Justification Text')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='per.formcomponent', verbose_name='component')),
            ],
        ),
        migrations.CreateModel(
            name='PerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='per/images/', verbose_name='file')),
                ('caption', models.CharField(blank=True, max_length=225, null=True)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
            ],
            options={
                'verbose_name': 'per file',
                'verbose_name_plural': 'per files',
            },
        ),
        migrations.CreateModel(
            name='PerComponentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('value', models.IntegerField(verbose_name='value')),
            ],
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='per.percomponentrating'),
        ),
        migrations.CreateModel(
            name='PerWorkPlanComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.TextField(blank=True, max_length=900, null=True, verbose_name='Actions')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'Ongoing'), (2, 'Delayed'), (3, 'Standby'), (4, 'Finished')], default=0, verbose_name='status')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='per.formcomponent', verbose_name='Component')),
                ('supported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.AddField(
            model_name='overview',
            name='orientation_documents',
            field=models.ManyToManyField(blank=True, to='per.perfile', verbose_name='orientation documents'),
        ),
        migrations.CreateModel(
            name='FormPrioritization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioritized_action_responses', models.ManyToManyField(blank=True, to='per.formprioritizationcomponent', verbose_name='Form prioritization component')),
                ('overview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='per.overview', verbose_name='Overview')),
                ('is_draft', models.BooleanField(default=True, verbose_name='is draft')),
            ],
        ),
        migrations.CreateModel(
            name='PerWorkPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='per.overview', verbose_name='Overview')),
                ('prioritized_action_responses', models.ManyToManyField(blank=True, to='per.perworkplancomponent', verbose_name='WorkPlan Component')),
                ('additional_action_responses', models.ManyToManyField(blank=True, to='per.customperworkplancomponent', verbose_name='Custom Per-WorkPlan Component')),
                ('is_draft', models.BooleanField(default=True, verbose_name='is draft')),
            ],
        ),
        migrations.AlterField(
            model_name='overview',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='is draft'),
        ),
        migrations.CreateModel(
            name='PerAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_responses', models.ManyToManyField(blank=True, to='per.arearesponse', verbose_name='Area Response')),
                ('overview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='per.overview', verbose_name='Overview')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('is_draft', models.BooleanField(default=True, verbose_name='is draft')),
            ],
        ),
        migrations.RemoveField(
            model_name='formcomponentresponse',
            name='consideration_responses',
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='climate_environmental_considerations',
            field=models.TextField(blank=True, null=True, verbose_name='Climate Environmental Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='epi_considerations',
            field=models.TextField(blank=True, null=True, verbose_name='Epi Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='urban_considerations',
            field=models.TextField(blank=True, null=True, verbose_name='Urban Considerations'),
        ),
        migrations.DeleteModel(
            name='FormComponentConsiderations',
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.RenameField(
            model_name='overview',
            old_name='method_asmt_used',
            new_name='assessment_method',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='type_of_per_assessment',
        ),
        migrations.AddField(
            model_name='overview',
            name='type_of_previous_assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_of_previous_assessment', to='per.assessmenttype', verbose_name='type of previous assessment'),
        ),
        migrations.AlterField(
            model_name='formcomponentresponse',
            name='component',
            field=models.ForeignKey(default=85, on_delete=django.db.models.deletion.CASCADE, to='per.formcomponent', verbose_name='Form Component'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formprioritizationcomponent',
            name='component',
            field=models.ForeignKey(default=85, on_delete=django.db.models.deletion.CASCADE, to='per.formcomponent', verbose_name='component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='date_of_assessment',
            field=models.DateField(blank=True, null=True, verbose_name='date of assessment'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='assessment_method',
            field=models.CharField(blank=True, choices=[('per', 'PER'), ('drce', 'DRCE'), ('wpns', 'WPNS')], max_length=90, null=True, verbose_name='what method has this assessment used'),
        ),
        migrations.RunPython(
            code=_0086__migrate_data,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=_0087__update_phase,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=_0088__update_overview_assessment_method,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='overview',
            name='type_of_previous_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_of_previous_assessment', to='per.assessmenttype', verbose_name='type of previous assessment'),
        ),
        migrations.RunPython(
            code=_0090__update_question_answer,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='OpsLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning', models.TextField(blank=True, null=True, verbose_name='learning')),
                ('learning_validated', models.TextField(blank=True, null=True, verbose_name='learning (validated)')),
                ('appeal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='appeal (MDR) code')),
                ('type', models.IntegerField(choices=[(1, 'Lesson learned'), (2, 'Challenge')], default=1, verbose_name='type')),
                ('type_validated', models.IntegerField(choices=[(1, 'Lesson learned'), (2, 'Challenge')], default=1, verbose_name='type (validated)')),
                ('is_validated', models.BooleanField(default=False, verbose_name='is validated?')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('per_component', models.ManyToManyField(blank=True, related_name='components', to='per.formcomponent', verbose_name='PER Components')),
                ('per_component_validated', models.ManyToManyField(blank=True, related_name='validated_components', to='per.formcomponent', verbose_name='PER Components (validated)')),
                ('sector', models.ManyToManyField(blank=True, related_name='sectors', to='deployments.sectortag', verbose_name='Sectors')),
                ('sector_validated', models.ManyToManyField(blank=True, related_name='validated_sectors', to='deployments.sectortag', verbose_name='Sectors (validated)')),
                ('organization', models.IntegerField(choices=[(1, 'Secretariat'), (2, 'National Society')], default=1, verbose_name='organization')),
                ('organization_validated', models.IntegerField(choices=[(1, 'Secretariat'), (2, 'National Society')], default=1, verbose_name='organization (validated)')),
            ],
            options={
                'verbose_name': 'Operational Learning',
                'verbose_name_plural': 'Operational Learnings',
                'ordering': ('learning',),
            },
        ),
        migrations.AddField(
            model_name='perworkplancomponent',
            name='supported_by_organization_type',
            field=models.IntegerField(blank=True, choices=[(0, 'UN Organization'), (1, 'Private Sector'), (2, 'Government'), (3, 'National Society')], null=True, verbose_name='Supported By Organization Type'),
        ),
        migrations.RunPython(
            code=_0094__update_suported_by_oragnization_type,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='PerDocumentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='per/documents/', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country', verbose_name='country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
            ],
        ),
        migrations.RunPython(
            code=_0096__migrate_formdata_notes,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='is_parent',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is parent'),
        ),
        migrations.RunPython(
            code=_0098__update_component_description,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='FormQuestionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_ar', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description')),
                ('translation_module_original_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language')),
                ('translation_module_skip_auto_translation', models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='per.formcomponent', verbose_name='component')),
            ],
        ),
        migrations.AddField(
            model_name='formquestion',
            name='question_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='per.formquestiongroup'),
        ),
        migrations.RunPython(
            code=_0100__migrate_component_to_question_group,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='OrganizationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('is_deprecated', models.BooleanField(default=False, help_text='Is this a deprecated Organization type?')),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Organization type',
                'verbose_name_plural': 'Organization types',
            },
        ),
        migrations.RunPython(
            code=_0093__seed_forwards,
            reverse_code=_0093__seed_reverse,
        ),
        migrations.RemoveField(
            model_name='opslearning',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='opslearning',
            name='organization_validated',
        ),
        migrations.AddField(
            model_name='opslearning',
            name='organization',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='per.organizationtypes', verbose_name='Organizations'),
        ),
        migrations.AddField(
            model_name='opslearning',
            name='organization_validated',
            field=models.ManyToManyField(blank=True, related_name='validated_organizations', to='per.organizationtypes', verbose_name='Organizations (validated)'),
        ),
        migrations.AddField(
            model_name='opslearning',
            name='appeal_document_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Appeal document ID'),
        ),
        migrations.AlterField(
            model_name='opslearning',
            name='appeal_code',
            field=models.ForeignKey(blank=True, db_column='appeal_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.appeal', to_field='code', verbose_name='appeal (MDR) code'),
        ),
        migrations.RunPython(
            code=_0098__modify_per_datetime_data_to_date,
            reverse_code=_0098__modify_per_date_data_to_datetime,
        ),
        migrations.RunPython(
            code=_0099__migrate_formdata_notes,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=_0100__migrate_formdata_notes,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='overview',
            name='phase',
            field=models.IntegerField(blank=True, choices=[(1, 'Orientation'), (2, 'Assessment'), (3, 'Prioritisation'), (4, 'WorkPlan'), (5, 'Action And Accountability')], default=1, null=True, verbose_name='phase'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='has_question_group',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has Question Group'),
        ),
        migrations.RunPython(
            code=_0106__update_component_question_group,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='customperworkplancomponent',
            name='supported_by_organization_type',
            field=models.IntegerField(blank=True, choices=[(0, 'UN Organization'), (1, 'Private Sector'), (2, 'Government'), (3, 'National Society')], null=True, verbose_name='Supported By Organization Type'),
        ),
        migrations.RunPython(
            code=_0108__update_suported_by_oragnization_type,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=_0109__update_description_to_null,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=_0110__update_description_to_null,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='perdocumentupload',
            name='per',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='per.overview', verbose_name='Per'),
        ),
        migrations.RunPython(
            code=_0112__delete_form_question,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='notes_ar',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='notes_es',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='notes_fr',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='climate_environmental_considerations_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Climate Environmental Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='climate_environmental_considerations_en',
            field=models.TextField(blank=True, null=True, verbose_name='Climate Environmental Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='climate_environmental_considerations_es',
            field=models.TextField(blank=True, null=True, verbose_name='Climate Environmental Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='climate_environmental_considerations_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Climate Environmental Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='epi_considerations_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Epi Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='epi_considerations_en',
            field=models.TextField(blank=True, null=True, verbose_name='Epi Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='epi_considerations_es',
            field=models.TextField(blank=True, null=True, verbose_name='Epi Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='epi_considerations_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Epi Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='notes_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='notes_es',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='notes_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='urban_considerations_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Urban Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='urban_considerations_en',
            field=models.TextField(blank=True, null=True, verbose_name='Urban Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='urban_considerations_es',
            field=models.TextField(blank=True, null=True, verbose_name='Urban Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='urban_considerations_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Urban Considerations'),
        ),
        migrations.AddField(
            model_name='overview',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='overview',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='arearesponse',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='arearesponse',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='perassessment',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='perassessment',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='title_ar',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='title_es',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='title_fr',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='customperworkplancomponent',
            name='actions_ar',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='Actions'),
        ),
        migrations.AddField(
            model_name='customperworkplancomponent',
            name='actions_en',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='Actions'),
        ),
        migrations.AddField(
            model_name='customperworkplancomponent',
            name='actions_es',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='Actions'),
        ),
        migrations.AddField(
            model_name='customperworkplancomponent',
            name='actions_fr',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='Actions'),
        ),
        migrations.AddField(
            model_name='customperworkplancomponent',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='customperworkplancomponent',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='formprioritizationcomponent',
            name='justification_text_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Justification Text'),
        ),
        migrations.AddField(
            model_name='formprioritizationcomponent',
            name='justification_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Justification Text'),
        ),
        migrations.AddField(
            model_name='formprioritizationcomponent',
            name='justification_text_es',
            field=models.TextField(blank=True, null=True, verbose_name='Justification Text'),
        ),
        migrations.AddField(
            model_name='formprioritizationcomponent',
            name='justification_text_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Justification Text'),
        ),
        migrations.AddField(
            model_name='formprioritizationcomponent',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='formprioritizationcomponent',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='perworkplancomponent',
            name='actions_ar',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='Actions'),
        ),
        migrations.AddField(
            model_name='perworkplancomponent',
            name='actions_en',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='Actions'),
        ),
        migrations.AddField(
            model_name='perworkplancomponent',
            name='actions_es',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='Actions'),
        ),
        migrations.AddField(
            model_name='perworkplancomponent',
            name='actions_fr',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='Actions'),
        ),
        migrations.AddField(
            model_name='perworkplancomponent',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='perworkplancomponent',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AlterField(
            model_name='formcomponent',
            name='status',
            field=models.CharField(blank=True, choices=[('high_performance', 'High Performance'), ('exists_could_be_strengthened', 'Exists – Could be Strengthened'), ('needs_improvement', 'Needs Improvement'), ('partially_exists', 'Partially Exists'), ('does_not_exist', 'Does Not Exist')], max_length=100, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='climate_environmental_considerations_guidance',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Climate and Environmental Considerations '),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='climate_environmental_considerations_guidance_ar',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Climate and Environmental Considerations '),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='climate_environmental_considerations_guidance_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Climate and Environmental Considerations '),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='climate_environmental_considerations_guidance_es',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Climate and Environmental Considerations '),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='climate_environmental_considerations_guidance_fr',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Climate and Environmental Considerations '),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='epi_considerations_guidance',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='EPI Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='epi_considerations_guidance_ar',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='EPI Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='epi_considerations_guidance_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='EPI Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='epi_considerations_guidance_es',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='EPI Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='epi_considerations_guidance_fr',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='EPI Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='urban_considerations_guidance',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Urban Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='urban_considerations_guidance_ar',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Urban Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='urban_considerations_guidance_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Urban Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='urban_considerations_guidance_es',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Urban Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='urban_considerations_guidance_fr',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Urban Considerations'),
        ),
        migrations.CreateModel(
            name='OpsLearningCacheResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_filters_hash', models.CharField(max_length=32, verbose_name='used filters hash')),
                ('used_filters', models.JSONField(default=dict, verbose_name='used filters')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Started'), (3, 'Success'), (4, 'No extract available'), (5, 'Failed')], default=1, verbose_name='status')),
                ('insights1_content', models.TextField(blank=True, null=True, verbose_name='insights 1')),
                ('insights1_content_en', models.TextField(blank=True, null=True, verbose_name='insights 1')),
                ('insights1_content_es', models.TextField(blank=True, null=True, verbose_name='insights 1')),
                ('insights1_content_fr', models.TextField(blank=True, null=True, verbose_name='insights 1')),
                ('insights1_content_ar', models.TextField(blank=True, null=True, verbose_name='insights 1')),
                ('insights2_content', models.TextField(blank=True, null=True, verbose_name='insights 2')),
                ('insights2_content_en', models.TextField(blank=True, null=True, verbose_name='insights 2')),
                ('insights2_content_es', models.TextField(blank=True, null=True, verbose_name='insights 2')),
                ('insights2_content_fr', models.TextField(blank=True, null=True, verbose_name='insights 2')),
                ('insights2_content_ar', models.TextField(blank=True, null=True, verbose_name='insights 2')),
                ('insights3_content', models.TextField(blank=True, null=True, verbose_name='insights 3')),
                ('insights3_content_en', models.TextField(blank=True, null=True, verbose_name='insights 3')),
                ('insights3_content_es', models.TextField(blank=True, null=True, verbose_name='insights 3')),
                ('insights3_content_fr', models.TextField(blank=True, null=True, verbose_name='insights 3')),
                ('insights3_content_ar', models.TextField(blank=True, null=True, verbose_name='insights 3')),
                ('insights1_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 1 title')),
                ('insights1_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 1 title')),
                ('insights1_title_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 1 title')),
                ('insights1_title_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 1 title')),
                ('insights1_title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 1 title')),
                ('insights2_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 2 title')),
                ('insights2_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 2 title')),
                ('insights2_title_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 2 title')),
                ('insights2_title_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 2 title')),
                ('insights2_title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 2 title')),
                ('insights3_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 3 title')),
                ('insights3_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 3 title')),
                ('insights3_title_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 3 title')),
                ('insights3_title_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 3 title')),
                ('insights3_title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='insights 3 title')),
                ('insights1_confidence_level', models.CharField(blank=True, max_length=10, null=True, verbose_name='insights 1 confidence level')),
                ('insights2_confidence_level', models.CharField(blank=True, max_length=10, null=True, verbose_name='insights 2 confidence level')),
                ('insights3_confidence_level', models.CharField(blank=True, max_length=10, null=True, verbose_name='insights 3 confidence level')),
                ('contradictory_reports', models.TextField(blank=True, null=True, verbose_name='contradictory reports')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('export_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed')], default=1, verbose_name='export status')),
                ('exported_file', models.FileField(blank=True, null=True, upload_to='ops-learning/summary/export/', verbose_name='exported file')),
                ('exported_at', models.DateTimeField(blank=True, null=True, verbose_name='exported at')),
                ('translation_module_original_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language')),
                ('translation_module_skip_auto_translation', models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation')),
            ],
        ),
        migrations.AddField(
            model_name='opslearning',
            name='learning_ar',
            field=models.TextField(blank=True, null=True, verbose_name='learning'),
        ),
        migrations.AddField(
            model_name='opslearning',
            name='learning_en',
            field=models.TextField(blank=True, null=True, verbose_name='learning'),
        ),
        migrations.AddField(
            model_name='opslearning',
            name='learning_es',
            field=models.TextField(blank=True, null=True, verbose_name='learning'),
        ),
        migrations.AddField(
            model_name='opslearning',
            name='learning_fr',
            field=models.TextField(blank=True, null=True, verbose_name='learning'),
        ),
        migrations.AddField(
            model_name='opslearning',
            name='learning_validated_ar',
            field=models.TextField(blank=True, null=True, verbose_name='learning (validated)'),
        ),
        migrations.AddField(
            model_name='opslearning',
            name='learning_validated_en',
            field=models.TextField(blank=True, null=True, verbose_name='learning (validated)'),
        ),
        migrations.AddField(
            model_name='opslearning',
            name='learning_validated_es',
            field=models.TextField(blank=True, null=True, verbose_name='learning (validated)'),
        ),
        migrations.AddField(
            model_name='opslearning',
            name='learning_validated_fr',
            field=models.TextField(blank=True, null=True, verbose_name='learning (validated)'),
        ),
        migrations.AddField(
            model_name='opslearning',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='opslearning',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.CreateModel(
            name='OpsLearningSectorCacheResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='content')),
                ('content_es', models.TextField(blank=True, null=True, verbose_name='content')),
                ('content_fr', models.TextField(blank=True, null=True, verbose_name='content')),
                ('content_ar', models.TextField(blank=True, null=True, verbose_name='content')),
                ('translation_module_original_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language')),
                ('translation_module_skip_auto_translation', models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation')),
                ('filter_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_learning_sector', to='per.opslearningcacheresponse', verbose_name='filter response')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='deployments.sectortag', verbose_name='sector')),
                ('used_ops_learning', models.ManyToManyField(related_name='+', to='per.opslearning')),
            ],
        ),
        migrations.CreateModel(
            name='OpsLearningComponentCacheResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='content')),
                ('content_es', models.TextField(blank=True, null=True, verbose_name='content')),
                ('content_fr', models.TextField(blank=True, null=True, verbose_name='content')),
                ('content_ar', models.TextField(blank=True, null=True, verbose_name='content')),
                ('translation_module_original_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language')),
                ('translation_module_skip_auto_translation', models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='per.formcomponent', verbose_name='component')),
                ('filter_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_learning_component', to='per.opslearningcacheresponse', verbose_name='filter response')),
                ('used_ops_learning', models.ManyToManyField(related_name='+', to='per.opslearning')),
            ],
        ),
        migrations.AddField(
            model_name='opslearningcacheresponse',
            name='used_ops_learning',
            field=models.ManyToManyField(related_name='+', to='per.opslearning'),
        ),
        migrations.AlterField(
            model_name='perdocumentupload',
            name='file',
            field=main.fields.SecureFileField(upload_to='per/documents/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='perfile',
            name='file',
            field=main.fields.SecureFileField(upload_to='per/images/', verbose_name='file'),
        ),
        migrations.CreateModel(
            name='OpsLearningPromptResponseCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_hash', models.CharField(max_length=32, verbose_name='used prompt hash')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='used prompt')),
                ('type', models.IntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Sector'), (4, 'Component')], verbose_name='type')),
                ('response', models.JSONField(default=dict, verbose_name='response')),
            ],
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='migration_considerations_guidance',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Migration Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='migration_considerations_guidance_ar',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Migration Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='migration_considerations_guidance_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Migration Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='migration_considerations_guidance_es',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Migration Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='migration_considerations_guidance_fr',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Migration Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='migration_considerations',
            field=models.TextField(blank=True, null=True, verbose_name='Migration Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='migration_considerations_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Migration Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='migration_considerations_en',
            field=models.TextField(blank=True, null=True, verbose_name='Migration Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='migration_considerations_es',
            field=models.TextField(blank=True, null=True, verbose_name='Migration Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='migration_considerations_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Migration Considerations'),
        ),
        migrations.AddField(
            model_name='overview',
            name='assess_migration_aspect_of_country',
            field=models.BooleanField(blank=True, null=True, verbose_name='Do you want to assess the migration aspects of your National Society?'),
        ),
    ]
