# Generated by Django 2.0.12 on 2019-06-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0004_auto_20190520_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ('code', 'name', 'language', 'created_at'), 'verbose_name': 'Form', 'verbose_name_plural': 'Forms'},
        ),
    ]
