# Generated by Django 2.0.12 on 2019-07-09 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0008_erureadiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsphase',
            name='country',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Country'),
        ),
    ]
