# Generated by Django 2.0.12 on 2019-07-11 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0011_auto_20190711_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erureadiness',
            name='national_society',
        ),
        migrations.AlterField(
            model_name='workplan',
            name='components',
            field=models.CharField(blank=True, help_text='Redundant, if the form details are given below', max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Redundant, if the form is given below', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country'),
        ),
        migrations.DeleteModel(
            name='ERUReadiness',
        ),
    ]
