# Generated by Django 2.0.12 on 2019-07-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0012_auto_20190711_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplan',
            name='form',
        ),
    ]
