# Generated by Django 2.0.12 on 2019-07-11 10:31

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import per.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190703_0614'),
        ('per', '0013_remove_workplan_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_current_capacity_assessment', models.DateTimeField(auto_now=True)),
                ('type_of_capacity_assessment', enumfields.fields.EnumIntegerField(default=0, enum=per.models.CAssessmentType)),
                ('branch_involved', models.CharField(blank=True, max_length=90, null=True)),
                ('focal_point_name', models.CharField(blank=True, max_length=90, null=True)),
                ('focal_point_email', models.CharField(blank=True, max_length=90, null=True)),
                ('had_previous_assessment', models.BooleanField(default=False)),
                ('focus', models.CharField(blank=True, max_length=90, null=True)),
                ('facilitated_by', models.CharField(blank=True, max_length=90, null=True)),
                ('facilitator_email', models.CharField(blank=True, max_length=90, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=90, null=True)),
                ('skype_address', models.CharField(blank=True, max_length=90, null=True)),
                ('date_of_mid_term_review', models.DateTimeField(auto_now=True)),
                ('approximate_date_next_capacity_assmt', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asmt_country', to='api.Country')),
            ],
            options={
                'verbose_name': 'PER General Overview',
                'verbose_name_plural': 'PER General Overviews',
                'ordering': ('country',),
            },
        ),
    ]
