# Generated by Django 2.0.12 on 2019-07-15 11:17

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import per.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190703_0614'),
        ('per', '0016_auto_20190711_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to=per.models.nice_document_path)),
                ('document_url', models.URLField(blank=True)),
                ('visibility', enumfields.fields.EnumIntegerField(default=1, enum=per.models.Visibilities)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perdoc_country', to='api.Country')),
            ],
            options={
                'verbose_name': 'PER Document',
                'verbose_name_plural': 'PER Documents',
                'ordering': ('visibility', 'country'),
            },
        ),
    ]
