# Generated by Django 2.2.13 on 2020-10-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0022_auto_20201012_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='answers',
            field=models.ManyToManyField(blank=True, to='per.FormAnswer', verbose_name='answers'),
        ),
    ]
