# Generated by Django 2.2.13 on 2020-10-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0023_auto_20201012_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcomponent',
            name='component_letter',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='component letter'),
        ),
    ]
