# Generated by Django 2.2.13 on 2020-10-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0025_auto_20201028_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name': 'PER Assessment Type',
                'verbose_name_plural': 'PER Assessment Types',
            },
        ),
        migrations.RemoveField(
            model_name='overview',
            name='type_of_capacity_assessment',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='type_of_last_capacity_assessment',
        ),
        migrations.AddField(
            model_name='overview',
            name='type_of_ca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_of_capacity_assessment', to='per.AssessmentType', verbose_name='type of capacity assessment'),
        ),
        migrations.AddField(
            model_name='overview',
            name='type_of_last_ca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_of_last_capacity_assessment', to='per.AssessmentType', verbose_name='type of last capacity assessment'),
        ),
    ]
