# Generated by Django 2.2.13 on 2020-10-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0026_auto_20201029_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttype',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='name_es',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='formanswer',
            name='text_ar',
            field=models.CharField(max_length=40, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='formanswer',
            name='text_en',
            field=models.CharField(max_length=40, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='formanswer',
            name='text_es',
            field=models.CharField(max_length=40, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='formanswer',
            name='text_fr',
            field=models.CharField(max_length=40, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='formarea',
            name='title_ar',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='formarea',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='formarea',
            name='title_es',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='formarea',
            name='title_fr',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='notes_ar',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='notes_es',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='notes_fr',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='question_ar',
            field=models.CharField(max_length=500, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='question_en',
            field=models.CharField(max_length=500, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='question_es',
            field=models.CharField(max_length=500, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='question_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='question'),
        ),
    ]
