# Generated by Django 2.2.13 on 2020-11-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0029_auto_20201105_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='approximate_date_next_capacity_assmt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='approximate date next capacity assessment'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='date_of_current_capacity_assessment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of current capacity assessment'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='date_of_mid_term_review',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of mid term review'),
        ),
    ]
