# Generated by Django 2.2.13 on 2020-11-16 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0032_remove_form_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='approximate_date_next_capacity_assmt',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='branch_involved',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='date_of_current_capacity_assessment',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='date_of_last_capacity_assessment',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='facilitated_by',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='focal_point_email',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='focal_point_name',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='focus',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='had_previous_assessment',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='skype_address',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='type_of_ca',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='type_of_last_ca',
        ),
        migrations.AddField(
            model_name='overview',
            name='branches_involved',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='branches involved'),
        ),
        migrations.AddField(
            model_name='overview',
            name='date_of_assessment',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overview',
            name='date_of_next_asmt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='estimated date of next assessment'),
        ),
        migrations.AddField(
            model_name='overview',
            name='facilitator_contact',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='facilitated other contacts'),
        ),
        migrations.AddField(
            model_name='overview',
            name='facilitator_name',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='facilitator name'),
        ),
        migrations.AddField(
            model_name='overview',
            name='facilitator_phone',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='facilitated phone'),
        ),
        migrations.AddField(
            model_name='overview',
            name='method_asmt_used',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='what method has this assessment used'),
        ),
        migrations.AddField(
            model_name='overview',
            name='ns_focal_point_email',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='ns focal point email'),
        ),
        migrations.AddField(
            model_name='overview',
            name='ns_focal_point_name',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='ns focal point name'),
        ),
        migrations.AddField(
            model_name='overview',
            name='ns_focal_point_phone',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='ns focal point phone'),
        ),
        migrations.AddField(
            model_name='overview',
            name='other_consideration',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='other consideration'),
        ),
        migrations.AddField(
            model_name='overview',
            name='partner_focal_point_email',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='partner focal point email'),
        ),
        migrations.AddField(
            model_name='overview',
            name='partner_focal_point_name',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='partner focal point name'),
        ),
        migrations.AddField(
            model_name='overview',
            name='partner_focal_point_organization',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='partner focal point organization name'),
        ),
        migrations.AddField(
            model_name='overview',
            name='partner_focal_point_phone',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='partner focal point phone'),
        ),
        migrations.AddField(
            model_name='overview',
            name='type_of_assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_of_assessment', to='per.AssessmentType', verbose_name='type of assessment'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='date_of_mid_term_review',
            field=models.DateTimeField(blank=True, null=True, verbose_name='estimated date of mid term review'),
        ),
    ]
