# Generated by Django 3.2.18 on 2023-05-10 05:27

from django.db import migrations, models
import per.validators


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0046_form_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perworkplancomponent',
            name='responsible_email',
        ),
        migrations.RemoveField(
            model_name='perworkplancomponent',
            name='responsible_name',
        ),
        migrations.AddField(
            model_name='perworkplan',
            name='custom_component',
            field=models.JSONField(blank=True, default=dict, validators=[per.validators.validate_custom_component], verbose_name='Custom Component'),
        ),
        migrations.AlterField(
            model_name='perworkplancomponent',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due date'),
        ),
    ]
