# Generated by Django 3.2.19 on 2023-06-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0048_auto_20230608_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='arearesponse',
            name='is_draft',
            field=models.BooleanField(blank=True, null=True, verbose_name='is draft'),
        ),
    ]
