# Generated by Django 3.2.19 on 2023-06-08 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("per", "0049_auto_20230608_0621"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perassessment",
            name="overview",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="per.overview", verbose_name="Overview"),
        ),
    ]
