# Generated by Django 3.2.19 on 2023-06-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0050_alter_perassessment_overview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perassessment',
            old_name='area_response',
            new_name='area_responses',
        ),
    ]
