# Generated by Django 3.2.19 on 2023-06-08 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0051_rename_area_response_perassessment_area_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormComponentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('high_performance', 'High Performance'), ('exists_could_be_strengthened', 'Exits Could be Strengthened'), ('needs_improvement', 'Needs Improvement'), ('partially_exists', 'Partially Exists'), ('does_not_exist', 'Does Not Exist')], max_length=100, null=True, verbose_name='status')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='per.formcomponent', verbose_name='Form Component')),
                ('consideration_responses', models.ManyToManyField(blank=True, to='per.FormComponentConsiderations', verbose_name='Consideration responses')),
                ('question_responses', models.ManyToManyField(blank=True, to='per.FormComponentQuestionAndAnswer', verbose_name='Question responses')),
            ],
        ),
        migrations.AlterField(
            model_name='arearesponse',
            name='component_response',
            field=models.ManyToManyField(blank=True, to='per.FormComponentResponse', verbose_name='Component Response'),
        ),
    ]
