# Generated by Django 3.2.19 on 2023-06-08 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("per", "0053_auto_20230608_0919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formprioritizationcomponent",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="per.formcomponent",
                verbose_name="component",
            ),
        ),
        migrations.AlterField(
            model_name="perworkplan",
            name="overview",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="per.overview", verbose_name="Overview"
            ),
        ),
    ]
