# Generated by Django 3.2.19 on 2023-06-09 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0054_auto_20230608_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcomponentresponse',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='per.formcomponent', verbose_name='Form Component'),
        ),
        migrations.AlterField(
            model_name='perassessment',
            name='overview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='per.overview', verbose_name='Overview'),
        ),
    ]
