# Generated by Django 3.2.19 on 2023-06-13 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('per', '0055_auto_20230609_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='per/images/', verbose_name='file')),
                ('caption', models.CharField(blank=True, max_length=225, null=True)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
            ],
            options={
                'verbose_name': 'per file',
                'verbose_name_plural': 'per files',
            },
        ),
    ]
