# Generated by Django 3.2.19 on 2023-06-13 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0057_remove_overview_orientation_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='orientation_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientation_document_dref', to='per.perfile', verbose_name='orientation document'),
        ),
    ]
