# Generated by Django 3.2.19 on 2023-06-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0058_overview_orientation_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='is_epi',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is epi'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='is_finalized',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is finalized'),
        ),
    ]
