# Generated by Django 3.2.19 on 2023-06-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0060_perassessment_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='phase',
            field=models.IntegerField(blank=True, choices=[(1, 'Orientation'), (2, 'Assessment'), (3, 'Prioritisation'), (4, 'WorkPlan'), (5, 'Action And Accoutability')], null=True, verbose_name='phase'),
        ),
    ]
