# Generated by Django 3.2.19 on 2023-06-21 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_auto_20230425_1120'),
        ('per', '0062_alter_overview_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='perworkplancomponent',
            name='supported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
    ]
