# Generated by Django 3.2.19 on 2023-06-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0064_overview_is_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formcomponentresponse',
            old_name='status',
            new_name='rating',
        ),
    ]
