# Generated by Django 3.2.19 on 2023-06-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0065_rename_status_formcomponentresponse_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formcomponentresponse',
            name='rating',
        ),
    ]
