# Generated by Django 3.2.19 on 2023-06-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0066_remove_formcomponentresponse_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerComponentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('value', models.IntegerField(verbose_name='value')),
            ],
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='per.percomponentrating'),
        ),
    ]
