# Generated by Django 3.2.19 on 2023-06-22 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0070_auto_20230622_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arearesponse',
            name='is_draft',
        ),
    ]
