# Generated by Django 3.2.19 on 2023-06-23 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0071_remove_arearesponse_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='orientation_document',
        ),
    ]
