# Generated by Django 3.2.19 on 2023-07-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0041_auto_20230410_0720'),
        ('per', '0075_auto_20230628_0552'),
    ]

    operations = [
    ]
