# Generated by Django 3.2.20 on 2023-07-12 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0078_auto_20230711_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcomponentquestionandanswer',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='per.formanswer', verbose_name='answer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formcomponentquestionandanswer',
            name='question',
            field=models.ForeignKey(default=422, on_delete=django.db.models.deletion.CASCADE, to='per.formquestion', verbose_name='question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formcomponentresponse',
            name='component',
            field=models.ForeignKey(default=85, on_delete=django.db.models.deletion.CASCADE, to='per.formcomponent', verbose_name='Form Component'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formprioritizationcomponent',
            name='component',
            field=models.ForeignKey(default=85, on_delete=django.db.models.deletion.CASCADE, to='per.formcomponent', verbose_name='component'),
            preserve_default=False,
        ),
    ]
