# Generated by Django 3.2.20 on 2023-07-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0079_auto_20230712_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcomponentresponse',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
