# Generated by Django 3.2.20 on 2023-09-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    def update_phase(apps, schema_editor):
        Overview = apps.get_model("per", "Overview")
        FormPrioritization = apps.get_model("per", "FormPrioritization")
        overviews = Overview.objects.all()
        for overview in overviews:
            overview.phase = 2
            overview.save(update_fields=["phase"])

    dependencies = [
        ("per", "0086_migrate_old_form"),
    ]

    operations = [
        migrations.RunPython(update_phase, reverse_code=migrations.RunPython.noop),
    ]
