# Generated by Django 3.2.20 on 2023-10-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0088_update_assessment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='type_of_previous_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_of_previous_assessment', to='per.assessmenttype', verbose_name='type of previous assessment'),
        ),
    ]
