# Generated by Django 3.2.23 on 2024-01-16 17:39

from django.core.management import call_command
from django.db import migrations, models


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        print("forwards")
        call_command("loaddata", "organizationtypes.json", verbosity=2)

    def reverse_func(apps, schema_editor):
        print("reverse")
        model = apps.get_model("per", "organizationtypes")
        model.objects.all().delete()

    dependencies = [
        ("per", "0092_auto_20240109_1950"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationTypes",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("is_deprecated", models.BooleanField(default=False, help_text="Is this a deprecated Organization type?")),
                ("order", models.SmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Organization type",
                "verbose_name_plural": "Organization types",
            },
        ),
        migrations.RunPython(forwards_func, reverse_func, elidable=True),
        migrations.AddField(
            model_name="opslearning",
            name="organization2",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="per.OrganizationTypes", verbose_name="Organizations"
            ),
        ),
        migrations.AddField(
            model_name="opslearning",
            name="organization2_validated",
            field=models.ManyToManyField(
                blank=True,
                related_name="validated_organizations",
                to="per.OrganizationTypes",
                verbose_name="Organizations (validated)",
            ),
        ),
    ]
