# Generated by Django 3.2.23 on 2024-02-08 05:02

from django.db import migrations

from main.utils import DjangoReversionDataFixHelper


def modify_per_datetime_data_to_date(self, schema_editor):
    ContentType = self.get_model("contenttypes", "ContentType")
    Version = self.get_model("reversion", "Version")
    Overview = self.get_model("per", "Overview")
    DjangoReversionDataFixHelper.datetime_fields_to_date(ContentType, Version, Overview, ["date_of_assessment"])


def modify_per_date_data_to_datetime(self, schema_editor):
    ContentType = self.get_model("contenttypes", "ContentType")
    Version = self.get_model("reversion", "Version")
    Overview = self.get_model("per", "Overview")
    DjangoReversionDataFixHelper.date_fields_to_datetime(ContentType, Version, Overview, ["date_of_assessment"])


class Migration(migrations.Migration):

    dependencies = [
        ("reversion", "0001_squashed_0004_auto_20160611_1202"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("per", "0097_alter_opslearning_appeal_code"),
    ]

    operations = [
        migrations.RunPython(
            modify_per_datetime_data_to_date, reverse_code=modify_per_date_data_to_datetime  # Time data is lost here
        ),
    ]
