# Generated by Django 3.2.23 on 2024-01-30 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("per", "0098_auto_20240118_0552"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormQuestionGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250, verbose_name="title")),
                ("title_en", models.CharField(max_length=250, null=True, verbose_name="title")),
                ("title_es", models.CharField(max_length=250, null=True, verbose_name="title")),
                ("title_fr", models.CharField(max_length=250, null=True, verbose_name="title")),
                ("title_ar", models.CharField(max_length=250, null=True, verbose_name="title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                ("description_en", models.TextField(blank=True, null=True, verbose_name="description")),
                ("description_es", models.TextField(blank=True, null=True, verbose_name="description")),
                ("description_fr", models.TextField(blank=True, null=True, verbose_name="description")),
                ("description_ar", models.TextField(blank=True, null=True, verbose_name="description")),
                (
                    "translation_module_original_language",
                    models.CharField(
                        choices=[("en", "English"), ("es", "Spanish"), ("fr", "French"), ("ar", "Arabic")],
                        default="en",
                        help_text="Language used to create this entity",
                        max_length=2,
                        verbose_name="Entity Original language",
                    ),
                ),
                (
                    "translation_module_skip_auto_translation",
                    models.BooleanField(
                        default=False,
                        help_text="Skip auto translation operation for this entity?",
                        verbose_name="Skip auto translation",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="per.formcomponent", verbose_name="component"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="formquestion",
            name="question_group",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="per.formquestiongroup"
            ),
        ),
    ]
