# Generated by Django 3.2.23 on 2024-01-30 08:51

from django.db import migrations
from api.logger import logger


class Migration(migrations.Migration):

    def migrate_component_to_question_group(apps, schema_editor):
        FormComponent = apps.get_model('per', 'FormComponent')
        FormQuestionGroup = apps.get_model('per', 'FormQuestionGroup')
        FormQuestion = apps.get_model('per', 'FormQuestion')
        FormComponentResponse = apps.get_model('per', 'FormComponentResponse')

        to_migrate_component = FormComponent.objects.filter(id__in=[53,52,51,50,49])
        question_group_count = 0
        for component in to_migrate_component:
            FormQuestionGroup.objects.create(
                title_en=component.title_en,
                title_es=component.title_es,
                title_ar=component.title_ar,
                title_fr=component.title_fr,
                description_en=component.description_en,
                description_es=component.description_es,
                description_ar=component.description_ar,
                description_fr=component.description_fr,
                component_id=48
            )
            question_group_count += 1
        logger.info(f'Created QuestionGroup count {question_group_count}')

        # now attach question to question group
        form_questions_to_migrate = FormQuestion.objects.filter(component_id__in=[53,52,51,50,49])
        question_count = 0
        for question in form_questions_to_migrate:
            form_question = FormQuestionGroup.objects.filter(
                title_en=question.question
            )
            if form_question.exists():
                form_question_first = form_question.first()
                question.form_question = form_question_first
                question.save(update_fields=['form_question'])
                question_count += 1
        logger.info(f'Attached Question count {question_count}')

        FormComponentResponse.objects.filter(component_id__in=[53,52,51,50,49]).update(component_id=48)

        # update the component to 48 for the old data
        form_questions_to_migrate.update(component_id=48)

        # delete the form component now
        print(to_migrate_component.delete())

    dependencies = [
        ('per', '0099_auto_20240130_0850'),
    ]

    operations = [
        migrations.RunPython(
            migrate_component_to_question_group,
            reverse_code=migrations.RunPython.noop
        ),
    ]
