# Generated by Django 3.2.23 on 2024-02-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0097_alter_opslearning_appeal_code'),
        ('per', '0100_auto_20240130_0851'),
    ]

    operations = [
    ]
