# Generated by Django 3.2.23 on 2024-02-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("per", "0100_migrate_all_notes"),
        ("per", "0102_merge_20240216_0447"),
    ]

    operations = []
