# Generated by Django 3.2.24 on 2024-03-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0103_merge_0100_migrate_all_notes_0102_merge_20240216_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='phase',
            field=models.IntegerField(blank=True, choices=[(1, 'Orientation'), (2, 'Assessment'), (3, 'Prioritisation'), (4, 'WorkPlan'), (5, 'Action And Accountability')], default=1, null=True, verbose_name='phase'),
        ),
    ]
