# Generated by Django 3.2.25 on 2024-05-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0112_auto_20240426_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='notes_ar',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='notes_es',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='notes_fr',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='climate_environmental_considerations_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Climate Environmental Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='climate_environmental_considerations_en',
            field=models.TextField(blank=True, null=True, verbose_name='Climate Environmental Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='climate_environmental_considerations_es',
            field=models.TextField(blank=True, null=True, verbose_name='Climate Environmental Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='climate_environmental_considerations_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Climate Environmental Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='epi_considerations_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Epi Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='epi_considerations_en',
            field=models.TextField(blank=True, null=True, verbose_name='Epi Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='epi_considerations_es',
            field=models.TextField(blank=True, null=True, verbose_name='Epi Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='epi_considerations_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Epi Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='notes_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='notes_es',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='notes_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='urban_considerations_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Urban Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='urban_considerations_en',
            field=models.TextField(blank=True, null=True, verbose_name='Urban Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='urban_considerations_es',
            field=models.TextField(blank=True, null=True, verbose_name='Urban Considerations'),
        ),
        migrations.AddField(
            model_name='formcomponentresponse',
            name='urban_considerations_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Urban Considerations'),
        ),
        migrations.AddField(
            model_name='overview',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='overview',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='title_ar',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='title_es',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='title_fr',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='value_ar',
            field=models.IntegerField(null=True, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='value_en',
            field=models.IntegerField(null=True, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='value_es',
            field=models.IntegerField(null=True, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='percomponentrating',
            name='value_fr',
            field=models.IntegerField(null=True, verbose_name='value'),
        ),
    ]
