# Generated by Django 3.2.25 on 2024-05-21 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0113_auto_20240521_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='arearesponse',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='arearesponse',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='answer_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='per.formanswer', verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='answer_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='per.formanswer', verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='answer_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='per.formanswer', verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='answer_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='per.formanswer', verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='question_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='per.formquestion', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='question_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='per.formquestion', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='question_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='per.formquestion', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='formcomponentquestionandanswer',
            name='question_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='per.formquestion', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='perassessment',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='perassessment',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
    ]
