# Generated by Django 3.2.25 on 2024-05-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("per", "0115_auto_20240521_0813"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formcomponentquestionandanswer",
            name="answer_ar",
        ),
        migrations.RemoveField(
            model_name="formcomponentquestionandanswer",
            name="answer_en",
        ),
        migrations.RemoveField(
            model_name="formcomponentquestionandanswer",
            name="answer_es",
        ),
        migrations.RemoveField(
            model_name="formcomponentquestionandanswer",
            name="answer_fr",
        ),
        migrations.RemoveField(
            model_name="formcomponentquestionandanswer",
            name="question_ar",
        ),
        migrations.RemoveField(
            model_name="formcomponentquestionandanswer",
            name="question_en",
        ),
        migrations.RemoveField(
            model_name="formcomponentquestionandanswer",
            name="question_es",
        ),
        migrations.RemoveField(
            model_name="formcomponentquestionandanswer",
            name="question_fr",
        ),
    ]
