# Generated by Django 4.2.13 on 2024-05-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0118_customperworkplancomponent_actions_ar_and_more'),
        ('per', '0118_percomponentrating_title_ar_and_more'),
    ]

    operations = [
    ]
