# Generated by Django 4.2.13 on 2024-06-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("per", "0119_merge_20240524_0548"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formcomponent",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_performance", "High Performance"),
                    ("exists_could_be_strengthened", "Exists – Could be Strengthened"),
                    ("needs_improvement", "Needs Improvement"),
                    ("partially_exists", "Partially Exists"),
                    ("does_not_exist", "Does Not Exist"),
                ],
                max_length=100,
                null=True,
                verbose_name="status",
            ),
        ),
    ]
