# Generated by Django 4.2.15 on 2024-09-12 05:40

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("per", "0120_alter_formcomponent_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="formcomponent",
            name="climate_environmental_considerations_guidance",
            field=tinymce.models.HTMLField(blank=True, default="", verbose_name="Climate and Environmental Considerations "),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="climate_environmental_considerations_guidance_ar",
            field=tinymce.models.HTMLField(
                blank=True, default="", null=True, verbose_name="Climate and Environmental Considerations "
            ),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="climate_environmental_considerations_guidance_en",
            field=tinymce.models.HTMLField(
                blank=True, default="", null=True, verbose_name="Climate and Environmental Considerations "
            ),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="climate_environmental_considerations_guidance_es",
            field=tinymce.models.HTMLField(
                blank=True, default="", null=True, verbose_name="Climate and Environmental Considerations "
            ),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="climate_environmental_considerations_guidance_fr",
            field=tinymce.models.HTMLField(
                blank=True, default="", null=True, verbose_name="Climate and Environmental Considerations "
            ),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="epi_considerations_guidance",
            field=tinymce.models.HTMLField(blank=True, default="", verbose_name="EPI Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="epi_considerations_guidance_ar",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="EPI Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="epi_considerations_guidance_en",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="EPI Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="epi_considerations_guidance_es",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="EPI Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="epi_considerations_guidance_fr",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="EPI Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="urban_considerations_guidance",
            field=tinymce.models.HTMLField(blank=True, default="", verbose_name="Urban Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="urban_considerations_guidance_ar",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="Urban Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="urban_considerations_guidance_en",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="Urban Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="urban_considerations_guidance_es",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="Urban Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="urban_considerations_guidance_fr",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="Urban Considerations"),
        ),
    ]
