# Generated by Django 4.2.16 on 2024-10-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("per", "0121_formcomponent_climate_environmental_considerations_guidance_and_more"),
        ("per", "0121_opslearningcacheresponse_and_more"),
    ]

    operations = []
