# Generated by Django 4.2.16 on 2024-10-29 08:51

from django.db import migrations

import main.fields


class Migration(migrations.Migration):

    dependencies = [
        ("per", "0122_opslearningcacheresponse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perdocumentupload",
            name="file",
            field=main.fields.SecureFileField(upload_to="per/documents/", verbose_name="file"),
        ),
        migrations.AlterField(
            model_name="perfile",
            name="file",
            field=main.fields.SecureFileField(upload_to="per/images/", verbose_name="file"),
        ),
    ]
