# Generated by Django 4.2.19 on 2025-07-31 09:40

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("per", "0124_alter_opslearningpromptresponsecache_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="formcomponent",
            name="migration_considerations_guidance",
            field=tinymce.models.HTMLField(blank=True, default="", verbose_name="Migration Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="migration_considerations_guidance_ar",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="Migration Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="migration_considerations_guidance_en",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="Migration Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="migration_considerations_guidance_es",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="Migration Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponent",
            name="migration_considerations_guidance_fr",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="Migration Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponentresponse",
            name="migration_considerations",
            field=models.TextField(blank=True, null=True, verbose_name="Migration Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponentresponse",
            name="migration_considerations_ar",
            field=models.TextField(blank=True, null=True, verbose_name="Migration Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponentresponse",
            name="migration_considerations_en",
            field=models.TextField(blank=True, null=True, verbose_name="Migration Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponentresponse",
            name="migration_considerations_es",
            field=models.TextField(blank=True, null=True, verbose_name="Migration Considerations"),
        ),
        migrations.AddField(
            model_name="formcomponentresponse",
            name="migration_considerations_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Migration Considerations"),
        ),
        migrations.AddField(
            model_name="overview",
            name="assess_migration_aspect_of_country",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Do you want to assess the migration aspects of your National Society?"
            ),
        ),
    ]
