# Generated by Django 4.2.15 on 2024-09-13 15:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# deployments.migrations.0024_migrate_project_districts_to_new_field_20200513_1126
# deployments.migrations.0026_sector_health_merge
# deployments.migrations.0030_actual_expenditure_complete_project


class Migration(migrations.Migration):

    replaces = [
        ("deployments", "0001_initial"),
        ("deployments", "0002_auto_20180614_2206"),
        ("deployments", "0003_auto_20180620_0950"),
        ("deployments", "0004_auto_20180621_1519"),
        ("deployments", "0005_auto_20180726_2025"),
        ("deployments", "0006_auto_20180817_1554"),
        ("deployments", "0007_auto_20190413_1421"),
        ("deployments", "0008_project"),
        ("deployments", "0009_auto_20190708_1626"),
        ("deployments", "0010_auto_20190711_0822"),
        ("deployments", "0011_erureadiness"),
        ("deployments", "0012_auto_20190722_1408"),
        ("deployments", "0013_auto_20190722_1410"),
        ("deployments", "0014_auto_20191024_0646"),
        ("deployments", "0015_auto_20191128_0640"),
        ("deployments", "0016_auto_20200107_0855"),
        ("deployments", "0017_auto_20200122_1434"),
        ("deployments", "0018_auto_20200319_0431"),
        ("deployments", "0019_auto_20200319_0806"),
        ("deployments", "0020_project_is_private"),
        ("deployments", "0021_projectimport"),
        ("deployments", "0022_auto_20200409_1214"),
        ("deployments", "0023_project_multiple_districts_20200513_1125"),
        ("deployments", "0024_migrate_project_districts_to_new_field_20200513_1126"),
        ("deployments", "0025_remove_project_district_20200513_1130"),
        ("deployments", "0026_sector_health_merge"),
        ("deployments", "0027_auto_20200528_0840"),
        ("deployments", "0028_auto_20200618_0904"),
        ("deployments", "0029_auto_20200625_1019"),
        ("deployments", "0030_actual_expenditure_complete_project"),
        ("deployments", "0031_auto_20200701_0939"),
        ("deployments", "0032_auto_20200729_0934"),
        ("deployments", "0033_molnixtag"),
        ("deployments", "0034_auto_20201111_1056"),
        ("deployments", "0035_personnel_molnix_tags"),
    ]

    initial = True

    dependencies = [
        ("api", "0020_auto_20190703_0614"),
        ("api", "0006_fieldreport_report_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
        ("api", "0064_auto_20200504_1438"),
        ("api", "0005_auto_20180614_2206"),
        ("api", "0042_auto_20200128_1045"),
        ("api", "0009_auto_20180712_1922"),
        ("api", "0019_auto_20190626_1420"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeployedPerson",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("role", models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ERUOwner",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "national_society_country",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.country"),
                ),
            ],
            options={
                "verbose_name": "ERUs from a National Society",
                "verbose_name_plural": "ERUs",
            },
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateTimeField(null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.country")),
                (
                    "dtype",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.disastertype"),
                ),
                ("event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.event")),
                ("region", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.region")),
            ],
            options={
                "verbose_name": "FACT",
                "verbose_name_plural": "FACTs",
            },
        ),
        migrations.CreateModel(
            name="Heop",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("person", models.CharField(blank=True, max_length=100, null=True)),
                ("role", models.CharField(blank=True, default="HeOps", max_length=32, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.country")),
                (
                    "dtype",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.disastertype"),
                ),
                ("event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.event")),
                ("region", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.region")),
            ],
            options={
                "verbose_name": "HeOp",
                "verbose_name_plural": "HeOps",
            },
        ),
        migrations.CreateModel(
            name="Rdrt",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateTimeField(null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.country")),
                (
                    "dtype",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.disastertype"),
                ),
                ("event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.event")),
                ("region", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.region")),
            ],
            options={
                "verbose_name": "RDRT/RIT",
                "verbose_name_plural": "RDRTs/RITs",
            },
        ),
        migrations.CreateModel(
            name="FactPerson",
            fields=[
                (
                    "deployedperson_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="deployments.deployedperson",
                    ),
                ),
                ("fact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="deployments.fact")),
                ("society_deployed_from", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "FACT Person",
                "verbose_name_plural": "FACT People",
            },
            bases=("deployments.deployedperson",),
        ),
        migrations.CreateModel(
            name="RdrtPerson",
            fields=[
                (
                    "deployedperson_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="deployments.deployedperson",
                    ),
                ),
                ("rdrt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="deployments.rdrt")),
                ("society_deployed_from", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "RDRT/RIT Person",
                "verbose_name_plural": "RDRT/RIT People",
            },
            bases=("deployments.deployedperson",),
        ),
        migrations.CreateModel(
            name="PartnerSocietyActivities",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activity", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Partner society activity",
                "verbose_name_plural": "Partner society activities",
            },
        ),
        migrations.CreateModel(
            name="PartnerSocietyDeployment",
            fields=[
                (
                    "deployedperson_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="deployments.deployedperson",
                    ),
                ),
                (
                    "country_deployed_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="country_partner_deployments",
                        to="api.country",
                    ),
                ),
                (
                    "parent_society",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_society_members",
                        to="api.country",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_societies",
                        to="deployments.partnersocietyactivities",
                    ),
                ),
                ("district_deployed_to", models.ManyToManyField(to="api.district")),
            ],
            bases=("deployments.deployedperson",),
        ),
        migrations.CreateModel(
            name="PersonnelDeployment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comments", models.TextField(blank=True, null=True)),
                ("country_deployed_to", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.country")),
                (
                    "event_deployed_to",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.event"),
                ),
                ("region_deployed_to", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.region")),
                ("alert_date", models.DateTimeField(help_text="Still not used in frontend", null=True)),
                (
                    "appeal_deployed_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Still not used in frontend",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.appeal",
                    ),
                ),
                ("end_date", models.DateTimeField(help_text="Still not used in frontend", null=True)),
                ("end_duration", models.CharField(blank=True, help_text="Still not used in frontend", max_length=100, null=True)),
                ("exp_start_date", models.DateTimeField(help_text="Still not used in frontend", null=True)),
                ("start_date", models.DateTimeField(help_text="Still not used in frontend", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("previous_update", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Personnel Deployments",
            },
        ),
        migrations.CreateModel(
            name="ERU",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Basecamp"),
                            (1, "IT & Telecom"),
                            (2, "Logistics"),
                            (3, "RCRC Emergency Hospital"),
                            (4, "RCRC Emergency Clinic"),
                            (5, "Relief"),
                            (6, "Wash M15"),
                            (7, "Wash MSM20"),
                            (8, "Wash M40"),
                            (9, "Water Supply and rehabilitation"),
                            (10, "Household Water Treatment and safe storage"),
                            (11, "Cholera Case management at Community level"),
                            (12, "Safe and Dignified Burials"),
                            (13, "Community Based Surveillance"),
                            (14, "Base Camp – S"),
                            (15, "Base Camp – M"),
                            (16, "Base Camp – L"),
                            (17, "Outpatient Department (OPD) Module"),
                            (18, "MHPSS"),
                        ],
                        default=0,
                    ),
                ),
                ("units", models.IntegerField(default=0)),
                ("equipment_units", models.IntegerField(default=0)),
                ("available", models.BooleanField(default=False)),
                (
                    "deployed_to",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.country"),
                ),
                ("eru_owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="deployments.eruowner")),
                ("event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.event")),
                ("alert_date", models.DateTimeField(help_text="Still not used in frontend", null=True)),
                (
                    "appeal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Still not used in frontend",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.appeal",
                    ),
                ),
                ("end_date", models.DateTimeField(help_text="Still not used in frontend", null=True)),
                ("num_people_deployed", models.IntegerField(default=0, help_text="Still not used in frontend")),
                ("start_date", models.DateTimeField(help_text="Still not used in frontend", null=True)),
                (
                    "supporting_societies",
                    models.CharField(blank=True, help_text="Still not used in frontend", max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ERUReadiness",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ERU_type",
                    models.IntegerField(
                        choices=[
                            (0, "Basecamp"),
                            (1, "IT & Telecom"),
                            (2, "Logistics"),
                            (3, "RCRC Emergency Hospital"),
                            (4, "RCRC Emergency Clinic"),
                            (5, "Relief"),
                            (6, "Wash M15"),
                            (7, "Wash MSM20"),
                            (8, "Wash M40"),
                            (9, "Water Supply and rehabilitation"),
                            (10, "Household Water Treatment and safe storage"),
                            (11, "Cholera Case management at Community level"),
                            (12, "Safe and Dignified Burials"),
                            (13, "Community Based Surveillance"),
                            (14, "Base Camp – S"),
                            (15, "Base Camp – M"),
                            (16, "Base Camp – L"),
                            (17, "Outpatient Department (OPD) Module"),
                            (18, "MHPSS"),
                        ],
                        default=0,
                    ),
                ),
                ("is_personnel", models.BooleanField(default=False)),
                ("is_equipment", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "national_society",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.country"),
                ),
            ],
            options={
                "verbose_name": "ERU Readiness",
                "verbose_name_plural": "NS-es ERU Readiness",
                "ordering": ("updated_at", "national_society"),
            },
        ),
        migrations.CreateModel(
            name="RegionalProject",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "deployedperson_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="deployments.deployedperson",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("fact", "FACT"),
                            ("heop", "HEOP"),
                            ("rdrt", "RDRT"),
                            ("ifrc", "IFRC"),
                            ("eru", "ERU HR"),
                            ("rr", "Rapid Response"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "country_from",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personnel_deployments",
                        to="api.country",
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="deployments.personneldeployment"),
                ),
            ],
            options={
                "verbose_name_plural": "Personnel",
            },
            bases=("deployments.deployedperson",),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                (
                    "programme_type",
                    models.IntegerField(choices=[(0, "Bilateral"), (1, "Multilateral"), (2, "Domestic")], default=0),
                ),
                ("primary_sector", models.IntegerField(default=0)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("budget_amount", models.IntegerField(default=0)),
                ("status", models.IntegerField(choices=[(0, "Planned"), (1, "Ongoing"), (2, "Completed")], default=0)),
                (
                    "project_district",
                    models.ForeignKey(
                        blank=True,
                        help_text="No selection will indicate all districts.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="api.district",
                    ),
                ),
                (
                    "reporting_ns",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ns_projects", to="api.country"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("operation_type", models.IntegerField(choices=[(0, "Programme"), (1, "Emergency Operation")], default=0)),
                (
                    "secondary_sectors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(default=0), blank=True, default=list, size=None
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "regional_project",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="deployments.regionalproject"
                    ),
                ),
                (
                    "dtype",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.disastertype"),
                ),
                ("event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.event")),
                ("reached_other", models.IntegerField(blank=True, null=True)),
                ("reached_female", models.IntegerField(blank=True, null=True)),
                ("reached_male", models.IntegerField(blank=True, null=True)),
                ("reached_total", models.IntegerField(blank=True, null=True)),
                ("target_other", models.IntegerField(blank=True, null=True)),
                ("target_female", models.IntegerField(blank=True, null=True)),
                ("target_male", models.IntegerField(blank=True, null=True)),
                ("target_total", models.IntegerField(blank=True, null=True)),
                (
                    "project_country",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name="projects", to="api.country"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("logged_in_user", "Logged in user"), ("ifrc_only", "IFRC only")],
                        default="public",
                        max_length=32,
                    ),
                ),
                (
                    "project_districts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="No selection will indicate all districts.",
                        related_name="many_to_many_projects",
                        to="api.district",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectImport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("success", "Success"), ("failure", "Failure")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="project-imports/")),
                (
                    "created_by",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
                ("projects_created", models.ManyToManyField(to="deployments.project")),
            ],
        ),
        # migrations.RunPython(
        #     code=deployments.migrations.0024_migrate_project_districts_to_new_field_20200513_1126.make_many_districts,
        # ),
        migrations.RemoveField(
            model_name="project",
            name="project_district",
        ),
        migrations.AlterField(
            model_name="project",
            name="project_districts",
            field=models.ManyToManyField(blank=True, help_text="No selection will indicate all districts.", to="api.district"),
        ),
        # migrations.RunPython(
        #     code=deployments.migrations.0026_sector_health_merge.merge_sector_health,
        # ),
        migrations.AlterField(
            model_name="project",
            name="project_districts",
            field=models.ManyToManyField(to="api.district"),
        ),
        migrations.AlterModelOptions(
            name="deployedperson",
            options={"verbose_name": "Deployed Person", "verbose_name_plural": "Deployed Persons"},
        ),
        migrations.AlterModelOptions(
            name="eru",
            options={"verbose_name": "Emergency Response Unit", "verbose_name_plural": "Emergency Response Units"},
        ),
        migrations.AlterModelOptions(
            name="partnersocietydeployment",
            options={"verbose_name": "Partner Society Deployment", "verbose_name_plural": "Partner Society Deployments"},
        ),
        migrations.AlterModelOptions(
            name="personnel",
            options={"verbose_name": "Personnel", "verbose_name_plural": "Personnels"},
        ),
        migrations.AlterModelOptions(
            name="personneldeployment",
            options={"verbose_name": "Personnel Deployment", "verbose_name_plural": "Personnel Deployments"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Project", "verbose_name_plural": "Projects"},
        ),
        migrations.AlterModelOptions(
            name="projectimport",
            options={"verbose_name": "Project Import", "verbose_name_plural": "Projects Import"},
        ),
        migrations.AlterModelOptions(
            name="regionalproject",
            options={"verbose_name": "Regional Project", "verbose_name_plural": "Regional Projects"},
        ),
        migrations.AlterField(
            model_name="deployedperson",
            name="end_date",
            field=models.DateTimeField(null=True, verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="deployedperson",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="deployedperson",
            name="role",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="role"),
        ),
        migrations.AlterField(
            model_name="deployedperson",
            name="start_date",
            field=models.DateTimeField(null=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="eru",
            name="alert_date",
            field=models.DateTimeField(help_text="still not used in frontend", null=True, verbose_name="alert date"),
        ),
        migrations.AlterField(
            model_name="eru",
            name="appeal",
            field=models.ForeignKey(
                blank=True,
                help_text="still not used in frontend",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.appeal",
                verbose_name="appeal",
            ),
        ),
        migrations.AlterField(
            model_name="eru",
            name="available",
            field=models.BooleanField(default=False, verbose_name="available"),
        ),
        migrations.AlterField(
            model_name="eru",
            name="deployed_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.country",
                verbose_name="country deployed to",
            ),
        ),
        migrations.AlterField(
            model_name="eru",
            name="end_date",
            field=models.DateTimeField(help_text="still not used in frontend", null=True, verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="eru",
            name="equipment_units",
            field=models.IntegerField(default=0, verbose_name="equipment units"),
        ),
        migrations.AlterField(
            model_name="eru",
            name="eru_owner",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="deployments.eruowner", verbose_name="owner"),
        ),
        migrations.AlterField(
            model_name="eru",
            name="event",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.event", verbose_name="event"
            ),
        ),
        migrations.AlterField(
            model_name="eru",
            name="num_people_deployed",
            field=models.IntegerField(
                default=0, help_text="still not used in frontend", verbose_name="number of people deployed"
            ),
        ),
        migrations.AlterField(
            model_name="eru",
            name="start_date",
            field=models.DateTimeField(help_text="still not used in frontend", null=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="eru",
            name="supporting_societies",
            field=models.CharField(
                blank=True, help_text="still not used in frontend", max_length=500, null=True, verbose_name="suuporting societies"
            ),
        ),
        migrations.AlterField(
            model_name="eru",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "Basecamp"),
                    (1, "IT & Telecom"),
                    (2, "Logistics"),
                    (3, "RCRC Emergency Hospital"),
                    (4, "RCRC Emergency Clinic"),
                    (5, "Relief"),
                    (6, "Wash M15"),
                    (7, "Wash MSM20"),
                    (8, "Wash M40"),
                    (9, "Water Supply and rehabilitation"),
                    (10, "Household Water Treatment and safe storage"),
                    (11, "Cholera Case management at Community level"),
                    (12, "Safe and Dignified Burials"),
                    (13, "Community Based Surveillance"),
                    (14, "Base Camp – S"),
                    (15, "Base Camp – M"),
                    (16, "Base Camp – L"),
                    (17, "Outpatient Department (OPD) Module"),
                    (18, "MHPSS"),
                ],
                default=0,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="eru",
            name="units",
            field=models.IntegerField(default=0, verbose_name="units"),
        ),
        migrations.AlterField(
            model_name="eruowner",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="eruowner",
            name="national_society_country",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.country", verbose_name="national society country"
            ),
        ),
        migrations.AlterField(
            model_name="eruowner",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="erureadiness",
            name="ERU_type",
            field=models.IntegerField(
                choices=[
                    (0, "Basecamp"),
                    (1, "IT & Telecom"),
                    (2, "Logistics"),
                    (3, "RCRC Emergency Hospital"),
                    (4, "RCRC Emergency Clinic"),
                    (5, "Relief"),
                    (6, "Wash M15"),
                    (7, "Wash MSM20"),
                    (8, "Wash M40"),
                    (9, "Water Supply and rehabilitation"),
                    (10, "Household Water Treatment and safe storage"),
                    (11, "Cholera Case management at Community level"),
                    (12, "Safe and Dignified Burials"),
                    (13, "Community Based Surveillance"),
                    (14, "Base Camp – S"),
                    (15, "Base Camp – M"),
                    (16, "Base Camp – L"),
                    (17, "Outpatient Department (OPD) Module"),
                    (18, "MHPSS"),
                ],
                default=0,
                verbose_name="ERU type",
            ),
        ),
        migrations.AlterField(
            model_name="erureadiness",
            name="is_equipment",
            field=models.BooleanField(default=False, verbose_name="is equipment?"),
        ),
        migrations.AlterField(
            model_name="erureadiness",
            name="is_personnel",
            field=models.BooleanField(default=False, verbose_name="is personnel?"),
        ),
        migrations.AlterField(
            model_name="erureadiness",
            name="national_society",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.country",
                verbose_name="national society",
            ),
        ),
        migrations.AlterField(
            model_name="erureadiness",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="partnersocietyactivities",
            name="activity",
            field=models.CharField(max_length=50, verbose_name="activity"),
        ),
        migrations.AlterField(
            model_name="partnersocietydeployment",
            name="activity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_societies",
                to="deployments.partnersocietyactivities",
                verbose_name="activity",
            ),
        ),
        migrations.AlterField(
            model_name="partnersocietydeployment",
            name="country_deployed_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="country_partner_deployments",
                to="api.country",
                verbose_name="country deployed to",
            ),
        ),
        migrations.AlterField(
            model_name="partnersocietydeployment",
            name="district_deployed_to",
            field=models.ManyToManyField(to="api.district", verbose_name="district deployed to"),
        ),
        migrations.AlterField(
            model_name="partnersocietydeployment",
            name="parent_society",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_society_members",
                to="api.country",
                verbose_name="parent society",
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="country_from",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel_deployments",
                to="api.country",
                verbose_name="country from",
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="deployment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="deployments.personneldeployment", verbose_name="deployment"
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="type",
            field=models.CharField(
                choices=[
                    ("fact", "Fact"),
                    ("heop", "HEOP"),
                    ("rdrt", "RDRT"),
                    ("ifrc", "IFRC"),
                    ("eru", "ERU HR"),
                    ("rr", "Rapid Response"),
                ],
                max_length=4,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="personneldeployment",
            name="alert_date",
            field=models.DateTimeField(help_text="still not used in frontend", null=True, verbose_name="alert date"),
        ),
        migrations.AlterField(
            model_name="personneldeployment",
            name="appeal_deployed_to",
            field=models.ForeignKey(
                blank=True,
                help_text="still not used in frontend",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.appeal",
                verbose_name="appeal deployed to",
            ),
        ),
        migrations.AlterField(
            model_name="personneldeployment",
            name="comments",
            field=models.TextField(blank=True, null=True, verbose_name="comments"),
        ),
        migrations.AlterField(
            model_name="personneldeployment",
            name="country_deployed_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.country", verbose_name="country deployed to"
            ),
        ),
        migrations.AlterField(
            model_name="personneldeployment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="personneldeployment",
            name="end_date",
            field=models.DateTimeField(help_text="still not used in frontend", null=True, verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="personneldeployment",
            name="end_duration",
            field=models.CharField(
                blank=True, help_text="still not used in frontend", max_length=100, null=True, verbose_name="end duration"
            ),
        ),
        migrations.AlterField(
            model_name="personneldeployment",
            name="event_deployed_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.event",
                verbose_name="event deployed to",
            ),
        ),
        migrations.AlterField(
            model_name="personneldeployment",
            name="exp_start_date",
            field=models.DateTimeField(help_text="still not used in frontend", null=True, verbose_name="expire start date"),
        ),
        migrations.AlterField(
            model_name="personneldeployment",
            name="previous_update",
            field=models.DateTimeField(blank=True, null=True, verbose_name="previous update"),
        ),
        migrations.AlterField(
            model_name="personneldeployment",
            name="region_deployed_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.region", verbose_name="region deployed to"
            ),
        ),
        migrations.AlterField(
            model_name="personneldeployment",
            name="start_date",
            field=models.DateTimeField(help_text="still not used in frontend", null=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="personneldeployment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="project",
            name="budget_amount",
            field=models.IntegerField(verbose_name="budget amount"),
        ),
        migrations.AlterField(
            model_name="project",
            name="dtype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.disastertype",
                verbose_name="disaster type",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="event",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.event", verbose_name="event"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modified at"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.TextField(verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="project",
            name="operation_type",
            field=models.IntegerField(
                choices=[(0, "Programme"), (1, "Emergency Operation")], default=0, verbose_name="operation type"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="primary_sector",
            field=models.IntegerField(default=0, verbose_name="sector"),
        ),
        migrations.AlterField(
            model_name="project",
            name="programme_type",
            field=models.IntegerField(
                choices=[(0, "Bilateral"), (1, "Multilateral"), (2, "Domestic")], default=0, verbose_name="programme type"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="api.country",
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_districts",
            field=models.ManyToManyField(to="api.district", verbose_name="districts"),
        ),
        migrations.AlterField(
            model_name="project",
            name="reached_female",
            field=models.IntegerField(blank=True, null=True, verbose_name="reached female"),
        ),
        migrations.AlterField(
            model_name="project",
            name="reached_male",
            field=models.IntegerField(blank=True, null=True, verbose_name="reached male"),
        ),
        migrations.AlterField(
            model_name="project",
            name="reached_other",
            field=models.IntegerField(blank=True, null=True, verbose_name="reached other"),
        ),
        migrations.AlterField(
            model_name="project",
            name="reached_total",
            field=models.IntegerField(blank=True, null=True, verbose_name="reached total"),
        ),
        migrations.AlterField(
            model_name="project",
            name="regional_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deployments.regionalproject",
                verbose_name="regional project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="reporting_ns",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ns_projects",
                to="api.country",
                verbose_name="reporting national society",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="secondary_sectors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(default=0), blank=True, default=list, size=None, verbose_name="tags"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Planned"), (1, "Ongoing"), (2, "Completed")], default=0, verbose_name="status"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="target_female",
            field=models.IntegerField(blank=True, null=True, verbose_name="target female"),
        ),
        migrations.AlterField(
            model_name="project",
            name="target_male",
            field=models.IntegerField(blank=True, null=True, verbose_name="target male"),
        ),
        migrations.AlterField(
            model_name="project",
            name="target_other",
            field=models.IntegerField(blank=True, null=True, verbose_name="target other"),
        ),
        migrations.AlterField(
            model_name="project",
            name="target_total",
            field=models.IntegerField(blank=True, null=True, verbose_name="target total"),
        ),
        migrations.AlterField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="visibility",
            field=models.CharField(
                choices=[("logged_in_user", "Membership"), ("ifrc_only", "IFRC Only"), ("public", "Public")],
                default="public",
                max_length=32,
                verbose_name="visibility",
            ),
        ),
        migrations.AlterField(
            model_name="projectimport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="projectimport",
            name="created_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="created by"
            ),
        ),
        migrations.AlterField(
            model_name="projectimport",
            name="file",
            field=models.FileField(upload_to="project-imports/", verbose_name="file"),
        ),
        migrations.AlterField(
            model_name="projectimport",
            name="message",
            field=models.TextField(verbose_name="message"),
        ),
        migrations.AlterField(
            model_name="projectimport",
            name="projects_created",
            field=models.ManyToManyField(to="deployments.project", verbose_name="projects created"),
        ),
        migrations.AlterField(
            model_name="projectimport",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("success", "Success"), ("failure", "Failure")],
                default="pending",
                max_length=10,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="regionalproject",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="regionalproject",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modified at"),
        ),
        migrations.AlterField(
            model_name="regionalproject",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="project",
            name="actual_expenditure",
            field=models.IntegerField(blank=True, null=True, verbose_name="actual expenditure"),
        ),
        migrations.AlterField(
            model_name="project",
            name="budget_amount",
            field=models.IntegerField(blank=True, null=True, verbose_name="budget amount"),
        ),
        # migrations.RunPython(
        #     code=deployments.migrations.0030_actual_expenditure_complete_project.set_actual_expenditure_for_completed_projects,
        # ),
        migrations.AlterField(
            model_name="personnel",
            name="type",
            field=models.CharField(
                choices=[
                    ("fact", "FACT"),
                    ("heop", "HEOP"),
                    ("rdrt", "RDRT"),
                    ("ifrc", "IFRC"),
                    ("eru", "ERU HR"),
                    ("rr", "Rapid Response"),
                ],
                max_length=4,
                verbose_name="type",
            ),
        ),
        migrations.AddField(
            model_name="deployedperson",
            name="role_ar",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="role"),
        ),
        migrations.AddField(
            model_name="deployedperson",
            name="role_en",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="role"),
        ),
        migrations.AddField(
            model_name="deployedperson",
            name="role_es",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="role"),
        ),
        migrations.AddField(
            model_name="deployedperson",
            name="role_fr",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="role"),
        ),
        migrations.AddField(
            model_name="partnersocietyactivities",
            name="activity_ar",
            field=models.CharField(max_length=50, null=True, verbose_name="activity"),
        ),
        migrations.AddField(
            model_name="partnersocietyactivities",
            name="activity_en",
            field=models.CharField(max_length=50, null=True, verbose_name="activity"),
        ),
        migrations.AddField(
            model_name="partnersocietyactivities",
            name="activity_es",
            field=models.CharField(max_length=50, null=True, verbose_name="activity"),
        ),
        migrations.AddField(
            model_name="partnersocietyactivities",
            name="activity_fr",
            field=models.CharField(max_length=50, null=True, verbose_name="activity"),
        ),
        migrations.AddField(
            model_name="personneldeployment",
            name="comments_ar",
            field=models.TextField(blank=True, null=True, verbose_name="comments"),
        ),
        migrations.AddField(
            model_name="personneldeployment",
            name="comments_en",
            field=models.TextField(blank=True, null=True, verbose_name="comments"),
        ),
        migrations.AddField(
            model_name="personneldeployment",
            name="comments_es",
            field=models.TextField(blank=True, null=True, verbose_name="comments"),
        ),
        migrations.AddField(
            model_name="personneldeployment",
            name="comments_fr",
            field=models.TextField(blank=True, null=True, verbose_name="comments"),
        ),
        migrations.AddField(
            model_name="project",
            name="name_ar",
            field=models.TextField(null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="project",
            name="name_en",
            field=models.TextField(null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="project",
            name="name_es",
            field=models.TextField(null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="project",
            name="name_fr",
            field=models.TextField(null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="regionalproject",
            name="name_ar",
            field=models.CharField(max_length=100, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="regionalproject",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="regionalproject",
            name="name_es",
            field=models.CharField(max_length=100, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="regionalproject",
            name="name_fr",
            field=models.CharField(max_length=100, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="eru",
            name="supporting_societies",
            field=models.CharField(
                blank=True, help_text="still not used in frontend", max_length=500, null=True, verbose_name="supporting societies"
            ),
        ),
        migrations.CreateModel(
            name="MolnixTag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("molnix_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=512)),
                ("color", models.CharField(max_length=6)),
                ("tag_type", models.CharField(max_length=127)),
            ],
        ),
        migrations.AddField(
            model_name="personnel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="personnel",
            name="molnix_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personneldeployment",
            name="is_molnix",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personnel",
            name="molnix_tags",
            field=models.ManyToManyField(blank=True, to="deployments.molnixtag"),
        ),
    ]
