# Generated by Django 5.2.17 on 2026-09-20 05:23

import django.contrib.postgres.fields
import django.db.migrations.operations.special
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models
from deployments.models import Statuses
from django.db import migrations
from django.db.models import F
from django.db.models.expressions import F, Func, Value


def _0024__make_many_districts(apps, schema_editor):
    """
    Adds the District object in Project.project_district to the
    many-to-many relationship in Project.project_districts
    """
    Project = apps.get_model('deployments', 'Project')
    for project in Project.objects.all():
        if project.project_district:
            project.project_districts.add(project.project_district)
        elif project.project_country:
            project.project_districts.set(project.project_country.district_set.all())

def _0026__merge_sector_health(apps, schema_editor):
    """
    Merge Sectors Health (public) and Health (clinical) to Health for Sectors
    """
    Project = apps.get_model("deployments", "Project")

    # This value can change so using value from this time
    HEALTH = 4  # HEALTH_PUBLIC is same as HEALTH in DB
    HEALTH_CLINICAL = 10

    # Migrate all HEALTH_CLINICAL to HEALTH
    Project.objects.filter(primary_sector=HEALTH_CLINICAL).update(primary_sector=HEALTH)

def _0030__set_actual_expenditure_for_completed_projects(apps, schema_editor):
    """
    set actual expenditure using budget amount for completed projects
    """
    Project = apps.get_model('deployments', 'Project')
    Project.objects.filter(status=Statuses.COMPLETED).update(actual_expenditure=F('budget_amount'))

def _0038__remove_rcce_tag(apps, schema_editor):
    """
    Remove RCCE tag and change it to combination of CEA and HEALTH_PUBLIC
    """
    # NOTE: This is broken, keeping it as it is already deployed to staging.
    return

    # Hardcode enum value present this time
    RCCE = 14
    HEALTH_PUBLIC = 4
    CEA = 2

    Project = apps.get_model("deployments", "Project")
    # get only the project that have `RCCE` tag
    projects = Project.objects.filter(secondary_sectors__contains=[RCCE])
    for project in projects:
        project.secondary_sectors.remove(RCCE)
        project.secondary_sectors.extend([HEALTH_PUBLIC, CEA])
        project.save(update_fields=["secondary_sectors"])

def _0039___remove_rcce_tag(Project):
    """
    Remove RCCE tag and change it to combination of CEA and HEALTH_PUBLIC
    """
    # Hardcode enum value present this time
    RCCE = 14
    HEALTH_PUBLIC = 4
    CEA = 2

    # Add HEALTH_PUBLIC/CEA if there is RCCE
    for tag in [HEALTH_PUBLIC, CEA]:
        Project.objects.filter(secondary_sectors__contains=[RCCE]).exclude(secondary_sectors__contains=[tag]).update(
            secondary_sectors=Func(
                F("secondary_sectors"),
                Value(tag),
                function="ARRAY_APPEND",
            )
        )

    # Finally remove
    Project.objects.filter(secondary_sectors__contains=[RCCE]).update(
        secondary_sectors=Func(F("secondary_sectors"), Value(RCCE), function="ARRAY_REMOVE")
    )

def _0039__remove_rcce_tag(apps, schema_editor):
    Project = apps.get_model('deployments', 'Project')
    _0039___remove_rcce_tag(Project)


# Squashed in two parts: notifications.0001_squashed_0017 depends on
# deployments.0033_molnixtag (in this range) while deployments.0082_squashed_0097
# depends on notifications.0013, so one deployments node would form a cycle.
class Migration(migrations.Migration):

    replaces = [('deployments', '0001_initial'), ('deployments', '0002_auto_20180614_2206'), ('deployments', '0003_auto_20180620_0950'), ('deployments', '0004_auto_20180621_1519'), ('deployments', '0005_auto_20180726_2025'), ('deployments', '0006_auto_20180817_1554'), ('deployments', '0007_auto_20190413_1421'), ('deployments', '0008_project'), ('deployments', '0009_auto_20190708_1626'), ('deployments', '0010_auto_20190711_0822'), ('deployments', '0011_erureadiness'), ('deployments', '0012_auto_20190722_1408'), ('deployments', '0013_auto_20190722_1410'), ('deployments', '0014_auto_20191024_0646'), ('deployments', '0015_auto_20191128_0640'), ('deployments', '0016_auto_20200107_0855'), ('deployments', '0017_auto_20200122_1434'), ('deployments', '0018_auto_20200319_0431'), ('deployments', '0019_auto_20200319_0806'), ('deployments', '0020_project_is_private'), ('deployments', '0021_projectimport'), ('deployments', '0022_auto_20200409_1214'), ('deployments', '0023_project_multiple_districts_20200513_1125'), ('deployments', '0024_migrate_project_districts_to_new_field_20200513_1126'), ('deployments', '0025_remove_project_district_20200513_1130'), ('deployments', '0026_sector_health_merge'), ('deployments', '0027_auto_20200528_0840'), ('deployments', '0028_auto_20200618_0904'), ('deployments', '0029_auto_20200625_1019'), ('deployments', '0030_actual_expenditure_complete_project'), ('deployments', '0031_auto_20200701_0939'), ('deployments', '0032_auto_20200729_0934'), ('deployments', '0033_molnixtag'), ('deployments', '0034_auto_20201111_1056'), ('deployments', '0035_personnel_molnix_tags'), ('deployments', '0036_auto_20201118_0812'), ('deployments', '0037_project_modified_by'), ('deployments', '0038_auto_20210820_0733'), ('deployments', '0039_auto_20210823_1159'), ('deployments', '0040_auto_20210920_1250'), ('deployments', '0041_auto_20211110_0924'), ('deployments', '0042_personnel_country_to'), ('deployments', '0043_personnel_country_to_fill'), ('deployments', '0044_auto_20220305_0922'), ('deployments', '0045_remove_emergencyproject_country'), ('deployments', '0046_auto_20220307_0926'), ('deployments', '0047_emergencyproject_country'), ('deployments', '0048_auto_20220310_0524'), ('deployments', '0049_auto_20220311_0400'), ('deployments', '0050_emergencyprojectactivity_people_households'), ('deployments', '0051_auto_20220311_0947'), ('deployments', '0052_auto_20220314_0633'), ('deployments', '0044_personnel_molnix_status'), ('deployments', '0053_merge_20220314_1059'), ('deployments', '0054_auto_20220314_1059'), ('deployments', '0055_auto_20220315_0420'), ('deployments', '0056_auto_20220318_0413'), ('deployments', '0045_molnixtag_tag_category'), ('deployments', '0057_merge_20220318_0527'), ('deployments', '0058_auto_20220322_1056'), ('deployments', '0059_auto_20220323_1028'), ('deployments', '0060_auto_20220323_1527'), ('deployments', '0061_auto_20220331_1121'), ('deployments', '0062_auto_20220331_1143'), ('deployments', '0063_auto_20220413_1438'), ('deployments', '0064_auto_20220414_0842'), ('deployments', '0065_emergencyproject_visibility'), ('deployments', '0066_auto_20220727_0708'), ('deployments', '0066_auto_20220523_0824'), ('deployments', '0067_merge_0066_auto_20220523_0824_0066_auto_20220727_0708'), ('deployments', '0067_annualsplit'), ('deployments', '0068_merge_20220818_1357'), ('deployments', '0069_auto_20221022_1542'), ('deployments', '0070_alter_personnel_options'), ('deployments', '0071_sector'), ('deployments', '0072_sectortag'), ('deployments', '0073_auto_20230301_1606'), ('deployments', '0074_alter_molnixtag_description'), ('deployments', '0075_alter_project_primary_sector'), ('deployments', '0076_auto_20230309_1556'), ('deployments', '0077_auto_20230420_1609'), ('deployments', '0078_auto_20230421_1110'), ('deployments', '0079_auto_20230423_0628'), ('deployments', '0077_project_project_admin2'), ('deployments', '0078_emergencyproject_admin2'), ('deployments', '0080_merge_20230505_0418'), ('deployments', '0077_auto_20230410_0720'), ('deployments', '0081_merge_20230614_0804')]

    dependencies = [
        ('api', '0001_initial'),
        ('api', '0005_auto_20180614_2206'),
        ('api', '0006_fieldreport_report_date'),
        ('api', '0009_auto_20180712_1922'),
        ('api', '0019_auto_20190626_1420'),
        ('api', '0020_auto_20190703_0614'),
        ('api', '0042_auto_20200128_1045'),
        ('api', '0064_auto_20200504_1438'),
        ('api', '0137_auto_20220105_1533'),
        ('api', '0146_auto_20220228_0952'),
        ('api', '0152_countryoffieldreporttoreview'),
        ('api', '0161_alter_event_options'),
        ('api', '0164_appealdocumenttype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ERUOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national_society_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country')),
            ],
            options={
                'verbose_name': 'ERUs from a National Society',
                'verbose_name_plural': 'ERUs',
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('dtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disastertype')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.event')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
            options={
                'verbose_name': 'FACT',
                'verbose_name_plural': 'FACTs',
            },
        ),
        migrations.CreateModel(
            name='Heop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('person', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, default='HeOps', max_length=32, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('dtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disastertype')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.event')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
            options={
                'verbose_name': 'HeOp',
                'verbose_name_plural': 'HeOps',
            },
        ),
        migrations.CreateModel(
            name='Rdrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('dtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disastertype')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.event')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
            options={
                'verbose_name': 'RDRT/RIT',
                'verbose_name_plural': 'RDRTs/RITs',
            },
        ),
        migrations.CreateModel(
            name='FactPerson',
            fields=[
                ('deployedperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deployments.deployedperson')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.fact')),
                ('society_deployed_from', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'FACT Person',
                'verbose_name_plural': 'FACT People',
            },
            bases=('deployments.deployedperson',),
        ),
        migrations.CreateModel(
            name='RdrtPerson',
            fields=[
                ('deployedperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deployments.deployedperson')),
                ('rdrt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.rdrt')),
                ('society_deployed_from', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'RDRT/RIT Person',
                'verbose_name_plural': 'RDRT/RIT People',
            },
            bases=('deployments.deployedperson',),
        ),
        migrations.CreateModel(
            name='PartnerSocietyActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Partner society activity',
                'verbose_name_plural': 'Partner society activities',
            },
        ),
        migrations.CreateModel(
            name='PartnerSocietyDeployment',
            fields=[
                ('deployedperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deployments.deployedperson')),
                ('country_deployed_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_partner_deployments', to='api.country')),
                ('parent_society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_society_members', to='api.country')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_societies', to='deployments.partnersocietyactivities')),
                ('district_deployed_to', models.ManyToManyField(to='api.district')),
            ],
            bases=('deployments.deployedperson',),
        ),
        migrations.CreateModel(
            name='PersonnelDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('country_deployed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('event_deployed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.event')),
                ('region_deployed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
                ('alert_date', models.DateTimeField(help_text='Still not used in frontend', null=True)),
                ('appeal_deployed_to', models.ForeignKey(blank=True, help_text='Still not used in frontend', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.appeal')),
                ('end_date', models.DateTimeField(help_text='Still not used in frontend', null=True)),
                ('end_duration', models.CharField(blank=True, help_text='Still not used in frontend', max_length=100, null=True)),
                ('exp_start_date', models.DateTimeField(help_text='Still not used in frontend', null=True)),
                ('start_date', models.DateTimeField(help_text='Still not used in frontend', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_update', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Personnel Deployments',
            },
        ),
        migrations.CreateModel(
            name='ERU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'IT & Telecom'), (2, 'Logistics'), (3, 'RCRC Emergency Hospital'), (4, 'RCRC Emergency Clinic'), (5, 'Relief'), (6, 'WASH M15'), (7, 'WASH MSM20'), (8, 'WASH M40'), (9, 'Water Supply and rehabilitation'), (10, 'Household Water Treatment and safe storage'), (11, 'Cholera Case management at Community level'), (12, 'Safe and Dignified Burials'), (13, 'Community Based Surveillance'), (17, 'Outpatient Department (OPD) Module'), (18, 'MHPSS'), (19, 'Operations Support HUB'), (20, 'Public Health'), (21, 'Public Health IPC - Infection Prevention and Control'), (22, 'Clinical Advances Team')], default=0)),
                ('units', models.IntegerField(default=0)),
                ('equipment_units', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('deployed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country')),
                ('eru_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.eruowner')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.event')),
                ('alert_date', models.DateTimeField(help_text='Still not used in frontend', null=True)),
                ('appeal', models.ForeignKey(blank=True, help_text='Still not used in frontend', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.appeal')),
                ('end_date', models.DateTimeField(help_text='Still not used in frontend', null=True)),
                ('num_people_deployed', models.IntegerField(default=0, help_text='Still not used in frontend')),
                ('start_date', models.DateTimeField(help_text='Still not used in frontend', null=True)),
                ('supporting_societies', models.CharField(blank=True, help_text='Still not used in frontend', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ERUReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ERU_type', models.IntegerField(choices=[(1, 'IT & Telecom'), (2, 'Logistics'), (3, 'RCRC Emergency Hospital'), (4, 'RCRC Emergency Clinic'), (5, 'Relief'), (6, 'WASH M15'), (7, 'WASH MSM20'), (8, 'WASH M40'), (9, 'Water Supply and rehabilitation'), (10, 'Household Water Treatment and safe storage'), (11, 'Cholera Case management at Community level'), (12, 'Safe and Dignified Burials'), (13, 'Community Based Surveillance'), (17, 'Outpatient Department (OPD) Module'), (18, 'MHPSS'), (19, 'Operations Support HUB'), (20, 'Public Health'), (21, 'Public Health IPC - Infection Prevention and Control'), (22, 'Clinical Advances Team')], default=0)),
                ('is_personnel', models.BooleanField(default=False)),
                ('is_equipment', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national_society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country')),
            ],
            options={
                'verbose_name': 'ERU Readiness',
                'verbose_name_plural': 'NS-es ERU Readiness',
                'ordering': ('updated_at', 'national_society'),
            },
        ),
        migrations.CreateModel(
            name='RegionalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('deployedperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deployments.deployedperson')),
                ('type', models.CharField(choices=[('fact', 'FACT'), ('heop', 'HEOP'), ('rdrt', 'RDRT'), ('ifrc', 'IFRC'), ('eru', 'ERU HR'), ('rr', 'Rapid Response')], max_length=4)),
                ('country_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_deployments', to='api.country')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.personneldeployment')),
            ],
            options={
                'verbose_name_plural': 'Personnel',
            },
            bases=('deployments.deployedperson',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('programme_type', models.IntegerField(choices=[(0, 'Bilateral'), (1, 'Multilateral'), (2, 'Domestic')], default=0)),
                ('primary_sector', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget_amount', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Planned'), (1, 'Ongoing'), (2, 'Completed')], default=0)),
                ('project_district', models.ForeignKey(blank=True, help_text='No selection will indicate all districts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.district')),
                ('reporting_ns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ns_projects', to='api.country')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operation_type', models.IntegerField(choices=[(0, 'Programme'), (1, 'Emergency Operation')], default=0)),
                ('secondary_sectors', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, size=None)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('regional_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deployments.regionalproject')),
                ('dtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disastertype')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.event')),
                ('reached_other', models.IntegerField(blank=True, null=True)),
                ('reached_female', models.IntegerField(blank=True, null=True)),
                ('reached_male', models.IntegerField(blank=True, null=True)),
                ('reached_total', models.IntegerField(blank=True, null=True)),
                ('target_other', models.IntegerField(blank=True, null=True)),
                ('target_female', models.IntegerField(blank=True, null=True)),
                ('target_male', models.IntegerField(blank=True, null=True)),
                ('target_total', models.IntegerField(blank=True, null=True)),
                ('project_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.country')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('logged_in_user', 'Logged in user'), ('ifrc_only', 'IFRC only')], default='public', max_length=32)),
                ('project_districts', models.ManyToManyField(blank=True, help_text='No selection will indicate all districts.', related_name='many_to_many_projects', to='api.district')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=10)),
                ('file', models.FileField(upload_to='project-imports/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projects_created', models.ManyToManyField(to='deployments.project')),
            ],
        ),
        migrations.RunPython(
            code=_0024__make_many_districts,
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_district',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_districts',
            field=models.ManyToManyField(blank=True, help_text='No selection will indicate all districts.', to='api.district'),
        ),
        migrations.RunPython(
            code=_0026__merge_sector_health,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_districts',
            field=models.ManyToManyField(to='api.district'),
        ),
        migrations.AlterModelOptions(
            name='deployedperson',
            options={'verbose_name': 'Deployed Person', 'verbose_name_plural': 'Deployed Persons'},
        ),
        migrations.AlterModelOptions(
            name='eru',
            options={'verbose_name': 'Emergency Response Unit', 'verbose_name_plural': 'Emergency Response Units'},
        ),
        migrations.AlterModelOptions(
            name='partnersocietydeployment',
            options={'verbose_name': 'Partner Society Deployment', 'verbose_name_plural': 'Partner Society Deployments'},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name': 'Personnel', 'verbose_name_plural': 'Personnels'},
        ),
        migrations.AlterModelOptions(
            name='personneldeployment',
            options={'verbose_name': 'Personnel Deployment', 'verbose_name_plural': 'Personnel Deployments'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectimport',
            options={'verbose_name': 'Project Import', 'verbose_name_plural': 'Projects Import'},
        ),
        migrations.AlterModelOptions(
            name='regionalproject',
            options={'verbose_name': 'Regional Project', 'verbose_name_plural': 'Regional Projects'},
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='role',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='alert_date',
            field=models.DateTimeField(help_text='still not used in frontend', null=True, verbose_name='alert date'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='appeal',
            field=models.ForeignKey(blank=True, help_text='still not used in frontend', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.appeal', verbose_name='appeal'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='available',
            field=models.BooleanField(default=False, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='deployed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country', verbose_name='country deployed to'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='end_date',
            field=models.DateTimeField(help_text='still not used in frontend', null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='equipment_units',
            field=models.IntegerField(default=0, verbose_name='equipment units'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='eru_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.eruowner', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='num_people_deployed',
            field=models.IntegerField(default=0, help_text='still not used in frontend', verbose_name='number of people deployed'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='start_date',
            field=models.DateTimeField(help_text='still not used in frontend', null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='supporting_societies',
            field=models.CharField(blank=True, help_text='still not used in frontend', max_length=500, null=True, verbose_name='suuporting societies'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='type',
            field=models.IntegerField(choices=[(1, 'IT & Telecom'), (2, 'Logistics'), (3, 'RCRC Emergency Hospital'), (4, 'RCRC Emergency Clinic'), (5, 'Relief'), (6, 'WASH M15'), (7, 'WASH MSM20'), (8, 'WASH M40'), (9, 'Water Supply and rehabilitation'), (10, 'Household Water Treatment and safe storage'), (11, 'Cholera Case management at Community level'), (12, 'Safe and Dignified Burials'), (13, 'Community Based Surveillance'), (17, 'Outpatient Department (OPD) Module'), (18, 'MHPSS'), (19, 'Operations Support HUB'), (20, 'Public Health'), (21, 'Public Health IPC - Infection Prevention and Control'), (22, 'Clinical Advances Team')], default=0, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='units',
            field=models.IntegerField(default=0, verbose_name='units'),
        ),
        migrations.AlterField(
            model_name='eruowner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='eruowner',
            name='national_society_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country', verbose_name='national society country'),
        ),
        migrations.AlterField(
            model_name='eruowner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='erureadiness',
            name='ERU_type',
            field=models.IntegerField(choices=[(1, 'IT & Telecom'), (2, 'Logistics'), (3, 'RCRC Emergency Hospital'), (4, 'RCRC Emergency Clinic'), (5, 'Relief'), (6, 'WASH M15'), (7, 'WASH MSM20'), (8, 'WASH M40'), (9, 'Water Supply and rehabilitation'), (10, 'Household Water Treatment and safe storage'), (11, 'Cholera Case management at Community level'), (12, 'Safe and Dignified Burials'), (13, 'Community Based Surveillance'), (17, 'Outpatient Department (OPD) Module'), (18, 'MHPSS'), (19, 'Operations Support HUB'), (20, 'Public Health'), (21, 'Public Health IPC - Infection Prevention and Control'), (22, 'Clinical Advances Team')], default=0, verbose_name='ERU type'),
        ),
        migrations.AlterField(
            model_name='erureadiness',
            name='is_equipment',
            field=models.BooleanField(default=False, verbose_name='is equipment?'),
        ),
        migrations.AlterField(
            model_name='erureadiness',
            name='is_personnel',
            field=models.BooleanField(default=False, verbose_name='is personnel?'),
        ),
        migrations.AlterField(
            model_name='erureadiness',
            name='national_society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country', verbose_name='national society'),
        ),
        migrations.AlterField(
            model_name='erureadiness',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='partnersocietyactivities',
            name='activity',
            field=models.CharField(max_length=50, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='partnersocietydeployment',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_societies', to='deployments.partnersocietyactivities', verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='partnersocietydeployment',
            name='country_deployed_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_partner_deployments', to='api.country', verbose_name='country deployed to'),
        ),
        migrations.AlterField(
            model_name='partnersocietydeployment',
            name='district_deployed_to',
            field=models.ManyToManyField(to='api.district', verbose_name='district deployed to'),
        ),
        migrations.AlterField(
            model_name='partnersocietydeployment',
            name='parent_society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_society_members', to='api.country', verbose_name='parent society'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='country_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_deployments', to='api.country', verbose_name='country from'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.personneldeployment', verbose_name='deployment'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='type',
            field=models.CharField(choices=[('fact', 'Fact'), ('heop', 'HEOP'), ('rdrt', 'RDRT'), ('ifrc', 'IFRC'), ('eru', 'ERU HR'), ('rr', 'Rapid Response')], max_length=4, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='alert_date',
            field=models.DateTimeField(help_text='still not used in frontend', null=True, verbose_name='alert date'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='appeal_deployed_to',
            field=models.ForeignKey(blank=True, help_text='still not used in frontend', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.appeal', verbose_name='appeal deployed to'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='country_deployed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country', verbose_name='country deployed to'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='end_date',
            field=models.DateTimeField(help_text='still not used in frontend', null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='end_duration',
            field=models.CharField(blank=True, help_text='still not used in frontend', max_length=100, null=True, verbose_name='end duration'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='event_deployed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.event', verbose_name='event deployed to'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='exp_start_date',
            field=models.DateTimeField(help_text='still not used in frontend', null=True, verbose_name='expire start date'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='previous_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='previous update'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='region_deployed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region', verbose_name='region deployed to'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='start_date',
            field=models.DateTimeField(help_text='still not used in frontend', null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='budget amount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disastertype', verbose_name='disaster type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='operation_type',
            field=models.IntegerField(choices=[(0, 'Programme'), (1, 'Emergency Operation')], default=0, verbose_name='operation type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_sector',
            field=models.IntegerField(default=0, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='project',
            name='programme_type',
            field=models.IntegerField(choices=[(0, 'Bilateral'), (1, 'Multilateral'), (2, 'Domestic')], default=0, verbose_name='programme type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_districts',
            field=models.ManyToManyField(to='api.district', verbose_name='districts'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reached_female',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached female'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reached_male',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached male'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reached_other',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached other'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reached_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached total'),
        ),
        migrations.AlterField(
            model_name='project',
            name='regional_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deployments.regionalproject', verbose_name='regional project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reporting_ns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ns_projects', to='api.country', verbose_name='reporting national society'),
        ),
        migrations.AlterField(
            model_name='project',
            name='secondary_sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, size=None, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Planned'), (1, 'Ongoing'), (2, 'Completed')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_female',
            field=models.IntegerField(blank=True, null=True, verbose_name='target female'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_male',
            field=models.IntegerField(blank=True, null=True, verbose_name='target male'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_other',
            field=models.IntegerField(blank=True, null=True, verbose_name='target other'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='target total'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('logged_in_user', 'Membership'), ('ifrc_only', 'IFRC Only'), ('public', 'Public')], default='public', max_length=32, verbose_name='visibility'),
        ),
        migrations.AlterField(
            model_name='projectimport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='projectimport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='projectimport',
            name='file',
            field=models.FileField(upload_to='project-imports/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='projectimport',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='projectimport',
            name='projects_created',
            field=models.ManyToManyField(to='deployments.project', verbose_name='projects created'),
        ),
        migrations.AlterField(
            model_name='projectimport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='regionalproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='regionalproject',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='regionalproject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_expenditure',
            field=models.IntegerField(blank=True, null=True, verbose_name='actual expenditure'),
        ),
        migrations.RunPython(
            code=_0030__set_actual_expenditure_for_completed_projects,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='type',
            field=models.CharField(choices=[('fact', 'FACT'), ('heop', 'HEOP'), ('rdrt', 'RDRT'), ('ifrc', 'IFRC'), ('eru', 'ERU HR'), ('rr', 'Rapid Response')], max_length=4, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='partnersocietyactivities',
            name='activity_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='partnersocietyactivities',
            name='activity_en',
            field=models.CharField(max_length=50, null=True, verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='partnersocietyactivities',
            name='activity_es',
            field=models.CharField(max_length=50, null=True, verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='partnersocietyactivities',
            name='activity_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='personneldeployment',
            name='comments_ar',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='personneldeployment',
            name='comments_en',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='personneldeployment',
            name='comments_es',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='personneldeployment',
            name='comments_fr',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ar',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_es',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_fr',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='regionalproject',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='regionalproject',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='regionalproject',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='regionalproject',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='supporting_societies',
            field=models.CharField(blank=True, help_text='still not used in frontend', max_length=500, null=True, verbose_name='supporting societies'),
        ),
        migrations.CreateModel(
            name='MolnixTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molnix_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=512)),
                ('color', models.CharField(max_length=6)),
                ('tag_type', models.CharField(max_length=127)),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='molnix_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personneldeployment',
            name='is_molnix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personnel',
            name='molnix_tags',
            field=models.ManyToManyField(blank=True, to='deployments.molnixtag'),
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='role',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='deployedperson',
            name='role_ar',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='deployedperson',
            name='role_en',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='deployedperson',
            name='role_es',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='deployedperson',
            name='role_fr',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='project',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.RunPython(
            code=_0038__remove_rcce_tag,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=_0039__remove_rcce_tag,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='region_deployed_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.region', verbose_name='region deployed to'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('logged_in_user', 'Membership'), ('ifrc_only', 'IFRC Only'), ('public', 'Public'), ('ifrc_ns', 'IFRC_NS')], default='public', max_length=32, verbose_name='visibility'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='country_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_deployments_to', to='api.country', verbose_name='country to'),
        ),
        migrations.RunSQL(
            sql=['update deployments_personnel set country_to_id=d.country_id from deployments_personnel a join deployments_personneldeployment b on a.deployment_id = b.id join api_event c on b.event_deployed_to_id = c.id join api_event_countries d on c.id = d.event_id join api_country e on d.country_id = e.id where deployments_personnel.deployedperson_ptr_id = a.deployedperson_ptr_id and e.record_type = 1'],
            reverse_sql=['update deployments_personnel set country_to_id=NULL'],
        ),
        migrations.CreateModel(
            name='EmergencyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('activity_lead', models.CharField(choices=[('national_society', 'National Society'), ('deployed_eru', 'Deployed ERU')], max_length=30, verbose_name='Activity lead')),
                ('reporting_ns_contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='NS Contanct Information: Name')),
                ('reporting_ns_contact_role', models.CharField(blank=True, max_length=255, null=True, verbose_name='NS Contanct Information: Role')),
                ('reporting_ns_contact_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='NS Contanct Information: Email')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('status', models.CharField(choices=[('on_going', 'Ongoing'), ('complete', 'Complete'), ('planned', 'Planned')], default='on_going', max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deployed_eru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='deployments.eru', verbose_name='Deployed ERU')),
                ('districts', models.ManyToManyField(related_name='_emergencyproject_districts_+', to='api.district', verbose_name='Districts')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.event', verbose_name='Event')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('reporting_ns', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.country', verbose_name='Reporting national society')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.country', verbose_name='Country')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('visibility', models.CharField(choices=[('logged_in_user', 'Membership'), ('ifrc_only', 'IFRC Only'), ('public', 'Public'), ('ifrc_ns', 'IFRC_NS')], default='public', max_length=32, verbose_name='visibility')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyProjectActivityAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('order', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyProjectActivitySector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('order', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyProjectActivityActionSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('order', models.SmallIntegerField(default=0)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='deployments.emergencyprojectactivityaction', verbose_name='action')),
            ],
        ),
        migrations.AddField(
            model_name='emergencyprojectactivityaction',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deployments.emergencyprojectactivitysector', verbose_name='sector'),
        ),
        migrations.CreateModel(
            name='EmergencyProjectActivityLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('description', models.TextField(verbose_name='location description')),
            ],
        ),
        migrations.AddField(
            model_name='emergencyprojectactivityaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='molnix_status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('hidden', 'HIDDEN'), ('draft', 'DRAFT'), ('deleted', 'DELETED')], default='active', max_length=8, verbose_name='molnix status'),
        ),
        migrations.AddField(
            model_name='emergencyprojectactivityaction',
            name='is_cash_type',
            field=models.BooleanField(default=False, verbose_name='is_cash_type'),
        ),
        migrations.AddField(
            model_name='emergencyprojectactivityaction',
            name='has_location',
            field=models.BooleanField(default=False, verbose_name='has location'),
        ),
        migrations.AddField(
            model_name='molnixtag',
            name='tag_category',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reporting_ns_contact_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NS Contanct Information: Email'),
        ),
        migrations.AddField(
            model_name='project',
            name='reporting_ns_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NS Contanct Information: Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='reporting_ns_contact_role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NS Contanct Information: Role'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ar',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_es',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fr',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.generaldocument', verbose_name='linked document'),
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='end_date',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='end date'),
        ),
        migrations.CreateModel(
            name='EmergencyProjectActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_simplified_report', models.BooleanField(default=True, verbose_name='is_simplified_report')),
                ('people_count', models.IntegerField(blank=True, null=True, verbose_name='People')),
                ('male_count', models.IntegerField(blank=True, null=True, verbose_name='Men')),
                ('female_count', models.IntegerField(blank=True, null=True, verbose_name='Female')),
                ('male_6_12_count', models.IntegerField(blank=True, null=True, verbose_name='Boys 6-12')),
                ('male_13_17_count', models.IntegerField(blank=True, null=True, verbose_name='Boys 13-17')),
                ('male_18_59_count', models.IntegerField(blank=True, null=True, verbose_name='Men 18-29')),
                ('female_6_12_count', models.IntegerField(blank=True, null=True, verbose_name='Girls 6-12')),
                ('female_13_17_count', models.IntegerField(blank=True, null=True, verbose_name='Girls 13-17')),
                ('female_18_59_count', models.IntegerField(blank=True, null=True, verbose_name='Women 18-29')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('supplies', models.JSONField(default=dict, verbose_name='supplies')),
                ('custom_action', models.CharField(blank=True, max_length=255, null=True, verbose_name='custom_action')),
                ('custom_supplies', models.JSONField(default=dict, verbose_name='custom supplies')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.emergencyprojectactivityaction', verbose_name='action')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='deployments.emergencyproject', verbose_name='emergency project/3W')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.emergencyprojectactivitysector', verbose_name='sector')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('household_count', models.IntegerField(blank=True, null=True, verbose_name='Household')),
                ('item_count', models.IntegerField(blank=True, null=True, verbose_name='Item')),
                ('other_13_17_count', models.IntegerField(blank=True, null=True, verbose_name='Others/Unknown 13-17')),
                ('other_18_59_count', models.IntegerField(blank=True, null=True, verbose_name='Others/Unknown 18-29')),
                ('other_6_12_count', models.IntegerField(blank=True, null=True, verbose_name='Others/Unknown 6-12')),
                ('point_count', models.IntegerField(blank=True, null=True, verbose_name='Point Count')),
                ('points', models.ManyToManyField(blank=True, to='deployments.emergencyprojectactivitylocation', verbose_name='Points')),
                ('people_households', models.CharField(blank=True, choices=[('people', 'People'), ('households', 'Households')], max_length=50, null=True, verbose_name='People Households')),
                ('beneficiaries_count', models.IntegerField(blank=True, null=True, verbose_name='Beneficiaries Count')),
                ('disabled_female_13_17_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Girls 13-17')),
                ('disabled_female_18_59_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Women 18-29')),
                ('disabled_female_6_12_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Girls 6-12')),
                ('disabled_male_13_17_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Boys 13-17')),
                ('disabled_male_18_59_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Men 18-29')),
                ('disabled_male_6_12_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Boys 6-12')),
                ('disabled_other_13_17_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Others/Unknown 13-17')),
                ('disabled_other_18_59_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Others/Unknown 18-29')),
                ('disabled_other_6_12_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Others/Unknown 6-12')),
                ('female_unknown_age_count', models.IntegerField(blank=True, null=True, verbose_name='Female Unknown Age')),
                ('is_disaggregated_for_disabled', models.BooleanField(blank=True, null=True, verbose_name='Is disaggregated for disabled')),
                ('male_unknown_age_count', models.IntegerField(blank=True, null=True, verbose_name='Male Unknown Age')),
                ('other_unknown_age_count', models.IntegerField(blank=True, null=True, verbose_name='Other Unknown Age')),
                ('disabled_female_0_1_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Girls 0-1')),
                ('disabled_female_2_5_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Girls 2-5')),
                ('disabled_female_60_plus_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Older Women 60+')),
                ('disabled_male_0_1_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Boys 0-1')),
                ('disabled_male_2_5_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Boys 2-5')),
                ('disabled_male_60_plus_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Older Men 60+')),
                ('disabled_other_0_1_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Others/Unknown 0-1')),
                ('disabled_other_2_5_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Others/Unknown 2-5')),
                ('disabled_other_60_plus_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Others/Unknown 60+')),
                ('female_0_1_count', models.IntegerField(blank=True, null=True, verbose_name='Girls 0-1')),
                ('female_2_5_count', models.IntegerField(blank=True, null=True, verbose_name='Girls 2-5')),
                ('female_60_plus_count', models.IntegerField(blank=True, null=True, verbose_name='Older Women 60+')),
                ('male_0_1_count', models.IntegerField(blank=True, null=True, verbose_name='Boys 0-1')),
                ('male_2_5_count', models.IntegerField(blank=True, null=True, verbose_name='Boys 2-5')),
                ('male_60_plus_count', models.IntegerField(blank=True, null=True, verbose_name='Older Men 60+')),
                ('other_0_1_count', models.IntegerField(blank=True, null=True, verbose_name='Others/Unknown 0-1')),
                ('other_2_5_count', models.IntegerField(blank=True, null=True, verbose_name='Others/Unknown 2-5')),
                ('other_60_plus_count', models.IntegerField(blank=True, null=True, verbose_name='Others/Unknown 60+')),
                ('has_no_data_on_people_reached', models.BooleanField(blank=True, null=True, verbose_name='Has no data on people reached')),
                ('disabled_female_unknown_age_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Female Unknown Age')),
                ('disabled_male_unknown_age_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Male Unknown Age')),
                ('disabled_other_unknown_age_count', models.IntegerField(blank=True, null=True, verbose_name='Disabled Other Unknown Age')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='year')),
                ('budget_amount', models.IntegerField(blank=True, null=True, verbose_name='amount')),
                ('target_male', models.IntegerField(blank=True, null=True, verbose_name='target male')),
                ('target_female', models.IntegerField(blank=True, null=True, verbose_name='target female')),
                ('target_other', models.IntegerField(blank=True, null=True, verbose_name='target other')),
                ('target_total', models.IntegerField(blank=True, null=True, verbose_name='target total')),
                ('reached_male', models.IntegerField(blank=True, null=True, verbose_name='reached male')),
                ('reached_female', models.IntegerField(blank=True, null=True, verbose_name='reached female')),
                ('reached_other', models.IntegerField(blank=True, null=True, verbose_name='reached other')),
                ('reached_total', models.IntegerField(blank=True, null=True, verbose_name='reached total')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_splits', to='deployments.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Annual Split',
                'verbose_name_plural': 'Annual Splits',
            },
        ),
        migrations.AlterField(
            model_name='eru',
            name='type',
            field=models.IntegerField(choices=[(0, 'Basecamp'), (1, 'IT & Telecom'), (2, 'Logistics'), (3, 'RCRC Emergency Hospital'), (4, 'RCRC Emergency Clinic'), (5, 'Relief'), (6, 'Wash M15'), (7, 'Wash MSM20'), (8, 'Wash M40'), (9, 'Water Supply and rehabilitation'), (10, 'Household Water Treatment and safe storage'), (11, 'Cholera Case management at Community level'), (12, 'Safe and Dignified Burials'), (13, 'Community Based Surveillance'), (14, 'Base Camp – S'), (15, 'Base Camp – M'), (16, 'Base Camp – L')], default=0, help_text='<a target="_blank" href="/api/v2/erutype">Key/value pairs</a>', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='operation_type',
            field=models.IntegerField(choices=[(0, 'Programme'), (1, 'Emergency Operation')], default=0, help_text='<a target="_blank" href="/api/v2/operationtype">Key/value pairs</a>', verbose_name='operation type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_sector',
            field=models.IntegerField(choices=[(0, 'WASH'), (1, 'PGI'), (2, 'CEA'), (3, 'Migration'), (4, 'Health'), (5, 'DRR'), (6, 'Shelter'), (7, 'NS Strengthening'), (8, 'Education'), (9, 'Livelihoods and basic needs')], default=0, help_text='<a target="_blank" href="/api/v2/primarysector">Key/value pairs</a>', verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='project',
            name='programme_type',
            field=models.IntegerField(choices=[(0, 'Bilateral'), (1, 'Multilateral'), (2, 'Domestic')], default=0, help_text='<a target="_blank" href="/api/v2/programmetype">Key/value pairs</a>', verbose_name='programme type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Planned'), (1, 'Ongoing'), (2, 'Completed')], default=0, help_text='<a target="_blank" href="/api/v2/projectstatus">Key/value pairs</a>', verbose_name='status'),
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ('deployment', 'country_to', 'country_from', 'molnix_id', 'deployedperson_ptr_id'), 'verbose_name': 'Personnel', 'verbose_name_plural': 'Personnels'},
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
                ('order', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SectorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
                ('order', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.RunSQL(
            sql=['INSERT INTO deployments_sector   (id, "order", slug, title) values (0 ,0 ,\'WASH\', \'WASH\')', 'INSERT INTO deployments_sector   (id, "order", slug, title) values (1 ,1 ,\'PGI\', \'PGI\')', 'INSERT INTO deployments_sector   (id, "order", slug, title) values (2 ,2 ,\'CEA\' , \'CEA\')', 'INSERT INTO deployments_sector   (id, "order", slug, title) values (3 ,3 ,\'MIGRATION\', \'Migration\')', 'INSERT INTO deployments_sector   (id, "order", slug, title) values (4 ,4 ,\'HEALTH_PUBLIC\' , \'Health (public)\')', 'INSERT INTO deployments_sector   (id, "order", slug, title) values (5 ,5 ,\'DRR\', \'DRR\')', 'INSERT INTO deployments_sector   (id, "order", slug, title) values (6 ,6 ,\'SHELTER\' ,\'Shelter\')', 'INSERT INTO deployments_sector   (id, "order", slug, title) values (7 ,7 ,\'NS_STRENGTHENING\' , \'NS Strengthening\')', 'INSERT INTO deployments_sector   (id, "order", slug, title) values (8 ,8 ,\'EDUCATION\' , \'Education\')', 'INSERT INTO deployments_sector   (id, "order", slug, title) values (9 ,9 ,\'LIVELIHOODS_AND_BASIC_NEEDS\', \'Livelihoods and basic needs\')', "SELECT SETVAL('deployments_sector_id_seq', (select max(id) from deployments_sector))", 'INSERT INTO deployments_sectortag(id, "order", slug, title) values (0 ,0 ,\'WASH\', \'WASH\')', 'INSERT INTO deployments_sectortag(id, "order", slug, title) values (1 ,1 ,\'PGI\', \'PGI\')', 'INSERT INTO deployments_sectortag(id, "order", slug, title) values (2 ,2 ,\'CEA\' , \'CEA\')', 'INSERT INTO deployments_sectortag(id, "order", slug, title) values (3 ,3 ,\'MIGRATION\', \'Migration\')', 'INSERT INTO deployments_sectortag(id, "order", slug, title) values (4 ,4 ,\'HEALTH_PUBLIC\' , \'Health (public)\')', 'INSERT INTO deployments_sectortag(id, "order", slug, title) values (5 ,5 ,\'DRR\', \'DRR\')', 'INSERT INTO deployments_sectortag(id, "order", slug, title) values (6 ,6 ,\'SHELTER\' ,\'Shelter\')', 'INSERT INTO deployments_sectortag(id, "order", slug, title) values (7 ,7 ,\'NS_STRENGTHENING\' , \'NS Strengthening\')', 'INSERT INTO deployments_sectortag(id, "order", slug, title) values (8 ,8 ,\'EDUCATION\' , \'Education\')', 'INSERT INTO deployments_sectortag(id, "order", slug, title) values (9 ,9 ,\'LIVELIHOODS_AND_BASIC_NEEDS\', \'Livelihoods and basic needs\')', 'INSERT INTO deployments_sectortag(id, "order", slug, title) values (10,10,\'RECOVERY\', \'Recovery\')', 'INSERT INTO deployments_sectortag(id, "order", slug, title) values (11,11,\'INTERNAL_DISPLACEMENT\', \'Internal displacement\')', 'INSERT INTO deployments_sectortag(id, "order", slug, title) values (12,12,\'HEALTH_CLINICAL\' , \'Health (clinical)\')', 'INSERT INTO deployments_sectortag(id, "order", slug, title) values (13,13,\'COVID_19\' , \'COVID-19\')', "SELECT SETVAL('deployments_sectortag_id_seq', (select max(id) from deployments_sectortag))", 'CREATE TABLE tmp2sect as select id, secondary_sectors from deployments_project'],
            reverse_sql=['DELETE FROM deployments_sector', 'DELETE FROM deployments_sectortag', 'DROP TABLE tmp2sect'],
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.sector', verbose_name='sector'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='secondary_sectors',
        ),
        migrations.AddField(
            model_name='project',
            name='secondary_sectors',
            field=models.ManyToManyField(blank=True, related_name='tags', to='deployments.sectortag'),
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Project Sector', 'verbose_name_plural': 'Project Sectors'},
        ),
        migrations.AlterModelOptions(
            name='sectortag',
            options={'verbose_name': 'Project Sector Tag', 'verbose_name_plural': 'Project Sector Tags'},
        ),
        migrations.RunSQL(
            sql=['INSERT INTO deployments_project_secondary_sectors (project_id,sectortag_id) (select distinct id, unnest(secondary_sectors) FROM tmp2sect)', 'DROP TABLE tmp2sect'],
            reverse_sql=['DELETE FROM deployments_project_secondary_sectors'],
        ),
        migrations.AlterField(
            model_name='molnixtag',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deployments.sector', verbose_name='sector'),
        ),
        migrations.RemoveField(
            model_name='sector',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sectortag',
            name='slug',
        ),
        migrations.AddField(
            model_name='sector',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='sector',
            name='is_deprecated',
            field=models.BooleanField(default=False, help_text='Is this a deprecated sector?'),
        ),
        migrations.AddField(
            model_name='sectortag',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='sectortag',
            name='is_deprecated',
            field=models.BooleanField(default=False, help_text='Is this a deprecated sector tag?'),
        ),
        migrations.AlterField(
            model_name='emergencyproject',
            name='districts',
            field=models.ManyToManyField(blank=True, related_name='_deployments_emergencyproject_districts_+', to='api.district', verbose_name='Districts'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_districts',
            field=models.ManyToManyField(blank=True, to='api.district', verbose_name='districts'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='type',
            field=models.IntegerField(choices=[(0, 'Basecamp'), (1, 'IT & Telecom'), (2, 'Logistics'), (3, 'RCRC Emergency Hospital'), (4, 'RCRC Emergency Clinic'), (5, 'Relief'), (6, 'Wash M15'), (7, 'Wash MSM20'), (8, 'Wash M40'), (9, 'Water Supply and rehabilitation'), (10, 'Household Water Treatment and safe storage'), (11, 'Cholera Case management at Community level'), (12, 'Safe and Dignified Burials'), (13, 'Community Based Surveillance'), (14, 'Base Camp – S'), (15, 'Base Camp – M'), (16, 'Base Camp – L'), (17, 'Outpatient Department (OPD) Module'), (18, 'MHPSS')], default=0, help_text='<a target="_blank" href="/api/v2/erutype">Key/value pairs</a>', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='emergencyprojectactivity',
            name='custom_supplies',
            field=models.JSONField(blank=True, default=dict, verbose_name='custom supplies'),
        ),
        migrations.AlterField(
            model_name='emergencyprojectactivity',
            name='supplies',
            field=models.JSONField(blank=True, default=dict, verbose_name='supplies'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_admin2',
            field=models.ManyToManyField(blank=True, to='api.admin2', verbose_name='admin2'),
        ),
        migrations.AddField(
            model_name='emergencyproject',
            name='admin2',
            field=models.ManyToManyField(blank=True, to='api.admin2', verbose_name='admin2'),
        ),
        migrations.AddField(
            model_name='deployedperson',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='deployedperson',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='partnersocietyactivities',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='partnersocietyactivities',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='personneldeployment',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='personneldeployment',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='project',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='project',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='regionalproject',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='regionalproject',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
    ]
