# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eruowner',
            options={'verbose_name': 'ERU owner', 'verbose_name_plural': 'ERU owners'},
        ),
        migrations.AlterModelOptions(
            name='fact',
            options={'verbose_name': 'FACT', 'verbose_name_plural': 'FACTs'},
        ),
        migrations.AlterModelOptions(
            name='heop',
            options={'verbose_name': 'HeOp', 'verbose_name_plural': 'HeOps'},
        ),
        migrations.AlterModelOptions(
            name='rdit',
            options={'verbose_name': 'RDRT/RIT', 'verbose_name_plural': 'RDRTs/RITs'},
        ),
    ]
