# Generated by Django 2.0.5 on 2018-06-14 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180614_2206'),
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSocietyDeployment',
            fields=[
                ('deployedperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deployments.DeployedPerson')),
                ('country_deployed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_partner_deployments', to='api.Country')),
                ('district_deployed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_partner_deployments', to='api.District')),
                ('parent_society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_society_members', to='api.Country')),
            ],
            bases=('deployments.deployedperson',),
        ),
        migrations.RemoveField(
            model_name='deployedperson',
            name='society_deployed_from',
        ),
        migrations.AddField(
            model_name='factperson',
            name='society_deployed_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rdrtperson',
            name='society_deployed_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
