# Generated by Django 2.0.5 on 2018-06-20 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_auto_20180614_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSocietyActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='partnersocietydeployment',
            name='district_deployed_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_partner_deployments', to='api.District'),
        ),
        migrations.AddField(
            model_name='partnersocietydeployment',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_societies', to='deployments.PartnerSocietyActivities'),
        ),
    ]
