# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_eru_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=32, null=True)),
                ('society_deployed_from', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fact',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='person',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='role',
        ),
        migrations.RemoveField(
            model_name='rdit',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='rdit',
            name='person',
        ),
        migrations.RemoveField(
            model_name='rdit',
            name='role',
        ),
        migrations.CreateModel(
            name='FactPerson',
            fields=[
                ('deployedperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deployments.DeployedPerson')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.Fact')),
            ],
            options={
                'verbose_name': 'FACT Person',
                'verbose_name_plural': 'FACT People',
            },
            bases=('deployments.deployedperson',),
        ),
        migrations.CreateModel(
            name='RditPerson',
            fields=[
                ('deployedperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deployments.DeployedPerson')),
                ('rdit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.Rdit')),
            ],
            options={
                'verbose_name': 'RDRT/RIT Person',
                'verbose_name_plural': 'RDRT/RIT People',
            },
            bases=('deployments.deployedperson',),
        ),
    ]
