# Generated by Django 2.0.5 on 2018-06-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fieldreport_report_date'),
        ('deployments', '0003_auto_20180620_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersocietydeployment',
            name='country_deployed_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_partner_deployments', to='api.Country'),
        ),
        migrations.RemoveField(
            model_name='partnersocietydeployment',
            name='district_deployed_to',
        ),
        migrations.AddField(
            model_name='partnersocietydeployment',
            name='district_deployed_to',
            field=models.ManyToManyField(to='api.District'),
        ),
        migrations.AlterField(
            model_name='partnersocietydeployment',
            name='parent_society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_society_members', to='api.Country'),
        ),
    ]
