# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_auto_20180123_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rdit',
            new_name='Rdrt',
        ),
        migrations.RenameModel(
            old_name='RditPerson',
            new_name='RdrtPerson',
        ),
        migrations.RenameField(
            model_name='rdrtperson',
            old_name='rdit',
            new_name='rdrt',
        ),
    ]
