# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180126_1933'),
        ('deployments', '0005_auto_20180123_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eruowner',
            options={'verbose_name': 'ERUs from a National Society', 'verbose_name_plural': 'ERUs'},
        ),
        migrations.RenameField(
            model_name='eruowner',
            old_name='country',
            new_name='national_society_country',
        ),
        migrations.RemoveField(
            model_name='eru',
            name='countries',
        ),
        migrations.AddField(
            model_name='eru',
            name='deployed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country'),
        ),
    ]
