# Generated by Django 2.0.12 on 2019-06-27 11:06

import deployments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_auto_20190626_1420'),
        ('deployments', '0007_auto_20190413_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('programme_type', enumfields.fields.EnumIntegerField(enum=deployments.models.ProgrammeTypes)),
                ('sector', enumfields.fields.EnumIntegerField(enum=deployments.models.Sectors)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget_amount', models.IntegerField()),
                ('status', enumfields.fields.EnumIntegerField(enum=deployments.models.Statuses)),
                ('project_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.District')),
                ('reporting_ns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
