# Generated by Django 2.0.12 on 2019-07-11 08:59

import deployments.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190703_0614'),
        ('deployments', '0010_auto_20190711_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERUReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ERU_type', enumfields.fields.EnumIntegerField(default=0, enum=deployments.models.ERUType)),
                ('is_personnel', models.BooleanField(default=False)),
                ('is_equipment', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national_society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country')),
            ],
            options={
                'verbose_name': 'ERU Readiness',
                'verbose_name_plural': 'NS-es ERU Readiness',
                'ordering': ('updated_at', 'national_society'),
            },
        ),
    ]
