# Generated by Django 2.0.12 on 2019-07-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0012_auto_20190722_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personneldeployment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
