# Generated by Django 2.0.12 on 2019-10-04 06:46

import deployments.models
import django.contrib.postgres.fields
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0013_auto_20190722_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sector',
            new_name='primary_sector',
        ),
        migrations.AddField(
            model_name='project',
            name='operation_type',
            field=enumfields.fields.EnumIntegerField(default=0, enum=deployments.models.OperationTypes),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='secondary_sectors',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=enumfields.fields.EnumIntegerField(enum=deployments.models.Sectors),
                blank=True, default=list, size=None,
            ),
        ),

        migrations.AddField(
            model_name='project',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),

        migrations.CreateModel(
            name='RegionalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='regional_project',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='deployments.RegionalProject',
            ),
        ),

        migrations.AddField(
            model_name='project',
            name='dtype',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='api.DisasterType',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='event',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='api.Event',
            ),
        ),

        migrations.AddField(
            model_name='project',
            name='reached_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
