# Generated by Django 2.0.12 on 2019-10-04 06:46

import deployments.models
import django.contrib.postgres.fields
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0013_auto_20190722_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sector',
            new_name='primary_sector',
        ),
        migrations.AddField(
            model_name='project',
            name='operation_type',
            field=enumfields.fields.EnumIntegerField(default=0, enum=deployments.models.OperationTypes),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='secondary_sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=enumfields.fields.EnumIntegerField(enum=deployments.models.Sectors), blank=True, default=list, size=None),
        ),
    ]
