# Generated by Django 2.0.12 on 2019-11-28 06:40

import deployments.models
import django.contrib.postgres.fields
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0014_auto_20191024_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='secondary_sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=enumfields.fields.EnumIntegerField(enum=deployments.models.SectorTags), blank=True, default=list, size=None),
        ),
    ]
