# Generated by Django 2.0.12 on 2019-10-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0016_auto_20191016_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reached_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_male',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
