# Generated by Django 2.0.12 on 2019-10-23 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_fieldreportcontact_phone'),
        ('deployments', '0017_auto_20191021_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.DisasterType'),
        ),
        migrations.AddField(
            model_name='project',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Event'),
        ),
    ]
