# Generated by Django 2.0.12 on 2020-03-19 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0017_auto_20200122_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_district',
            field=models.ForeignKey(blank=True, help_text='No selection will indicate all districts.', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.District'),
        ),
    ]
