# Generated by Django 2.0.12 on 2020-03-19 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20200128_1045'),
        ('deployments', '0018_auto_20200319_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.Country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reporting_ns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ns_projects', to='api.Country'),
        ),
    ]
