# Generated by Django 2.2.10 on 2020-05-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20200504_1438'),
        ('deployments', '0022_auto_20200409_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_districts',
            field=models.ManyToManyField(blank=True, help_text='No selection will indicate all districts.', related_name='many_to_many_projects', to='api.District'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_district',
            field=models.ForeignKey(blank=True, help_text='No selection will indicate all districts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.District'),
        ),
    ]
