# Generated by Django 2.2.13 on 2020-06-18 09:04

import deployments.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0027_auto_20200528_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployedperson',
            options={'verbose_name': 'Deployed Person', 'verbose_name_plural': 'Deployed Persons'},
        ),
        migrations.AlterModelOptions(
            name='eru',
            options={'verbose_name': 'Emergency Response Unit', 'verbose_name_plural': 'Emergency Response Units'},
        ),
        migrations.AlterModelOptions(
            name='partnersocietydeployment',
            options={'verbose_name': 'Partner Society Deployment', 'verbose_name_plural': 'Partner Society Deployments'},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name': 'Personnel', 'verbose_name_plural': 'Personnels'},
        ),
        migrations.AlterModelOptions(
            name='personneldeployment',
            options={'verbose_name': 'Personnel Deployment', 'verbose_name_plural': 'Personnel Deployments'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectimport',
            options={'verbose_name': 'Project Import', 'verbose_name_plural': 'Projects Import'},
        ),
        migrations.AlterModelOptions(
            name='regionalproject',
            options={'verbose_name': 'Regional Project', 'verbose_name_plural': 'Regional Projects'},
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='role',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='alert_date',
            field=models.DateTimeField(help_text='still not used in frontend', null=True, verbose_name='alert date'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='appeal',
            field=models.ForeignKey(blank=True, help_text='still not used in frontend', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Appeal', verbose_name='appeal'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='available',
            field=models.BooleanField(default=False, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='deployed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country', verbose_name='country deployed to'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='end_date',
            field=models.DateTimeField(help_text='still not used in frontend', null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='equipment_units',
            field=models.IntegerField(default=0, verbose_name='equipment units'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='eru_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.ERUOwner', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='num_people_deployed',
            field=models.IntegerField(default=0, help_text='still not used in frontend', verbose_name='number of people deployed'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='start_date',
            field=models.DateTimeField(help_text='still not used in frontend', null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='supporting_societies',
            field=models.CharField(blank=True, help_text='still not used in frontend', max_length=500, null=True, verbose_name='suuporting societies'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='type',
            field=enumfields.fields.EnumIntegerField(default=0, enum=deployments.models.ERUType, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='units',
            field=models.IntegerField(default=0, verbose_name='units'),
        ),
        migrations.AlterField(
            model_name='eruowner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='eruowner',
            name='national_society_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country', verbose_name='national society country'),
        ),
        migrations.AlterField(
            model_name='eruowner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='erureadiness',
            name='ERU_type',
            field=enumfields.fields.EnumIntegerField(default=0, enum=deployments.models.ERUType, verbose_name='ERU type'),
        ),
        migrations.AlterField(
            model_name='erureadiness',
            name='is_equipment',
            field=models.BooleanField(default=False, verbose_name='is equipment?'),
        ),
        migrations.AlterField(
            model_name='erureadiness',
            name='is_personnel',
            field=models.BooleanField(default=False, verbose_name='is personnel?'),
        ),
        migrations.AlterField(
            model_name='erureadiness',
            name='national_society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country', verbose_name='national society'),
        ),
        migrations.AlterField(
            model_name='erureadiness',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='partnersocietyactivities',
            name='activity',
            field=models.CharField(max_length=50, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='partnersocietydeployment',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_societies', to='deployments.PartnerSocietyActivities', verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='partnersocietydeployment',
            name='country_deployed_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_partner_deployments', to='api.Country', verbose_name='country deployed to'),
        ),
        migrations.AlterField(
            model_name='partnersocietydeployment',
            name='district_deployed_to',
            field=models.ManyToManyField(to='api.District', verbose_name='district deployed to'),
        ),
        migrations.AlterField(
            model_name='partnersocietydeployment',
            name='parent_society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_society_members', to='api.Country', verbose_name='parent society'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='country_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_deployments', to='api.Country', verbose_name='country from'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.PersonnelDeployment', verbose_name='deployment'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='type',
            field=models.CharField(choices=[('fact', 'Fact'), ('heop', 'HEOP'), ('rdrt', 'RDRT'), ('ifrc', 'IFRC'), ('eru', 'ERU HR'), ('rr', 'Rapid Response')], max_length=4, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='alert_date',
            field=models.DateTimeField(help_text='still not used in frontend', null=True, verbose_name='alert date'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='appeal_deployed_to',
            field=models.ForeignKey(blank=True, help_text='still not used in frontend', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Appeal', verbose_name='appeal deployed to'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='country_deployed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country', verbose_name='country deployed to'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='end_date',
            field=models.DateTimeField(help_text='still not used in frontend', null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='end_duration',
            field=models.CharField(blank=True, help_text='still not used in frontend', max_length=100, null=True, verbose_name='end duration'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='event_deployed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Event', verbose_name='event deployed to'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='exp_start_date',
            field=models.DateTimeField(help_text='still not used in frontend', null=True, verbose_name='expire start date'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='previous_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='previous update'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='region_deployed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Region', verbose_name='region deployed to'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='start_date',
            field=models.DateTimeField(help_text='still not used in frontend', null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='personneldeployment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_amount',
            field=models.IntegerField(verbose_name='budget amount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.DisasterType', verbose_name='disaster type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='operation_type',
            field=enumfields.fields.EnumIntegerField(enum=deployments.models.OperationTypes, verbose_name='operation type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_sector',
            field=enumfields.fields.EnumIntegerField(enum=deployments.models.Sectors, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='project',
            name='programme_type',
            field=enumfields.fields.EnumIntegerField(enum=deployments.models.ProgrammeTypes, verbose_name='programme type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_districts',
            field=models.ManyToManyField(to='api.District', verbose_name='districts'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reached_female',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached female'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reached_male',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached male'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reached_other',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached other'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reached_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='reached total'),
        ),
        migrations.AlterField(
            model_name='project',
            name='regional_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deployments.RegionalProject', verbose_name='regional project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reporting_ns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ns_projects', to='api.Country', verbose_name='reporting national society'),
        ),
        migrations.AlterField(
            model_name='project',
            name='secondary_sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=enumfields.fields.EnumIntegerField(enum=deployments.models.SectorTags), blank=True, default=list, size=None, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=enumfields.fields.EnumIntegerField(enum=deployments.models.Statuses, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_female',
            field=models.IntegerField(blank=True, null=True, verbose_name='target female'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_male',
            field=models.IntegerField(blank=True, null=True, verbose_name='target male'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_other',
            field=models.IntegerField(blank=True, null=True, verbose_name='target other'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='target total'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('logged_in_user', 'Membership'), ('ifrc_only', 'IFRC Only'), ('public', 'Public')], default='public', max_length=32, verbose_name='visibility'),
        ),
        migrations.AlterField(
            model_name='projectimport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='projectimport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='projectimport',
            name='file',
            field=models.FileField(upload_to='project-imports/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='projectimport',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='projectimport',
            name='projects_created',
            field=models.ManyToManyField(to='deployments.Project', verbose_name='projects created'),
        ),
        migrations.AlterField(
            model_name='projectimport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='regionalproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='regionalproject',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='regionalproject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
