# Generated by Django 2.2.13 on 2020-06-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0028_auto_20200603_0613'),
        ('deployments', '0027_auto_20200528_0840'),
    ]

    operations = [
    ]
