# Generated by Django 2.2.13 on 2020-06-26 07:29

from deployments.models import Statuses
from django.db import migrations
from django.db.models import F

def set_actual_expenditure_for_completed_projects(apps, schema_editor):
    """
        set actual expenditure using budget amount for completed projects
    """
    Project = apps.get_model('deployments', 'Project')
    Project.objects.filter(status=Statuses.COMPLETED).update(actual_expenditure=F('budget_amount'))


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0029_auto_20200625_1019'),
    ]

    operations = [
        migrations.RunPython(set_actual_expenditure_for_completed_projects),
    ]
