# Generated by Django 2.2.13 on 2020-06-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0030_actual_expenditure_complete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedperson',
            name='role_ar',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='deployedperson',
            name='role_en',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='deployedperson',
            name='role_es',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='deployedperson',
            name='role_fr',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='partnersocietyactivities',
            name='activity_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='partnersocietyactivities',
            name='activity_en',
            field=models.CharField(max_length=50, null=True, verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='partnersocietyactivities',
            name='activity_es',
            field=models.CharField(max_length=50, null=True, verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='partnersocietyactivities',
            name='activity_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='personneldeployment',
            name='comments_ar',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='personneldeployment',
            name='comments_en',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='personneldeployment',
            name='comments_es',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='personneldeployment',
            name='comments_fr',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ar',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_es',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_fr',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='regionalproject',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='regionalproject',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='regionalproject',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='regionalproject',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='supporting_societies',
            field=models.CharField(blank=True, help_text='still not used in frontend', max_length=500, null=True, verbose_name='supporting societies'),
        ),
    ]
