# Generated by Django 2.2.13 on 2020-11-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0035_personnel_molnix_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployedperson',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='role',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='role_ar',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='role_en',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='role_es',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='deployedperson',
            name='role_fr',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='role'),
        ),
    ]
