# Generated by Django 2.2.24 on 2021-09-20 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0039_auto_20210823_1159"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personneldeployment",
            name="region_deployed_to",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.Region", verbose_name="region deployed to"
            ),
        ),
    ]
