# Generated by Django 2.2.26 on 2022-01-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_auto_20220105_1533'),
        ('deployments', '0041_auto_20211110_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='country_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_deployments_to', to='api.Country', verbose_name='country to'),
        ),
    ]
