# Generated by Django 2.2.27 on 2022-03-05 09:22

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import deployments.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0146_auto_20220228_0952"),
        ("deployments", "0043_personnel_country_to_fill"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyProject",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modified at")),
                (
                    "activity_lead",
                    models.CharField(
                        choices=[("national_society", "National Society"), ("deployed_eru", "Deployed ERU")],
                        max_length=30,
                        verbose_name="Activity lead",
                    ),
                ),
                (
                    "reporting_ns_contact_name",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="NS Contanct Information: Name"),
                ),
                (
                    "reporting_ns_contact_role",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="NS Contanct Information: Role"),
                ),
                (
                    "reporting_ns_contact_email",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="NS Contanct Information: Email"),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "status",
                    models.CharField(
                        choices=[("on_going", "Activity Ongoing"), ("complete", "Activity Complete")],
                        default=deployments.models.EmergencyProject.ActivityStatus("on_going"),
                        max_length=40,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="api.Country", verbose_name="Country"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deployed_eru",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="deployments.ERU",
                        verbose_name="Deployed ERU",
                    ),
                ),
                (
                    "districts",
                    models.ManyToManyField(
                        related_name="_emergencyproject_districts_+", to="api.District", verbose_name="Districts"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="api.Event", verbose_name="Event"
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
                (
                    "reporting_ns",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="api.Country",
                        verbose_name="Reporting national society",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyProjectActivityAction",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("order", models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyProjectActivitySector",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("order", models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyProjectActivityActionSupply",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("order", models.SmallIntegerField(default=0)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplies",
                        to="deployments.EmergencyProjectActivityAction",
                        verbose_name="action",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="emergencyprojectactivityaction",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="deployments.EmergencyProjectActivitySector",
                verbose_name="sector",
            ),
        ),
        migrations.CreateModel(
            name="EmergencyProjectActivity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_simplified_report", models.BooleanField(default=True, verbose_name="is_simplified_report")),
                ("people_count", models.IntegerField(blank=True, null=True, verbose_name="People")),
                ("male_count", models.IntegerField(blank=True, null=True, verbose_name="Men")),
                ("female_count", models.IntegerField(blank=True, null=True, verbose_name="Female")),
                ("male_0_5_count", models.IntegerField(blank=True, null=True, verbose_name="Boys 0-5")),
                ("male_6_12_count", models.IntegerField(blank=True, null=True, verbose_name="Boys 6-12")),
                ("male_13_17_count", models.IntegerField(blank=True, null=True, verbose_name="Boys 13-17")),
                ("male_18_29_count", models.IntegerField(blank=True, null=True, verbose_name="Men 18-29")),
                ("male_30_39_count", models.IntegerField(blank=True, null=True, verbose_name="Men 30-39")),
                ("male_40_49_count", models.IntegerField(blank=True, null=True, verbose_name="Men 40-49")),
                ("male_50_59_count", models.IntegerField(blank=True, null=True, verbose_name="Men 50-59")),
                ("male_60_69_count", models.IntegerField(blank=True, null=True, verbose_name="Men 60-69")),
                ("male_70_plus_count", models.IntegerField(blank=True, null=True, verbose_name="Men 70+")),
                ("female_0_5_count", models.IntegerField(blank=True, null=True, verbose_name="Girls 0-5")),
                ("female_6_12_count", models.IntegerField(blank=True, null=True, verbose_name="Girls 6-12")),
                ("female_13_17_count", models.IntegerField(blank=True, null=True, verbose_name="Girls 13-17")),
                ("female_18_29_count", models.IntegerField(blank=True, null=True, verbose_name="Women 18-29")),
                ("female_30_39_count", models.IntegerField(blank=True, null=True, verbose_name="Women 30-39")),
                ("female_40_49_count", models.IntegerField(blank=True, null=True, verbose_name="Women 40-49")),
                ("female_50_59_count", models.IntegerField(blank=True, null=True, verbose_name="Women 50-59")),
                ("female_60_69_count", models.IntegerField(blank=True, null=True, verbose_name="Women 60-69")),
                ("female_70_plus_count", models.IntegerField(blank=True, null=True, verbose_name="Women 70+")),
                ("details", models.TextField(blank=True, verbose_name="details")),
                ("supplies", django.db.models.JSONField(default=dict, verbose_name="supplies")),
                ("custom_action", models.CharField(blank=True, max_length=255, null=True, verbose_name="custom_action")),
                ("custom_supplies", django.db.models.JSONField(default=dict, verbose_name="custom supplies")),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deployments.EmergencyProjectActivityAction",
                        verbose_name="action",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="deployments.EmergencyProject",
                        verbose_name="emergency project/3W",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deployments.EmergencyProjectActivitySector",
                        verbose_name="sector",
                    ),
                ),
            ],
        ),
    ]
