# Generated by Django 2.2.27 on 2022-03-09 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_auto_20220228_0952'),
        ('deployments', '0046_auto_20220307_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyproject',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Country', verbose_name='Country'),
            preserve_default=False,
        ),
    ]
