# Generated by Django 2.2.27 on 2022-03-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0048_auto_20220310_0524"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencyprojectactivitylocation",
            name="latitude",
            field=models.FloatField(verbose_name="latitude"),
        ),
        migrations.AlterField(
            model_name="emergencyprojectactivitylocation",
            name="longitude",
            field=models.FloatField(verbose_name="longitude"),
        ),
    ]
