# Generated by Django 2.2.27 on 2022-03-11 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0050_emergencyprojectactivity_people_households"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencyproject",
            name="deployed_eru",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="deployments.ERU",
                verbose_name="Deployed ERU",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyproject",
            name="reporting_ns",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="api.Country",
                verbose_name="Reporting national society",
            ),
        ),
    ]
