# Generated by Django 2.2.27 on 2022-03-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0051_auto_20220311_0947"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyprojectactivityaction",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="emergencyprojectactivity",
            name="details",
            field=models.TextField(blank=True, null=True, verbose_name="details"),
        ),
    ]
