# Generated by Django 2.2.27 on 2022-03-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0053_merge_20220314_1059"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyproject",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End Date"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="beneficiaries_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Beneficiaries Count"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_female_0_5_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Girls 0-5"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_female_13_17_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Girls 13-17"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_female_18_29_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Women 18-29"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_female_30_39_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Women 30-39"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_female_40_49_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Women 40-49"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_female_50_59_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Women 50-59"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_female_60_69_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Women 60-69"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_female_6_12_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Girls 6-12"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_female_70_plus_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Women 70+"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_male_0_5_count",
            field=models.IntegerField(blank=True, null=True, verbose_name=" Disabled Boys 0-5"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_male_13_17_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Boys 13-17"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_male_18_29_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Men 18-29"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_male_30_39_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Men 30-39"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_male_40_49_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Men 40-49"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_male_50_59_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Men 50-59"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_male_60_69_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Men 60-69"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_male_6_12_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Boys 6-12"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_male_70_plus_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Men 70+"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_other_0_5_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Others/Unknown 0-5"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_other_13_17_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Others/Unknown 13-17"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_other_18_29_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Others/Unknown 18-29"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_other_30_39_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Others/Unknown 30-39"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_other_40_49_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Others/Unknown 40-49"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_other_50_59_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Others/Unknown 50-59"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_other_60_69_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Others/Unknown 60-69"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_other_6_12_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Others/Unknown 6-12"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="disabled_other_70_plus_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disabled Others/Unknown 70+"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="female_unknown_age",
            field=models.IntegerField(blank=True, null=True, verbose_name="Female Unknown Age"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="is_disaggregated_for_disabled",
            field=models.BooleanField(default=False, verbose_name="is_disaggregated_for_disabled"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="male_unknown_age",
            field=models.IntegerField(blank=True, null=True, verbose_name="Male Unknown Age"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivity",
            name="other_unknown_age",
            field=models.IntegerField(blank=True, null=True, verbose_name="Other Unknown Age"),
        ),
        migrations.AddField(
            model_name="emergencyprojectactivityaction",
            name="is_cash_type",
            field=models.BooleanField(default=False, verbose_name="is_cash_type"),
        ),
    ]
