# Generated by Django 2.2.27 on 2022-03-18 05:27

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0056_auto_20220318_0413'),
        ('deployments', '0045_molnixtag_tag_category'),
    ]

    operations = [
    ]
