# Generated by Django 2.2.27 on 2022-04-14 08:42

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0152_countryoffieldreporttoreview"),
        ("deployments", "0063_auto_20220413_1438"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=tinymce.models.HTMLField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AddField(
            model_name="project",
            name="description_ar",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="project",
            name="description_en",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="project",
            name="description_es",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="project",
            name="description_fr",
            field=tinymce.models.HTMLField(blank=True, default="", null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="project",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.GeneralDocument",
                verbose_name="linked document",
            ),
        ),
    ]
