# Generated by Django 3.2 on 2022-05-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0064_auto_20220414_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='operation_type',
            field=models.IntegerField(choices=[(0, 'Programme'), (1, 'Emergency Operation')], default=0, verbose_name='operation type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Planned'), (1, 'Ongoing'), (2, 'Completed')], default=0, verbose_name='status'),
        ),
    ]
