# Generated by Django 2.2.27 on 2022-07-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0065_emergencyproject_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployedperson',
            name='end_date',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='end date'),
        ),
    ]
