# Generated by Django 3.2.14 on 2022-08-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0066_auto_20220523_0824'),
        ('deployments', '0066_auto_20220727_0708'),
    ]

    operations = [
    ]
