# Generated by Django 3.2.14 on 2022-08-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0067_annualsplit'),
        ('deployments', '0067_merge_0066_auto_20220523_0824_0066_auto_20220727_0708'),
    ]

    operations = [
    ]
