# Generated by Django 3.2.16 on 2023-01-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0069_auto_20221022_1542"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personnel",
            options={
                "ordering": ("deployment", "country_to", "country_from", "molnix_id", "deployedperson_ptr_id"),
                "verbose_name": "Personnel",
                "verbose_name_plural": "Personnels",
            },
        ),
    ]
