# Generated by Django 3.2.18 on 2023-03-01 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0072_sectortag'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                 ("INSERT INTO deployments_sector   (id, \"order\", slug, title) values (0 ,0 ,'WASH', 'WASH')"),
                 ("INSERT INTO deployments_sector   (id, \"order\", slug, title) values (1 ,1 ,'PGI', 'PGI')"),
                 ("INSERT INTO deployments_sector   (id, \"order\", slug, title) values (2 ,2 ,'CEA' , 'CEA')"),
                 ("INSERT INTO deployments_sector   (id, \"order\", slug, title) values (3 ,3 ,'MIGRATION', 'Migration')"),
                 ("INSERT INTO deployments_sector   (id, \"order\", slug, title) values (4 ,4 ,'HEALTH_PUBLIC' , 'Health (public)')"),
                 ("INSERT INTO deployments_sector   (id, \"order\", slug, title) values (5 ,5 ,'DRR', 'DRR')"),
                 ("INSERT INTO deployments_sector   (id, \"order\", slug, title) values (6 ,6 ,'SHELTER' ,'Shelter')"),
                 ("INSERT INTO deployments_sector   (id, \"order\", slug, title) values (7 ,7 ,'NS_STRENGTHENING' , 'NS Strengthening')"),
                 ("INSERT INTO deployments_sector   (id, \"order\", slug, title) values (8 ,8 ,'EDUCATION' , 'Education')"),
                 ("INSERT INTO deployments_sector   (id, \"order\", slug, title) values (9 ,9 ,'LIVELIHOODS_AND_BASIC_NEEDS', 'Livelihoods and basic needs')"),
                 ("SELECT SETVAL('deployments_sector_id_seq', (select max(id) from deployments_sector))"),
                 # ----------------
                 ("INSERT INTO deployments_sectortag(id, \"order\", slug, title) values (0 ,0 ,'WASH', 'WASH')"),
                 ("INSERT INTO deployments_sectortag(id, \"order\", slug, title) values (1 ,1 ,'PGI', 'PGI')"),
                 ("INSERT INTO deployments_sectortag(id, \"order\", slug, title) values (2 ,2 ,'CEA' , 'CEA')"),
                 ("INSERT INTO deployments_sectortag(id, \"order\", slug, title) values (3 ,3 ,'MIGRATION', 'Migration')"),
                 ("INSERT INTO deployments_sectortag(id, \"order\", slug, title) values (4 ,4 ,'HEALTH_PUBLIC' , 'Health (public)')"),
                 ("INSERT INTO deployments_sectortag(id, \"order\", slug, title) values (5 ,5 ,'DRR', 'DRR')"),
                 ("INSERT INTO deployments_sectortag(id, \"order\", slug, title) values (6 ,6 ,'SHELTER' ,'Shelter')"),
                 ("INSERT INTO deployments_sectortag(id, \"order\", slug, title) values (7 ,7 ,'NS_STRENGTHENING' , 'NS Strengthening')"),
                 ("INSERT INTO deployments_sectortag(id, \"order\", slug, title) values (8 ,8 ,'EDUCATION' , 'Education')"),
                 ("INSERT INTO deployments_sectortag(id, \"order\", slug, title) values (9 ,9 ,'LIVELIHOODS_AND_BASIC_NEEDS', 'Livelihoods and basic needs')"),
                 ("INSERT INTO deployments_sectortag(id, \"order\", slug, title) values (10,10,'RECOVERY', 'Recovery')"),
                 ("INSERT INTO deployments_sectortag(id, \"order\", slug, title) values (11,11,'INTERNAL_DISPLACEMENT', 'Internal displacement')"),
                 ("INSERT INTO deployments_sectortag(id, \"order\", slug, title) values (12,12,'HEALTH_CLINICAL' , 'Health (clinical)')"),
                 ("INSERT INTO deployments_sectortag(id, \"order\", slug, title) values (13,13,'COVID_19' , 'COVID-19')"),
                 ("SELECT SETVAL('deployments_sectortag_id_seq', (select max(id) from deployments_sectortag))"),
                 # ----------------
                 ("CREATE TABLE tmp2sect as select id, secondary_sectors from deployments_project"),
            ],
            reverse_sql=[("DELETE FROM deployments_sector"), ("DELETE FROM deployments_sectortag"), ("DROP TABLE tmp2sect"),],
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.sector', verbose_name='sector'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='secondary_sectors',
        ),
        migrations.AddField(
            model_name='project',
            name='secondary_sectors',
            field=models.ManyToManyField(blank=True, related_name='tags', to='deployments.SectorTag'),
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Project Sector', 'verbose_name_plural': 'Project Sectors'},
        ),
        migrations.AlterModelOptions(
            name='sectortag',
            options={'verbose_name': 'Project Sector Tag', 'verbose_name_plural': 'Project Sector Tags'},
        ),
        migrations.RunSQL(
            sql=[
                 ("INSERT INTO deployments_project_secondary_sectors (project_id,sectortag_id) (select distinct id, unnest(secondary_sectors) FROM tmp2sect)"),
                 ("DROP TABLE tmp2sect"),
            ],
            reverse_sql=[("DELETE FROM deployments_project_secondary_sectors"),],
        ),
    ]
