# Generated by Django 3.2.18 on 2023-04-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0077_auto_20230420_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyprojectactivity',
            name='custom_supplies',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='custom supplies'),
        ),
        migrations.AlterField(
            model_name='emergencyprojectactivity',
            name='supplies',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='supplies'),
        ),
    ]
