# Generated by Django 3.2.18 on 2023-05-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0078_emergencyproject_admin2"),
        ("deployments", "0079_auto_20230423_0628"),
    ]

    operations = []
