# Generated by Django 3.2.18 on 2023-06-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0077_auto_20230410_0720'),
        ('deployments', '0080_merge_20230505_0418'),
    ]

    operations = [
    ]
