# Generated by Django 5.2.17 on 2026-09-20 05:24

import django.db.models.deletion
from django.db import migrations, models


# Second half of the deployments squash; see 0001_squashed_0081 for why it is split.
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0232'),
        ('deployments', '0001_squashed_0081'),
        ('notifications', '0001_squashed_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='surge_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.surgealert', verbose_name='surge alert'),
        ),
        migrations.CreateModel(
            name='MolnixTagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molnix_id', models.IntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deprecated', models.BooleanField(default=False, help_text='Is this a deprecated group?')),
            ],
            options={
                'verbose_name': 'Molnix Tag Group',
                'verbose_name_plural': 'Molnix Tag Groups',
            },
        ),
        migrations.AddField(
            model_name='molnixtag',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='deployments.molnixtaggroup'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='appraisal_received',
            field=models.BooleanField(default=False, verbose_name='appraisal received'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='gender',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='emergencyproject',
            name='reporting_ns_contact_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NS Contact Information: Email'),
        ),
        migrations.AlterField(
            model_name='emergencyproject',
            name='reporting_ns_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NS Contact Information: Name'),
        ),
        migrations.AlterField(
            model_name='emergencyproject',
            name='reporting_ns_contact_role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NS Contact Information: Role'),
        ),
        migrations.AlterField(
            model_name='emergencyproject',
            name='visibility',
            field=models.CharField(choices=[('logged_in_user', 'RCRC Movement'), ('ifrc_only', 'IFRC Secretariat'), ('public', 'Public'), ('ifrc_ns', 'IFRC and NS')], default='public', max_length=32, verbose_name='visibility'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('logged_in_user', 'RCRC Movement'), ('ifrc_only', 'IFRC Secretariat'), ('public', 'Public'), ('ifrc_ns', 'IFRC and NS')], default='public', max_length=64, verbose_name='visibility'),
        ),
        migrations.AlterField(
            model_name='emergencyproject',
            name='districts',
            field=models.ManyToManyField(blank=True, related_name='+', to='api.district', verbose_name='Districts'),
        ),
        migrations.AddField(
            model_name='sectortag',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='sectortag',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='sectortag',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='sectortag',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='sectortag',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='sectortag',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.CreateModel(
            name='ERUReadinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'IT & Telecom'), (2, 'Logistics'), (3, 'RCRC Emergency Hospital'), (4, 'RCRC Emergency Clinic'), (5, 'Relief'), (6, 'WASH M15'), (7, 'WASH MSM20'), (8, 'WASH M40'), (9, 'Water Supply and rehabilitation'), (10, 'Household Water Treatment and safe storage'), (11, 'Cholera Case management at Community level'), (12, 'Safe and Dignified Burials'), (13, 'Community Based Surveillance'), (17, 'Outpatient Department (OPD) Module'), (18, 'MHPSS'), (19, 'Operations Support HUB')], verbose_name='ERU type')),
                ('equipment_readiness', models.IntegerField(choices=[(1, 'Ready'), (2, 'Partial capacity'), (3, 'No capacity')], verbose_name='equipment readiness')),
                ('people_readiness', models.IntegerField(choices=[(1, 'Ready'), (2, 'Partial capacity'), (3, 'No capacity')], verbose_name='people readiness')),
                ('funding_readiness', models.IntegerField(choices=[(1, 'Ready'), (2, 'Partial capacity'), (3, 'No capacity')], verbose_name='funding readiness')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'ERU Readiness Type',
                'verbose_name_plural': 'ERU Readiness Types',
            },
        ),
        migrations.AlterModelOptions(
            name='erureadiness',
            options={'ordering': ('updated_at', 'eru_owner'), 'verbose_name': 'ERU Readiness', 'verbose_name_plural': 'ERU Readiness'},
        ),
        migrations.RemoveField(
            model_name='erureadiness',
            name='ERU_type',
        ),
        migrations.RemoveField(
            model_name='erureadiness',
            name='is_equipment',
        ),
        migrations.RemoveField(
            model_name='erureadiness',
            name='is_personnel',
        ),
        migrations.RemoveField(
            model_name='erureadiness',
            name='national_society',
        ),
        migrations.AddField(
            model_name='erureadiness',
            name='eru_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deployments.eruowner', verbose_name='national society'),
        ),
        migrations.AddField(
            model_name='erureadiness',
            name='eru_types',
            field=models.ManyToManyField(blank=True, to='deployments.erureadinesstype', verbose_name='ERU types with readiness'),
        ),
        migrations.AlterField(
            model_name='eru',
            name='type',
            field=models.IntegerField(choices=[(1, 'IT & Telecom'), (2, 'Logistics'), (3, 'RCRC Emergency Hospital'), (4, 'RCRC Emergency Clinic'), (5, 'Relief'), (6, 'WASH M15'), (7, 'WASH MSM20'), (8, 'WASH M40'), (9, 'Water Supply and rehabilitation'), (10, 'Household Water Treatment and safe storage'), (11, 'Cholera Case management at Community level'), (12, 'Safe and Dignified Burials'), (13, 'Community Based Surveillance'), (17, 'Outpatient Department (OPD) Module'), (18, 'MHPSS'), (19, 'Operations Support HUB')], default=0, help_text='<a target="_blank" href="/api/v2/erutype">Key/value pairs</a>', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='sector',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='sector',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='sector',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='sector',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='sector',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='sector',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.CreateModel(
            name='MolnixAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molnix_id', models.BigIntegerField(unique=True)),
                ('target_id', models.BigIntegerField()),
                ('deployment_molnix_id', models.BigIntegerField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=64, null=True)),
                ('appraisers_count', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('deployment_country_id', models.IntegerField(blank=True, null=True)),
                ('deployment_start', models.DateTimeField(blank=True, null=True)),
                ('deployment_end', models.DateTimeField(blank=True, null=True)),
                ('deployment_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sending_organization_id', models.BigIntegerField(blank=True, null=True)),
                ('receiving_organization_id', models.BigIntegerField(blank=True, null=True)),
                ('deployment_tags_json', models.JSONField(blank=True, null=True)),
                ('competencies_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='molnix_appraisals', to='deployments.personnel')),
            ],
            options={
                'verbose_name': 'Molnix Appraisal',
                'verbose_name_plural': 'Molnix Appraisals',
            },
        ),
        migrations.CreateModel(
            name='RrmsEventParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField()),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person_id', models.BigIntegerField()),
                ('event_person_role', models.CharField(blank=True, max_length=128, null=True)),
                ('event_type', models.CharField(blank=True, max_length=128, null=True)),
                ('event_scale_type', models.CharField(blank=True, max_length=128, null=True)),
                ('event_from', models.DateTimeField(blank=True, null=True)),
                ('event_to', models.DateTimeField(blank=True, null=True)),
                ('participant_start', models.DateTimeField(blank=True, null=True)),
                ('participant_end', models.DateTimeField(blank=True, null=True)),
                ('requested', models.BooleanField(blank=True, null=True)),
                ('event_organization_id', models.BigIntegerField(blank=True, null=True)),
                ('event_organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('tags_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'RRMS Event Participation',
                'verbose_name_plural': 'RRMS Event Participation',
                'db_table': 'rrms_event_participation',
                'indexes': [models.Index(fields=['event_id'], name='rrms_event_id_idx'), models.Index(fields=['person_id'], name='rrms_event_person_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_id', 'person_id', 'event_person_role'), name='rrms_event_person_role_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RrmsPersonSnapshot',
            fields=[
                ('person_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('person_status', models.CharField(blank=True, max_length=32, null=True)),
                ('sex', models.CharField(blank=True, max_length=32, null=True)),
                ('current_availability', models.CharField(blank=True, max_length=64, null=True)),
                ('outofscope', models.BooleanField(blank=True, null=True)),
                ('organization_id', models.BigIntegerField(blank=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('roles_json', models.JSONField(blank=True, null=True)),
                ('languages_json', models.JSONField(blank=True, null=True)),
                ('tags_json', models.JSONField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rrms_person_snapshots', to='deployments.personnel')),
            ],
            options={
                'verbose_name': 'RRMS Person Snapshot',
                'verbose_name_plural': 'RRMS Person Snapshots',
                'db_table': 'rrms_person_snapshot',
                'indexes': [models.Index(fields=['organization_id'], name='rrms_person_org_idx'), models.Index(fields=['personnel'], name='rrms_personnel_idx')],
            },
        ),
        migrations.CreateModel(
            name='MolnixAppraiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molnix_id', models.BigIntegerField(unique=True)),
                ('appraisal_molnix_id', models.BigIntegerField()),
                ('appraiser_type', models.CharField(blank=True, max_length=32, null=True)),
                ('person_id', models.BigIntegerField(blank=True, null=True)),
                ('required', models.BooleanField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('appraisal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisers', to='deployments.molnixappraisal')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='molnix_appraisers', to='deployments.personnel')),
            ],
            options={
                'verbose_name': 'Molnix Appraiser',
                'verbose_name_plural': 'Molnix Appraisers',
                'indexes': [models.Index(fields=['appraisal_molnix_id'], name='molnix_appr_mol_idx'), models.Index(fields=['appraisal'], name='molnix_appr_idx'), models.Index(fields=['person_id'], name='molnix_appr_person_idx'), models.Index(fields=['personnel'], name='molnix_appr_personnel_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='molnixappraisal',
            index=models.Index(fields=['target_id'], name='molnix_app_target_idx'),
        ),
        migrations.AddIndex(
            model_name='molnixappraisal',
            index=models.Index(fields=['personnel'], name='molnix_app_personnel_idx'),
        ),
        migrations.AddIndex(
            model_name='molnixappraisal',
            index=models.Index(fields=['updated_at'], name='molnix_app_updated_idx'),
        ),
        migrations.AddField(
            model_name='erureadinesstype',
            name='ns_contribution',
            field=models.IntegerField(choices=[(1, 'Confirm that you have the capacity to hold this type of ERU'), (2, 'Confirm that you have the capacity to support this type of ERU')], default=1, verbose_name='National Society Contribution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='molnixappraisal',
            name='appraised_person_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='molnixappraisal',
            index=models.Index(fields=['appraised_person_id'], name='molnix_appraised_person_idx'),
        ),
        migrations.RemoveConstraint(
            model_name='rrmseventparticipation',
            name='rrms_event_person_role_uniq',
        ),
        migrations.AlterField(
            model_name='eru',
            name='type',
            field=models.IntegerField(choices=[(1, 'IT & Telecom'), (2, 'Logistics'), (3, 'RCRC Emergency Hospital'), (4, 'RCRC Emergency Clinic'), (5, 'Relief'), (6, 'WASH M15'), (7, 'WASH MSM20'), (8, 'WASH M40'), (9, 'Water Supply and rehabilitation'), (10, 'Household Water Treatment and safe storage'), (11, 'Cholera Case management at Community level'), (12, 'Safe and Dignified Burials'), (13, 'Community Based Surveillance'), (17, 'Outpatient Department (OPD) Module'), (18, 'MHPSS'), (19, 'Operations Support HUB'), (20, 'Public Health'), (21, 'Public Health IPC - Infection Prevention and Control'), (22, 'Clinical Advances Team')], default=0, help_text='<a target="_blank" href="/api/v2/erutype">Key/value pairs</a>', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='erureadinesstype',
            name='type',
            field=models.IntegerField(choices=[(1, 'IT & Telecom'), (2, 'Logistics'), (3, 'RCRC Emergency Hospital'), (4, 'RCRC Emergency Clinic'), (5, 'Relief'), (6, 'WASH M15'), (7, 'WASH MSM20'), (8, 'WASH M40'), (9, 'Water Supply and rehabilitation'), (10, 'Household Water Treatment and safe storage'), (11, 'Cholera Case management at Community level'), (12, 'Safe and Dignified Burials'), (13, 'Community Based Surveillance'), (17, 'Outpatient Department (OPD) Module'), (18, 'MHPSS'), (19, 'Operations Support HUB'), (20, 'Public Health'), (21, 'Public Health IPC - Infection Prevention and Control'), (22, 'Clinical Advances Team')], verbose_name='ERU type'),
        ),
        migrations.AlterField(
            model_name='emergencyproject',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_projects', to='api.event', verbose_name='Event'),
        ),
    ]
