# Generated by Django 4.2.15 on 2024-09-18 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_squashed_0213_merge_20240807_1001"),
        ("deployments", "0036_auto_20201118_0812_squashed_0089_alter_emergencyproject_districts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencyproject",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="api.country", verbose_name="Country"
            ),
        ),
    ]
