# Generated by Django 4.2.19 on 2025-05-13 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0090_sectortag_title_ar_sectortag_title_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eru",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "Basecamp"),
                    (1, "IT & Telecom"),
                    (2, "Logistics"),
                    (3, "RCRC Emergency Hospital"),
                    (4, "RCRC Emergency Clinic"),
                    (5, "Relief"),
                    (6, "WASH M15"),
                    (7, "WASH MSM20"),
                    (8, "WASH M40"),
                    (9, "Water Supply and rehabilitation"),
                    (10, "Household Water Treatment and safe storage"),
                    (11, "Cholera Case management at Community level"),
                    (12, "Safe and Dignified Burials"),
                    (13, "Community Based Surveillance"),
                    (14, "Base Camp – S"),
                    (15, "Base Camp – M"),
                    (16, "Base Camp – L"),
                    (17, "Outpatient Department (OPD) Module"),
                    (18, "MHPSS"),
                ],
                default=0,
                help_text='<a target="_blank" href="/api/v2/erutype">Key/value pairs</a>',
                verbose_name="type",
            ),
        ),
        migrations.CreateModel(
            name="ERUReadinessType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Basecamp"),
                            (1, "IT & Telecom"),
                            (2, "Logistics"),
                            (3, "RCRC Emergency Hospital"),
                            (4, "RCRC Emergency Clinic"),
                            (5, "Relief"),
                            (6, "WASH M15"),
                            (7, "WASH MSM20"),
                            (8, "WASH M40"),
                            (9, "Water Supply and rehabilitation"),
                            (10, "Household Water Treatment and safe storage"),
                            (11, "Cholera Case management at Community level"),
                            (12, "Safe and Dignified Burials"),
                            (13, "Community Based Surveillance"),
                            (14, "Base Camp – S"),
                            (15, "Base Camp – M"),
                            (16, "Base Camp – L"),
                            (17, "Outpatient Department (OPD) Module"),
                            (18, "MHPSS"),
                        ],
                        verbose_name="ERU type",
                    ),
                ),
                (
                    "equipment_readiness",
                    models.IntegerField(
                        choices=[(1, "Ready"), (2, "Partial capacity"), (3, "No capacity")], verbose_name="equipment readiness"
                    ),
                ),
                (
                    "people_readiness",
                    models.IntegerField(
                        choices=[(1, "Ready"), (2, "Partial capacity"), (3, "No capacity")], verbose_name="people readiness"
                    ),
                ),
                (
                    "funding_readiness",
                    models.IntegerField(
                        choices=[(1, "Ready"), (2, "Partial capacity"), (3, "No capacity")], verbose_name="funding readiness"
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True, verbose_name="comment")),
            ],
            options={
                "verbose_name": "ERU Readiness Type",
                "verbose_name_plural": "ERU Readiness Types",
            },
        ),
        migrations.AlterModelOptions(
            name="erureadiness",
            options={
                "ordering": ("updated_at", "eru_owner"),
                "verbose_name": "ERU Readiness",
                "verbose_name_plural": "ERU Readiness",
            },
        ),
        migrations.RemoveField(
            model_name="erureadiness",
            name="ERU_type",
        ),
        migrations.RemoveField(
            model_name="erureadiness",
            name="is_equipment",
        ),
        migrations.RemoveField(
            model_name="erureadiness",
            name="is_personnel",
        ),
        migrations.RemoveField(
            model_name="erureadiness",
            name="national_society",
        ),
        migrations.AddField(
            model_name="erureadiness",
            name="eru_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deployments.eruowner",
                verbose_name="national society",
            ),
        ),
        migrations.AddField(
            model_name="erureadiness",
            name="eru_types",
            field=models.ManyToManyField(blank=True, to="deployments.erureadinesstype", verbose_name="ERU types with readiness"),
        ),
    ]
