# Generated by Django 4.2.19 on 2025-11-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0091_erureadinesstype_alter_erureadiness_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eru',
            name='type',
            field=models.IntegerField(choices=[(1, 'IT & Telecom'), (2, 'Logistics'), (3, 'RCRC Emergency Hospital'), (4, 'RCRC Emergency Clinic'), (5, 'Relief'), (6, 'WASH M15'), (7, 'WASH MSM20'), (8, 'WASH M40'), (9, 'Water Supply and rehabilitation'), (10, 'Household Water Treatment and safe storage'), (11, 'Cholera Case management at Community level'), (12, 'Safe and Dignified Burials'), (13, 'Community Based Surveillance'), (17, 'Outpatient Department (OPD) Module'), (18, 'MHPSS'), (19, 'Operations Support HUB')], default=0, help_text='<a target="_blank" href="/api/v2/erutype">Key/value pairs</a>', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='erureadinesstype',
            name='type',
            field=models.IntegerField(choices=[(1, 'IT & Telecom'), (2, 'Logistics'), (3, 'RCRC Emergency Hospital'), (4, 'RCRC Emergency Clinic'), (5, 'Relief'), (6, 'WASH M15'), (7, 'WASH MSM20'), (8, 'WASH M40'), (9, 'Water Supply and rehabilitation'), (10, 'Household Water Treatment and safe storage'), (11, 'Cholera Case management at Community level'), (12, 'Safe and Dignified Burials'), (13, 'Community Based Surveillance'), (17, 'Outpatient Department (OPD) Module'), (18, 'MHPSS'), (19, 'Operations Support HUB')], verbose_name='ERU type'),
        ),
    ]
