# Generated by Django 4.2.19 on 2025-04-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0091_erureadinesstype_alter_erureadiness_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="erureadinesstype",
            old_name="equipment_readiness",
            new_name="equipment",
        ),
        migrations.RenameField(
            model_name="erureadinesstype",
            old_name="funding_readiness",
            new_name="funding",
        ),
        migrations.RemoveField(
            model_name="erureadinesstype",
            name="has_capacity_to_lead",
        ),
        migrations.RemoveField(
            model_name="erureadinesstype",
            name="has_capacity_to_support",
        ),
        migrations.RenameField(
            model_name="erureadinesstype",
            old_name="people_readiness",
            new_name="people",
        ),
        migrations.AlterField(
            model_name="eru",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "Basecamp"),
                    (1, "IT & Telecom"),
                    (2, "Logistics"),
                    (3, "RCRC Emergency Hospital"),
                    (4, "RCRC Emergency Clinic"),
                    (5, "Relief"),
                    (6, "WASH M15"),
                    (7, "WASH MSM20"),
                    (8, "WASH M40"),
                    (9, "Water Supply and rehabilitation"),
                    (10, "Household Water Treatment and safe storage"),
                    (11, "Cholera Case management at Community level"),
                    (12, "Safe and Dignified Burials"),
                    (13, "Community Based Surveillance"),
                    (14, "Base Camp – S"),
                    (15, "Base Camp – M"),
                    (16, "Base Camp – L"),
                    (17, "Outpatient Department (OPD) Module"),
                    (18, "MHPSS"),
                ],
                default=0,
                help_text='<a target="_blank" href="/api/v2/erutype">Key/value pairs</a>',
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="erureadinesstype",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "Basecamp"),
                    (1, "IT & Telecom"),
                    (2, "Logistics"),
                    (3, "RCRC Emergency Hospital"),
                    (4, "RCRC Emergency Clinic"),
                    (5, "Relief"),
                    (6, "WASH M15"),
                    (7, "WASH MSM20"),
                    (8, "WASH M40"),
                    (9, "Water Supply and rehabilitation"),
                    (10, "Household Water Treatment and safe storage"),
                    (11, "Cholera Case management at Community level"),
                    (12, "Safe and Dignified Burials"),
                    (13, "Community Based Surveillance"),
                    (14, "Base Camp – S"),
                    (15, "Base Camp – M"),
                    (16, "Base Camp – L"),
                    (17, "Outpatient Department (OPD) Module"),
                    (18, "MHPSS"),
                ],
                verbose_name="ERU type",
            ),
        ),
        migrations.AlterField(
            model_name="erureadinesstype",
            name="equipment",
            field=models.IntegerField(
                choices=[(1, "Ready"), (2, "Partial capacity"), (3, "No capacity")], verbose_name="equipment"
            ),
        ),
        migrations.AlterField(
            model_name="erureadinesstype",
            name="funding",
            field=models.IntegerField(
                choices=[(1, "Ready"), (2, "Partial capacity"), (3, "No capacity")], verbose_name="funding"
            ),
        ),
        migrations.AlterField(
            model_name="erureadinesstype",
            name="people",
            field=models.IntegerField(choices=[(1, "Ready"), (2, "Partial capacity"), (3, "No capacity")], verbose_name="people"),
        ),
    ]
