# Generated by Django 4.2.19 on 2025-04-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0092_remove_erureadinesstype_equipment_readiness_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erureadinesstype",
            name="equipment",
            field=models.IntegerField(
                choices=[(1, "Ready"), (2, "Partial capacity"), (3, "No capacity")], verbose_name="equipment"
            ),
        ),
        migrations.AlterField(
            model_name="erureadinesstype",
            name="funding",
            field=models.IntegerField(
                choices=[(1, "Ready"), (2, "Partial capacity"), (3, "No capacity")], verbose_name="funding"
            ),
        ),
        migrations.AlterField(
            model_name="erureadinesstype",
            name="people",
            field=models.IntegerField(choices=[(1, "Ready"), (2, "Partial capacity"), (3, "No capacity")], verbose_name="people"),
        ),
    ]
