# Generated by Django 4.2.29 on 2026-04-10 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0093_sector_title_ar_sector_title_en_sector_title_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MolnixAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molnix_id', models.BigIntegerField(unique=True)),
                ('target_id', models.BigIntegerField()),
                ('deployment_molnix_id', models.BigIntegerField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=64, null=True)),
                ('appraisers_count', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('deployment_country_id', models.IntegerField(blank=True, null=True)),
                ('deployment_start', models.DateTimeField(blank=True, null=True)),
                ('deployment_end', models.DateTimeField(blank=True, null=True)),
                ('deployment_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sending_organization_id', models.BigIntegerField(blank=True, null=True)),
                ('receiving_organization_id', models.BigIntegerField(blank=True, null=True)),
                ('deployment_tags_json', models.JSONField(blank=True, null=True)),
                ('competencies_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Molnix Appraisal',
                'verbose_name_plural': 'Molnix Appraisals',
            },
        ),
        migrations.CreateModel(
            name='MolnixAppraiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molnix_id', models.BigIntegerField(unique=True)),
                ('appraisal_molnix_id', models.BigIntegerField()),
                ('appraiser_type', models.CharField(blank=True, max_length=32, null=True)),
                ('person_id', models.BigIntegerField(blank=True, null=True)),
                ('required', models.BooleanField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Molnix Appraiser',
                'verbose_name_plural': 'Molnix Appraisers',
            },
        ),
        migrations.CreateModel(
            name='RrmsPersonSnapshot',
            fields=[
                ('person_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('person_status', models.CharField(blank=True, max_length=32, null=True)),
                ('sex', models.CharField(blank=True, max_length=32, null=True)),
                ('current_availability', models.CharField(blank=True, max_length=64, null=True)),
                ('outofscope', models.BooleanField(blank=True, null=True)),
                ('organization_id', models.BigIntegerField(blank=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('roles_json', models.JSONField(blank=True, null=True)),
                ('languages_json', models.JSONField(blank=True, null=True)),
                ('tags_json', models.JSONField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rrms_person_snapshots', to='deployments.personnel')),
            ],
            options={
                'verbose_name': 'RRMS Person Snapshot',
                'verbose_name_plural': 'RRMS Person Snapshots',
                'db_table': 'rrms_person_snapshot',
            },
        ),
        migrations.CreateModel(
            name='RrmsEventParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField()),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person_id', models.BigIntegerField()),
                ('event_person_role', models.CharField(blank=True, max_length=128, null=True)),
                ('event_type', models.CharField(blank=True, max_length=128, null=True)),
                ('event_scale_type', models.CharField(blank=True, max_length=128, null=True)),
                ('event_from', models.DateTimeField(blank=True, null=True)),
                ('event_to', models.DateTimeField(blank=True, null=True)),
                ('participant_start', models.DateTimeField(blank=True, null=True)),
                ('participant_end', models.DateTimeField(blank=True, null=True)),
                ('requested', models.BooleanField(blank=True, null=True)),
                ('event_organization_id', models.BigIntegerField(blank=True, null=True)),
                ('event_organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('tags_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'RRMS Event Participation',
                'verbose_name_plural': 'RRMS Event Participation',
                'db_table': 'rrms_event_participation',
                'indexes': [models.Index(fields=['event_id'], name='rrms_event_id_idx'), models.Index(fields=['person_id'], name='rrms_event_person_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='rrmseventparticipation',
            constraint=models.UniqueConstraint(fields=('event_id', 'person_id', 'event_person_role'), name='rrms_event_person_role_uniq'),
        ),
        migrations.AddField(
            model_name='molnixappraiser',
            name='appraisal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisers', to='deployments.molnixappraisal'),
        ),
        migrations.AddField(
            model_name='molnixappraiser',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='molnix_appraisers', to='deployments.personnel'),
        ),
        migrations.AddField(
            model_name='molnixappraisal',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='molnix_appraisals', to='deployments.personnel'),
        ),
        migrations.AddIndex(
            model_name='rrmspersonsnapshot',
            index=models.Index(fields=['organization_id'], name='rrms_person_org_idx'),
        ),
        migrations.AddIndex(
            model_name='rrmspersonsnapshot',
            index=models.Index(fields=['personnel'], name='rrms_personnel_idx'),
        ),
        migrations.AddIndex(
            model_name='molnixappraiser',
            index=models.Index(fields=['appraisal_molnix_id'], name='molnix_appr_mol_idx'),
        ),
        migrations.AddIndex(
            model_name='molnixappraiser',
            index=models.Index(fields=['appraisal'], name='molnix_appr_idx'),
        ),
        migrations.AddIndex(
            model_name='molnixappraiser',
            index=models.Index(fields=['person_id'], name='molnix_appr_person_idx'),
        ),
        migrations.AddIndex(
            model_name='molnixappraiser',
            index=models.Index(fields=['personnel'], name='molnix_appr_personnel_idx'),
        ),
        migrations.AddIndex(
            model_name='molnixappraisal',
            index=models.Index(fields=['target_id'], name='molnix_app_target_idx'),
        ),
        migrations.AddIndex(
            model_name='molnixappraisal',
            index=models.Index(fields=['personnel'], name='molnix_app_personnel_idx'),
        ),
        migrations.AddIndex(
            model_name='molnixappraisal',
            index=models.Index(fields=['updated_at'], name='molnix_app_updated_idx'),
        ),
    ]
