# Generated by Django 4.2.29 on 2026-03-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0093_sector_title_ar_sector_title_en_sector_title_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erureadinesstype',
            name='ns_contribution',
            field=models.IntegerField(choices=[(1, 'Confirm that you have the capacity to hold this type of ERU'), (2, 'Confirm that you have the capacity to support this type of ERU')], default=0, verbose_name='National Society Contribution'),
            preserve_default=False,
        ),
    ]
