# Generated by Django 4.2.30 on 2026-05-14 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0232_remove_event_auto_generated_source_event_source_and_more'),
        ('deployments', '0094_erureadinesstype_ns_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyproject',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_projects', to='api.event', verbose_name='Event'),
        ),
    ]
