# Generated by Django 4.2.29 on 2026-05-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0094_erureadinesstype_ns_contribution"),
        ("deployments", "0094_molnixappraisal_molnixappraiser_rrmspersonsnapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="molnixappraisal",
            name="appraised_person_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="molnixappraisal",
            index=models.Index(fields=["appraised_person_id"], name="molnix_appraised_person_idx"),
        ),
        migrations.RemoveConstraint(
            model_name="rrmseventparticipation",
            name="rrms_event_person_role_uniq",
        ),
    ]
