# Generated by Django 5.2.16 on 2026-08-25 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0232_remove_event_auto_generated_source_event_source_and_more'),
        ('deployments', '0096_alter_eru_type_alter_erureadinesstype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyproject',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_projects', to='api.event', verbose_name='Event'),
        ),
    ]
