{{- if .Values.azure.aksSecretsProviderAvailable -}}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "ifrcgo-helm.fullname" . }}-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.azure.keyvault.clientId }}
    keyvaultName: {{ .Values.azure.keyvault.name }}
    tenantId: {{ .Values.azure.keyvault.tenantId }}
    objects: |
      array:
    {{- range $name, $value := .Values.secrets }}
        - |
          objectName: {{ $name | upper | replace "_" "-" }}
          objectType: secret
    {{- end }}
  secretObjects:
    - secretName: {{ include "ifrcgo-helm.secretname" . }}
      type: Opaque
      data:
      {{- range $name, $value := .Values.secrets }}
        - objectName: {{ $name | replace "_" "-" | upper }}
          key: {{ $name }}
      {{- end }}

{{- end }}
