kind: Secret
apiVersion: v1
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-api-secret
  labels:
    component: api-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "{{ .Values.env.DJANGO_SECRET_KEY }}"
  DJANGO_DB_NAME: "{{ .Values.env.DJANGO_DB_NAME }}"
  DJANGO_DB_USER: "{{ .Values.env.DJANGO_DB_USER }}"
  DJANGO_DB_PASS: "{{ .Values.env.DJANGO_DB_PASS }}"
  DJANGO_DB_HOST: "{{ .Values.env.DJANGO_DB_HOST }}"
  DJANGO_DB_PORT: "{{ .Values.env.DJANGO_DB_PORT }}"
  AZURE_STORAGE_ACCOUNT: "{{ .Values.env.AZURE_STORAGE_ACCOUNT }}"
  AZURE_STORAGE_KEY: "{{ .Values.env.AZURE_STORAGE_KEY }}"
  EMAIL_API_ENDPOINT: "{{ .Values.env.EMAIL_API_ENDPOINT }}"
  EMAIL_HOST: "{{ .Values.env.EMAIL_HOST }}"
  EMAIL_PORT: "{{ .Values.env.EMAIL_PORT }}"
  EMAIL_USER: "{{ .Values.env.EMAIL_USER }}"
  EMAIL_PASS: "{{ .Values.env.EMAIL_PASS }}"
  TEST_EMAILS: "{{ .Values.env.TEST_EMAILS }}"
  AWS_TRANSLATE_ACCESS_KEY: "{{ .Values.env.AWS_TRANSLATE_ACCESS_KEY }}"
  AWS_TRANSLATE_SECRET_KEY: "{{ .Values.env.AWS_TRANSLATE_SECRET_KEY }}"
  AWS_TRANSLATE_REGION: "{{ .Values.env.AWS_TRANSLATE_REGION }}"
  MOLNIX_API_BASE: "{{ .Values.env.MOLNIX_API_BASE }}"
  MOLNIX_USERNAME: "{{ .Values.env.MOLNIX_USERNAME }}"
  MOLNIX_PASSWORD: "{{ .Values.env.MOLNIX_PASSWORD }}"
  ERP_API_ENDPOINT: "{{ .Values.env.ERP_API_ENDPOINT }}"
  ERP_API_SUBSCRIPTION_KEY: "{{ .Values.env.ERP_API_SUBSCRIPTION_KEY }}"
  FDRS_CREDENTIAL: "{{ .Values.env.FDRS_CREDENTIAL }}"
  HPC_CREDENTIAL: "{{ .Values.env.HPC_CREDENTIAL }}"
  APPLICATION_INSIGHTS_INSTRUMENTATION_KEY: "{{ .Values.env.APPLICATION_INSIGHTS_INSTRUMENTATION_KEY }}"
  ELASTIC_SEARCH_HOST: "{{ .Values.env.ELASTIC_SEARCH_HOST }}"
  GO_FTPHOST: "{{ .Values.env.GO_FTPHOST }}"
  GO_FTPUSER: "{{ .Values.env.GO_FTPUSER }}"
  GO_FTPPASS: "{{ .Values.env.GO_FTPPASS }}"
  APPEALS_USER: "{{ .Values.env.APPEALS_USER }}"
  APPEALS_PASS: "{{ .Values.env.APPEALS_PASS }}"
  GO_DBPASS: "{{ .Values.env.GO_DBPASS }}"
  IFRC_TRANSLATION_HEADER_API_KEY: "{{ .Values.env.IFRC_TRANSLATION_HEADER_API_KEY }}"
  FDRS_APIKEY : "{{ .Values.env.FDRS_APIKEY}}"
  NS_CONTACT_USERNAME: "{{ .Values.env.NS_CONTACT_USERNAME}}"
  NS_CONTACT_PASSWORD: "{{ .Values.env.NS_CONTACT_PASSWORD}}"
  ACAPS_API_TOKEN: "{{ .Values.env.ACAPS_API_TOKEN}}"
  NS_DOCUMENT_API_KEY: "{{ .Values.env.NS_DOCUMENT_API_KEY}}"
  NS_INITIATIVES_API_KEY: "{{ .Values.env.NS_INITIATIVES_API_KEY}}"
  NS_INITIATIVES_API_TOKEN: "{{ .Values.env.NS_INITIATIVES_API_TOKEN}}"
  JWT_PRIVATE_KEY_BASE64_ENCODED: "{{ .Values.env.JWT_PRIVATE_KEY_BASE64_ENCODED}}"
  JWT_PUBLIC_KEY_BASE64_ENCODED: "{{ .Values.env.JWT_PUBLIC_KEY_BASE64_ENCODED}}"
  JWT_EXPIRE_TIMESTAMP_DAYS: "{{ .Values.env.JWT_EXPIRE_TIMESTAMP_DAYS}}"
  AZURE_OPENAI_DEPLOYMENT_NAME: "{{ .Values.env.AZURE_OPENAI_DEPLOYMENT_NAME}}"
  AZURE_OPENAI_ENDPOINT: "{{ .Values.env.AZURE_OPENAI_ENDPOINT}}"
  AZURE_OPENAI_API_KEY: "{{ .Values.env.AZURE_OPENAI_API_KEY}}"

  # Additional secrets
  {{- range $name, $value := .Values.secretsAdditional }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}