services:
    deploy:
      container_name: go-api-deploy
      image: go-api-deploy
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        # For Terraform
        - TF_VAR_domain='ifrcgo-test.ds.io'
        - TF_VAR_username=${USER}
        - TF_VAR_environment=${environment}
        - TF_VAR_subscriptionId=${subscriptionId}
        - TF_VAR_DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        - TF_VAR_DJANGO_DB_NAME=${DJANGO_DB_NAME}
        - TF_VAR_DJANGO_DB_USER=${DJANGO_DB_USER}
        - TF_VAR_DJANGO_DB_PASS=${DJANGO_DB_PASS}
        - TF_VAR_DJANGO_DB_HOST=${DJANGO_DB_HOST}
        - TF_VAR_DJANGO_DB_PORT=${DJANGO_DB_PORT}
        - TF_VAR_AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
        - TF_VAR_AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
        - TF_VAR_EMAIL_API_ENDPOINT=${EMAIL_API_ENDPOINT}
        - TF_VAR_EMAIL_HOST=${EMAIL_HOST}
        - TF_VAR_EMAIL_PORT=${EMAIL_PORT}
        - TF_VAR_EMAIL_USER=${EMAIL_USER}
        - TF_VAR_EMAIL_PASS=${EMAIL_PASS}
        - TF_VAR_TEST_EMAILS=${TEST_EMAILS}
        - TF_VAR_AWS_TRANSLATE_ACCESS_KEY=${AWS_TRANSLATE_ACCESS_KEY}
        - TF_VAR_AWS_TRANSLATE_SECRET_KEY=${AWS_TRANSLATE_SECRET_KEY}
        - TF_VAR_AWS_TRANSLATE_REGION=${AWS_TRANSLATE_REGION}
        - TF_VAR_CELERY_REDIS_URL=${CELERY_REDIS_URL}
        - TF_VAR_MOLNIX_API_BASE=${MOLNIX_API_BASE}
        - TF_VAR_MOLNIX_USERNAME=${MOLNIX_USERNAME}
        - TF_VAR_MOLNIX_PASSWORD=${MOLNIX_PASSWORD}
        - TF_VAR_ERP_API_ENDPOINT=${ERP_API_ENDPOINT}
        - TF_VAR_ERP_API_SUBSCRIPTION_KEY=${ERP_API_SUBSCRIPTION_KEY}
        - TF_VAR_FDRS_APIKEY=${FDRS_APIKEY}
        - TF_VAR_FDRS_CREDENTIAL=${FDRS_CREDENTIAL}
        - TF_VAR_HPC_CREDENTIAL=${HPC_CREDENTIAL}
        - TF_VAR_APPLICATION_INSIGHTS_INSTRUMENTATION_KEY=${APPLICATION_INSIGHTS_INSTRUMENTATION_KEY}
        - TF_VAR_ELASTIC_SEARCH_HOST=${ELASTIC_SEARCH_HOST}
        - TF_VAR_GO_FTPHOST=${GO_FTPHOST}
        - TF_VAR_GO_FTPUSER=${GO_FTPUSER}
        - TF_VAR_GO_FTPPASS=${GO_FTPPASS}
        - TF_VAR_GO_DBPASS=${GO_DBPASS}
        - TF_VAR_DJANGO_DEBUG=${DJANGO_DEBUG}
        - TF_VAR_DOCKER_HOST_IP=${DJANGO_HOST_IP}
        - TF_VAR_DJANGO_ADDITIONAL_ALLOWED_HOSTS=${DJANGO_ADDITIONAL_ALLOWED_HOSTS}
        - TF_VAR_GO_ENVIRONMENT=${environment}
        - TF_VAR_API_FQDN='ifrcgo-test.ds.io'
        - TF_VAR_FRONTEND_URL=${FRONTEND_URL}
        - TF_VAR_DEBUG_EMAIL=${DEBUG_EMAIL}
        - ARM_SUBSCRIPTION_ID=${subscriptionId}
        - ARM_TENANT_ID=${tenantId}
        - ARM_CLIENT_ID=${servicePrincipalId}
        - ARM_CLIENT_SECRET=${servicePrincipalKey}
        - ARM_ACCESS_KEY=${storageAccessKey}
  
        # For Azure CLI
        - AZURE_TENANT_ID=${tenantId}
        - AZURE_CLIENT_ID=${servicePrincipalId}
        - AZURE_CLIENT_SECRET=${servicePrincipalKey}
  
        # For deployment
      volumes:
        - ./:/opt/src