{{- if .Values.celery.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-celery
  labels:
    component: celery-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "ifrcgo-helm.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-celery
  template:
    metadata:
      labels:
        app: {{ template "ifrcgo-helm.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-celery
    spec:
      containers:
        - name: {{ .Chart.Name }}-celery
          image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
          command: ["python", "/home/ifrc/go-api/manage.py", "run_celery_dev"] #FIXME: How to run for prod mode? 
          # args: ["-c", "while true; do npx knex migrate:latest && npm run prod; sleep 10;done"]
          resources:
            requests:
              cpu: {{ .Values.celery.resources.requests.cpu }}
              memory: {{ .Values.celery.resources.requests.memory }}
            limits:
              cpu: {{ .Values.celery.resources.limits.cpu }}
              memory: {{ .Values.celery.resources.limits.memory }}
          envFrom:
            - secretRef:
                name: {{ template "ifrcgo-helm.fullname" . }}-api-secret
            - configMapRef:
                name: {{ template "ifrcgo-helm.fullname" . }}-api-configmap

{{- end }}
