{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-redis
  labels:
    app: {{ template "ifrcgo-helm.name" . }}
    component: redis-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: null

  selector:
    app: {{ template "ifrcgo-helm.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-redis
{{- end }}