# Generated by Django 4.2.26 on 2025-12-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0227_alter_country_nsi_risk_management_framework'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkAgreement',
            fields=[
                ('fa_number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='FA Number')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Supplier Name')),
                ('pa_type', models.CharField(choices=[('Global Services', 'Global Services'), ('Local Services', 'Local Services')], max_length=50, verbose_name='PA Type')),
                ('pa_bu_region_name', models.CharField(max_length=100, verbose_name='PA BU Region Name')),
                ('pa_bu_country_name', models.CharField(max_length=100, verbose_name='PA BU Country Name')),
                ('pa_effective_date', models.DateTimeField(verbose_name='PA Effective Date (FA Start Date)')),
                ('pa_expiration_date', models.DateTimeField(verbose_name='PA Expiration Date (FA End Date)')),
                ('pa_workflow_status', models.CharField(choices=[('NotSubmitted', 'Not Submitted'), ('Approved', 'Approved')], max_length=50, verbose_name='PA Workflow Status')),
                ('pa_status', models.CharField(choices=[('On hold', 'On Hold'), ('Effective', 'Effective')], max_length=50, verbose_name='PA Status')),
                ('pa_buyer_group_code', models.CharField(blank=True, max_length=50, verbose_name='PA Buyer Group Code')),
                ('fa_owner_name', models.CharField(max_length=100, verbose_name='FA Owner Name')),
                ('fa_geographical_coverage', models.CharField(choices=[('Global', 'Global'), ('Local', 'Local')], max_length=50, verbose_name='FA Geographical Coverage')),
                ('region_countries_covered', models.CharField(max_length=100, verbose_name='Region / Countries Covered')),
                ('item_type', models.CharField(max_length=100, verbose_name='Item Type')),
                ('item_category', models.CharField(max_length=100, verbose_name='Item Category')),
                ('item_service_description', models.CharField(max_length=255, verbose_name='Item / Service Short Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Framework Agreement',
                'verbose_name_plural': 'Framework Agreements',
            },
        ),
        migrations.CreateModel(
            name='FrameworkAgreementLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item_code', models.CharField(blank=True, max_length=100, verbose_name='PA Line Item Code')),
                ('product_type', models.CharField(blank=True, max_length=100, verbose_name='PA Line Product Type')),
                ('procurement_category', models.CharField(blank=True, max_length=100, verbose_name='PA Line Procurement Category')),
                ('line_item_name', models.CharField(blank=True, max_length=255, verbose_name='PA Line Item Name')),
                ('framework_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='api.frameworkagreement')),
            ],
            options={
                'verbose_name': 'Framework Agreement Line Item',
                'verbose_name_plural': 'Framework Agreement Line Items',
            },
        ),
        migrations.CreateModel(
            name='FrameworkAgreementCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country', to_field='iso', verbose_name='Country')),
                ('framework_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_countries', to='api.frameworkagreement')),
            ],
            options={
                'verbose_name': 'Framework Agreement Country',
                'verbose_name_plural': 'Framework Agreement Countries',
                'unique_together': {('framework_agreement', 'country')},
            },
        ),
    ]