# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot

snapshots = Snapshot()

snapshots["TestProjectAPI::test_global_project_api 1"] = {
    "ns_with_ongoing_activities": 2,
    "projects_per_programme_type": [
        {"count": 4, "programme_type": 0, "programme_type_display": "Bilateral"},
        {"count": 4, "programme_type": 1, "programme_type_display": "Multilateral"},
        {"count": 8, "programme_type": 2, "programme_type_display": "Domestic"},
    ],
    "projects_per_secondary_sectors": [
        {
            "count": 8,
            "secondary_sectors": 1,
            "secondary_sectors_display": "sect-tag-EDccPugTHOrVqLIKlyPyxLPeHqyoHzwwFYEMaGiCkoeGPrnjlk",
        },
        {
            "count": 8,
            "secondary_sectors": 2,
            "secondary_sectors_display": "sect-tag-MThQoAZvUhEREEnLkPAbpciKLkiOGcKjdkqlHzMKObUUQsfnCM",
        },
        {
            "count": 8,
            "secondary_sectors": 3,
            "secondary_sectors_display": "sect-tag-EkoAMjYLXlNQGqkURvDMLeoyyigbmHGRAjMglENMcYIGWhfEQi",
        },
        {
            "count": 8,
            "secondary_sectors": 4,
            "secondary_sectors_display": "sect-tag-IaXRPBHAxcSHBoZEYXywLZVWSKgBiqEXofsMIAqmaTVYaKHhHa",
        },
    ],
    "projects_per_sector": [
        {"count": 16, "primary_sector": 1, "primary_sector_display": "sect-zoXLUsiDGGfzxGaQpZNRkWGiCklKKQjVUEwcoWFoeqxocQnHYx"}
    ],
    "target_total": 0,
    "total_ongoing_projects": 16,
}

snapshots["TestProjectAPI::test_global_project_api 2"] = [
    {
        "budget_amount_total": 800000,
        "id": 3,
        "iso3": "Osx",
        "name": "country-sKRWmlNOzBGufzQgliEupaqypCWrvtLUKaqPxSpdQhDtkzRGTX",
        "ongoing_projects": 8,
        "operation_types": [0, 1],
        "operation_types_display": ["Programme", "Emergency Operation"],
        "projects_per_sector": [
            {"count": 8, "primary_sector": 1, "primary_sector_display": "sect-zoXLUsiDGGfzxGaQpZNRkWGiCklKKQjVUEwcoWFoeqxocQnHYx"}
        ],
        "society_name": "society-name-NooiEjDVMxASJEWIZQnWpRWMYfHCHTxeKhdJGmKIjkuHChRnTL",
        "target_total": 0,
    },
    {
        "budget_amount_total": 800000,
        "id": 4,
        "iso3": "ZRt",
        "name": "country-fLgGiOzeLKdBQipsquZzSVuuCroemiXXLgjgkCDuAhIwXnCtDq",
        "ongoing_projects": 8,
        "operation_types": [0, 1],
        "operation_types_display": ["Programme", "Emergency Operation"],
        "projects_per_sector": [
            {"count": 8, "primary_sector": 1, "primary_sector_display": "sect-zoXLUsiDGGfzxGaQpZNRkWGiCklKKQjVUEwcoWFoeqxocQnHYx"}
        ],
        "society_name": "society-name-TSMcnujfTpwzGdRtqlbzCJVJpgDgZYihadXoimzxROPfLLqebe",
        "target_total": 0,
    },
]

snapshots[
    "TestProjectAPI::test_personnel_csv_api 1"
] = """event_id,event_glide_id,event_name,event_ifrc_severity_level,event_disaster_type,event_country_name,event_country_iso3,event_country_nationalsociety,event_country_regionname,role,type,surge_alert_id,appraisal_received,gender,location,deployed_id,deployed_to_name,deployed_to_iso3,deployed_to_nationalsociety,deployed_to_regionname,deployed_from_name,deployed_from_iso3,deployed_from_nationalsociety,deployed_from_regionname,start_date,end_date,ongoing,is_active,name,molnix_status,molnix_id,molnix_sector,molnix_role_profile,molnix_language,molnix_region,molnix_scope,molnix_modality,molnix_operation\r
,,,,,,,,,,,,False,,,1,,,,,,,,,,,True,True,,,,,,,,,,\r
,,,,,,,,,,,,False,,,2,,,,,,,,,,,True,True,,,,,,,,,,\r
,,,,,,,,,,,,False,,,3,,,,,,,,,,,True,True,,,,,,,,,,\r
,,,,,,,,,,,,False,,,4,,,,,,,,,,,True,True,,,,,,,,,,\r
,,,,,,,,,,,,False,,,5,,,,,,,,,,,True,True,,,,,,,,,,\r
,,,,,,,,,,,,False,,,6,,,,,,,,,,,True,True,,,,,,,,,,\r
,,,,,,,,,,,,False,,,7,,,,,,,,,,,True,True,,,,,,,,,,\r
,,,,,,,,,,,,False,,,8,,,,,,,,,,,True,True,,,,,,,,,,\r
,,,,,,,,,,,,False,,,9,,,,,,,,,,,True,True,,,,,,,,,,\r
,,,,,,,,,,,,False,,,10,,,,,,,,,,,True,True,,,,,,,,,,\r
"""

snapshots[
    "TestProjectAPI::test_project_csv_api 1"
] = """actual_expenditure,budget_amount,description,document,dtype,dtype_detail.id,dtype_detail.name,dtype_detail.summary,dtype_detail.translation_module_original_language,end_date,event,event_detail.dtype,event_detail.emergency_response_contact_email,event_detail.id,event_detail.name,event_detail.parent_event,event_detail.slug,event_detail.start_date,event_detail.translation_module_original_language,id,modified_at,modified_by,modified_by_detail,name,operation_type,operation_type_display,primary_sector,primary_sector_display,programme_type,programme_type_display,project_country,project_country_detail.id,project_country_detail.iso,project_country_detail.iso3,project_country_detail.name,project_country_detail.society_name,project_districts_detail.code,project_districts_detail.id,project_districts_detail.is_deprecated,project_districts_detail.is_enclave,project_districts_detail.name,reached_female,reached_male,reached_other,reached_total,regional_project,regional_project_detail.created_at,regional_project_detail.id,regional_project_detail.modified_at,regional_project_detail.name,regional_project_detail.translation_module_original_language,regional_project_detail.translation_module_skip_auto_translation,reporting_ns,reporting_ns_contact_email,reporting_ns_contact_name,reporting_ns_contact_role,reporting_ns_detail.id,reporting_ns_detail.iso,reporting_ns_detail.iso3,reporting_ns_detail.name,reporting_ns_detail.society_name,secondary_sectors,secondary_sectors_display,start_date,status,status_display,target_female,target_male,target_other,target_total,translation_module_original_language,translation_module_skip_auto_translation,user,visibility,visibility_display\r
0,100000,,,1,1,disaster-type-1,summary,en,2008-01-01,2,1,,2,rpo: disaster-type-1 - 03-2016 - event-1,1,event-slug,,en,1,2008-01-01T00:00:00.123456Z,,,project-1,1,Emergency Operation,1,sect-1,0,Bilateral,1,1,bV,rpo,country-1,society-name-1,"dct1, dct2","1, 2","True, False","False, True","district-1, district-2",0,0,0,0,1,2008-01-01T00:00:00.123456Z,1,2008-01-01T00:00:00.123456Z,regional-project-1,en,False,1,,,,1,bV,rpo,country-1,society-name-1,"1, 2","sec-tag-1, sec-tag-2",2008-01-01,1,Ongoing,0,0,0,0,en,False,5,public,Public\r
0,100000,,,1,1,disaster-type-1,summary,en,2008-01-01,2,1,,2,rpo: disaster-type-1 - 03-2016 - event-1,1,event-slug,,en,2,2008-01-01T00:00:00.123456Z,,,project-1,1,Emergency Operation,1,sect-1,0,Bilateral,1,1,bV,rpo,country-1,society-name-1,"dct1, dct2","1, 2","True, False","False, True","district-1, district-2",0,0,0,0,1,2008-01-01T00:00:00.123456Z,1,2008-01-01T00:00:00.123456Z,regional-project-1,en,False,1,,,,1,bV,rpo,country-1,society-name-1,"1, 2","sec-tag-1, sec-tag-2",2008-01-01,1,Ongoing,0,0,0,0,en,False,6,public,Public\r
0,100000,,,1,1,disaster-type-1,summary,en,2008-01-01,2,1,,2,rpo: disaster-type-1 - 03-2016 - event-1,1,event-slug,,en,3,2008-01-01T00:00:00.123456Z,,,project-1,1,Emergency Operation,1,sect-1,0,Bilateral,1,1,bV,rpo,country-1,society-name-1,"dct1, dct2","1, 2","True, False","False, True","district-1, district-2",0,0,0,0,1,2008-01-01T00:00:00.123456Z,1,2008-01-01T00:00:00.123456Z,regional-project-1,en,False,1,,,,1,bV,rpo,country-1,society-name-1,"1, 2","sec-tag-1, sec-tag-2",2008-01-01,1,Ongoing,0,0,0,0,en,False,7,public,Public\r
0,100000,,,1,1,disaster-type-1,summary,en,2008-01-01,2,1,,2,rpo: disaster-type-1 - 03-2016 - event-1,1,event-slug,,en,4,2008-01-01T00:00:00.123456Z,,,project-1,1,Emergency Operation,1,sect-1,0,Bilateral,1,1,bV,rpo,country-1,society-name-1,"dct1, dct2","1, 2","True, False","False, True","district-1, district-2",0,0,0,0,1,2008-01-01T00:00:00.123456Z,1,2008-01-01T00:00:00.123456Z,regional-project-1,en,False,1,,,,1,bV,rpo,country-1,society-name-1,"1, 2","sec-tag-1, sec-tag-2",2008-01-01,1,Ongoing,0,0,0,0,en,False,8,public,Public\r
0,100000,,,1,1,disaster-type-1,summary,en,2008-01-01,2,1,,2,rpo: disaster-type-1 - 03-2016 - event-1,1,event-slug,,en,5,2008-01-01T00:00:00.123456Z,,,project-1,1,Emergency Operation,1,sect-1,0,Bilateral,1,1,bV,rpo,country-1,society-name-1,"dct1, dct2","1, 2","True, False","False, True","district-1, district-2",0,0,0,0,1,2008-01-01T00:00:00.123456Z,1,2008-01-01T00:00:00.123456Z,regional-project-1,en,False,1,,,,1,bV,rpo,country-1,society-name-1,"1, 2","sec-tag-1, sec-tag-2",2008-01-01,1,Ongoing,0,0,0,0,en,False,9,public,Public\r
0,100000,,,1,1,disaster-type-1,summary,en,2008-01-01,2,1,,2,rpo: disaster-type-1 - 03-2016 - event-1,1,event-slug,,en,6,2008-01-01T00:00:00.123456Z,,,project-1,1,Emergency Operation,1,sect-1,0,Bilateral,1,1,bV,rpo,country-1,society-name-1,"dct1, dct2","1, 2","True, False","False, True","district-1, district-2",0,0,0,0,1,2008-01-01T00:00:00.123456Z,1,2008-01-01T00:00:00.123456Z,regional-project-1,en,False,1,,,,1,bV,rpo,country-1,society-name-1,"1, 2","sec-tag-1, sec-tag-2",2008-01-01,1,Ongoing,0,0,0,0,en,False,10,public,Public\r
0,100000,,,1,1,disaster-type-1,summary,en,2008-01-01,2,1,,2,rpo: disaster-type-1 - 03-2016 - event-1,1,event-slug,,en,7,2008-01-01T00:00:00.123456Z,,,project-1,1,Emergency Operation,1,sect-1,0,Bilateral,1,1,bV,rpo,country-1,society-name-1,"dct1, dct2","1, 2","True, False","False, True","district-1, district-2",0,0,0,0,1,2008-01-01T00:00:00.123456Z,1,2008-01-01T00:00:00.123456Z,regional-project-1,en,False,1,,,,1,bV,rpo,country-1,society-name-1,"1, 2","sec-tag-1, sec-tag-2",2008-01-01,1,Ongoing,0,0,0,0,en,False,11,public,Public\r
0,100000,,,1,1,disaster-type-1,summary,en,2008-01-01,2,1,,2,rpo: disaster-type-1 - 03-2016 - event-1,1,event-slug,,en,8,2008-01-01T00:00:00.123456Z,,,project-1,1,Emergency Operation,1,sect-1,0,Bilateral,1,1,bV,rpo,country-1,society-name-1,"dct1, dct2","1, 2","True, False","False, True","district-1, district-2",0,0,0,0,1,2008-01-01T00:00:00.123456Z,1,2008-01-01T00:00:00.123456Z,regional-project-1,en,False,1,,,,1,bV,rpo,country-1,society-name-1,"1, 2","sec-tag-1, sec-tag-2",2008-01-01,1,Ongoing,0,0,0,0,en,False,12,public,Public\r
0,100000,,,1,1,disaster-type-1,summary,en,2008-01-01,2,1,,2,rpo: disaster-type-1 - 03-2016 - event-1,1,event-slug,,en,9,2008-01-01T00:00:00.123456Z,,,project-1,1,Emergency Operation,1,sect-1,0,Bilateral,1,1,bV,rpo,country-1,society-name-1,"dct1, dct2","1, 2","True, False","False, True","district-1, district-2",0,0,0,0,1,2008-01-01T00:00:00.123456Z,1,2008-01-01T00:00:00.123456Z,regional-project-1,en,False,1,,,,1,bV,rpo,country-1,society-name-1,"1, 2","sec-tag-1, sec-tag-2",2008-01-01,1,Ongoing,0,0,0,0,en,False,13,public,Public\r
0,100000,,,1,1,disaster-type-1,summary,en,2008-01-01,2,1,,2,rpo: disaster-type-1 - 03-2016 - event-1,1,event-slug,,en,10,2008-01-01T00:00:00.123456Z,,,project-1,1,Emergency Operation,1,sect-1,0,Bilateral,1,1,bV,rpo,country-1,society-name-1,"dct1, dct2","1, 2","True, False","False, True","district-1, district-2",0,0,0,0,1,2008-01-01T00:00:00.123456Z,1,2008-01-01T00:00:00.123456Z,regional-project-1,en,False,1,,,,1,bV,rpo,country-1,society-name-1,"1, 2","sec-tag-1, sec-tag-2",2008-01-01,1,Ongoing,0,0,0,0,en,False,14,public,Public\r
"""

snapshots["TestProjectAPI::test_project_delete 1"] = b""

snapshots["TestProjectAPI::test_project_list_one 1"] = {
    "count": 1,
    "next": None,
    "previous": None,
    "results": [
        {
            "actual_expenditure": 0,
            "annual_splits": [],
            "budget_amount": 8500000,
            "description": "",
            "document": None,
            "dtype": 3,
            "dtype_detail": {
                "id": 3,
                "name": "disaster-type-SOuThWwJELKQTARVIsBZaHgbyjdQdmrWYksRqjdSYsnWIcwCgN",
                "summary": "RVJoVPJypGYYZSsSQdyyAYRuJdaVqmNXCoOTTPxWLIVMmXUmsClRellVGhycBrJqikLqavDTjcjuMdXONQtFYKJweYTuHolHeYGkAIIzfwonQvvxsnWNHEJWPahQwCpPNNpcRuyYhyqIUsbHXxGZGCFcsPmuGfgkXIIaOenQOXnRBgnISVXBPeVRjbDTvcfedlYqJeKoqAyCOzBubyRhIaPUNeWVLcSewGgsYRtMfsWCyzQbEkIoiVzYZIsOjtRYUPxaJJjhcaKMzIJftnVVUwnAPGjkloNqmhlQZKdWJDPJesQeqgmULFvwiQPpgsNemuFCvNQtSLjKKxZuBkaupYoTVPBrxiRUvEDCwXtFJglPMfriImqUOeUebGObLLzXLncJqIIEPXjxzoXLUsiDGGfzxGaQpZNRkWGiCklKKQjVUEwcoWFoeqxocQnHYxyEDccPugTHOrVqLIKlyPyxLPeHqyoHzwwFYEMaGiCkoeGPrnjlkxMT",
                "translation_module_original_language": "en",
            },
            "end_date": "2008-01-01",
            "event": 2,
            "event_detail": {
                "countries_for_preview": [],
                "dtype": 1,
                "emergency_response_contact_email": None,
                "id": 2,
                "name": "N/A: disaster-type-hlIzHiUoaWbtDRUIBIyopDwjrmUWhcZQANXbpnegMcCMRTdpVc - 12-2019 - LFfGCZdDiG",
                "parent_event": 1,
                "slug": "adkdjdrztubzqavnlecbwseideecsalxixpupaxycyyfrqiipw",
                "start_date": None,
                "translation_module_original_language": "en",
            },
            "id": 1,
            "modified_at": "2008-01-01T00:00:00.123456Z",
            "modified_by": None,
            "modified_by_detail": None,
            "name": "project-hQoAZvUhEREEnLkPAbpciKLkiOGcKjdkqlHzMKObUUQsfnCMEE",
            "operation_type": 0,
            "operation_type_display": "Programme",
            "primary_sector": 1,
            "primary_sector_display": "sect-OhbVrpoiVgRVIfLBcbfnoGMbJmTPSIAoCLrZaWZkSBvrjnWvgf",
            "programme_type": 0,
            "programme_type_display": "Bilateral",
            "project_admin2": [],
            "project_admin2_detail": [],
            "project_country": 2,
            "project_country_detail": {
                "id": 2,
                "iso": "Cp",
                "iso3": "xgR",
                "name": "country-oEbNJuNoPeODStPAhicctFhgpIiyDxQVSIALVUjAPgFNArcSxn",
                "society_name": "society-name-xIPwdzrmhDfQnPOMbdYvpiYKneWJnLnovXjYMarjiIqZlhQbia",
            },
            "project_districts": [],
            "project_districts_detail": [],
            "reached_female": 0,
            "reached_male": 0,
            "reached_other": 0,
            "reached_total": 0,
            "regional_project": 1,
            "regional_project_detail": {
                "created_at": "2008-01-01T00:00:00.123456Z",
                "id": 1,
                "modified_at": "2008-01-01T00:00:00.123456Z",
                "name": "regional-project-yyigbmHGRAjMglENMcYIGWhfEQiMIaXRPBHAxcSHBoZEYXywLZ",
                "translation_module_original_language": "en",
                "translation_module_skip_auto_translation": False,
            },
            "reporting_ns": 1,
            "reporting_ns_contact_email": None,
            "reporting_ns_contact_name": None,
            "reporting_ns_contact_role": None,
            "reporting_ns_detail": {
                "id": 1,
                "iso": "yr",
                "iso3": "OSJ",
                "name": "country-wMqZcUDIhyfJsONxKmTecQoXsfogyrDOxkxwnQrSRPeMOkIUpk",
                "society_name": "society-name-oRuXXdocZuzrenKTunPFzPDjqipVJIqVLBLzxoiGFfWdhjOkYR",
            },
            "secondary_sectors": [],
            "secondary_sectors_display": [],
            "start_date": "2008-01-01",
            "status": 1,
            "status_display": "Ongoing",
            "target_female": 0,
            "target_male": 0,
            "target_other": 0,
            "target_total": 0,
            "translation_module_original_language": "en",
            "translation_module_skip_auto_translation": False,
            "user": 5,
            "visibility": "public",
            "visibility_display": "Public",
        }
    ],
}

snapshots["TestProjectAPI::test_project_list_two 1"] = {
    "count": 2,
    "next": None,
    "previous": None,
    "results": [
        {
            "actual_expenditure": 0,
            "annual_splits": [],
            "budget_amount": 8500000,
            "description": "",
            "document": None,
            "dtype": 3,
            "dtype_detail": {
                "id": 3,
                "name": "disaster-type-SOuThWwJELKQTARVIsBZaHgbyjdQdmrWYksRqjdSYsnWIcwCgN",
                "summary": "RVJoVPJypGYYZSsSQdyyAYRuJdaVqmNXCoOTTPxWLIVMmXUmsClRellVGhycBrJqikLqavDTjcjuMdXONQtFYKJweYTuHolHeYGkAIIzfwonQvvxsnWNHEJWPahQwCpPNNpcRuyYhyqIUsbHXxGZGCFcsPmuGfgkXIIaOenQOXnRBgnISVXBPeVRjbDTvcfedlYqJeKoqAyCOzBubyRhIaPUNeWVLcSewGgsYRtMfsWCyzQbEkIoiVzYZIsOjtRYUPxaJJjhcaKMzIJftnVVUwnAPGjkloNqmhlQZKdWJDPJesQeqgmULFvwiQPpgsNemuFCvNQtSLjKKxZuBkaupYoTVPBrxiRUvEDCwXtFJglPMfriImqUOeUebGObLLzXLncJqIIEPXjxzoXLUsiDGGfzxGaQpZNRkWGiCklKKQjVUEwcoWFoeqxocQnHYxyEDccPugTHOrVqLIKlyPyxLPeHqyoHzwwFYEMaGiCkoeGPrnjlkxMT",
                "translation_module_original_language": "en",
            },
            "end_date": "2008-01-01",
            "event": 2,
            "event_detail": {
                "countries_for_preview": [],
                "dtype": 1,
                "emergency_response_contact_email": None,
                "id": 2,
                "name": "N/A: disaster-type-hlIzHiUoaWbtDRUIBIyopDwjrmUWhcZQANXbpnegMcCMRTdpVc - 12-2019 - LFfGCZdDiG",
                "parent_event": 1,
                "slug": "adkdjdrztubzqavnlecbwseideecsalxixpupaxycyyfrqiipw",
                "start_date": None,
                "translation_module_original_language": "en",
            },
            "id": 1,
            "modified_at": "2008-01-01T00:00:00.123456Z",
            "modified_by": None,
            "modified_by_detail": None,
            "name": "project-hQoAZvUhEREEnLkPAbpciKLkiOGcKjdkqlHzMKObUUQsfnCMEE",
            "operation_type": 0,
            "operation_type_display": "Programme",
            "primary_sector": 1,
            "primary_sector_display": "sect-OhbVrpoiVgRVIfLBcbfnoGMbJmTPSIAoCLrZaWZkSBvrjnWvgf",
            "programme_type": 0,
            "programme_type_display": "Bilateral",
            "project_admin2": [],
            "project_admin2_detail": [],
            "project_country": 2,
            "project_country_detail": {
                "id": 2,
                "iso": "Cp",
                "iso3": "xgR",
                "name": "country-oEbNJuNoPeODStPAhicctFhgpIiyDxQVSIALVUjAPgFNArcSxn",
                "society_name": "society-name-xIPwdzrmhDfQnPOMbdYvpiYKneWJnLnovXjYMarjiIqZlhQbia",
            },
            "project_districts": [],
            "project_districts_detail": [],
            "reached_female": 0,
            "reached_male": 0,
            "reached_other": 0,
            "reached_total": 0,
            "regional_project": 1,
            "regional_project_detail": {
                "created_at": "2008-01-01T00:00:00.123456Z",
                "id": 1,
                "modified_at": "2008-01-01T00:00:00.123456Z",
                "name": "regional-project-yyigbmHGRAjMglENMcYIGWhfEQiMIaXRPBHAxcSHBoZEYXywLZ",
                "translation_module_original_language": "en",
                "translation_module_skip_auto_translation": False,
            },
            "reporting_ns": 1,
            "reporting_ns_contact_email": None,
            "reporting_ns_contact_name": None,
            "reporting_ns_contact_role": None,
            "reporting_ns_detail": {
                "id": 1,
                "iso": "yr",
                "iso3": "OSJ",
                "name": "country-wMqZcUDIhyfJsONxKmTecQoXsfogyrDOxkxwnQrSRPeMOkIUpk",
                "society_name": "society-name-oRuXXdocZuzrenKTunPFzPDjqipVJIqVLBLzxoiGFfWdhjOkYR",
            },
            "secondary_sectors": [],
            "secondary_sectors_display": [],
            "start_date": "2008-01-01",
            "status": 1,
            "status_display": "Ongoing",
            "target_female": 0,
            "target_male": 0,
            "target_other": 0,
            "target_total": 0,
            "translation_module_original_language": "en",
            "translation_module_skip_auto_translation": False,
            "user": 5,
            "visibility": "public",
            "visibility_display": "Public",
        },
        {
            "actual_expenditure": 0,
            "annual_splits": [],
            "budget_amount": 9540000,
            "description": "",
            "document": None,
            "dtype": 6,
            "dtype_detail": {
                "id": 6,
                "name": "disaster-type-swYzzLWPaEPGWjzooUVnEoHLYJWDUDvYfumBXSAnCCJbxiKitV",
                "summary": "aFZQwvoABRWzWXSItuLbKYcijvKOZMMKzynzeIymEgvKCOtfkgRJlcSMFblmeysnosQHeDdxHakuAzkhiIAEVeynintBTQEkMKtLmGTRDrmajCezMZpHvKFDDKcVfsPDwSTYtzNZlAplNUBDyQlSKgzScpkrOIsQeSUUnFAWJhxeWgGXXuACkqnGcDbeOSRVDyvVzmzcaqhTiuQVDFDefJQpTCiErkkbMglshIVzkeQWaRrjCwlnTcRInCSdOZHPQTQgyStCdMadXyXmpxpmfbAbavmRQeogZQkUkcAGguuJOmNnIzBhongwulazPuaynDoeQrPNxcenAtXMFgTIYKkqgMuOSyRXSivlOWSuQEevbMLCyGOVoGLTaobNWhtpVBWpNfdixFsmjynPcpUMCVviruPYWcHYAPsWboUvvpnIdQpZRSUoMyHulCOaeFemdOjniflLJYnpGfBUDtkUmpBlMptsKCOmrYEfxzykECBGNVBWjYEb",
                "translation_module_original_language": "en",
            },
            "end_date": "2008-01-01",
            "event": 4,
            "event_detail": {
                "countries_for_preview": [],
                "dtype": 4,
                "emergency_response_contact_email": None,
                "id": 4,
                "name": "N/A: disaster-type-bfICRQfGzmFuMMGdQxzjTBxyxaswwtCJfnUCVAZCskZUBUAiLM - 05-2014 - kIthbzFXjD",
                "parent_event": 3,
                "slug": "ujavigvptseswkqjzkucvshuecirjhtbznocwfudmpmlhoyxrm",
                "start_date": None,
                "translation_module_original_language": "en",
            },
            "id": 2,
            "modified_at": "2008-01-01T00:00:00.123456Z",
            "modified_by": None,
            "modified_by_detail": None,
            "name": "project-WyBfWtMIjJUlqyDtDsyJMEeviTEmjmaaGUUxFzAzVxyFtPLeAc",
            "operation_type": 1,
            "operation_type_display": "Emergency Operation",
            "primary_sector": 1,
            "primary_sector_display": "sect-OhbVrpoiVgRVIfLBcbfnoGMbJmTPSIAoCLrZaWZkSBvrjnWvgf",
            "programme_type": 0,
            "programme_type_display": "Bilateral",
            "project_admin2": [],
            "project_admin2_detail": [],
            "project_country": 4,
            "project_country_detail": {
                "id": 4,
                "iso": "Al",
                "iso3": "kRs",
                "name": "country-imaNWqaDFFIZaMFpnLQEDACfMMapJrNOJndljdPwcjcQKMtvfd",
                "society_name": "society-name-NQSSMKYJlDVLxcfXtuxyeWBJesEihSrvHAHnSnNdgKUOHfEUSM",
            },
            "project_districts": [],
            "project_districts_detail": [],
            "reached_female": 0,
            "reached_male": 0,
            "reached_other": 0,
            "reached_total": 0,
            "regional_project": 2,
            "regional_project_detail": {
                "created_at": "2008-01-01T00:00:00.123456Z",
                "id": 2,
                "modified_at": "2008-01-01T00:00:00.123456Z",
                "name": "regional-project-VppEcxOTRbSQPjqMDRjqpMLQkahXfPTyzTLfHmBkBqStGIQyLt",
                "translation_module_original_language": "en",
                "translation_module_skip_auto_translation": False,
            },
            "reporting_ns": 3,
            "reporting_ns_contact_email": None,
            "reporting_ns_contact_name": None,
            "reporting_ns_contact_role": None,
            "reporting_ns_detail": {
                "id": 3,
                "iso": "YJ",
                "iso3": "Elx",
                "name": "country-gBiqEXofsMIAqmaTVYaKHhHayPnSZuAxgjBPLqqIBKxNrRzWnA",
                "society_name": "society-name-JJEqtKwXTzViQhVoCYSkgnGzYvZJNSRTdkyOaZfjEMBfeqoxfM",
            },
            "secondary_sectors": [],
            "secondary_sectors_display": [],
            "start_date": "2008-01-01",
            "status": 1,
            "status_display": "Ongoing",
            "target_female": 0,
            "target_male": 0,
            "target_other": 0,
            "target_total": 0,
            "translation_module_original_language": "en",
            "translation_module_skip_auto_translation": False,
            "user": 6,
            "visibility": "public",
            "visibility_display": "Public",
        },
    ],
}

snapshots["TestProjectAPI::test_project_list_zero 1"] = {"count": 0, "next": None, "previous": None, "results": []}

snapshots["TestProjectAPI::test_project_read 1"] = {
    "actual_expenditure": 0,
    "annual_splits": [],
    "budget_amount": 8500000,
    "description": "",
    "document": None,
    "dtype": 3,
    "dtype_detail": {
        "id": 3,
        "name": "disaster-type-SOuThWwJELKQTARVIsBZaHgbyjdQdmrWYksRqjdSYsnWIcwCgN",
        "summary": "RVJoVPJypGYYZSsSQdyyAYRuJdaVqmNXCoOTTPxWLIVMmXUmsClRellVGhycBrJqikLqavDTjcjuMdXONQtFYKJweYTuHolHeYGkAIIzfwonQvvxsnWNHEJWPahQwCpPNNpcRuyYhyqIUsbHXxGZGCFcsPmuGfgkXIIaOenQOXnRBgnISVXBPeVRjbDTvcfedlYqJeKoqAyCOzBubyRhIaPUNeWVLcSewGgsYRtMfsWCyzQbEkIoiVzYZIsOjtRYUPxaJJjhcaKMzIJftnVVUwnAPGjkloNqmhlQZKdWJDPJesQeqgmULFvwiQPpgsNemuFCvNQtSLjKKxZuBkaupYoTVPBrxiRUvEDCwXtFJglPMfriImqUOeUebGObLLzXLncJqIIEPXjxzoXLUsiDGGfzxGaQpZNRkWGiCklKKQjVUEwcoWFoeqxocQnHYxyEDccPugTHOrVqLIKlyPyxLPeHqyoHzwwFYEMaGiCkoeGPrnjlkxMT",
        "translation_module_original_language": "en",
    },
    "end_date": "2008-01-01",
    "event": 2,
    "event_detail": {
        "countries_for_preview": [],
        "dtype": 1,
        "emergency_response_contact_email": None,
        "id": 2,
        "name": "N/A: disaster-type-hlIzHiUoaWbtDRUIBIyopDwjrmUWhcZQANXbpnegMcCMRTdpVc - 12-2019 - LFfGCZdDiG",
        "parent_event": 1,
        "slug": "adkdjdrztubzqavnlecbwseideecsalxixpupaxycyyfrqiipw",
        "start_date": None,
        "translation_module_original_language": "en",
    },
    "id": 1,
    "modified_at": "2008-01-01T00:00:00.123456Z",
    "modified_by": None,
    "modified_by_detail": None,
    "name": "project-hQoAZvUhEREEnLkPAbpciKLkiOGcKjdkqlHzMKObUUQsfnCMEE",
    "operation_type": 0,
    "operation_type_display": "Programme",
    "primary_sector": 1,
    "primary_sector_display": "sect-OhbVrpoiVgRVIfLBcbfnoGMbJmTPSIAoCLrZaWZkSBvrjnWvgf",
    "programme_type": 0,
    "programme_type_display": "Bilateral",
    "project_admin2": [],
    "project_admin2_detail": [],
    "project_country": 2,
    "project_country_detail": {
        "id": 2,
        "iso": "Cp",
        "iso3": "xgR",
        "name": "country-oEbNJuNoPeODStPAhicctFhgpIiyDxQVSIALVUjAPgFNArcSxn",
        "society_name": "society-name-xIPwdzrmhDfQnPOMbdYvpiYKneWJnLnovXjYMarjiIqZlhQbia",
    },
    "project_districts": [],
    "project_districts_detail": [],
    "reached_female": 0,
    "reached_male": 0,
    "reached_other": 0,
    "reached_total": 0,
    "regional_project": 1,
    "regional_project_detail": {
        "created_at": "2008-01-01T00:00:00.123456Z",
        "id": 1,
        "modified_at": "2008-01-01T00:00:00.123456Z",
        "name": "regional-project-yyigbmHGRAjMglENMcYIGWhfEQiMIaXRPBHAxcSHBoZEYXywLZ",
        "translation_module_original_language": "en",
        "translation_module_skip_auto_translation": False,
    },
    "reporting_ns": 1,
    "reporting_ns_contact_email": None,
    "reporting_ns_contact_name": None,
    "reporting_ns_contact_role": None,
    "reporting_ns_detail": {
        "id": 1,
        "iso": "yr",
        "iso3": "OSJ",
        "name": "country-wMqZcUDIhyfJsONxKmTecQoXsfogyrDOxkxwnQrSRPeMOkIUpk",
        "society_name": "society-name-oRuXXdocZuzrenKTunPFzPDjqipVJIqVLBLzxoiGFfWdhjOkYR",
    },
    "secondary_sectors": [],
    "secondary_sectors_display": [],
    "start_date": "2008-01-01",
    "status": 1,
    "status_display": "Ongoing",
    "target_female": 0,
    "target_male": 0,
    "target_other": 0,
    "target_total": 0,
    "translation_module_original_language": "en",
    "translation_module_skip_auto_translation": False,
    "user": 5,
    "visibility": "public",
    "visibility_display": "Public",
}

snapshots["TestProjectAPI::test_project_update 1"] = {
    "actual_expenditure": 0,
    "annual_splits": [],
    "budget_amount": 8500000,
    "description": "",
    "document": None,
    "dtype": 3,
    "dtype_detail": {
        "id": 3,
        "name": "disaster-type-SOuThWwJELKQTARVIsBZaHgbyjdQdmrWYksRqjdSYsnWIcwCgN",
        "summary": "RVJoVPJypGYYZSsSQdyyAYRuJdaVqmNXCoOTTPxWLIVMmXUmsClRellVGhycBrJqikLqavDTjcjuMdXONQtFYKJweYTuHolHeYGkAIIzfwonQvvxsnWNHEJWPahQwCpPNNpcRuyYhyqIUsbHXxGZGCFcsPmuGfgkXIIaOenQOXnRBgnISVXBPeVRjbDTvcfedlYqJeKoqAyCOzBubyRhIaPUNeWVLcSewGgsYRtMfsWCyzQbEkIoiVzYZIsOjtRYUPxaJJjhcaKMzIJftnVVUwnAPGjkloNqmhlQZKdWJDPJesQeqgmULFvwiQPpgsNemuFCvNQtSLjKKxZuBkaupYoTVPBrxiRUvEDCwXtFJglPMfriImqUOeUebGObLLzXLncJqIIEPXjxzoXLUsiDGGfzxGaQpZNRkWGiCklKKQjVUEwcoWFoeqxocQnHYxyEDccPugTHOrVqLIKlyPyxLPeHqyoHzwwFYEMaGiCkoeGPrnjlkxMT",
        "translation_module_original_language": "en",
    },
    "end_date": "2008-01-01",
    "event": 2,
    "event_detail": {
        "countries_for_preview": [],
        "dtype": 1,
        "emergency_response_contact_email": None,
        "id": 2,
        "name": "N/A: disaster-type-hlIzHiUoaWbtDRUIBIyopDwjrmUWhcZQANXbpnegMcCMRTdpVc - 12-2019 - LFfGCZdDiG",
        "parent_event": 1,
        "slug": "adkdjdrztubzqavnlecbwseideecsalxixpupaxycyyfrqiipw",
        "start_date": None,
        "translation_module_original_language": "en",
    },
    "id": 1,
    "modified_at": "2008-01-01T00:00:00.123456Z",
    "modified_by": 3,
    "modified_by_detail": {"email": "jon@dave.com", "first_name": "Jon", "id": 3, "last_name": "Mon", "username": "jon@dave.com"},
    "name": "Mock Project for Update API Test",
    "operation_type": 0,
    "operation_type_display": "Programme",
    "primary_sector": 1,
    "primary_sector_display": "sect-OhbVrpoiVgRVIfLBcbfnoGMbJmTPSIAoCLrZaWZkSBvrjnWvgf",
    "programme_type": 0,
    "programme_type_display": "Bilateral",
    "project_admin2": [],
    "project_admin2_detail": [],
    "project_country": 3,
    "project_country_detail": {
        "id": 3,
        "iso": "AJ",
        "iso3": "YJE",
        "name": "country-SKgBiqEXofsMIAqmaTVYaKHhHayPnSZuAxgjBPLqqIBKxNrRzW",
        "society_name": "society-name-lxJJEqtKwXTzViQhVoCYSkgnGzYvZJNSRTdkyOaZfjEMBfeqox",
    },
    "project_districts": [1],
    "project_districts_detail": [{"id": 1, "name": "district-imaNWqaDFFIZaMFpnLQEDACfMMapJrNOJndljdPwcjcQKMtvfd"}],
    "reached_female": 0,
    "reached_male": 0,
    "reached_other": 0,
    "reached_total": 0,
    "regional_project": 1,
    "regional_project_detail": {
        "created_at": "2008-01-01T00:00:00.123456Z",
        "id": 1,
        "modified_at": "2008-01-01T00:00:00.123456Z",
        "name": "regional-project-yyigbmHGRAjMglENMcYIGWhfEQiMIaXRPBHAxcSHBoZEYXywLZ",
        "translation_module_original_language": "en",
        "translation_module_skip_auto_translation": False,
    },
    "reporting_ns": 3,
    "reporting_ns_contact_email": None,
    "reporting_ns_contact_name": None,
    "reporting_ns_contact_role": None,
    "reporting_ns_detail": {
        "id": 3,
        "iso": "AJ",
        "iso3": "YJE",
        "name": "country-SKgBiqEXofsMIAqmaTVYaKHhHayPnSZuAxgjBPLqqIBKxNrRzW",
        "society_name": "society-name-lxJJEqtKwXTzViQhVoCYSkgnGzYvZJNSRTdkyOaZfjEMBfeqox",
    },
    "secondary_sectors": [],
    "secondary_sectors_display": [],
    "start_date": "2008-01-01",
    "status": 1,
    "status_display": "Ongoing",
    "target_female": 0,
    "target_male": 0,
    "target_other": 0,
    "target_total": 0,
    "translation_module_original_language": "en",
    "translation_module_skip_auto_translation": False,
    "user": 5,
    "visibility": "public",
    "visibility_display": "Public",
}
