# Generated by Django 2.2.13 on 2020-06-18 09:04

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0002_auto_20200603_0613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryoverview',
            options={'verbose_name': 'country overview', 'verbose_name_plural': 'countries overview'},
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='avg_rainfall_precipitation',
            field=models.FloatField(blank=True, null=True, verbose_name='average rainfall precipitation'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='avg_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='average temperature'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='expenditures',
            field=models.FloatField(blank=True, null=True, verbose_name='expenditures (CHF)'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='fts_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='FTS data'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='income',
            field=models.FloatField(blank=True, null=True, verbose_name='income (CHF)'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='inform_indicators',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='inform indicators data'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='life_expectancy',
            field=models.IntegerField(blank=True, null=True, verbose_name='life expectancy'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='literacy',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='literacy (%)'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='past_crises_events',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='past crises data'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='past_epidemics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='past epidemics data'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='population',
            field=models.IntegerField(blank=True, null=True, verbose_name='population'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='poverty',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='poverty (%)'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='rainy_season',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('not_active', 'Not Active')], max_length=20, null=True, verbose_name='rainy season'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='start_network_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='start network data'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='trained_in_first_aid',
            field=models.IntegerField(blank=True, null=True, verbose_name='trained in first aid'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='urban_population',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='urban POP (%)'),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='volunteers',
            field=models.IntegerField(blank=True, null=True, verbose_name='volunteers'),
        ),
        migrations.AlterField(
            model_name='keyclimateevent',
            name='avg_max_temperature',
            field=models.FloatField(verbose_name='average maximum temperature'),
        ),
        migrations.AlterField(
            model_name='keyclimateevent',
            name='avg_min_temperature',
            field=models.FloatField(verbose_name='average minimum temperature'),
        ),
        migrations.AlterField(
            model_name='keyclimateevent',
            name='avg_rainfall_precipitation',
            field=models.FloatField(verbose_name='average rainfall precipitation'),
        ),
        migrations.AlterField(
            model_name='keyclimateevent',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='keyclimateevent',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='keyclimateevent',
            name='overview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databank.CountryOverview', verbose_name='country overview'),
        ),
        migrations.AlterField(
            model_name='seasonalcalender',
            name='date_end',
            field=models.DateField(verbose_name='date end'),
        ),
        migrations.AlterField(
            model_name='seasonalcalender',
            name='date_start',
            field=models.DateField(verbose_name='date start'),
        ),
        migrations.AlterField(
            model_name='seasonalcalender',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='seasonalcalender',
            name='overview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databank.CountryOverview', verbose_name='country overview'),
        ),
        migrations.AlterField(
            model_name='seasonalcalender',
            name='sector',
            field=models.CharField(max_length=20, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='seasonalcalender',
            name='title',
            field=models.CharField(max_length=20, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='socialevent',
            name='label',
            field=models.CharField(max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='socialevent',
            name='overview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databank.CountryOverview', verbose_name='country overview'),
        ),
        migrations.AlterField(
            model_name='socialevent',
            name='value',
            field=models.CharField(max_length=255, verbose_name='value'),
        ),
    ]
