# Generated by Django 2.2.13 on 2020-07-21 16:11

import databank.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0003_auto_20200618_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyDocumentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='KeyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('date', models.DateField(verbose_name='date')),
                ('file', models.FileField(upload_to=databank.models.key_document_path, verbose_name='file')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databank.KeyDocumentGroup', verbose_name='group')),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databank.CountryOverview', verbose_name='country overview')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('url', models.URLField(max_length=300, verbose_name='url')),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databank.CountryOverview', verbose_name='country overview')),
            ],
        ),
    ]
