# Generated by Django 2.2.13 on 2020-09-03 08:43

from django.db import migrations, models

import databank.models


class Migration(migrations.Migration):

    dependencies = [
        ("databank", "0004_externalsource_keydocument_keydocumentgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keydocument",
            name="file",
            field=models.FileField(upload_to=databank.models.key_document_path, verbose_name="file"),
        ),
    ]
