# Generated by Django 3.2.23 on 2023-12-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0007_auto_20231221_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryoverview',
            name='branches',
            field=models.IntegerField(blank=True, null=True, verbose_name='Branches'),
        ),
    ]
