# Generated by Django 3.2.23 on 2023-12-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0009_auto_20231226_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryoverview',
            name='people_age_13_17',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='people_age_18_29',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='people_age_60_69',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='people_age_6_12',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='people_age_70_79',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='people_age_80',
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_staff_age_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 18 to 29'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_staff_age_18_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 18 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_staff_age_30_39',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 30 to 39'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_staff_age_40_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 40 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_staff_age_50_59',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 50 to 59'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_staff_age_60_69',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 60 to 69'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_staff_age_70_79',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 70 to 79'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_staff_age_80',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 80'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_volunteer_age_13_17',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 13 to 17'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_volunteer_age_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 18 to 29'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_volunteer_age_18_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 18 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_volunteer_age_30_39',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 30 to 39'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_volunteer_age_40_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 40 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_volunteer_age_50_59',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 50 to 59'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_volunteer_age_60_69',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 60 to 69'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_volunteer_age_6_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 6 to 12'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_volunteer_age_70_79',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 70 to 79'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='female_volunteer_age_80',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 80'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_staff_age_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 18 to 29'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_staff_age_18_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 18 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_staff_age_30_39',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 30 to 39'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_staff_age_40_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 40 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_staff_age_50_59',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 50 to 59'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_staff_age_60_69',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 60 to 69'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_staff_age_70_79',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 70 to 79'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_staff_age_80',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 80'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_volunteer_age_13_17',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 13 to 17'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_volunteer_age_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 18 to 29'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_volunteer_age_18_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 18 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_volunteer_age_30_39',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 30 to 39'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_volunteer_age_40_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 40 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_volunteer_age_50_59',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 50 to 59'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_volunteer_age_60_69',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 60 to 69'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_volunteer_age_6_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 6 to 12'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_volunteer_age_70_79',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 70 to 79'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='male_volunteer_age_80',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 80'),
        ),
    ]
