# Generated by Django 3.2.23 on 2024-01-22 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databank", "0015_auto_20240111_0813"),
    ]

    operations = [
        migrations.CreateModel(
            name="FDRSIncome",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="date")),
                (
                    "indicator",
                    models.CharField(
                        choices=[
                            ("h_gov_CHF", "Home Government"),
                            ("f_gov_CHF", "Foreign Government"),
                            ("ind_CHF", "Individual"),
                            ("corp_CHF", "Corporation"),
                            ("found_CHF", "Foundation"),
                            ("un_CHF", "UN Agencies"),
                            ("pooled_f_CHF", "Pooled funds"),
                            ("ngo_CHF", "Non Governmental Organization"),
                            ("si_CHF", "Service Income"),
                            ("iga_CHF", "Income Generating Activity"),
                            ("KPI_incomeFromNSsLC_CHF", "Other National Society"),
                            ("ifrc_CHF", "Ifrc"),
                            ("icrc_CHF", "Icrc"),
                            ("other_CHF", "Other Source"),
                        ],
                        max_length=255,
                        verbose_name="indicator",
                    ),
                ),
                ("value", models.FloatField(blank=True, null=True, verbose_name="value")),
                (
                    "overview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databank.countryoverview",
                        verbose_name="country overview",
                    ),
                ),
            ],
        ),
    ]
