# Generated by Django 3.2.23 on 2024-02-02 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0019_countryoverview_hdr_gii'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDRSAnnualIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='value')),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databank.countryoverview', verbose_name='country overview')),
            ],
        ),
    ]
