# Generated by Django 3.2.25 on 2024-04-02 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0022_alter_fdrsincome_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDRSIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Indicator Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Indicator Descritpion')),
            ],
        ),
        migrations.AlterField(
            model_name='fdrsincome',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databank.fdrsindicator', verbose_name='FDRS Indicator'),
        ),
    ]
