# Generated by Django 4.2.16 on 2024-10-23 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0026_countryoverview_calculated_world_bank_gdp_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryoverview',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='calculated_world_bank_gdp_year',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='calculated_world_bank_gender_equality_index_year',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='calculated_world_bank_gni_capita_year',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='calculated_world_bank_gni_year',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='calculated_world_bank_life_expectancy_year',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='calculated_world_bank_literacy_rate_year',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='calculated_world_bank_population_above_age_65_year',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='calculated_world_bank_population_age_14_year',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='calculated_world_bank_population_year',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='calculated_world_bank_poverty_rate_year',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='calculated_world_bank_urban_population_percentage_year',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='expenditures',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='fdrs_data_fetched_year',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_staff_age_18_29',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_staff_age_18_49',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_staff_age_30_39',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_staff_age_40_49',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_staff_age_50_59',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_staff_age_60_69',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_staff_age_70_79',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_staff_age_80',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_staff_age_other',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_staff_total',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_volunteer_age_13_17',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_volunteer_age_18_29',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_volunteer_age_18_49',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_volunteer_age_30_39',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_volunteer_age_40_49',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_volunteer_age_50_59',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_volunteer_age_60_69',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_volunteer_age_6_12',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_volunteer_age_70_79',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_volunteer_age_80',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_volunteer_age_other',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='female_volunteer_total',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='gdp',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='gnipc',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='income',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='life_expectancy',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='literacy',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_staff_age_18_29',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_staff_age_18_49',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_staff_age_30_39',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_staff_age_40_49',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_staff_age_50_59',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_staff_age_60_69',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_staff_age_70_79',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_staff_age_80',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_staff_age_other',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_staff_total',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_volunteer_age_13_17',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_volunteer_age_18_29',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_volunteer_age_18_49',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_volunteer_age_30_39',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_volunteer_age_40_49',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_volunteer_age_50_59',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_volunteer_age_60_69',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_volunteer_age_6_12',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_volunteer_age_70_79',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_volunteer_age_80',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_volunteer_age_other',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='male_volunteer_total',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='population',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='poverty',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='staff_age_18_29',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='staff_total',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='trained_in_first_aid',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='urban_population',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='volunteer_age_13_17',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='volunteer_age_18_29',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='volunteer_age_6_12',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='volunteer_total',
        ),
        migrations.RemoveField(
            model_name='countryoverview',
            name='volunteers',
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_branches',
            field=models.IntegerField(blank=True, null=True, verbose_name='Branches'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_branches_data_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='branches data fetched year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_expenditures',
            field=models.FloatField(blank=True, null=True, verbose_name='expenditures (CHF)'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_expenditures_data_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='expenditures data fetched year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_staff_age_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 18 to 29'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_staff_age_18_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 18 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_staff_age_30_39',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 30 to 39'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_staff_age_40_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 40 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_staff_age_50_59',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 50 to 59'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_staff_age_60_69',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 60 to 69'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_staff_age_70_79',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 70 to 79'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_staff_age_80',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff age 80'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_staff_age_other',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff other'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_staff_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='female staff total'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_volunteer_age_13_17',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 13 to 17'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_volunteer_age_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 18 to 29'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_volunteer_age_18_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 18 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_volunteer_age_30_39',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 30 to 39'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_volunteer_age_40_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 40 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_volunteer_age_50_59',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 50 to 59'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_volunteer_age_60_69',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 60 to 69'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_volunteer_age_6_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 6 to 12'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_volunteer_age_70_79',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 70 to 79'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_volunteer_age_80',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer age 80'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_volunteer_age_other',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer other'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_female_volunteer_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='female volunteer total'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_gdp',
            field=models.FloatField(blank=True, null=True, verbose_name='GDP'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_gdp_data_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='GDP data fetched year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_gnipc',
            field=models.IntegerField(blank=True, null=True, verbose_name='GNI/CAPITA'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_gnipc_data_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='GNI/CAPITA data fetched year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_income',
            field=models.FloatField(blank=True, null=True, verbose_name='income (CHF)'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_income_data_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='income data fetched year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_life_expectancy',
            field=models.IntegerField(blank=True, null=True, verbose_name='life expectancy'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_life_expectancy_data_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='life expectancy data fetched year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_literacy',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='literacy (%)'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_literacy_data_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='literacy data fetched year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_staff_age_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 18 to 29'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_staff_age_18_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 18 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_staff_age_30_39',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 30 to 39'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_staff_age_40_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 40 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_staff_age_50_59',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 50 to 59'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_staff_age_60_69',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 60 to 69'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_staff_age_70_79',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 70 to 79'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_staff_age_80',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff age 80'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_staff_age_other',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff other'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_staff_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='male staff total'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_volunteer_age_13_17',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 13 to 17'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_volunteer_age_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 18 to 29'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_volunteer_age_18_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 18 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_volunteer_age_30_39',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 30 to 39'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_volunteer_age_40_49',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 40 to 49'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_volunteer_age_50_59',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 50 to 59'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_volunteer_age_60_69',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 60 to 69'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_volunteer_age_6_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 6 to 12'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_volunteer_age_70_79',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 70 to 79'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_volunteer_age_80',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer age 80'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_volunteer_age_other',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer other'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_male_volunteer_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='male volunteer total'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_population',
            field=models.IntegerField(blank=True, null=True, verbose_name='population'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_population_data_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='population data fetched year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_poverty',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='poverty (%)'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_poverty_data_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='poverty data fetched year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_staff_age_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='staff age 18 to 29'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_staff_data_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='staff data fetched year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_staff_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='staff total'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_trained_in_first_aid',
            field=models.IntegerField(blank=True, null=True, verbose_name='trained in first aid'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_trained_in_first_aid_data_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='trained in first aid data fetched year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_urban_population',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='urban POP (%)'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_urban_population_data_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='urban population data fetched year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_volunteer_age_13_17',
            field=models.IntegerField(blank=True, null=True, verbose_name='volunteer age 13 to 17'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_volunteer_age_18_29',
            field=models.IntegerField(blank=True, null=True, verbose_name='volunteer age 18 to 29'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_volunteer_age_6_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='volunteer age 6 to 12'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_volunteer_data_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='volunteer data fetched year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='fdrs_volunteer_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='volunteer total'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='world_bank_gdp_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='world bank gdp year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='world_bank_gender_equality_index_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='world bank gender equality index year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='world_bank_gni_capita_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='world bank gni capita year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='world_bank_gni_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='world bank gni year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='world_bank_life_expectancy_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='world bank life expectancy year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='world_bank_literacy_rate_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='world bank literacy rate year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='world_bank_population_above_age_65_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='world bank population above age 65 date in year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='world_bank_population_age_14_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='world bank population age 14 date in year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='world_bank_population_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='world bank population year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='world_bank_poverty_rate_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='world bank poverty rate year'),
        ),
        migrations.AddField(
            model_name='countryoverview',
            name='world_bank_urban_population_percentage_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='world bank urban population percentage year'),
        ),
    ]
