{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-elasticsearch
  labels:
    component: elasticsearch
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "ifrcgo-helm.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: http
  type: ClusterIP
{{- end }}