# Generated by Django 2.2.20 on 2021-08-12 09:49

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import dref.models
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0133_auto_20210729_1609'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifiedNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('shelter_and_basic_household_items', 'Shelter And Basic Household Items'), ('livelihoods', 'Livelihoods'), ('multipurpose_cash', 'Multipurpose Cash'), ('health', 'Health'), ('water_sanitation_hygiene', 'Water Sanitation Hygiene'), ('protection_gender_inculsion', 'Protection Gender Inculsion'), ('education', 'Education'), ('migration', 'Migration'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction Climate Adaptation And Recovery'), ('community_engagement_and _accountability', 'Community Engagement And Accountability'), ('environment_sustainability ', 'Environment Sustainability'), ('shelter_cluster_coordination', 'Shelter Cluster Coordination')], max_length=255, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='description')),
            ],
            options={
                'verbose_name': 'identified need',
                'verbose_name_plural': 'identified needs',
            },
        ),
        migrations.CreateModel(
            name='NationalSocietyAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ns_readiness', 'Ns Readiness'), ('assessment', 'Assessment'), ('coordination', 'Coordination'), ('resource_mobilization', 'Resource Mobilization'), ('activation_of_contingency', 'Activation Of Contingency'), ('national_society_eoc', 'National Society Eoc'), ('shelter_and_basic_household_items', 'Shelter And Basic Household Items'), ('livelihoods', 'Livelihoods'), ('multipurpose_cash', 'Multipurpose Cash'), ('health', 'Health'), ('water_sanitation_hygiene', 'Water Sanitation Hygiene'), ('protection_gender_inculsion', 'Protection Gender Inculsion'), ('education', 'Education'), ('migration', 'Migration'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction Climate Adaptation And Recovery'), ('community_engagement_and _accountability', 'Community Engagement And Accountability'), ('environment_sustainability ', 'Environment Sustainability'), ('other', 'Other')], max_length=255, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='description')),
            ],
            options={
                'verbose_name': 'national society action',
                'verbose_name_plural': 'national society actions',
            },
        ),
        migrations.CreateModel(
            name='PlannedIntervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('shelter_and_basic_household_items', 'Shelter And Basic Household Items'), ('livelihoods', 'Livelihoods'), ('multipurpose_cash', 'Multipurpose Cash'), ('health', 'Health'), ('water_sanitation_hygiene', 'Water Sanitation Hygiene'), ('protection_gender_inculsion', 'Protection Gender Inculsion'), ('education', 'Education'), ('migration', 'Migration'), ('risk_reduction_climate_adaptation_and_recovery_', 'Risk Reduction Climate Adaptation And Recovery'), ('secretariat_services', 'Secretariat Services'), ('national_society_strengthening', 'National Society Strengthening')], max_length=255, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='description')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='budget')),
                ('person_targated', models.IntegerField(blank=True, null=True, verbose_name='person targated')),
            ],
            options={
                'verbose_name': 'planned intervention',
                'verbose_name_plural': 'planned interventions',
            },
        ),
        migrations.CreateModel(
            name='Dref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('type_of_onset', enumfields.fields.EnumIntegerField(enum=dref.models.Dref.OnsetType, verbose_name='onset type')),
                ('disaster_category', enumfields.fields.EnumIntegerField(enum=dref.models.Dref.DisasterCategory, verbose_name='disaster category')),
                ('status', enumfields.fields.EnumIntegerField(blank=True, enum=dref.models.Dref.Status, null=True, verbose_name='status')),
                ('num_assisted', models.IntegerField(blank=True, null=True, verbose_name='number of assisted')),
                ('num_affected', models.IntegerField(blank=True, null=True, verbose_name='number of affected')),
                ('amount_requested', models.IntegerField(blank=True, null=True, verbose_name='amount requested')),
                ('emergency_appeal_planned', models.BooleanField(default=False, verbose_name='emergency appeal planned ')),
                ('event_map', models.FileField(blank=True, help_text='Map and other images of the event', null=True, storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to=dref.models.dref_document_path, verbose_name='event map')),
                ('event_date', models.DateField(blank=True, help_text='Date of event/Approximate date of impact', null=True, verbose_name='event date')),
                ('event_text', models.CharField(blank=True, max_length=500, verbose_name='event text')),
                ('ns_respond_date', models.DateField(blank=True, help_text='NS anticipatory actions started/NS response', null=True, verbose_name='ns respond date')),
                ('affect_same_area', models.BooleanField(default=False, help_text='Has a similar event affected the same areas in the past?')),
                ('affect_same_population', models.BooleanField(default=False, help_text='Did it affect the same population?')),
                ('affect_same_population_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='affect same population text')),
                ('ns_respond', models.BooleanField(default=False, help_text='Did NS respond')),
                ('ns_request_fund', models.BooleanField(default=False, help_text='Did the NS request funding from DREF?')),
                ('ns_request_text', models.CharField(blank=True, max_length=10, null=True, verbose_name='ns request text')),
                ('lessons_learned', models.CharField(blank=True, max_length=500, verbose_name='lessons learned')),
                ('event_description', models.CharField(blank=True, max_length=800, verbose_name='event description')),
                ('image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to='dref/%Y/%m/%d/', verbose_name='image')),
                ('anticipatory_actions', models.CharField(blank=True, help_text='Description of anticipatory actions or imminent disaster', max_length=800, verbose_name='anaticipatory actions')),
                ('event_scope', models.CharField(blank=True, help_text='Scope and scale of event', max_length=800, verbose_name='event scope')),
                ('government_requested_assistance', models.BooleanField(default=False, help_text='Has government requested assistance')),
                ('government_requested_assistance_date', models.DateField(blank=True, null=True, verbose_name='government requested assistance date')),
                ('national_authorities', models.CharField(blank=True, max_length=300, verbose_name='national authorities')),
                ('ifrc', models.CharField(blank=True, max_length=300, verbose_name='ifrc')),
                ('icrc', models.CharField(blank=True, max_length=300, verbose_name='icrc')),
                ('partner_national_society', models.CharField(blank=True, max_length=300, verbose_name='partner national society')),
                ('un_or_other_actor', models.CharField(blank=True, max_length=300, verbose_name='un or other')),
                ('major_coordination_mechanism', models.CharField(blank=True, help_text='List major coordination mechanisms in place', max_length=300, verbose_name='major coordination mechanism')),
                ('identified_gaps', models.CharField(blank=True, help_text='Any identified gaps/limitations in the assessment', max_length=300, verbose_name='identified gaps')),
                ('people_assisted', models.CharField(blank=True, max_length=300, verbose_name='people assisted')),
                ('selection_criteria', models.CharField(blank=True, help_text='Selection criteria for affected people', max_length=300, verbose_name='selection criteria')),
                ('entity_affected', models.CharField(blank=True, help_text='Protection, gender, Inclusion affected in this process', max_length=300, verbose_name='entity affected')),
                ('community_involved', models.TextField(blank=True, help_text='Community been involved in the analysis of the process', verbose_name='community involved')),
                ('women', models.IntegerField(blank=True, null=True, verbose_name='women')),
                ('men', models.IntegerField(blank=True, null=True, verbose_name='men')),
                ('girls', models.IntegerField(blank=True, help_text='Girls under 18', null=True, verbose_name='girls')),
                ('boys', models.IntegerField(blank=True, help_text='Boys under 18', null=True, verbose_name='boys')),
                ('disability_people_per', models.DecimalField(blank=True, decimal_places=1, help_text='Estimated % people disability', max_digits=3, null=True, verbose_name='disability people per')),
                ('people_per_urban_local', models.DecimalField(blank=True, decimal_places=1, help_text='Estimated % people Urban/Rural', max_digits=3, null=True, verbose_name='people per urban local')),
                ('people_targeted_with_early_actions', models.IntegerField(blank=True, help_text='Number of persons targeted with early actions', null=True, verbose_name='people targeted with early actions')),
                ('displaced_people', models.IntegerField(blank=True, help_text='Estimated number of displaced people', null=True, verbose_name='displaced people')),
                ('operation_objective', models.CharField(blank=True, help_text='Overall objective of the operation', max_length=400, verbose_name='operation objective')),
                ('response_strategy', models.CharField(blank=True, max_length=200, verbose_name='response strategy')),
                ('go_field_report_date', models.DateField(blank=True, null=True, verbose_name='go field report date')),
                ('ns_request_date', models.DateField(blank=True, null=True, verbose_name='ns request date')),
                ('submission_to_geneva', models.DateField(blank=True, null=True, verbose_name='submission to geneva')),
                ('date_of_approval', models.DateField(blank=True, null=True, verbose_name='date of approval')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('publishing_date', models.DateField(blank=True, null=True, verbose_name='publishing date')),
                ('operation_timeframe', models.IntegerField(blank=True, null=True, verbose_name='operation timeframe')),
                ('appeal_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='appeal code')),
                ('glide_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='glide number')),
                ('ifrc_appeal_manager_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ifrc appeal manager name')),
                ('ifrc_appeal_manager_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='ifrc appeal manager email')),
                ('ifrc_project_manager_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ifrc project manager name')),
                ('ifrc_project_manager_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='ifrc project manager email')),
                ('national_society_contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='national society contact name')),
                ('national_society_contact_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='national society contact email')),
                ('media_contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='media contact name')),
                ('media_contact_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='media contact email')),
                ('ifrc_emergency_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ifrc emergency name')),
                ('ifrc_emergency_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='ifrc emergency email')),
                ('originator_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='originator name')),
                ('originator_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='originator email')),
                ('human_resource', models.CharField(blank=True, help_text='how many volunteers and staff involved in the response?', max_length=300, verbose_name='human resource')),
                ('surge_personnel_deployed', models.CharField(blank=True, help_text='Will a Surge personnel be deployed?', max_length=500, verbose_name='surge personnel deployed')),
                ('logistic_capacity_of_ns', models.CharField(blank=True, help_text='what is the logistics capacity of the National Society?', max_length=500, verbose_name='logistic capacity of ns')),
                ('safety_concerns', models.CharField(blank=True, help_text='Are there any safety/security concerns which may impact the implementation of this operation?', max_length=500, verbose_name='safety concerns')),
                ('pmer', models.CharField(blank=True, help_text='Does the NS have PMER capacity?', max_length=500, verbose_name='pmer')),
                ('communication', models.CharField(blank=True, help_text='Does the NS have Communications capacity?', max_length=500, verbose_name='organization')),
                ('disaster_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.DisasterType', verbose_name='disaster type')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('national_society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country', verbose_name='national_society')),
                ('national_society_actions', models.ManyToManyField(blank=True, to='dref.NationalSocietyAction', verbose_name='national society actions')),
                ('needs_identified', models.ManyToManyField(blank=True, to='dref.IdentifiedNeed', verbose_name='needs identified')),
                ('planned_interventions', models.ManyToManyField(blank=True, to='dref.PlannedIntervention', verbose_name='planned intervention')),
            ],
            options={
                'verbose_name': 'dref',
                'verbose_name_plural': 'drefs',
            },
        ),
        migrations.CreateModel(
            name='DrefCountryDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(help_text='Affected County', on_delete=django.db.models.deletion.CASCADE, to='api.Country', verbose_name='country')),
                ('district', models.ManyToManyField(blank=True, to='api.District', verbose_name='district')),
                ('dref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dref.Dref', verbose_name='dref')),
            ],
            options={
                'unique_together': {('dref', 'country')},
            },
        ),
    ]
