# Generated by Django 2.2.20 on 2021-08-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dref',
            name='image',
        ),
    ]
