# Generated by Django 2.2.20 on 2021-08-25 06:20

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import dref.models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0002_remove_dref_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrefImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Images of the event', null=True, storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to=dref.models.image_path, verbose_name='image')),
                ('dref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dref.Dref', verbose_name='dref')),
            ],
        ),
    ]
