# Generated by Django 2.2.27 on 2022-04-04 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dref', '0003_auto_20220314_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrefFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dref/file-upload/', verbose_name='file')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
            ],
            options={
                'verbose_name': 'dref file upload',
                'verbose_name_plural': 'dref files upload',
            },
        ),
    ]
