# Generated by Django 2.2.20 on 2021-09-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0005_auto_20210830_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedintervention',
            name='indicator',
            field=models.CharField(blank=True, max_length=300, verbose_name='indicator'),
        ),
    ]
