# Generated by Django 2.2.27 on 2022-04-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0005_drefoperationalupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drefoperationalupdate',
            name='number_of_people_targated',
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='number_of_people_targeted',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of people targeted'),
        ),
    ]
