# Generated by Django 2.2.20 on 2021-09-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_auto_20210729_1609'),
        ('dref', '0006_plannedintervention_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='dref',
            name='field_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_report_dref', to='api.FieldReport', verbose_name='field report'),
        ),
    ]
