# Generated by Django 2.2.27 on 2022-04-19 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_merge_20220325_1027'),
        ('dref', '0007_drefoperationalupdate_entity_affected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drefoperationalupdate',
            name='country',
        ),
        migrations.RemoveField(
            model_name='drefoperationalupdate',
            name='district',
        ),
        migrations.CreateModel(
            name='DrefOperationalUpdateCountryDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(help_text='Affected County', on_delete=django.db.models.deletion.CASCADE, to='api.Country', verbose_name='country')),
                ('district', models.ManyToManyField(blank=True, to='api.District', verbose_name='district')),
                ('dref_operational_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dref.DrefOperationalUpdate', verbose_name='Dref Operational Update')),
            ],
            options={
                'unique_together': {('dref_operational_update', 'country')},
            },
        ),
    ]
