# Generated by Django 2.2.27 on 2022-04-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0008_auto_20220419_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drefoperationalupdate',
            name='parent',
        ),
    ]
