# Generated by Django 2.2.20 on 2021-09-29 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0010_auto_20210927_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dref',
            name='start_date',
        ),
        migrations.AddField(
            model_name='dref',
            name='total_targated_population',
            field=models.IntegerField(blank=True, help_text='Estimated number of targated people', null=True, verbose_name='total targated population'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='budget_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dref.DrefFile', verbose_name='budget file'),
        ),
    ]
