# Generated by Django 2.2.27 on 2022-06-13 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0011_plannedintervention_indicators"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drefoperationalupdate",
            name="change_since_request",
        ),
        migrations.AddField(
            model_name="drefoperationalupdate",
            name="anticipatory_actions",
            field=models.TextField(blank=True, null=True, verbose_name="Anticipatory actions"),
        ),
        migrations.AddField(
            model_name="drefoperationalupdate",
            name="budget_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_file_dref_operational_update",
                to="dref.DrefFile",
                verbose_name="budget file",
            ),
        ),
        migrations.AddField(
            model_name="drefoperationalupdate",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_image_dref_operational_update",
                to="dref.DrefFile",
                verbose_name="cover image",
            ),
        ),
        migrations.AddField(
            model_name="drefoperationalupdate",
            name="event_description",
            field=models.TextField(blank=True, null=True, verbose_name="Event description"),
        ),
        migrations.AddField(
            model_name="drefoperationalupdate",
            name="event_scope",
            field=models.TextField(blank=True, null=True, verbose_name="Event scope"),
        ),
        migrations.AddField(
            model_name="drefoperationalupdate",
            name="has_change_since_request",
            field=models.BooleanField(blank=True, null=True, verbose_name="Has change since request"),
        ),
    ]
