# Generated by Django 2.2.20 on 2021-10-20 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0012_auto_20211004_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedintervention',
            name='budget_file',
        ),
        migrations.AddField(
            model_name='dref',
            name='budget_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_file_dref', to='dref.DrefFile', verbose_name='budget file'),
        ),
        migrations.AddField(
            model_name='dref',
            name='ifrc_appeal_manager_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ifrc appeal manager phone number'),
        ),
        migrations.AddField(
            model_name='dref',
            name='ifrc_appeal_manager_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ifrc appeal manager title'),
        ),
        migrations.AddField(
            model_name='dref',
            name='ifrc_emergency_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ifrc emergency phone number'),
        ),
        migrations.AddField(
            model_name='dref',
            name='ifrc_emergency_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ifrc emergency title'),
        ),
        migrations.AddField(
            model_name='dref',
            name='ifrc_project_manager_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ifrc project manager phone number'),
        ),
        migrations.AddField(
            model_name='dref',
            name='ifrc_project_manager_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ifrc project manager title'),
        ),
        migrations.AddField(
            model_name='dref',
            name='media_contact_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='media_contact phone number'),
        ),
        migrations.AddField(
            model_name='dref',
            name='media_contact_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='media contact title'),
        ),
        migrations.AddField(
            model_name='dref',
            name='national_society_contact_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='national society contact phone number'),
        ),
        migrations.AddField(
            model_name='dref',
            name='national_society_contact_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='national society contact title'),
        ),
        migrations.AddField(
            model_name='dref',
            name='originator_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='originator phone number'),
        ),
        migrations.AddField(
            model_name='dref',
            name='originator_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='originator title'),
        ),
    ]
