# Generated by Django 2.2.27 on 2022-06-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0014_auto_20220616_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreffinalreport',
            name='number_of_people_affected',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of people affected'),
        ),
    ]
