# Generated by Django 2.2.20 on 2021-11-09 04:17

from django.db import migrations
import dref.models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0015_auto_20211026_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dref',
            name='disaster_category',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=dref.models.Dref.DisasterCategory, null=True, verbose_name='disaster category'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='type_of_onset',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=dref.models.Dref.OnsetType, null=True, verbose_name='onset type'),
        ),
    ]
