# Generated by Django 2.2.27 on 2022-06-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0015_dreffinalreport_number_of_people_affected'),
    ]

    operations = [
        migrations.AddField(
            model_name='dref',
            name='is_final_report_created',
            field=models.BooleanField(default=False, verbose_name='Is final report created'),
        ),
    ]
