# Generated by Django 2.2.27 on 2022-07-25 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0015_auto_20220708_0739'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dreffinalreportcountrydistrict',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dreffinalreportcountrydistrict',
            name='country',
        ),
        migrations.RemoveField(
            model_name='dreffinalreportcountrydistrict',
            name='district',
        ),
        migrations.RemoveField(
            model_name='dreffinalreportcountrydistrict',
            name='dref_final_report',
        ),
        migrations.AlterUniqueTogether(
            name='drefoperationalupdatecountrydistrict',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='drefoperationalupdatecountrydistrict',
            name='country',
        ),
        migrations.RemoveField(
            model_name='drefoperationalupdatecountrydistrict',
            name='district',
        ),
        migrations.RemoveField(
            model_name='drefoperationalupdatecountrydistrict',
            name='dref_operational_update',
        ),
        migrations.DeleteModel(
            name='DrefCountryDistrict',
        ),
        migrations.DeleteModel(
            name='DrefFinalReportCountryDistrict',
        ),
        migrations.DeleteModel(
            name='DrefOperationalUpdateCountryDistrict',
        ),
    ]
