# Generated by Django 2.2.20 on 2021-11-09 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0016_auto_20211109_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dref',
            name='anticipatory_actions',
            field=models.TextField(blank=True, help_text='Description of anticipatory actions or imminent disaster', null=True, verbose_name='anaticipatory actions'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='communication',
            field=models.TextField(blank=True, help_text='Does the NS have Communications capacity?', null=True, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='community_involved',
            field=models.TextField(blank=True, help_text='Community been involved in the analysis of the process', null=True, verbose_name='community involved'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='dref_recurrent_text',
            field=models.TextField(blank=True, null=True, verbose_name='dref recurrent text'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='entity_affected',
            field=models.TextField(blank=True, help_text='Protection, gender, Inclusion affected in this process', null=True, verbose_name='entity affected'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='event_description',
            field=models.TextField(blank=True, null=True, verbose_name='event description'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='event_scope',
            field=models.TextField(blank=True, help_text='Scope and scale of event', null=True, verbose_name='event scope'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='event_text',
            field=models.TextField(blank=True, null=True, verbose_name='event text'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='human_resource',
            field=models.TextField(blank=True, help_text='how many volunteers and staff involved in the response?', null=True, verbose_name='human resource'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='icrc',
            field=models.TextField(blank=True, null=True, verbose_name='icrc'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='identified_gaps',
            field=models.TextField(blank=True, help_text='Any identified gaps/limitations in the assessment', null=True, verbose_name='identified gaps'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='ifrc',
            field=models.TextField(blank=True, null=True, verbose_name='ifrc'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='lessons_learned',
            field=models.TextField(blank=True, null=True, verbose_name='lessons learned'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='logistic_capacity_of_ns',
            field=models.TextField(blank=True, help_text='what is the logistics capacity of the National Society?', null=True, verbose_name='logistic capacity of ns'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='major_coordination_mechanism',
            field=models.TextField(blank=True, help_text='List major coordination mechanisms in place', null=True, verbose_name='major coordination mechanism'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='national_authorities',
            field=models.TextField(blank=True, null=True, verbose_name='national authorities'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='national_society',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Country', verbose_name='national_society'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dref',
            name='operation_objective',
            field=models.TextField(blank=True, help_text='Overall objective of the operation', null=True, verbose_name='operation objective'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='partner_national_society',
            field=models.TextField(blank=True, null=True, verbose_name='partner national society'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='people_assisted',
            field=models.TextField(blank=True, null=True, verbose_name='people assisted'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='pmer',
            field=models.TextField(blank=True, help_text='Does the NS have PMER capacity?', null=True, verbose_name='pmer'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='response_strategy',
            field=models.TextField(blank=True, null=True, verbose_name='response strategy'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='safety_concerns',
            field=models.TextField(blank=True, help_text='Are there any safety/security concerns which may impact the implementation of this operation?', null=True, verbose_name='safety concerns'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='selection_criteria',
            field=models.TextField(blank=True, help_text='Selection criteria for affected people', null=True, verbose_name='selection criteria'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='surge_personnel_deployed',
            field=models.TextField(blank=True, help_text='Will a Surge personnel be deployed?', null=True, verbose_name='surge personnel deployed'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='un_or_other_actor',
            field=models.TextField(blank=True, null=True, verbose_name='un or other'),
        ),
        migrations.AlterField(
            model_name='identifiedneed',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='nationalsocietyaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='plannedintervention',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='plannedintervention',
            name='indicator',
            field=models.TextField(blank=True, null=True, verbose_name='indicator'),
        ),
    ]
