# Generated by Django 2.2.27 on 2022-07-25 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_appealfilter_comment'),
        ('dref', '0016_auto_20220725_0445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dreffinalreport',
            options={'verbose_name': 'Dref Final Report', 'verbose_name_plural': 'Dref Final Reports'},
        ),
        migrations.RemoveField(
            model_name='dref',
            name='go_field_report_date',
        ),
        migrations.AddField(
            model_name='dref',
            name='assessment_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dref_assessment_report', to='dref.DrefFile', verbose_name='Assessment Report'),
        ),
        migrations.AddField(
            model_name='dref',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Affected County', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dref_country', to='api.Country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='dref',
            name='district',
            field=models.ManyToManyField(blank=True, to='api.District', verbose_name='district'),
        ),
        migrations.AddField(
            model_name='dreffile',
            name='caption',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='dreffile',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='assessment_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dref_final_report_assessment_report', to='dref.DrefFile', verbose_name='Assessment Report'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Affected County', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_report_country', to='api.Country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='district',
            field=models.ManyToManyField(blank=True, to='api.District', verbose_name='district'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='assessment_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dref_operational_update_assessment_report', to='dref.DrefFile', verbose_name='Assessment Report'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Affected County', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_update_country', to='api.Country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='district',
            field=models.ManyToManyField(blank=True, to='api.District', verbose_name='district'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='is_there_major_coordination_mechanism',
            field=models.BooleanField(blank=True, help_text='Is there major coordinate mechanism', null=True),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='is_there_un_or_other_actor',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is there un_or_other_actor'),
        ),
        migrations.AlterField(
            model_name='identifiedneed',
            name='title',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration', 'Migration'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and _accountability', 'Community Engagement And Accountability'), ('environment_sustainability ', 'Environment Sustainability'), ('shelter_cluster_coordination', 'Shelter Cluster Coordination'), ('multi-purpose_cash', 'Multi-purpose Cash')], max_length=255, verbose_name='title'),
        ),
    ]
