# Generated by Django 2.2.27 on 2022-06-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0017_dreffinalreport_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreffinalreport',
            name='dref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dref.Dref', verbose_name='Dref'),
        ),
    ]
