# Generated by Django 2.2.24 on 2021-12-16 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0018_auto_20211109_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='dref',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_image_dref', to='dref.DrefFile', verbose_name='cover image'),
        ),
    ]
