# Generated by Django 2.2.27 on 2022-07-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0018_auto_20220630_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannedintervention',
            old_name='challanges',
            new_name='challenges',
        ),
    ]
