# Generated by Django 2.2.24 on 2021-12-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0020_dref_budget_file_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifiedneed',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='image_url'),
        ),
        migrations.AddField(
            model_name='nationalsocietyaction',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='image_url'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='image_url'),
        ),
    ]
