# Generated by Django 2.2.27 on 2022-08-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0024_auto_20220728_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='dref',
            name='title_prefix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='title_prefix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='title_prefix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AlterField(
            model_name='dref',
            name='risk_security_concern',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
    ]
