# Generated by Django 2.2.27 on 2022-08-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0030_dref_is_assessment_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dref",
            name="is_man_made_event",
            field=models.BooleanField(blank=True, null=True, verbose_name="Is Man-made Event"),
        ),
    ]
