# Generated by Django 2.2.27 on 2022-09-07 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dref', '0032_auto_20220824_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='anticipatory_to_response',
            field=models.TextField(blank=True, null=True, verbose_name='Please explain how is the operation is transitioning from Anticipatory to Response'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='event_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_map_dref_operational_update', to='dref.DrefFile', verbose_name='event map'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='has_forcasted_event_materialize',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has Forcasted Event Materialize'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='risk_security',
            field=models.ManyToManyField(blank=True, to='dref.RiskSecurity', verbose_name='Risk Security'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='risk_security_concern',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='specified_trigger_met',
            field=models.TextField(blank=True, null=True, verbose_name='Specified Trigger Met'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_dref_operational_update', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
