# Generated by Django 2.2.27 on 2022-08-26 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0033_dreffileupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreffileupload",
            name="dref",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dref.Dref", verbose_name="Dref"
            ),
        ),
    ]
