# Generated by Django 2.2.28 on 2022-09-14 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0035_merge_20220914_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dref',
            name='national_society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Country', verbose_name='national_society'),
        ),
    ]
