# Generated by Django 2.2.28 on 2022-09-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0036_auto_20220914_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiedneed',
            name='title',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration', 'Migration'), ('multi_purpose_cash_grants', 'Multi purpose cash grants'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and _accountability', 'Community Engagement And Accountability'), ('environment_sustainability ', 'Environment Sustainability'), ('shelter_cluster_coordination', 'Shelter Cluster Coordination')], max_length=255, verbose_name='title'),
        ),
    ]
