# Generated by Django 2.2.28 on 2022-09-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0037_auto_20220915_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dref',
            name='national_society',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Country', verbose_name='national_society'),
            preserve_default=False,
        ),
    ]
