# Generated by Django 3.2.15 on 2022-10-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0039_alter_dref_field_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='event_date',
            field=models.DateField(blank=True, help_text='Date of event/Approximate date of impact', null=True, verbose_name='event date'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='has_event_occured',
            field=models.BooleanField(blank=True, help_text='Has Event occured', null=True),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='ns_respond',
            field=models.BooleanField(blank=True, default=False, help_text='Did NS respond', null=True),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='ns_respond_date',
            field=models.DateField(blank=True, help_text='NS anticipatory actions started/NS response', null=True, verbose_name='ns respond date'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='people_in_need',
            field=models.IntegerField(blank=True, null=True, verbose_name='people in need'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='reporting_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Reporting Time End Date'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='reporting_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Reporting Time Start Date'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='total_targeted_population',
            field=models.IntegerField(blank=True, help_text='Estimated number of targeted people', null=True, verbose_name='total targeted population'),
        ),
    ]
