# Generated by Django 3.2.16 on 2022-12-02 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dref', '0045_alter_dref_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreffinalreport',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_image_dref_final_report', to='dref.dreffile', verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='image_dref_final_report', to='dref.DrefFile', verbose_name='images'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='is_assessment_report',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is assessment Report'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='is_there_major_coordination_mechanism',
            field=models.BooleanField(blank=True, help_text='Is there major coordinate mechanism', null=True),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='risk_security',
            field=models.ManyToManyField(blank=True, to='dref.RiskSecurity', verbose_name='Risk Security'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='risk_security_concern',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='total_targeted_population',
            field=models.IntegerField(blank=True, null=True, verbose_name='total targeted population'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_dref_final_report', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
