# Generated by Django 3.2.16 on 2022-12-27 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0048_auto_20221213_0402"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dreffinalreport",
            name="budget_file",
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="financial_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="financial_report_dref_final_report",
                to="dref.dreffile",
                verbose_name="financial report",
            ),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="financial_report_description",
            field=models.TextField(blank=True, null=True, verbose_name="Financial Report Description"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="has_national_society_conducted",
            field=models.BooleanField(blank=True, null=True, verbose_name="Has national society conducted any intervention"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="national_society_conducted_description",
            field=models.TextField(blank=True, null=True, verbose_name="National Society conducted description"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="num_assisted",
            field=models.IntegerField(blank=True, null=True, verbose_name="number of assisted"),
        ),
        migrations.AddField(
            model_name="plannedintervention",
            name="person_assisted",
            field=models.IntegerField(blank=True, null=True, verbose_name="person assisted"),
        ),
    ]
