# Generated by Django 3.2.18 on 2023-03-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0053_auto_20230313_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dref',
            name='type_of_dref',
            field=models.IntegerField(blank=True, choices=[(0, 'Imminent'), (1, 'Assessment'), (2, 'Response'), (3, 'Loan')], null=True, verbose_name='dref type'),
        ),
        migrations.AlterField(
            model_name='dreffinalreport',
            name='type_of_dref',
            field=models.IntegerField(blank=True, choices=[(0, 'Imminent'), (1, 'Assessment'), (2, 'Response'), (3, 'Loan')], null=True, verbose_name='dref type'),
        ),
        migrations.AlterField(
            model_name='drefoperationalupdate',
            name='type_of_dref',
            field=models.IntegerField(blank=True, choices=[(0, 'Imminent'), (1, 'Assessment'), (2, 'Response'), (3, 'Loan')], null=True, verbose_name='dref type'),
        ),
    ]
