# Generated by Django 3.2.18 on 2023-04-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0056_auto_20230410_0720"),
        ("dref", "0056_auto_20230418_0703"),
    ]

    operations = []
