# Generated by Django 3.2.18 on 2023-04-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0057_merge_0056_auto_20230410_0720_0056_auto_20230418_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='dref',
            name='anticipatory_actions_ar',
            field=models.TextField(blank=True, help_text='Description of anticipatory actions or imminent disaster', null=True, verbose_name='anticipatory actions'),
        ),
        migrations.AddField(
            model_name='dref',
            name='anticipatory_actions_en',
            field=models.TextField(blank=True, help_text='Description of anticipatory actions or imminent disaster', null=True, verbose_name='anticipatory actions'),
        ),
        migrations.AddField(
            model_name='dref',
            name='anticipatory_actions_es',
            field=models.TextField(blank=True, help_text='Description of anticipatory actions or imminent disaster', null=True, verbose_name='anticipatory actions'),
        ),
        migrations.AddField(
            model_name='dref',
            name='anticipatory_actions_fr',
            field=models.TextField(blank=True, help_text='Description of anticipatory actions or imminent disaster', null=True, verbose_name='anticipatory actions'),
        ),
        migrations.AddField(
            model_name='dref',
            name='communication_ar',
            field=models.TextField(blank=True, help_text='Does the NS have Communications capacity?', null=True, verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='dref',
            name='communication_en',
            field=models.TextField(blank=True, help_text='Does the NS have Communications capacity?', null=True, verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='dref',
            name='communication_es',
            field=models.TextField(blank=True, help_text='Does the NS have Communications capacity?', null=True, verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='dref',
            name='communication_fr',
            field=models.TextField(blank=True, help_text='Does the NS have Communications capacity?', null=True, verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='dref',
            name='dref_recurrent_text_ar',
            field=models.TextField(blank=True, null=True, verbose_name='dref recurrent text'),
        ),
        migrations.AddField(
            model_name='dref',
            name='dref_recurrent_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='dref recurrent text'),
        ),
        migrations.AddField(
            model_name='dref',
            name='dref_recurrent_text_es',
            field=models.TextField(blank=True, null=True, verbose_name='dref recurrent text'),
        ),
        migrations.AddField(
            model_name='dref',
            name='dref_recurrent_text_fr',
            field=models.TextField(blank=True, null=True, verbose_name='dref recurrent text'),
        ),
        migrations.AddField(
            model_name='dref',
            name='event_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='event description'),
        ),
        migrations.AddField(
            model_name='dref',
            name='event_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='event description'),
        ),
        migrations.AddField(
            model_name='dref',
            name='event_description_es',
            field=models.TextField(blank=True, null=True, verbose_name='event description'),
        ),
        migrations.AddField(
            model_name='dref',
            name='event_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='event description'),
        ),
        migrations.AddField(
            model_name='dref',
            name='event_scope_ar',
            field=models.TextField(blank=True, help_text='Scope and scale of event', null=True, verbose_name='event scope'),
        ),
        migrations.AddField(
            model_name='dref',
            name='event_scope_en',
            field=models.TextField(blank=True, help_text='Scope and scale of event', null=True, verbose_name='event scope'),
        ),
        migrations.AddField(
            model_name='dref',
            name='event_scope_es',
            field=models.TextField(blank=True, help_text='Scope and scale of event', null=True, verbose_name='event scope'),
        ),
        migrations.AddField(
            model_name='dref',
            name='event_scope_fr',
            field=models.TextField(blank=True, help_text='Scope and scale of event', null=True, verbose_name='event scope'),
        ),
        migrations.AddField(
            model_name='dref',
            name='event_text_ar',
            field=models.TextField(blank=True, null=True, verbose_name='event text'),
        ),
        migrations.AddField(
            model_name='dref',
            name='event_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='event text'),
        ),
        migrations.AddField(
            model_name='dref',
            name='event_text_es',
            field=models.TextField(blank=True, null=True, verbose_name='event text'),
        ),
        migrations.AddField(
            model_name='dref',
            name='event_text_fr',
            field=models.TextField(blank=True, null=True, verbose_name='event text'),
        ),
        migrations.AddField(
            model_name='dref',
            name='human_resource_ar',
            field=models.TextField(blank=True, help_text='how many volunteers and staff involved in the response?', null=True, verbose_name='human resource'),
        ),
        migrations.AddField(
            model_name='dref',
            name='human_resource_en',
            field=models.TextField(blank=True, help_text='how many volunteers and staff involved in the response?', null=True, verbose_name='human resource'),
        ),
        migrations.AddField(
            model_name='dref',
            name='human_resource_es',
            field=models.TextField(blank=True, help_text='how many volunteers and staff involved in the response?', null=True, verbose_name='human resource'),
        ),
        migrations.AddField(
            model_name='dref',
            name='human_resource_fr',
            field=models.TextField(blank=True, help_text='how many volunteers and staff involved in the response?', null=True, verbose_name='human resource'),
        ),
        migrations.AddField(
            model_name='dref',
            name='icrc_ar',
            field=models.TextField(blank=True, null=True, verbose_name='icrc'),
        ),
        migrations.AddField(
            model_name='dref',
            name='icrc_en',
            field=models.TextField(blank=True, null=True, verbose_name='icrc'),
        ),
        migrations.AddField(
            model_name='dref',
            name='icrc_es',
            field=models.TextField(blank=True, null=True, verbose_name='icrc'),
        ),
        migrations.AddField(
            model_name='dref',
            name='icrc_fr',
            field=models.TextField(blank=True, null=True, verbose_name='icrc'),
        ),
        migrations.AddField(
            model_name='dref',
            name='identified_gaps_ar',
            field=models.TextField(blank=True, help_text='Any identified gaps/limitations in the assessment', null=True, verbose_name='identified gaps'),
        ),
        migrations.AddField(
            model_name='dref',
            name='identified_gaps_en',
            field=models.TextField(blank=True, help_text='Any identified gaps/limitations in the assessment', null=True, verbose_name='identified gaps'),
        ),
        migrations.AddField(
            model_name='dref',
            name='identified_gaps_es',
            field=models.TextField(blank=True, help_text='Any identified gaps/limitations in the assessment', null=True, verbose_name='identified gaps'),
        ),
        migrations.AddField(
            model_name='dref',
            name='identified_gaps_fr',
            field=models.TextField(blank=True, help_text='Any identified gaps/limitations in the assessment', null=True, verbose_name='identified gaps'),
        ),
        migrations.AddField(
            model_name='dref',
            name='ifrc_ar',
            field=models.TextField(blank=True, null=True, verbose_name='ifrc'),
        ),
        migrations.AddField(
            model_name='dref',
            name='ifrc_en',
            field=models.TextField(blank=True, null=True, verbose_name='ifrc'),
        ),
        migrations.AddField(
            model_name='dref',
            name='ifrc_es',
            field=models.TextField(blank=True, null=True, verbose_name='ifrc'),
        ),
        migrations.AddField(
            model_name='dref',
            name='ifrc_fr',
            field=models.TextField(blank=True, null=True, verbose_name='ifrc'),
        ),
        migrations.AddField(
            model_name='dref',
            name='lessons_learned_ar',
            field=models.TextField(blank=True, null=True, verbose_name='lessons learned'),
        ),
        migrations.AddField(
            model_name='dref',
            name='lessons_learned_en',
            field=models.TextField(blank=True, null=True, verbose_name='lessons learned'),
        ),
        migrations.AddField(
            model_name='dref',
            name='lessons_learned_es',
            field=models.TextField(blank=True, null=True, verbose_name='lessons learned'),
        ),
        migrations.AddField(
            model_name='dref',
            name='lessons_learned_fr',
            field=models.TextField(blank=True, null=True, verbose_name='lessons learned'),
        ),
        migrations.AddField(
            model_name='dref',
            name='logistic_capacity_of_ns_ar',
            field=models.TextField(blank=True, help_text='what is the logistics capacity of the National Society?', null=True, verbose_name='logistic capacity of ns'),
        ),
        migrations.AddField(
            model_name='dref',
            name='logistic_capacity_of_ns_en',
            field=models.TextField(blank=True, help_text='what is the logistics capacity of the National Society?', null=True, verbose_name='logistic capacity of ns'),
        ),
        migrations.AddField(
            model_name='dref',
            name='logistic_capacity_of_ns_es',
            field=models.TextField(blank=True, help_text='what is the logistics capacity of the National Society?', null=True, verbose_name='logistic capacity of ns'),
        ),
        migrations.AddField(
            model_name='dref',
            name='logistic_capacity_of_ns_fr',
            field=models.TextField(blank=True, help_text='what is the logistics capacity of the National Society?', null=True, verbose_name='logistic capacity of ns'),
        ),
        migrations.AddField(
            model_name='dref',
            name='major_coordination_mechanism_ar',
            field=models.TextField(blank=True, help_text='List major coordination mechanisms in place', null=True, verbose_name='major coordination mechanism'),
        ),
        migrations.AddField(
            model_name='dref',
            name='major_coordination_mechanism_en',
            field=models.TextField(blank=True, help_text='List major coordination mechanisms in place', null=True, verbose_name='major coordination mechanism'),
        ),
        migrations.AddField(
            model_name='dref',
            name='major_coordination_mechanism_es',
            field=models.TextField(blank=True, help_text='List major coordination mechanisms in place', null=True, verbose_name='major coordination mechanism'),
        ),
        migrations.AddField(
            model_name='dref',
            name='major_coordination_mechanism_fr',
            field=models.TextField(blank=True, help_text='List major coordination mechanisms in place', null=True, verbose_name='major coordination mechanism'),
        ),
        migrations.AddField(
            model_name='dref',
            name='national_authorities_ar',
            field=models.TextField(blank=True, null=True, verbose_name='national authorities'),
        ),
        migrations.AddField(
            model_name='dref',
            name='national_authorities_en',
            field=models.TextField(blank=True, null=True, verbose_name='national authorities'),
        ),
        migrations.AddField(
            model_name='dref',
            name='national_authorities_es',
            field=models.TextField(blank=True, null=True, verbose_name='national authorities'),
        ),
        migrations.AddField(
            model_name='dref',
            name='national_authorities_fr',
            field=models.TextField(blank=True, null=True, verbose_name='national authorities'),
        ),
        migrations.AddField(
            model_name='dref',
            name='ns_request_text_ar',
            field=models.TextField(blank=True, null=True, verbose_name='ns request text'),
        ),
        migrations.AddField(
            model_name='dref',
            name='ns_request_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='ns request text'),
        ),
        migrations.AddField(
            model_name='dref',
            name='ns_request_text_es',
            field=models.TextField(blank=True, null=True, verbose_name='ns request text'),
        ),
        migrations.AddField(
            model_name='dref',
            name='ns_request_text_fr',
            field=models.TextField(blank=True, null=True, verbose_name='ns request text'),
        ),
        migrations.AddField(
            model_name='dref',
            name='operation_objective_ar',
            field=models.TextField(blank=True, help_text='Overall objective of the operation', null=True, verbose_name='operation objective'),
        ),
        migrations.AddField(
            model_name='dref',
            name='operation_objective_en',
            field=models.TextField(blank=True, help_text='Overall objective of the operation', null=True, verbose_name='operation objective'),
        ),
        migrations.AddField(
            model_name='dref',
            name='operation_objective_es',
            field=models.TextField(blank=True, help_text='Overall objective of the operation', null=True, verbose_name='operation objective'),
        ),
        migrations.AddField(
            model_name='dref',
            name='operation_objective_fr',
            field=models.TextField(blank=True, help_text='Overall objective of the operation', null=True, verbose_name='operation objective'),
        ),
        migrations.AddField(
            model_name='dref',
            name='partner_national_society_ar',
            field=models.TextField(blank=True, null=True, verbose_name='partner national society'),
        ),
        migrations.AddField(
            model_name='dref',
            name='partner_national_society_en',
            field=models.TextField(blank=True, null=True, verbose_name='partner national society'),
        ),
        migrations.AddField(
            model_name='dref',
            name='partner_national_society_es',
            field=models.TextField(blank=True, null=True, verbose_name='partner national society'),
        ),
        migrations.AddField(
            model_name='dref',
            name='partner_national_society_fr',
            field=models.TextField(blank=True, null=True, verbose_name='partner national society'),
        ),
        migrations.AddField(
            model_name='dref',
            name='people_assisted_ar',
            field=models.TextField(blank=True, null=True, verbose_name='people assisted'),
        ),
        migrations.AddField(
            model_name='dref',
            name='people_assisted_en',
            field=models.TextField(blank=True, null=True, verbose_name='people assisted'),
        ),
        migrations.AddField(
            model_name='dref',
            name='people_assisted_es',
            field=models.TextField(blank=True, null=True, verbose_name='people assisted'),
        ),
        migrations.AddField(
            model_name='dref',
            name='people_assisted_fr',
            field=models.TextField(blank=True, null=True, verbose_name='people assisted'),
        ),
        migrations.AddField(
            model_name='dref',
            name='pmer_ar',
            field=models.TextField(blank=True, help_text='Does the NS have PMER capacity?', null=True, verbose_name='pmer'),
        ),
        migrations.AddField(
            model_name='dref',
            name='pmer_en',
            field=models.TextField(blank=True, help_text='Does the NS have PMER capacity?', null=True, verbose_name='pmer'),
        ),
        migrations.AddField(
            model_name='dref',
            name='pmer_es',
            field=models.TextField(blank=True, help_text='Does the NS have PMER capacity?', null=True, verbose_name='pmer'),
        ),
        migrations.AddField(
            model_name='dref',
            name='pmer_fr',
            field=models.TextField(blank=True, help_text='Does the NS have PMER capacity?', null=True, verbose_name='pmer'),
        ),
        migrations.AddField(
            model_name='dref',
            name='response_strategy_ar',
            field=models.TextField(blank=True, null=True, verbose_name='response strategy'),
        ),
        migrations.AddField(
            model_name='dref',
            name='response_strategy_en',
            field=models.TextField(blank=True, null=True, verbose_name='response strategy'),
        ),
        migrations.AddField(
            model_name='dref',
            name='response_strategy_es',
            field=models.TextField(blank=True, null=True, verbose_name='response strategy'),
        ),
        migrations.AddField(
            model_name='dref',
            name='response_strategy_fr',
            field=models.TextField(blank=True, null=True, verbose_name='response strategy'),
        ),
        migrations.AddField(
            model_name='dref',
            name='risk_security_concern_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
        migrations.AddField(
            model_name='dref',
            name='risk_security_concern_en',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
        migrations.AddField(
            model_name='dref',
            name='risk_security_concern_es',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
        migrations.AddField(
            model_name='dref',
            name='risk_security_concern_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
        migrations.AddField(
            model_name='dref',
            name='selection_criteria_ar',
            field=models.TextField(blank=True, help_text='Selection criteria for affected people', null=True, verbose_name='selection criteria'),
        ),
        migrations.AddField(
            model_name='dref',
            name='selection_criteria_en',
            field=models.TextField(blank=True, help_text='Selection criteria for affected people', null=True, verbose_name='selection criteria'),
        ),
        migrations.AddField(
            model_name='dref',
            name='selection_criteria_es',
            field=models.TextField(blank=True, help_text='Selection criteria for affected people', null=True, verbose_name='selection criteria'),
        ),
        migrations.AddField(
            model_name='dref',
            name='selection_criteria_fr',
            field=models.TextField(blank=True, help_text='Selection criteria for affected people', null=True, verbose_name='selection criteria'),
        ),
        migrations.AddField(
            model_name='dref',
            name='surge_personnel_deployed_ar',
            field=models.TextField(blank=True, help_text='Will a Surge personnel be deployed?', null=True, verbose_name='surge personnel deployed'),
        ),
        migrations.AddField(
            model_name='dref',
            name='surge_personnel_deployed_en',
            field=models.TextField(blank=True, help_text='Will a Surge personnel be deployed?', null=True, verbose_name='surge personnel deployed'),
        ),
        migrations.AddField(
            model_name='dref',
            name='surge_personnel_deployed_es',
            field=models.TextField(blank=True, help_text='Will a Surge personnel be deployed?', null=True, verbose_name='surge personnel deployed'),
        ),
        migrations.AddField(
            model_name='dref',
            name='surge_personnel_deployed_fr',
            field=models.TextField(blank=True, help_text='Will a Surge personnel be deployed?', null=True, verbose_name='surge personnel deployed'),
        ),
        migrations.AddField(
            model_name='dref',
            name='title_prefix_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AddField(
            model_name='dref',
            name='title_prefix_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AddField(
            model_name='dref',
            name='title_prefix_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AddField(
            model_name='dref',
            name='title_prefix_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AddField(
            model_name='dref',
            name='un_or_other_actor_ar',
            field=models.TextField(blank=True, null=True, verbose_name='un or other'),
        ),
        migrations.AddField(
            model_name='dref',
            name='un_or_other_actor_en',
            field=models.TextField(blank=True, null=True, verbose_name='un or other'),
        ),
        migrations.AddField(
            model_name='dref',
            name='un_or_other_actor_es',
            field=models.TextField(blank=True, null=True, verbose_name='un or other'),
        ),
        migrations.AddField(
            model_name='dref',
            name='un_or_other_actor_fr',
            field=models.TextField(blank=True, null=True, verbose_name='un or other'),
        ),
        migrations.AddField(
            model_name='dreffile',
            name='caption_ar',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='dreffile',
            name='caption_en',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='dreffile',
            name='caption_es',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='dreffile',
            name='caption_fr',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='dreffile',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='dreffile',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='anticipatory_actions_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Anticipatory actions'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='anticipatory_actions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Anticipatory actions'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='anticipatory_actions_es',
            field=models.TextField(blank=True, null=True, verbose_name='Anticipatory actions'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='anticipatory_actions_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Anticipatory actions'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='event_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Event description'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='event_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Event description'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='event_description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Event description'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='event_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Event description'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='event_scope_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Event scope'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='event_scope_en',
            field=models.TextField(blank=True, null=True, verbose_name='Event scope'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='event_scope_es',
            field=models.TextField(blank=True, null=True, verbose_name='Event scope'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='event_scope_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Event scope'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='event_text_ar',
            field=models.TextField(blank=True, null=True, verbose_name='event text'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='event_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='event text'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='event_text_es',
            field=models.TextField(blank=True, null=True, verbose_name='event text'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='event_text_fr',
            field=models.TextField(blank=True, null=True, verbose_name='event text'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='financial_report_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Financial Report Description'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='financial_report_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Financial Report Description'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='financial_report_description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Financial Report Description'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='financial_report_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Financial Report Description'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='icrc_ar',
            field=models.TextField(blank=True, null=True, verbose_name='icrc'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='icrc_en',
            field=models.TextField(blank=True, null=True, verbose_name='icrc'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='icrc_es',
            field=models.TextField(blank=True, null=True, verbose_name='icrc'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='icrc_fr',
            field=models.TextField(blank=True, null=True, verbose_name='icrc'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='ifrc_ar',
            field=models.TextField(blank=True, null=True, verbose_name='ifrc'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='ifrc_en',
            field=models.TextField(blank=True, null=True, verbose_name='ifrc'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='ifrc_es',
            field=models.TextField(blank=True, null=True, verbose_name='ifrc'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='ifrc_fr',
            field=models.TextField(blank=True, null=True, verbose_name='ifrc'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='major_coordination_mechanism_ar',
            field=models.TextField(blank=True, null=True, verbose_name='major coordination mechanism'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='major_coordination_mechanism_en',
            field=models.TextField(blank=True, null=True, verbose_name='major coordination mechanism'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='major_coordination_mechanism_es',
            field=models.TextField(blank=True, null=True, verbose_name='major coordination mechanism'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='major_coordination_mechanism_fr',
            field=models.TextField(blank=True, null=True, verbose_name='major coordination mechanism'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='national_authorities_ar',
            field=models.TextField(blank=True, null=True, verbose_name='national authorities'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='national_authorities_en',
            field=models.TextField(blank=True, null=True, verbose_name='national authorities'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='national_authorities_es',
            field=models.TextField(blank=True, null=True, verbose_name='national authorities'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='national_authorities_fr',
            field=models.TextField(blank=True, null=True, verbose_name='national authorities'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='national_society_conducted_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='National Society conducted description'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='national_society_conducted_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='National Society conducted description'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='national_society_conducted_description_es',
            field=models.TextField(blank=True, null=True, verbose_name='National Society conducted description'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='national_society_conducted_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='National Society conducted description'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='operation_objective_ar',
            field=models.TextField(blank=True, null=True, verbose_name='operation objective'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='operation_objective_en',
            field=models.TextField(blank=True, null=True, verbose_name='operation objective'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='operation_objective_es',
            field=models.TextField(blank=True, null=True, verbose_name='operation objective'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='operation_objective_fr',
            field=models.TextField(blank=True, null=True, verbose_name='operation objective'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='partner_national_society_ar',
            field=models.TextField(blank=True, null=True, verbose_name='partner national society'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='partner_national_society_en',
            field=models.TextField(blank=True, null=True, verbose_name='partner national society'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='partner_national_society_es',
            field=models.TextField(blank=True, null=True, verbose_name='partner national society'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='partner_national_society_fr',
            field=models.TextField(blank=True, null=True, verbose_name='partner national society'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='response_strategy_ar',
            field=models.TextField(blank=True, null=True, verbose_name='response strategy'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='response_strategy_en',
            field=models.TextField(blank=True, null=True, verbose_name='response strategy'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='response_strategy_es',
            field=models.TextField(blank=True, null=True, verbose_name='response strategy'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='response_strategy_fr',
            field=models.TextField(blank=True, null=True, verbose_name='response strategy'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='risk_security_concern_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='risk_security_concern_en',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='risk_security_concern_es',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='risk_security_concern_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='selection_criteria_ar',
            field=models.TextField(blank=True, help_text='Selection criteria for affected people', null=True, verbose_name='selection criteria'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='selection_criteria_en',
            field=models.TextField(blank=True, help_text='Selection criteria for affected people', null=True, verbose_name='selection criteria'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='selection_criteria_es',
            field=models.TextField(blank=True, help_text='Selection criteria for affected people', null=True, verbose_name='selection criteria'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='selection_criteria_fr',
            field=models.TextField(blank=True, help_text='Selection criteria for affected people', null=True, verbose_name='selection criteria'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='title_prefix_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='title_prefix_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='title_prefix_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='title_prefix_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='un_or_other_actor_ar',
            field=models.TextField(blank=True, null=True, verbose_name='un or other'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='un_or_other_actor_en',
            field=models.TextField(blank=True, null=True, verbose_name='un or other'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='un_or_other_actor_es',
            field=models.TextField(blank=True, null=True, verbose_name='un or other'),
        ),
        migrations.AddField(
            model_name='dreffinalreport',
            name='un_or_other_actor_fr',
            field=models.TextField(blank=True, null=True, verbose_name='un or other'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='anticipatory_actions_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Anticipatory actions'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='anticipatory_actions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Anticipatory actions'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='anticipatory_actions_es',
            field=models.TextField(blank=True, null=True, verbose_name='Anticipatory actions'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='anticipatory_actions_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Anticipatory actions'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='anticipatory_to_response_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Please explain how is the operation is transitioning from Anticipatory to Response'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='anticipatory_to_response_en',
            field=models.TextField(blank=True, null=True, verbose_name='Please explain how is the operation is transitioning from Anticipatory to Response'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='anticipatory_to_response_es',
            field=models.TextField(blank=True, null=True, verbose_name='Please explain how is the operation is transitioning from Anticipatory to Response'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='anticipatory_to_response_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Please explain how is the operation is transitioning from Anticipatory to Response'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='communication_ar',
            field=models.TextField(blank=True, help_text='Does the NS have Communications capacity?', null=True, verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='communication_en',
            field=models.TextField(blank=True, help_text='Does the NS have Communications capacity?', null=True, verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='communication_es',
            field=models.TextField(blank=True, help_text='Does the NS have Communications capacity?', null=True, verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='communication_fr',
            field=models.TextField(blank=True, help_text='Does the NS have Communications capacity?', null=True, verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='event_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Event description'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='event_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Event description'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='event_description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Event description'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='event_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Event description'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='event_scope_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Event scope'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='event_scope_en',
            field=models.TextField(blank=True, null=True, verbose_name='Event scope'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='event_scope_es',
            field=models.TextField(blank=True, null=True, verbose_name='Event scope'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='event_scope_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Event scope'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='human_resource_ar',
            field=models.TextField(blank=True, help_text='how many volunteers and staff involved in the response?', null=True, verbose_name='human resource'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='human_resource_en',
            field=models.TextField(blank=True, help_text='how many volunteers and staff involved in the response?', null=True, verbose_name='human resource'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='human_resource_es',
            field=models.TextField(blank=True, help_text='how many volunteers and staff involved in the response?', null=True, verbose_name='human resource'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='human_resource_fr',
            field=models.TextField(blank=True, help_text='how many volunteers and staff involved in the response?', null=True, verbose_name='human resource'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='icrc_ar',
            field=models.TextField(blank=True, null=True, verbose_name='icrc'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='icrc_en',
            field=models.TextField(blank=True, null=True, verbose_name='icrc'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='icrc_es',
            field=models.TextField(blank=True, null=True, verbose_name='icrc'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='icrc_fr',
            field=models.TextField(blank=True, null=True, verbose_name='icrc'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='ifrc_ar',
            field=models.TextField(blank=True, null=True, verbose_name='ifrc'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='ifrc_en',
            field=models.TextField(blank=True, null=True, verbose_name='ifrc'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='ifrc_es',
            field=models.TextField(blank=True, null=True, verbose_name='ifrc'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='ifrc_fr',
            field=models.TextField(blank=True, null=True, verbose_name='ifrc'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='logistic_capacity_of_ns_ar',
            field=models.TextField(blank=True, help_text='what is the logistics capacity of the National Society?', null=True, verbose_name='logistic capacity of ns'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='logistic_capacity_of_ns_en',
            field=models.TextField(blank=True, help_text='what is the logistics capacity of the National Society?', null=True, verbose_name='logistic capacity of ns'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='logistic_capacity_of_ns_es',
            field=models.TextField(blank=True, help_text='what is the logistics capacity of the National Society?', null=True, verbose_name='logistic capacity of ns'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='logistic_capacity_of_ns_fr',
            field=models.TextField(blank=True, help_text='what is the logistics capacity of the National Society?', null=True, verbose_name='logistic capacity of ns'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='major_coordination_mechanism_ar',
            field=models.TextField(blank=True, null=True, verbose_name='major coordination mechanism'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='major_coordination_mechanism_en',
            field=models.TextField(blank=True, null=True, verbose_name='major coordination mechanism'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='major_coordination_mechanism_es',
            field=models.TextField(blank=True, null=True, verbose_name='major coordination mechanism'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='major_coordination_mechanism_fr',
            field=models.TextField(blank=True, null=True, verbose_name='major coordination mechanism'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='national_authorities_ar',
            field=models.TextField(blank=True, null=True, verbose_name='national authorities'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='national_authorities_en',
            field=models.TextField(blank=True, null=True, verbose_name='national authorities'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='national_authorities_es',
            field=models.TextField(blank=True, null=True, verbose_name='national authorities'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='national_authorities_fr',
            field=models.TextField(blank=True, null=True, verbose_name='national authorities'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='operation_objective_ar',
            field=models.TextField(blank=True, null=True, verbose_name='operation objective'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='operation_objective_en',
            field=models.TextField(blank=True, null=True, verbose_name='operation objective'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='operation_objective_es',
            field=models.TextField(blank=True, null=True, verbose_name='operation objective'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='operation_objective_fr',
            field=models.TextField(blank=True, null=True, verbose_name='operation objective'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='partner_national_society_ar',
            field=models.TextField(blank=True, null=True, verbose_name='partner national society'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='partner_national_society_en',
            field=models.TextField(blank=True, null=True, verbose_name='partner national society'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='partner_national_society_es',
            field=models.TextField(blank=True, null=True, verbose_name='partner national society'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='partner_national_society_fr',
            field=models.TextField(blank=True, null=True, verbose_name='partner national society'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='people_assisted_ar',
            field=models.TextField(blank=True, null=True, verbose_name='people assisted'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='people_assisted_en',
            field=models.TextField(blank=True, null=True, verbose_name='people assisted'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='people_assisted_es',
            field=models.TextField(blank=True, null=True, verbose_name='people assisted'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='people_assisted_fr',
            field=models.TextField(blank=True, null=True, verbose_name='people assisted'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='pmer_ar',
            field=models.TextField(blank=True, help_text='Does the NS have PMER capacity?', null=True, verbose_name='pmer'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='pmer_en',
            field=models.TextField(blank=True, help_text='Does the NS have PMER capacity?', null=True, verbose_name='pmer'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='pmer_es',
            field=models.TextField(blank=True, help_text='Does the NS have PMER capacity?', null=True, verbose_name='pmer'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='pmer_fr',
            field=models.TextField(blank=True, help_text='Does the NS have PMER capacity?', null=True, verbose_name='pmer'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='response_strategy_ar',
            field=models.TextField(blank=True, null=True, verbose_name='response strategy'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='response_strategy_en',
            field=models.TextField(blank=True, null=True, verbose_name='response strategy'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='response_strategy_es',
            field=models.TextField(blank=True, null=True, verbose_name='response strategy'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='response_strategy_fr',
            field=models.TextField(blank=True, null=True, verbose_name='response strategy'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='risk_security_concern_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='risk_security_concern_en',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='risk_security_concern_es',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='risk_security_concern_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Security Concern'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='selection_criteria_ar',
            field=models.TextField(blank=True, help_text='Selection criteria for affected people', null=True, verbose_name='selection criteria'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='selection_criteria_en',
            field=models.TextField(blank=True, help_text='Selection criteria for affected people', null=True, verbose_name='selection criteria'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='selection_criteria_es',
            field=models.TextField(blank=True, help_text='Selection criteria for affected people', null=True, verbose_name='selection criteria'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='selection_criteria_fr',
            field=models.TextField(blank=True, help_text='Selection criteria for affected people', null=True, verbose_name='selection criteria'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='surge_personnel_deployed_ar',
            field=models.TextField(blank=True, help_text='Will a Surge personnel be deployed?', null=True, verbose_name='surge personnel deployed'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='surge_personnel_deployed_en',
            field=models.TextField(blank=True, help_text='Will a Surge personnel be deployed?', null=True, verbose_name='surge personnel deployed'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='surge_personnel_deployed_es',
            field=models.TextField(blank=True, help_text='Will a Surge personnel be deployed?', null=True, verbose_name='surge personnel deployed'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='surge_personnel_deployed_fr',
            field=models.TextField(blank=True, help_text='Will a Surge personnel be deployed?', null=True, verbose_name='surge personnel deployed'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='title_prefix_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='title_prefix_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='title_prefix_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='title_prefix_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title prefix'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='un_or_other_actor_ar',
            field=models.TextField(blank=True, null=True, verbose_name='un or other'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='un_or_other_actor_en',
            field=models.TextField(blank=True, null=True, verbose_name='un or other'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='un_or_other_actor_es',
            field=models.TextField(blank=True, null=True, verbose_name='un or other'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='un_or_other_actor_fr',
            field=models.TextField(blank=True, null=True, verbose_name='un or other'),
        ),
        migrations.AddField(
            model_name='identifiedneed',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='identifiedneed',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='identifiedneed',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='identifiedneed',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='identifiedneed',
            name='title_ar',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration', 'Migration'), ('multi_purpose_cash_grants', 'Multi purpose cash grants'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and _accountability', 'Community Engagement And Accountability'), ('environment_sustainability ', 'Environment Sustainability'), ('shelter_cluster_coordination', 'Shelter Cluster Coordination')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='identifiedneed',
            name='title_en',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration', 'Migration'), ('multi_purpose_cash_grants', 'Multi purpose cash grants'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and _accountability', 'Community Engagement And Accountability'), ('environment_sustainability ', 'Environment Sustainability'), ('shelter_cluster_coordination', 'Shelter Cluster Coordination')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='identifiedneed',
            name='title_es',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration', 'Migration'), ('multi_purpose_cash_grants', 'Multi purpose cash grants'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and _accountability', 'Community Engagement And Accountability'), ('environment_sustainability ', 'Environment Sustainability'), ('shelter_cluster_coordination', 'Shelter Cluster Coordination')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='identifiedneed',
            name='title_fr',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration', 'Migration'), ('multi_purpose_cash_grants', 'Multi purpose cash grants'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and _accountability', 'Community Engagement And Accountability'), ('environment_sustainability ', 'Environment Sustainability'), ('shelter_cluster_coordination', 'Shelter Cluster Coordination')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='identifiedneed',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='identifiedneed',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='nationalsocietyaction',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='nationalsocietyaction',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='nationalsocietyaction',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='nationalsocietyaction',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='nationalsocietyaction',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='nationalsocietyaction',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='challenges_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Challenges'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='challenges_en',
            field=models.TextField(blank=True, null=True, verbose_name='Challenges'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='challenges_es',
            field=models.TextField(blank=True, null=True, verbose_name='Challenges'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='challenges_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Challenges'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='lessons_learnt_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Lessons learnt'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='lessons_learnt_en',
            field=models.TextField(blank=True, null=True, verbose_name='Lessons learnt'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='lessons_learnt_es',
            field=models.TextField(blank=True, null=True, verbose_name='Lessons learnt'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='lessons_learnt_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Lessons learnt'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='narrative_description_of_achievements_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Narrative description of achievements'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='narrative_description_of_achievements_en',
            field=models.TextField(blank=True, null=True, verbose_name='Narrative description of achievements'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='narrative_description_of_achievements_es',
            field=models.TextField(blank=True, null=True, verbose_name='Narrative description of achievements'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='narrative_description_of_achievements_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Narrative description of achievements'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='progress_towards_outcome_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Progress Towards Outcome'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='progress_towards_outcome_en',
            field=models.TextField(blank=True, null=True, verbose_name='Progress Towards Outcome'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='progress_towards_outcome_es',
            field=models.TextField(blank=True, null=True, verbose_name='Progress Towards Outcome'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='progress_towards_outcome_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Progress Towards Outcome'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='title_ar',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration', 'Migration'), ('risk_reduction_climate_adaptation_and_recovery_', 'Risk Reduction, Climate Adaptation And Recovery'), ('secretariat_services', 'Secretariat Services'), ('national_society_strengthening', 'National Society Strengthening'), ('multi-purpose_cash', 'Multi-purpose Cash'), ('environmental_sustainability', 'Environmental Sustainability'), ('community_engagement_and_accountability', 'Community Engagement And Accountability')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='title_en',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration', 'Migration'), ('risk_reduction_climate_adaptation_and_recovery_', 'Risk Reduction, Climate Adaptation And Recovery'), ('secretariat_services', 'Secretariat Services'), ('national_society_strengthening', 'National Society Strengthening'), ('multi-purpose_cash', 'Multi-purpose Cash'), ('environmental_sustainability', 'Environmental Sustainability'), ('community_engagement_and_accountability', 'Community Engagement And Accountability')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='title_es',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration', 'Migration'), ('risk_reduction_climate_adaptation_and_recovery_', 'Risk Reduction, Climate Adaptation And Recovery'), ('secretariat_services', 'Secretariat Services'), ('national_society_strengthening', 'National Society Strengthening'), ('multi-purpose_cash', 'Multi-purpose Cash'), ('environmental_sustainability', 'Environmental Sustainability'), ('community_engagement_and_accountability', 'Community Engagement And Accountability')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='title_fr',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration', 'Migration'), ('risk_reduction_climate_adaptation_and_recovery_', 'Risk Reduction, Climate Adaptation And Recovery'), ('secretariat_services', 'Secretariat Services'), ('national_society_strengthening', 'National Society Strengthening'), ('multi-purpose_cash', 'Multi-purpose Cash'), ('environmental_sustainability', 'Environmental Sustainability'), ('community_engagement_and_accountability', 'Community Engagement And Accountability')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='plannedinterventionindicators',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='plannedinterventionindicators',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='plannedinterventionindicators',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='plannedinterventionindicators',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='plannedinterventionindicators',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='plannedinterventionindicators',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
        migrations.AddField(
            model_name='risksecurity',
            name='mitigation_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Mitigation'),
        ),
        migrations.AddField(
            model_name='risksecurity',
            name='mitigation_en',
            field=models.TextField(blank=True, null=True, verbose_name='Mitigation'),
        ),
        migrations.AddField(
            model_name='risksecurity',
            name='mitigation_es',
            field=models.TextField(blank=True, null=True, verbose_name='Mitigation'),
        ),
        migrations.AddField(
            model_name='risksecurity',
            name='mitigation_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Mitigation'),
        ),
        migrations.AddField(
            model_name='risksecurity',
            name='risk_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Risk'),
        ),
        migrations.AddField(
            model_name='risksecurity',
            name='risk_en',
            field=models.TextField(blank=True, null=True, verbose_name='Risk'),
        ),
        migrations.AddField(
            model_name='risksecurity',
            name='risk_es',
            field=models.TextField(blank=True, null=True, verbose_name='Risk'),
        ),
        migrations.AddField(
            model_name='risksecurity',
            name='risk_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Risk'),
        ),
        migrations.AddField(
            model_name='risksecurity',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='risksecurity',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
    ]
