# Generated by Django 3.2.19 on 2023-06-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0059_drefoperationalupdate_identified_gaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreffinalreport',
            name='date_of_approval',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Approval'),
        ),
    ]
