# Generated by Django 3.2.19 on 2023-06-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    def update_dref(apps, schema_editor):
        Dref = apps.get_model("dref", "Dref")
        drefs = Dref.objects.all()
        for dref in drefs:
            if hasattr(dref, "dreffinalreport"):
                if dref.dreffinalreport.is_published == True:
                    dref.is_active = False
                else:
                    dref.is_active = True
            else:
                dref.is_active = True
            dref.save(update_fields=["is_active"])

    dependencies = [
        ("dref", "0061_dref_is_active"),
    ]

    operations = [
        migrations.RunPython(update_dref, reverse_code=migrations.RunPython.noop),
    ]
