# Generated by Django 3.2.19 on 2023-06-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0062_auto_20230619_0931"),
        ("dref", "0062_merge_20230614_0818"),
    ]

    operations = []
