# Generated by Django 3.2.20 on 2023-07-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0063_merge_20230628_1022"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreffinalreport",
            name="financial_report_preview",
            field=models.FileField(blank=True, null=True, upload_to="dref/images/", verbose_name="financial preview"),
        ),
    ]
