# Generated by Django 3.2.20 on 2023-07-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0064_auto_20230713_0601'),
        ('dref', '0065_auto_20230728_0405'),
    ]

    operations = [
    ]
