# Generated by Django 3.2.20 on 2023-08-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0066_dreffinalreport_main_donors'),
        ('dref', '0066_merge_0064_auto_20230713_0601_0065_auto_20230728_0405'),
    ]

    operations = [
    ]
