# Generated by Django 3.2.20 on 2023-12-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0073_auto_20231120_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='dref',
            name='targeting_strategy_support_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dref_targeting_strategy_support_file', to='dref.dreffile', verbose_name='If available please upload additional support documentation for targeting strategy'),
        ),
    ]
