# Generated by Django 4.2.15 on 2024-09-18 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_squashed_0213_merge_20240807_1001"),
        ("dref", "0001_squashed_0074_auto_20240129_0909"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dref",
            name="national_society",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.country", verbose_name="national_society"
            ),
        ),
    ]
