# Generated by Django 4.2.16 on 2024-10-29 08:51

from django.db import migrations

import main.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0074_auto_20240129_0909"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dref",
            name="budget_file_preview",
            field=main.fields.SecureFileField(
                blank=True, null=True, upload_to="dref/images/", verbose_name="budget file preview"
            ),
        ),
        migrations.AlterField(
            model_name="dreffile",
            name="file",
            field=main.fields.SecureFileField(upload_to="dref/images/", verbose_name="file"),
        ),
        migrations.AlterField(
            model_name="dreffinalreport",
            name="financial_report_preview",
            field=main.fields.SecureFileField(blank=True, null=True, upload_to="dref/images/", verbose_name="financial preview"),
        ),
        migrations.AlterField(
            model_name="drefoperationalupdate",
            name="budget_file_preview",
            field=main.fields.SecureFileField(
                blank=True, null=True, upload_to="dref-op-update/images/", verbose_name="budget file preview"
            ),
        ),
    ]
