# Generated by Django 3.2.20 on 2023-12-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0075_auto_20231208_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiedneed',
            name='title',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('multi_purpose_cash_grants', 'Multi purpose cash grants'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration_and_displacement', 'Migration And Displacement'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and_accountability', 'Community Engagement And Accountability'), ('environment_sustainability', 'Environment Sustainability')], max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='identifiedneed',
            name='title_ar',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('multi_purpose_cash_grants', 'Multi purpose cash grants'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration_and_displacement', 'Migration And Displacement'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and_accountability', 'Community Engagement And Accountability'), ('environment_sustainability', 'Environment Sustainability')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='identifiedneed',
            name='title_en',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('multi_purpose_cash_grants', 'Multi purpose cash grants'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration_and_displacement', 'Migration And Displacement'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and_accountability', 'Community Engagement And Accountability'), ('environment_sustainability', 'Environment Sustainability')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='identifiedneed',
            name='title_es',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('multi_purpose_cash_grants', 'Multi purpose cash grants'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration_and_displacement', 'Migration And Displacement'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and_accountability', 'Community Engagement And Accountability'), ('environment_sustainability', 'Environment Sustainability')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='identifiedneed',
            name='title_fr',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('multi_purpose_cash_grants', 'Multi purpose cash grants'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration_and_displacement', 'Migration And Displacement'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and_accountability', 'Community Engagement And Accountability'), ('environment_sustainability', 'Environment Sustainability')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='nationalsocietyaction',
            name='title',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter, Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('multi-purpose_cash', 'Multi-purpose Cash'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration_and_displacement', 'Migration And Displacement'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and_accountability', 'Community Engagement And Accountability'), ('environment_sustainability', 'Environment Sustainability'), ('coordination', 'Coordination'), ('national_society_readiness', 'National Society Readiness'), ('assessment', 'Assessment'), ('resource_mobilization', 'Resource Mobilization'), ('activation_of_contingency_plans', 'Activation Of Contingency Plans'), ('national_society_eoc', 'National Society EOC'), ('other', 'Other')], max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='plannedintervention',
            name='title',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('multi-purpose_cash', 'Multi-purpose Cash'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration_and_displacement', 'Migration And Displacement'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and_accountability', 'Community Engagement And Accountability'), ('environmental_sustainability', 'Environmental Sustainability'), ('coordination_and_partnerships', 'Coordination And Partnerships'), ('secretariat_services', 'Secretariat Services'), ('national_society_strengthening', 'National Society Strengthening')], max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='plannedintervention',
            name='title_ar',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('multi-purpose_cash', 'Multi-purpose Cash'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration_and_displacement', 'Migration And Displacement'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and_accountability', 'Community Engagement And Accountability'), ('environmental_sustainability', 'Environmental Sustainability'), ('coordination_and_partnerships', 'Coordination And Partnerships'), ('secretariat_services', 'Secretariat Services'), ('national_society_strengthening', 'National Society Strengthening')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='plannedintervention',
            name='title_en',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('multi-purpose_cash', 'Multi-purpose Cash'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration_and_displacement', 'Migration And Displacement'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and_accountability', 'Community Engagement And Accountability'), ('environmental_sustainability', 'Environmental Sustainability'), ('coordination_and_partnerships', 'Coordination And Partnerships'), ('secretariat_services', 'Secretariat Services'), ('national_society_strengthening', 'National Society Strengthening')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='plannedintervention',
            name='title_es',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('multi-purpose_cash', 'Multi-purpose Cash'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration_and_displacement', 'Migration And Displacement'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and_accountability', 'Community Engagement And Accountability'), ('environmental_sustainability', 'Environmental Sustainability'), ('coordination_and_partnerships', 'Coordination And Partnerships'), ('secretariat_services', 'Secretariat Services'), ('national_society_strengthening', 'National Society Strengthening')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='plannedintervention',
            name='title_fr',
            field=models.CharField(choices=[('shelter_housing_and_settlements', 'Shelter Housing And Settlements'), ('livelihoods_and_basic_needs', 'Livelihoods And Basic Needs'), ('multi-purpose_cash', 'Multi-purpose Cash'), ('health', 'Health'), ('water_sanitation_and_hygiene', 'Water, Sanitation And Hygiene'), ('protection_gender_and_inclusion', 'Protection, Gender And Inclusion'), ('education', 'Education'), ('migration_and_displacement', 'Migration And Displacement'), ('risk_reduction_climate_adaptation_and_recovery', 'Risk Reduction, Climate Adaptation And Recovery'), ('community_engagement_and_accountability', 'Community Engagement And Accountability'), ('environmental_sustainability', 'Environmental Sustainability'), ('coordination_and_partnerships', 'Coordination And Partnerships'), ('secretariat_services', 'Secretariat Services'), ('national_society_strengthening', 'National Society Strengthening')], max_length=255, null=True, verbose_name='title'),
        ),
    ]
