# Generated by Django 3.2.23 on 2024-03-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0075_auto_20240301_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dref',
            name='selection_criteria_early_action',
        ),
        migrations.RemoveField(
            model_name='dref',
            name='targeting_population_early_action',
        ),
        migrations.RemoveField(
            model_name='identifiedneed',
            name='current_need',
        ),
    ]
