# Generated by Django 4.2.17 on 2025-01-03 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0090_sectortag_title_ar_sectortag_title_en_and_more"),
        ("dref", "0075_alter_dref_budget_file_preview_alter_dreffile_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dref",
            name="indirect_cost",
            field=models.IntegerField(blank=True, null=True, verbose_name="Indirect Cost"),
        ),
        migrations.AddField(
            model_name="dref",
            name="sub_total",
            field=models.IntegerField(blank=True, null=True, verbose_name="Sub total"),
        ),
        migrations.AddField(
            model_name="dref",
            name="surge_deployment",
            field=models.IntegerField(blank=True, null=True, verbose_name="Surge Deployment"),
        ),
        migrations.AddField(
            model_name="dref",
            name="total",
            field=models.IntegerField(blank=True, null=True, verbose_name="Total"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="indirect_cost",
            field=models.IntegerField(blank=True, null=True, verbose_name="Indirect Cost"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="sub_total",
            field=models.IntegerField(blank=True, null=True, verbose_name="Sub total"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="surge_deployment",
            field=models.IntegerField(blank=True, null=True, verbose_name="Surge Deployment"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="total",
            field=models.IntegerField(blank=True, null=True, verbose_name="Total"),
        ),
        migrations.AddField(
            model_name="drefoperationalupdate",
            name="indirect_cost",
            field=models.IntegerField(blank=True, null=True, verbose_name="Indirect Cost"),
        ),
        migrations.AddField(
            model_name="drefoperationalupdate",
            name="sub_total",
            field=models.IntegerField(blank=True, null=True, verbose_name="Sub total"),
        ),
        migrations.AddField(
            model_name="drefoperationalupdate",
            name="surge_deployment",
            field=models.IntegerField(blank=True, null=True, verbose_name="Surge Deployment"),
        ),
        migrations.AddField(
            model_name="drefoperationalupdate",
            name="total",
            field=models.IntegerField(blank=True, null=True, verbose_name="Total"),
        ),
        migrations.CreateModel(
            name="ProposedAction",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "proposed_type",
                    models.PositiveIntegerField(
                        choices=[(1, "Early Actions"), (2, "Early Response")], verbose_name="dref proposed action"
                    ),
                ),
                ("budget", models.PositiveIntegerField(blank=True, null=True, verbose_name="Early Action budgets")),
                (
                    "activities",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="deployments.sector"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dref",
            name="proposed_action",
            field=models.ManyToManyField(blank=True, to="dref.proposedaction", verbose_name="Proposed Action"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="proposed_action",
            field=models.ManyToManyField(blank=True, to="dref.proposedaction", verbose_name="Proposed Action"),
        ),
        migrations.AddField(
            model_name="drefoperationalupdate",
            name="proposed_action",
            field=models.ManyToManyField(blank=True, to="dref.proposedaction", verbose_name="Proposed Action"),
        ),
    ]
