# Generated by Django 4.2.17 on 2025-01-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0076_dref_indirect_cost_dref_sub_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dref",
            name="proposed_action",
            field=models.ManyToManyField(blank=True, null=True, to="dref.proposedaction", verbose_name="Proposed Action"),
        ),
        migrations.AlterField(
            model_name="dreffinalreport",
            name="proposed_action",
            field=models.ManyToManyField(blank=True, null=True, to="dref.proposedaction", verbose_name="Proposed Action"),
        ),
        migrations.AlterField(
            model_name="drefoperationalupdate",
            name="proposed_action",
            field=models.ManyToManyField(blank=True, null=True, to="dref.proposedaction", verbose_name="Proposed Action"),
        ),
        migrations.AlterField(
            model_name="proposedaction",
            name="budget",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=" Purpose Action budgets"),
        ),
    ]
