# Generated by Django 4.2.17 on 2025-02-19 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0090_sectortag_title_ar_sectortag_title_en_and_more"),
        ("dref", "0076_dref_addressed_humanitarian_impacts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dref",
            name="sub_total",
        ),
        migrations.RemoveField(
            model_name="dref",
            name="total",
        ),
        migrations.RemoveField(
            model_name="proposedaction",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="proposedaction",
            name="budget",
        ),
        migrations.AddField(
            model_name="dref",
            name="sub_total_cost",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Sub total Cost"),
        ),
        migrations.AddField(
            model_name="dref",
            name="total_cost",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Total Cost"),
        ),
        migrations.AddField(
            model_name="proposedaction",
            name="total_budget",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Total Purpose Action Budget"),
        ),
        migrations.CreateModel(
            name="ProposedActionActivities",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activity", models.TextField(blank=True, null=True, verbose_name="Activity")),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="deployments.sector", verbose_name="Sector Tag"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="proposedaction",
            name="activities",
            field=models.ManyToManyField(blank=True, to="dref.proposedactionactivities", verbose_name="Activities"),
        ),
    ]
