# Generated by Django 4.2.19 on 2025-04-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0077_dref_child_safeguarding_risk_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dref",
            name="estimated_number_of_affected_minors",
        ),
        migrations.RemoveField(
            model_name="dreffinalreport",
            name="estimated_number_of_affected_minors",
        ),
        migrations.RemoveField(
            model_name="drefoperationalupdate",
            name="estimated_number_of_affected_minors",
        ),
        migrations.AddField(
            model_name="dref",
            name="estimated_number_of_affected_boys_under_18",
            field=models.IntegerField(blank=True, null=True, verbose_name="estimated number of affected boys under 18"),
        ),
        migrations.AddField(
            model_name="dref",
            name="estimated_number_of_affected_girls_under_18",
            field=models.IntegerField(blank=True, null=True, verbose_name="estimated number of affected girls under 18"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="estimated_number_of_affected_boys_under_18",
            field=models.IntegerField(blank=True, null=True, verbose_name="estimated number of affected boys under 18"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="estimated_number_of_affected_girls_under_18",
            field=models.IntegerField(blank=True, null=True, verbose_name="estimated number of affected girls under 18"),
        ),
        migrations.AddField(
            model_name="drefoperationalupdate",
            name="estimated_number_of_affected_boys_under_18",
            field=models.IntegerField(blank=True, null=True, verbose_name="estimated number of affected boys under 18"),
        ),
        migrations.AddField(
            model_name="drefoperationalupdate",
            name="estimated_number_of_affected_girls_under_18",
            field=models.IntegerField(blank=True, null=True, verbose_name="estimated number of affected girls under 18"),
        ),
    ]
