# Generated by Django 3.2.23 on 2024-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0077_auto_20240312_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='dref',
            name='immediate_people_targeted_with_early_actions',
            field=models.IntegerField(blank=True, help_text='Number of persons targeted with early actions for immediate response', null=True, verbose_name='people targeted with early actions for immediate response'),
        ),
        migrations.AddField(
            model_name='drefoperationalupdate',
            name='immediate_people_targeted_with_early_actions',
            field=models.IntegerField(blank=True, help_text='Number of persons targeted with early actions for immediate response', null=True, verbose_name='people targeted with early actions for immediate response'),
        ),
    ]
