# Generated by Django 4.2.17 on 2025-02-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0077_remove_dref_sub_total_remove_dref_total_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proposedactionactivities",
            options={"verbose_name": "Proposed action activity", "verbose_name_plural": "Proposed action activities"},
        ),
        migrations.AddField(
            model_name="dref",
            name="operation_timeframe_imminent",
            field=models.IntegerField(blank=True, null=True, verbose_name="operation timeframe for imminent type"),
        ),
    ]
