# Generated by Django 4.2.19 on 2025-06-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0078_remove_dref_estimated_number_of_affected_minors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreffinalreport",
            name="assisted_num_of_boys_under_18",
            field=models.IntegerField(blank=True, null=True, verbose_name="Number of boys under 18 assisted"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="assisted_num_of_girls_under_18",
            field=models.IntegerField(blank=True, null=True, verbose_name="Number of girls under 18 assisted"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="assisted_num_of_men",
            field=models.IntegerField(blank=True, null=True, verbose_name="Number of men assisted"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="assisted_num_of_women",
            field=models.IntegerField(blank=True, null=True, verbose_name="Number of women assisted"),
        ),
    ]
