# Generated by Django 4.2.17 on 2025-02-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0078_alter_proposedactionactivities_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dref",
            name="hazard_date_and_location",
        ),
        migrations.AddField(
            model_name="dref",
            name="hazard_date",
            field=models.DateField(blank=True, null=True, verbose_name="When is the hazard expected to happen?"),
        ),
    ]
