# Generated by Django 3.2.23 on 2024-03-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0078_auto_20240313_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTimeFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('timeframe', models.IntegerField(blank=True, help_text='Timeframe in weeks', null=True, verbose_name='Timeframe')),
            ],
            options={
                'verbose_name': 'activity timeframe',
                'verbose_name_plural': 'activity timeframes',
            },
        ),
        migrations.RemoveField(
            model_name='plannedintervention',
            name='early_action_block',
        ),
        migrations.RemoveField(
            model_name='plannedintervention',
            name='early_response_block',
        ),
        migrations.RemoveField(
            model_name='plannedintervention',
            name='readiness_block',
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='early_action_block',
            field=models.ManyToManyField(blank=True, related_name='planned_intervention_early_action_block', to='dref.ActivityTimeFrame', verbose_name='Early Action Block'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='early_response_block',
            field=models.ManyToManyField(blank=True, related_name='planned_intervention_early_response_block', to='dref.ActivityTimeFrame', verbose_name='Early Response Block'),
        ),
        migrations.AddField(
            model_name='plannedintervention',
            name='readiness_block',
            field=models.ManyToManyField(blank=True, related_name='planned_intervention_readiness_block', to='dref.ActivityTimeFrame', verbose_name='Readiness Block'),
        ),
    ]
