# Generated by Django 4.2.19 on 2025-06-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0091_erureadinesstype_alter_erureadiness_options_and_more"),
        ("dref", "0079_dreffinalreport_assisted_num_of_boys_under_18_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dref",
            name="hazard_date_and_location",
        ),
        migrations.RemoveField(
            model_name="dref",
            name="sub_total",
        ),
        migrations.RemoveField(
            model_name="dref",
            name="total",
        ),
        migrations.RemoveField(
            model_name="proposedaction",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="proposedaction",
            name="budget",
        ),
        migrations.AddField(
            model_name="dref",
            name="hazard_date",
            field=models.DateField(blank=True, null=True, verbose_name="When is the hazard expected to happen?"),
        ),
        migrations.AddField(
            model_name="dref",
            name="is_dref_imminent_v2",
            field=models.BooleanField(
                default=False,
                help_text="Is this DREF Imminent V2? If yes, it will be used for the new dref imminent type.",
                verbose_name="Is DREF Imminent V2?",
            ),
        ),
        migrations.AddField(
            model_name="dref",
            name="operation_timeframe_imminent",
            field=models.IntegerField(blank=True, null=True, verbose_name="operation timeframe for imminent type"),
        ),
        migrations.AddField(
            model_name="dref",
            name="sub_total_cost",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Sub total Cost"),
        ),
        migrations.AddField(
            model_name="dref",
            name="total_cost",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Total Cost"),
        ),
        migrations.AddField(
            model_name="proposedaction",
            name="total_budget",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Total Purpose Action Budget"),
        ),
        migrations.CreateModel(
            name="ProposedActionActivities",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activity", models.TextField(blank=True, null=True, verbose_name="Activity")),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="deployments.sector", verbose_name="Sector Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposed action activity",
                "verbose_name_plural": "Proposed action activities",
            },
        ),
        migrations.AddField(
            model_name="proposedaction",
            name="activities",
            field=models.ManyToManyField(blank=True, to="dref.proposedactionactivities", verbose_name="Activities"),
        ),
    ]
