# Generated by Django 4.2.19 on 2025-07-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0081_remove_dref_hazard_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreffinalreport",
            name="indirect_cost",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Indirect Cost"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="indirect_expenditure_cost",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Indirect Expenditure Cost"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="is_dref_imminent_v2",
            field=models.BooleanField(default=False, verbose_name="Is DREF Imminent V2?"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="lessons_learned_and_challenges",
            field=models.TextField(blank=True, null=True, verbose_name="Lessons learnt and challenges"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="mitigation_efforts_and_achievements",
            field=models.TextField(blank=True, null=True, verbose_name="Mitigation Efforts and Achievements"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="proposed_action",
            field=models.ManyToManyField(blank=True, to="dref.proposedaction", verbose_name="Proposed Action"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="sub_total_cost",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Sub total Cost"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="sub_total_expenditure_cost",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Sub total Expenditure Cost"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="surge_deployment_cost",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Surge Deployment Cost"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="surge_deployment_expenditure_cost",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Surge Deployment Expenditure Cost"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="total_cost",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Total Cost"),
        ),
        migrations.AddField(
            model_name="dreffinalreport",
            name="total_expenditure_cost",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Total Expenditure Cost"),
        ),
        migrations.AddField(
            model_name="proposedaction",
            name="total_expenditure",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total expenditure for the proposed action", null=True, verbose_name="Expenditure"
            ),
        ),
    ]
