# Generated by Django 4.2.19 on 2025-09-10 08:48

from django.db import migrations, models


def update_status(apps, schema_editor):
    """
    Update old status to new workflow:
    - Not published or IN_PROGRESS → DRAFT
    - Published or COMPLETED → APPROVED
    Applies to Dref, DrefOperationalUpdate, and DrefFinalReport.
    """
    models = [
        "Dref",
        "DrefOperationalUpdate",
        "DrefFinalReport",
    ]
    for model_name in models:
        Model = apps.get_model("dref", model_name)
        Model.objects.filter(is_published=True).update(status=4)  # Published → APPROVED
        Model.objects.filter(is_published=False).update(status=1)  # Not published → DRAFT


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0083_dreffinalreport_total_operation_timeframe_imminent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dref",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Draft"), (2, "Finalizing"), (3, "Finalized"), (4, "Approved")],
                null=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="dreffinalreport",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Draft"), (2, "Finalizing"), (3, "Finalized"), (4, "Approved")],
                null=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="drefoperationalupdate",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Draft"), (2, "Finalizing"), (3, "Finalized"), (4, "Approved")],
                null=True,
                verbose_name="status",
            ),
        ),
        migrations.RunPython(update_status, reverse_code=migrations.RunPython.noop),
    ]
