# Generated by Django 4.2.19 on 2025-09-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dref", "0084_dref_original_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dref",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="dreffinalreport",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="drefoperationalupdate",
            name="is_published",
        ),
    ]
