# Generated by Django 4.2.19 on 2025-11-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0084_dref_original_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dref',
            name='is_published',
        ),
        migrations.RenameField(
            model_name='dref',
            old_name='original_language',
            new_name='starting_language',
        ),
        migrations.RemoveField(
            model_name='dreffinalreport',
            name='is_published',
        ),
        migrations.RenameField(
            model_name='dreffinalreport',
            old_name='original_language',
            new_name='starting_language',
        ),
        migrations.RemoveField(
            model_name='drefoperationalupdate',
            name='is_published',
        ),
        migrations.RenameField(
            model_name='drefoperationalupdate',
            old_name='original_language',
            new_name='starting_language',
        ),
        migrations.AlterField(
            model_name='dref',
            name='starting_language',
            field=models.CharField(blank=True, help_text='The language in which this record was first created.', null=True, verbose_name='Starting language'),
        ),
        migrations.AlterField(
            model_name='dreffinalreport',
            name='starting_language',
            field=models.CharField(blank=True, help_text='The language in which this record was first created.', null=True, verbose_name='Starting language'),
        ),
        migrations.AlterField(
            model_name='drefoperationalupdate',
            name='starting_language',
            field=models.CharField(blank=True, help_text='The language in which this record was first created.', null=True, verbose_name='Starting language'),
        ),
    ]
