# Generated by Django 4.2.19 on 2025-10-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0085_remove_dref_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dref',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Finalized'), (3, 'Approved')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='dreffinalreport',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Finalized'), (3, 'Approved')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='drefoperationalupdate',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Finalized'), (3, 'Approved')], default=1, verbose_name='status'),
        ),
    ]
