# Generated by Django 4.2.26 on 2025-12-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dref", "0085_dreffinalreport_main_donors_ar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposedactionactivities",
            name="activity_ar",
            field=models.TextField(blank=True, null=True, verbose_name="Activity"),
        ),
        migrations.AddField(
            model_name="proposedactionactivities",
            name="activity_en",
            field=models.TextField(blank=True, null=True, verbose_name="Activity"),
        ),
        migrations.AddField(
            model_name="proposedactionactivities",
            name="activity_es",
            field=models.TextField(blank=True, null=True, verbose_name="Activity"),
        ),
        migrations.AddField(
            model_name="proposedactionactivities",
            name="activity_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Activity"),
        ),
        migrations.AddField(
            model_name="proposedactionactivities",
            name="translation_module_original_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("ar", "Arabic"),
                ],
                default="en",
                help_text="Language used to create this entity",
                max_length=2,
                verbose_name="Entity Original language",
            ),
        ),
        migrations.AddField(
            model_name="proposedactionactivities",
            name="translation_module_skip_auto_translation",
            field=models.BooleanField(
                default=False,
                help_text="Skip auto translation operation for this entity?",
                verbose_name="Skip auto translation",
            ),
        ),
    ]
