# Generated by Django 4.2.19 on 2025-11-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0085_remove_dref_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dref',
            name='addressed_humanitarian_impacts_ar',
            field=models.TextField(blank=True, help_text=' Which of the expected severe humanitarian impacts of the hazard are your actions addressing?', null=True, verbose_name='Addressed Humanitarian Impacts'),
        ),
        migrations.AddField(
            model_name='dref',
            name='addressed_humanitarian_impacts_en',
            field=models.TextField(blank=True, help_text=' Which of the expected severe humanitarian impacts of the hazard are your actions addressing?', null=True, verbose_name='Addressed Humanitarian Impacts'),
        ),
        migrations.AddField(
            model_name='dref',
            name='addressed_humanitarian_impacts_es',
            field=models.TextField(blank=True, help_text=' Which of the expected severe humanitarian impacts of the hazard are your actions addressing?', null=True, verbose_name='Addressed Humanitarian Impacts'),
        ),
        migrations.AddField(
            model_name='dref',
            name='addressed_humanitarian_impacts_fr',
            field=models.TextField(blank=True, help_text=' Which of the expected severe humanitarian impacts of the hazard are your actions addressing?', null=True, verbose_name='Addressed Humanitarian Impacts'),
        ),
        migrations.AddField(
            model_name='dref',
            name='hazard_date_and_location_ar',
            field=models.TextField(blank=True, help_text='When and where is the hazard expected to happen?', null=True, verbose_name='Hazard Date and Location'),
        ),
        migrations.AddField(
            model_name='dref',
            name='hazard_date_and_location_en',
            field=models.TextField(blank=True, help_text='When and where is the hazard expected to happen?', null=True, verbose_name='Hazard Date and Location'),
        ),
        migrations.AddField(
            model_name='dref',
            name='hazard_date_and_location_es',
            field=models.TextField(blank=True, help_text='When and where is the hazard expected to happen?', null=True, verbose_name='Hazard Date and Location'),
        ),
        migrations.AddField(
            model_name='dref',
            name='hazard_date_and_location_fr',
            field=models.TextField(blank=True, help_text='When and where is the hazard expected to happen?', null=True, verbose_name='Hazard Date and Location'),
        ),
        migrations.AddField(
            model_name='dref',
            name='hazard_vulnerabilities_and_risks_ar',
            field=models.TextField(blank=True, help_text='Explain the underlying vulnerabilities and risks the hazard poses for at-risk communities?', null=True, verbose_name='Hazard Vulnerabilities and Risks'),
        ),
        migrations.AddField(
            model_name='dref',
            name='hazard_vulnerabilities_and_risks_en',
            field=models.TextField(blank=True, help_text='Explain the underlying vulnerabilities and risks the hazard poses for at-risk communities?', null=True, verbose_name='Hazard Vulnerabilities and Risks'),
        ),
        migrations.AddField(
            model_name='dref',
            name='hazard_vulnerabilities_and_risks_es',
            field=models.TextField(blank=True, help_text='Explain the underlying vulnerabilities and risks the hazard poses for at-risk communities?', null=True, verbose_name='Hazard Vulnerabilities and Risks'),
        ),
        migrations.AddField(
            model_name='dref',
            name='hazard_vulnerabilities_and_risks_fr',
            field=models.TextField(blank=True, help_text='Explain the underlying vulnerabilities and risks the hazard poses for at-risk communities?', null=True, verbose_name='Hazard Vulnerabilities and Risks'),
        ),
    ]
