# Generated by Django 4.2.19 on 2025-10-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0086_alter_dref_status_alter_dreffinalreport_status_and_more'),
    ]

    operations = [
         migrations.RenameField(
            model_name='dref',
            old_name='original_language',
            new_name='starting_language',
        ),
        migrations.RenameField(
            model_name='dreffinalreport',
            old_name='original_language',
            new_name='starting_language',
        ),
        migrations.RenameField(
            model_name='drefoperationalupdate',
            old_name='original_language',
            new_name='starting_language',
        )
    ]
