# Generated by Django 4.2.28 on 2026-02-26 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dref", "0087_dreffinalreport_lessons_learned_and_challenges_ar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="identifiedneed",
            name="title_ar",
        ),
        migrations.RemoveField(
            model_name="identifiedneed",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="identifiedneed",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="identifiedneed",
            name="title_fr",
        ),
        migrations.RemoveField(
            model_name="plannedintervention",
            name="title_ar",
        ),
        migrations.RemoveField(
            model_name="plannedintervention",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="plannedintervention",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="plannedintervention",
            name="title_fr",
        ),
    ]
