# Generated by Django 4.2.30 on 2026-05-13 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0232_remove_event_auto_generated_source_event_source_and_more'),
        ('dref', '0088_remove_identifiedneed_title_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dref',
            name='field_report',
        ),
        migrations.AddField(
            model_name='dref',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_dref', to='api.event', verbose_name='event'),
        ),
    ]
