# Generated by Django 4.2.29 on 2026-04-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0230_alter_districtgeoms_district'),
        ('dref', '0088_remove_identifiedneed_title_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dref',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dref_event', to='api.event', verbose_name='event'),
        ),
    ]
