# Generated by Django 5.2.14 on 2026-07-03 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0089_remove_dref_field_report_dref_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrefSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_model_name', models.IntegerField(choices=[(100, 'Dref'), (200, 'Dref Operational Update'), (300, 'Dref Final Report')], verbose_name='source model name')),
                ('source_id', models.PositiveBigIntegerField(verbose_name='source id')),
                ('source_hash', models.CharField(max_length=64, unique=True)),
                ('situational_overview', models.TextField(blank=True, null=True)),
                ('situational_overview_en', models.TextField(blank=True, null=True)),
                ('situational_overview_es', models.TextField(blank=True, null=True)),
                ('situational_overview_fr', models.TextField(blank=True, null=True)),
                ('situational_overview_ar', models.TextField(blank=True, null=True)),
                ('operational_strategy', models.TextField(blank=True, null=True)),
                ('operational_strategy_en', models.TextField(blank=True, null=True)),
                ('operational_strategy_es', models.TextField(blank=True, null=True)),
                ('operational_strategy_fr', models.TextField(blank=True, null=True)),
                ('operational_strategy_ar', models.TextField(blank=True, null=True)),
                ('people_centered_approach', models.TextField(blank=True, null=True)),
                ('people_centered_approach_en', models.TextField(blank=True, null=True)),
                ('people_centered_approach_es', models.TextField(blank=True, null=True)),
                ('people_centered_approach_fr', models.TextField(blank=True, null=True)),
                ('people_centered_approach_ar', models.TextField(blank=True, null=True)),
                ('challenges_identified', models.TextField(blank=True, null=True)),
                ('challenges_identified_en', models.TextField(blank=True, null=True)),
                ('challenges_identified_es', models.TextField(blank=True, null=True)),
                ('challenges_identified_fr', models.TextField(blank=True, null=True)),
                ('challenges_identified_ar', models.TextField(blank=True, null=True)),
                ('lessons_learned', models.TextField(blank=True, null=True)),
                ('lessons_learned_en', models.TextField(blank=True, null=True)),
                ('lessons_learned_es', models.TextField(blank=True, null=True)),
                ('lessons_learned_fr', models.TextField(blank=True, null=True)),
                ('lessons_learned_ar', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(100, 'Pending'), (200, 'Processing'), (300, 'Success'), (400, 'Failed')], default=100)),
                ('translation_module_original_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language')),
                ('translation_module_skip_auto_translation', models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation')),
                ('dref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='dref.dref')),
            ],
        ),
    ]
