# Generated by Django 4.2.30 on 2026-06-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0090_drefsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='drefsummary',
            name='challenges_identified_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='challenges_identified_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='challenges_identified_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='challenges_identified_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='lessons_learned_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='lessons_learned_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='lessons_learned_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='lessons_learned_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='operational_strategy_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='operational_strategy_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='operational_strategy_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='operational_strategy_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='people_centered_approach_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='people_centered_approach_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='people_centered_approach_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='people_centered_approach_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='situational_overview_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='situational_overview_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='situational_overview_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='situational_overview_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='translation_module_original_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language used to create this entity', max_length=2, verbose_name='Entity Original language'),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='translation_module_skip_auto_translation',
            field=models.BooleanField(default=False, help_text='Skip auto translation operation for this entity?', verbose_name='Skip auto translation'),
        ),
    ]
