# Generated by Django 5.2.16 on 2026-08-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0090_drefsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='drefsummary',
            name='needs_identified',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='needs_identified_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='needs_identified_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='needs_identified_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='needs_identified_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
