# Generated by Django 5.2.14 on 2026-06-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dref', '0091_drefsummary_challenges_identified_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drefsummary',
            name='source_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='source id'),
        ),
        migrations.AddField(
            model_name='drefsummary',
            name='source_model_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='source model name'),
        ),
    ]
