# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(editable=False, max_length=12)),
                ('admin_contact_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('admin_contact_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('admin_token', models.CharField(editable=False, max_length=12, null=True)),
                ('email_verified', models.BooleanField(default=False, editable=False)),
            ],
        ),
    ]
