# Generated by Django 2.2.10 on 2020-04-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_domainwhitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainwhitelist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
