# Generated by Django 3.2.25 on 2024-04-26 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0010_pending_reminder_sent_to_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExternalToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('jti', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the token', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expire_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='expire timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User External Token',
                'verbose_name_plural': 'User External Tokens',
            },
        ),
    ]
