# Generated by Django 4.2.19 on 2025-09-05 05:21

from django.db import migrations, models


def set_is_old_token(apps, schema_editor):
    UserExternalToken = apps.get_model("registrations", "UserExternalToken")
    UserExternalToken.objects.update(is_old_token=True)


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_userexternaltoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexternaltoken',
            name='is_old_token',
            field=models.BooleanField(default=False, help_text='Marks whether this is an old Montandon token', verbose_name='is old token?'),
        ),
        migrations.RunPython(set_is_old_token, reverse_code=migrations.RunPython.noop),
    ]
