# Generated by Django 4.2.19 on 2025-09-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_userexternaltoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexternaltoken',
            name='is_old_token',
            field=models.BooleanField(default=True, help_text='Marks whether this is an old Montandon token', verbose_name='is old token?'),
        ),
    ]
