# Generated by Django 5.2.14 on 2026-07-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_userexternaltoken_is_old_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexternaltoken',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='Marks whether this token has been disabled/revoked', verbose_name='is disabled?'),
        ),
    ]
