{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-api
  labels:
    component: api-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ifrcgo-helm.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ template "ifrcgo-helm.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-api
    spec:
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
          command: ["sh", "/usr/local/bin/runserver.sh"]
          # args: ["-c", "while true; do npx knex migrate:latest && npm run prod; sleep 10;done"]
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          livenessProbe: #FIXME Fix Liveness Probe
            httpGet:
              path: /api/
              port: {{ .Values.api.containerPort }}
            initialDelaySeconds: 10180
            periodSeconds: 5
          resources:
            requests:
              cpu: {{ .Values.api.resources.requests.cpu }}
              memory: {{ .Values.api.resources.requests.memory }}
            limits:
              cpu: {{ .Values.api.resources.limits.cpu }}
              memory: {{ .Values.api.resources.limits.memory }}
          envFrom:
            - secretRef:
              name: {{ template "ifrcgo-helm.fullname" . }}-api-secret
          env:
            # - name: DJANGO_DB_NAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: {{ template "ifrcgo-helm.fullname" . }}-api-secret
            #       key: DJANGO_DB_NAME
            - name: DJANGO_DB_NAME
              value: postgres

            - name: DJANGO_DEBUG
              value: {{ .Values.env.DJANGO_DEBUG }}

            - name: DOCKER_HOST_IP
              value: {{ .Values.env.DOCKER_HOST_IP }}

            - name: DJANGO_ADDITIONAL_ALLOWED_HOSTS
              value: {{ .Values.env.DJANGO_ADDITIONAL_ALLOWED_HOSTS }}

            - name: GO_ENVIRONMENT
              value: {{ .Values.env.GO_ENVIRONMENT }}

            - name: API_FQDN
              value: {{ .Values.env.API_FQDN }}

            - name: FRONTEND_URL
              value: {{ .Values.env.FRONTEND_URL }}

            - name: DEBUG_EMAIL
              value: {{ .Values.env.DEBUG_EMAIL }}


{{- end }}
