{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-api
  labels:
    component: api-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ifrcgo-helm.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ template "ifrcgo-helm.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-api
    spec:
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
          command: ["sh", "/usr/local/bin/k8s_runserver.sh"]
          # args: ["-c", "while true; do npx knex migrate:latest && npm run prod; sleep 10;done"]
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          livenessProbe: #FIXME Fix Liveness Probe
            httpGet:
              path: /docs/
              port: {{ .Values.api.containerPort }}
            initialDelaySeconds: 10180
            periodSeconds: 5
          resources:
            requests:
              cpu: {{ .Values.api.resources.requests.cpu }}
              memory: {{ .Values.api.resources.requests.memory }}
            limits:
              cpu: {{ .Values.api.resources.limits.cpu }}
              memory: {{ .Values.api.resources.limits.memory }}
          envFrom:
            - secretRef:
                name: {{ template "ifrcgo-helm.fullname" . }}-api-secret
            - configMapRef:
                name: {{ template "ifrcgo-helm.fullname" . }}-api-configmap

{{- end }}
