{{- if .Values.api.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-ingress-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "300m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360s"
spec:
  tls:
    - hosts:
      - {{ .Values.api.domain }}
      secretName: {{ template "ifrcgo-helm.fullname" . }}-secret-api-cert

  rules:
  - host: {{ .Values.api.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "ifrcgo-helm.fullname" . }}-api
            port:
              number: 80
{{- end }}
