{{- if .Values.api.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-ingress-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "300m"
    #FIXME: We probably need to use custom certs and not LE
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
spec:
  tls:
    - hosts:
      - api.{{ .Values.api.domain }}
      secretName: {{ template "ifrcgo-helm.fullname" . }}-secret-api

  rules:
  - host: api.{{ .Values.api.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "ifrcgo-helm.fullname" . }}-api
            port:
              number: 80
{{- end }}
