{{- if .Values.api.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-ingress-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "300m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360s"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
spec:
  ingressClassName:
    nginx
  {{- if .Values.api.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.api.domain }}
      secretName: {{ template "ifrcgo-helm.fullname" . }}-secret-api-cert
    {{- if .Values.api.additionalDomain }}
    - hosts:
      - {{ .Values.api.additionalDomain }}
      secretName: {{ template "ifrcgo-helm.fullname" . }}-secret-api-additional-domain-cert
    {{- end }}
  {{- end }}

  rules:
  - host: {{ .Values.api.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "ifrcgo-helm.fullname" . }}-api
            port:
              number: 80
  {{- if .Values.api.additionalDomain }}
  - host: {{ .Values.api.additionalDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "ifrcgo-helm.fullname" . }}-api
            port:
              number: 80
  {{- end }}
{{- end }}

{{- if eq (.Values.env.GO_ENVIRONMENT | default "") "staging" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-ingress-user-library
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: "https://www.chromatic.com/library?appId=66557be6b68dacbf0a96db23&branch=develop"
    nginx.ingress.kubernetes.io/permanent-redirect-code: "301"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
spec:
  ingressClassName:
    nginx
  tls:
    - hosts:
      - go-user-library.ifrc.org
      secretName: {{ template "ifrcgo-helm.fullname" . }}-secret-api-cert
  rules:
  - host: go-user-library.ifrc.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "ifrcgo-helm.fullname" . }}-api
            port:
              number: 80
{{- end }}
