{{- if .Values.api.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-ingress-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "300m"
    #FIXME: We probably need to use custom certs and not LE
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
spec:
  tls:
    - hosts:
      - {{ .Values.api.domain }}
      secretName: {{ template "ifrcgo-helm.fullname" . }}-secret-api
    # TODO: uncomment this when we have a second domain set up and pointed
    # to the cluster
    # {{- if .Values.api.additionalDomain }}
    # - hosts:
    #   - {{ .Values.api.additionalDomain }}
    #   secretName: {{ template "ifrcgo-helm.fullname" . }}-secret-api-additional-domain
    # {{- end }}

  rules:
  - host: {{ .Values.api.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "ifrcgo-helm.fullname" . }}-api
            port:
              number: 80
  {{- if .Values.api.additionalDomain }}
  - host: {{ .Values.api.additionalDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "ifrcgo-helm.fullname" . }}-api
            port:
              number: 80
  {{- end }}
{{- end }}
