kind: Secret
apiVersion: v1
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-api-secret
  labels:
    component: api-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.env.DJANGO_SECRET_KEY }}
  # DJANGO_DB_NAME: {{ .Values.env.DJANGO_DB_NAME }}
  DJANGO_DB_USER: {{ .Values.env.DJANGO_DB_USER }}
  DJANGO_DB_PASS: {{ .Values.env.DJANGO_DB_PASS }}
  DJANGO_DB_HOST: {{ .Values.env.DJANGO_DB_HOST }}
  DJANGO_DB_PORT: {{ .Values.env.DJANGO_DB_PORT }}
  AZURE_STORAGE_ACCOUNT: {{ .Values.env.AZURE_STORAGE_ACCOUNT }}
  AZURE_STORAGE_KEY: {{ .Values.env.AZURE_STORAGE_KEY }}
  EMAIL_API_ENDPOINT: {{ .Values.env.EMAIL_API_ENDPOINT }}
  EMAIL_HOST: {{ .Values.env.EMAIL_HOST }}
  EMAIL_PORT: {{ .Values.env.EMAIL_PORT }}
  EMAIL_USER: {{ .Values.env.EMAIL_USER }}
  EMAIL_PASS: {{ .Values.env.EMAIL_PASS }}
  TEST_EMAILS: {{ .Values.env.TEST_EMAILS }}
  AWS_TRANSLATE_ACCESS_KEY: {{ .Values.env.AWS_TRANSLATE_ACCESS_KEY }}
  AWS_TRANSLATE_SECRET_KEY: {{ .Values.env.AWS_TRANSLATE_SECRET_KEY }}
  AWS_TRANSLATE_REGION: {{ .Values.env.AWS_TRANSLATE_REGION }}
  CELERY_REDIS_URL: {{ .Values.env.CELERY_REDIS_URL }}
  MOLNIX_API_BASE: {{ .Values.env.MOLNIX_API_BASE }}
  MOLNIX_USERNAME: {{ .Values.env.MOLNIX_USERNAME }}
  MOLNIX_PASSWORD: {{ .Values.env.MOLNIX_PASSWORD }}
  ERP_API_ENDPOINT: {{ .Values.env.ERP_API_ENDPOINT }}
  ERP_API_SUBSCRIPTION_KEY: {{ .Values.env.ERP_API_SUBSCRIPTION_KEY }}
  FDRS_APIKEY: {{ .Values.env.FDRS_APIKEY }}
  FDRS_CREDENTIAL: {{ .Values.env.FDRS_CREDENTIAL }}
  HPC_CREDENTIAL: {{ .Values.env.HPC_CREDENTIAL }}
  APPLICATION_INSIGHTS_INSTRUMENTATION_KEY: {{ .Values.env.APPLICATION_INSIGHTS_INSTRUMENTATION_KEY }}
  ELASTIC_SEARCH_HOST: {{ .Values.env.ELASTIC_SEARCH_HOST }}
  GO_FTPHOST: {{ .Values.env.GO_FTPHOST }}
  GO_FTPUSER: {{ .Values.env.GO_FTPUSER }}
  GO_FTPPASS: {{ .Values.env.GO_FTPPASS }}
  GO_DBPASS: {{ .Values.env.GO_DBPASS }}
