apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-secret-api-cert
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.API_TLS_CRT | quote}}
  tls.key: {{ .Values.secrets.API_TLS_KEY | quote}}
