{{- if .Values.api.tls.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-secret-api-cert
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.API_TLS_CRT | quote}}
  tls.key: {{ .Values.secrets.API_TLS_KEY | quote}}


---

{{- if .Values.api.additionalDomain }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-secret-api-additional-domain-cert
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.API_ADDITIONAL_DOMAIN_TLS_CRT | quote}}
  tls.key: {{ .Values.secrets.API_ADDITIONAL_DOMAIN_TLS_KEY | quote}}
{{- end }}

{{- end }}
