apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-secret-api
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.API_TLS_CRT | quote}}
  tls.key: {{ .Values.secrets.API_TLS_KEY | quote}}

---

{{- if .Values.api.additionalDomain }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-secret-api-additional-domain
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.API_ADDITIONAL_DOMAIN_TLS_CRT | quote}}
  tls.key: {{ .Values.secrets.API_ADDITIONAL_DOMAIN_TLS_KEY | quote}}
{{- end }}