# Generated by Django 5.2.17 on 2026-09-20 05:21

import django.db.migrations.operations.special
from django.db import migrations, models
import hashlib


def _0009__fill_text_hash(apps, schema_editor):
    TranslationCache = apps.get_model('lang', 'TranslationCache')
    for obj in TranslationCache.objects.all():
        if not obj.text_hash:
            obj.text_hash = hashlib.sha256(obj.text.encode('utf-8')).hexdigest()
            obj.save(update_fields=['text_hash'])
    print(' Hash field is populated in lang_translationcache.')

def _0009__fill_last_used(apps, schema_editor):
    TranslationCache = apps.get_model('lang', 'TranslationCache')
    TranslationCache.objects.update(last_used=models.F('created_at'))


class Migration(migrations.Migration):

    replaces = [('lang', '0001_initial'), ('lang', '0002_auto_20200603_0613'), ('lang', '0003_auto_20200610_0911'), ('lang', '0004_auto_20200616_0713'), ('lang', '0005_string_page_name'), ('lang', '0006_alter_string_unique_together'), ('lang', '0007_translationcache'), ('lang', '0008_translationcache_table_field'), ('lang', '0009_remove_translationcache_lang_transl_text_4a497b_idx_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='key')),
                ('value', models.TextField(verbose_name='value')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], max_length=8, verbose_name='language')),
                ('hash', models.CharField(blank=True, max_length=32, null=True, verbose_name='hash')),
                ('page_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Page name')),
            ],
            options={
                'unique_together': {('language', 'page_name', 'key')},
                'verbose_name': 'String',
                'verbose_name_plural': 'Strings',
            },
        ),
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source_language', models.CharField(max_length=16)),
                ('dest_language', models.CharField(max_length=16)),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table_field', models.CharField(blank=True, default='', max_length=128)),
                ('other_fields', models.BooleanField(default=False)),
                ('num_calls', models.IntegerField(default=0)),
                ('text_hash', models.CharField(max_length=64)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['text_hash', 'source_language', 'dest_language'], name='lang_transl_text_ha_7b6786_idx')],
                'unique_together': {('text', 'source_language', 'dest_language')},
            },
        ),
        migrations.RunPython(
            code=_0009__fill_text_hash,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=_0009__fill_last_used,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
