# Generated by Django 4.2.16 on 2024-10-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="String",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("es", "Spanish"), ("fr", "French"), ("ar", "Arabic")],
                        max_length=8,
                        verbose_name="language",
                    ),
                ),
                ("key", models.CharField(max_length=255, verbose_name="key")),
                ("hash", models.CharField(blank=True, max_length=32, null=True, verbose_name="hash")),
                ("value", models.TextField(verbose_name="value")),
                ("page_name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Page name")),
            ],
            options={
                "verbose_name": "String",
                "verbose_name_plural": "Strings",
                "unique_together": {("language", "page_name", "key")},
            },
        ),
    ]
