# Generated by Django 4.2.19 on 2025-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lang", "0006_alter_string_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationCache",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("source_language", models.CharField(max_length=16)),
                ("dest_language", models.CharField(max_length=16)),
                ("translated_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["text", "source_language", "dest_language"], name="lang_transl_text_4a497b_idx")
                ],
                "unique_together": {("text", "source_language", "dest_language")},
            },
        ),
    ]
