# Generated by Django 4.2.19 on 2025-08-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lang", "0007_translationcache"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationcache",
            name="table_field",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="translationcache",
            name="other_fields",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="translationcache",
            name="num_calls",
            field=models.IntegerField(default=0),
        ),
    ]
