# Generated by Django 4.2.19 on 2025-08-11 08:18

import hashlib

from django.db import migrations, models


def fill_text_hash(apps, schema_editor):
    TranslationCache = apps.get_model("lang", "TranslationCache")
    for obj in TranslationCache.objects.all():
        if not obj.text_hash:
            obj.text_hash = hashlib.sha256(obj.text.encode("utf-8")).hexdigest()
            obj.save(update_fields=["text_hash"])
    print(" Hash field is populated in lang_translationcache.")


def fill_last_used(apps, schema_editor):
    TranslationCache = apps.get_model("lang", "TranslationCache")
    TranslationCache.objects.update(last_used=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("lang", "0008_translationcache_table_field"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="translationcache",
            name="lang_transl_text_4a497b_idx",
        ),
        migrations.AddField(
            model_name="translationcache",
            name="text_hash",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translationcache",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="translationcache",
            index=models.Index(fields=["text_hash", "source_language", "dest_language"], name="lang_transl_text_ha_7b6786_idx"),
        ),
        migrations.RunPython(fill_text_hash, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(fill_last_used, reverse_code=migrations.RunPython.noop),
    ]
