# Generated by Django 2.2.27 on 2022-03-02 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_update', '0002_auto_20220228_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashUpdateShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('donor_groups', models.ManyToManyField(blank=True, null=True, to='flash_update.DonorGroup')),
                ('donors', models.ManyToManyField(blank=True, null=True, to='flash_update.Donors')),
                ('flash_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_update_share', to='flash_update.FlashUpdate')),
            ],
        ),
    ]
