# Generated by Django 2.2.27 on 2022-03-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_update', '0004_auto_20220303_0633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donors',
            options={'verbose_name': 'donor'},
        ),
    ]
