# Generated by Django 2.2.27 on 2022-03-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flash_update", "0005_auto_20220303_0834"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flashemailsubscriptions",
            options={"verbose_name": "flash email subscription"},
        ),
    ]
