# Generated by Django 2.2.27 on 2022-03-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_update', '0007_auto_20220303_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashupdate',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='flash_update/documents/', verbose_name='file'),
        ),
    ]
