# Generated by Django 2.2.28 on 2022-08-05 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flash_update", "0010_auto_20220607_1157"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcountrydistrict",
            name="flash_update",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flash_country_district",
                to="flash_update.FlashUpdate",
                verbose_name="Flash update",
            ),
        ),
    ]
