# Generated by Django 4.2.15 on 2024-09-03 09:37

from django.db import migrations, models
import flash_update.models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_update', '0012_auto_20230410_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashgraphicmap',
            name='file',
            field=models.FileField(upload_to=flash_update.models.flash_map_upload_to, verbose_name='file'),
        ),
    ]
