# Generated by Django 4.2.15 on 2024-09-03 09:42

from django.db import migrations, models
import flash_update.models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_update', '0013_alter_flashgraphicmap_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashupdate',
            name='extracted_file',
            field=models.FileField(blank=True, null=True, upload_to=flash_update.models.flash_extracted_file_upload_to, verbose_name='extracted file'),
        ),
    ]
