# Generated by Django 4.2.16 on 2024-10-08 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("deployments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationGUID",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_guid",
                    models.CharField(
                        help_text="Can be used to do a GET request to check on the email sender API side.", max_length=200
                    ),
                ),
                ("email_type", models.CharField(blank=True, max_length=600, null=True)),
                ("to_list", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SurgeAlert",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "atype",
                    models.IntegerField(
                        choices=[
                            (0, "fact"),
                            (1, "SIMS"),
                            (2, "ERU"),
                            (3, "DHEOPS"),
                            (4, "HEOPS"),
                            (5, "surge"),
                            (6, "rapid response"),
                        ],
                        default=0,
                        verbose_name="alert type",
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[(0, "information"), (1, "deployment"), (2, "alert"), (3, "shelter"), (4, "stand down")],
                        default=0,
                        verbose_name="category",
                    ),
                ),
                ("operation", models.CharField(max_length=100, verbose_name="operation")),
                ("operation_en", models.CharField(max_length=100, null=True, verbose_name="operation")),
                ("operation_es", models.CharField(max_length=100, null=True, verbose_name="operation")),
                ("operation_fr", models.CharField(max_length=100, null=True, verbose_name="operation")),
                ("operation_ar", models.CharField(max_length=100, null=True, verbose_name="operation")),
                ("message", models.TextField(verbose_name="message")),
                ("message_en", models.TextField(null=True, verbose_name="message")),
                ("message_es", models.TextField(null=True, verbose_name="message")),
                ("message_fr", models.TextField(null=True, verbose_name="message")),
                ("message_ar", models.TextField(null=True, verbose_name="message")),
                ("deployment_needed", models.BooleanField(default=False, verbose_name="deployment needed")),
                ("is_private", models.BooleanField(default=False, verbose_name="is private?")),
                ("molnix_id", models.IntegerField(blank=True, null=True)),
                ("opens", models.DateTimeField(blank=True, null=True)),
                ("closes", models.DateTimeField(blank=True, null=True)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(verbose_name="created at")),
                (
                    "molnix_status",
                    models.IntegerField(
                        choices=[(0, "Open"), (1, "Stood Down"), (2, "Closed")], default=0, verbose_name="alert status"
                    ),
                ),
                (
                    "translation_module_original_language",
                    models.CharField(
                        choices=[("en", "English"), ("es", "Spanish"), ("fr", "French"), ("ar", "Arabic")],
                        default="en",
                        help_text="Language used to create this entity",
                        max_length=2,
                        verbose_name="Entity Original language",
                    ),
                ),
                (
                    "translation_module_skip_auto_translation",
                    models.BooleanField(
                        default=False,
                        help_text="Skip auto translation operation for this entity?",
                        verbose_name="Skip auto translation",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.event", verbose_name="event"
                    ),
                ),
                ("molnix_tags", models.ManyToManyField(blank=True, to="deployments.molnixtag")),
            ],
            options={
                "verbose_name": "Surge Alert",
                "verbose_name_plural": "Surge Alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stype", models.IntegerField(choices=[(0, "new"), (1, "edit")], default=0, verbose_name="subscription type")),
                (
                    "rtype",
                    models.IntegerField(
                        choices=[
                            (0, "event"),
                            (1, "appeal"),
                            (2, "field report"),
                            (3, "surge alert"),
                            (4, "country"),
                            (5, "region"),
                            (6, "disaster type"),
                            (7, "per due date"),
                            (8, "followed event"),
                            (9, "surge deployment messages"),
                            (10, "surge approaching end of mission"),
                            (11, "weekly digest"),
                            (12, "new emergencies"),
                            (13, "new operations"),
                            (14, "general announcements"),
                        ],
                        default=0,
                        verbose_name="record type",
                    ),
                ),
                ("lookup_id", models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name="lookup id")),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "dtype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.disastertype",
                        verbose_name="disaster type",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.event", verbose_name="event"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.region",
                        verbose_name="region",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
    ]
