# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='dtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DisasterType'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Region'),
        ),
    ]
