# Generated by Django 2.0.12 on 2019-05-16 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190424_1508'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Event'),
        ),
    ]
