# Generated by Django 2.2.10 on 2020-06-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_subscription_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='surgealert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Surge Alert', 'verbose_name_plural': 'Surge Alerts'},
        ),
    ]
