# Generated by Django 2.2.13 on 2020-06-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20200618_0904'),
        ('notifications', '0004_auto_20200618_1017'),
    ]

    operations = [
    ]
