# Generated by Django 2.2.20 on 2021-08-18 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_surgealert_molnix_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgealert",
            name="country",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.Country", verbose_name="country"
            ),
        ),
    ]
