# Generated by Django 2.2.24 on 2021-11-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_surgealert_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgealert',
            name='is_stood_down',
            field=models.BooleanField(default=False, verbose_name='is stood down?'),
        ),
    ]
