# Generated by Django 3.2.23 on 2024-02-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0013_auto_20230410_0720"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgealert",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Open"), (1, "Stood Down"), (2, "Closed")], default=0, verbose_name="alert status"
            ),
        ),
    ]
