# Generated by Django 4.2.13 on 2024-07-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0015_rename_molnix_status_surgealert_molnix_status_old"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surgealert",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="surgealert",
            name="is_stood_down",
        ),
    ]
