# Generated by Django 4.2.30 on 2026-05-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0231_alter_export_export_type'),
        ('notifications', '0016_alertsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsubscription',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='alert_subscriptions_countries', to='api.country', verbose_name='Countries'),
        ),
    ]
