FABRIC_DB = "logistics_gold"
FABRIC_SCHEMA = "dbo"
# Format: [logistics_gold].[dbo].[<table>]

FABRIC_IMPORT_STAGES = [
    # DIM tables
    {
        "slug": "dim-agreement-line",
        "table": "dim_agreement_line",
        "model": "DimAgreementLine",
        "page_key": "agreement_line_id",
        "pagination": "keyset",
    },
    {"slug": "dim-appeal", "table": "dim_appeal", "model": "DimAppeal", "page_key": "id", "pagination": "keyset"},
    {"slug": "dim-buyer-group", "table": "dim_buyer_group", "model": "DimBuyerGroup", "page_key": "code", "pagination": "keyset"},
    {"slug": "dim-consignment", "table": "dim_consignment", "model": "DimConsignment", "page_key": "id", "pagination": "keyset"},
    {
        "slug": "dim-delivery-mode",
        "table": "dim_delivery_mode",
        "model": "DimDeliveryMode",
        "page_key": "id",
        "pagination": "keyset",
    },
    {"slug": "dim-donor", "table": "dim_donor", "model": "DimDonor", "page_key": "donor_code", "pagination": "row_number"},
    {
        "slug": "dim-inventory-item",
        "table": "dim_inventory_item",
        "model": "DimInventoryItem",
        "page_key": "id",
        "pagination": "keyset",
    },
    {
        "slug": "dim-inventory-item-status",
        "table": "dim_inventory_item_status",
        "model": "DimInventoryItemStatus",
        "page_key": "id",
        "pagination": "keyset",
    },
    {
        "slug": "dim-inventory-module",
        "table": "dim_inventory_module",
        "model": "DimInventoryModule",
        "page_key": "id",
        "pagination": "keyset",
    },
    {
        "slug": "dim-inventory-owner",
        "table": "dim_inventory_owner",
        "model": "DimInventoryOwner",
        "page_key": "id",
        "pagination": "keyset",
    },
    {
        "slug": "dim-inventory-transaction",
        "table": "dim_inventory_transaction",
        "model": "DimInventoryTransaction",
        "page_key": "id",
        "pagination": "keyset",
    },
    {
        "slug": "dim-inventory-transaction-line",
        "table": "dim_inventory_transaction_line",
        "model": "DimInventoryTransactionLine",
        "page_key": "id",
        "pagination": "keyset",
    },
    {
        "slug": "dim-inventory-transaction-origin",
        "table": "dim_inventory_transaction_origin",
        "model": "DimInventoryTransactionOrigin",
        "page_key": "id",
        "pagination": "keyset",
    },
    {"slug": "dim-item-batch", "table": "dim_item_batch", "model": "DimItemBatch", "page_key": "id", "pagination": "keyset"},
    {"slug": "dim-location", "table": "dim_location", "model": "DimLocation", "page_key": "id", "pagination": "keyset"},
    {
        "slug": "dim-logistics-location",
        "table": "dim_logistics_location",
        "model": "DimLogisticsLocation",
        "page_key": "id",
        "pagination": "keyset",
    },
    {
        "slug": "dim-packing-slip-line",
        "table": "dim_packing_slip_line",
        "model": "DimPackingSlipLine",
        "page_key": "id",
        "pagination": "keyset",
    },
    {"slug": "dim-product", "table": "dim_product", "model": "DimProduct", "page_key": "id", "pagination": "keyset"},
    {
        "slug": "dim-product-category",
        "table": "dim_product_category",
        "model": "DimProductCategory",
        "page_key": "category_code",
        "pagination": "keyset",
    },
    {
        "slug": "dim-product-receipt-line",
        "table": "dim_product_receipt_line",
        "model": "DimProductReceiptLine",
        "page_key": "id",
        "pagination": "keyset",
    },
    {"slug": "dim-project", "table": "dim_project", "model": "DimProject", "page_key": "id", "pagination": "row_number"},
    {
        "slug": "dim-sales-order-line",
        "table": "dim_sales_order_line",
        "model": "DimSalesOrderLine",
        "page_key": "id",
        "pagination": "keyset",
    },
    {"slug": "dim-site", "table": "dim_site", "model": "DimSite", "page_key": "id", "pagination": "keyset"},
    {"slug": "dim-vendor", "table": "dim_vendor", "model": "DimVendor", "page_key": "code", "pagination": "keyset"},
    {
        "slug": "dim-vendor-contact",
        "table": "dim_vendor_contact",
        "model": "DimVendorContact",
        "page_key": "id",
        "pagination": "keyset",
    },
    {
        "slug": "dim-vendor-contact-email",
        "table": "dim_vendor_contact_email",
        "model": "DimVendorContactEmail",
        "page_key": "id",
        "pagination": "keyset",
    },
    {
        "slug": "dim-vendor-physical-address",
        "table": "dim_vendor_physical_address",
        "model": "DimVendorPhysicalAddress",
        "page_key": "id",
        "pagination": "row_number",
    },
    {"slug": "dim-warehouse", "table": "dim_warehouse", "model": "DimWarehouse", "page_key": "id", "pagination": "keyset"},
    # FCT tables
    {
        "slug": "fct-agreement",
        "table": "fct_agreement",
        "model": "FctAgreement",
        "page_key": "agreement_id",
        "pagination": "keyset",
    },
    {
        "slug": "fct-product-receipt",
        "table": "fct_product_receipt",
        "model": "FctProductReceipt",
        "page_key": "id",
        "pagination": "keyset",
    },
    {
        "slug": "fct-purchase-order",
        "table": "fct_purchase_order",
        "model": "FctPurchaseOrder",
        "page_key": "id",
        "pagination": "keyset",
    },
    {"slug": "fct-sales-order", "table": "fct_sales_order", "model": "FctSalesOrder", "page_key": "id", "pagination": "keyset"},
    # Derived / special
    {
        "slug": "product-category-hierarchy-flattened",
        "table": "product_category_hierarchy_flattened",
        "model": "ProductCategoryHierarchyFlattened",
        "page_key": "product_category",
        "pagination": "keyset",
    },
]
