from decimal import Decimal

from django.db.models import Count, Sum
from rest_framework import views
from rest_framework.response import Response

from api.esconnection import ES_CLIENT
from api.indexes import STOCK_INVENTORY_INDEX_NAME
from api.models import StockInventory
from api.utils import derive_country_iso3, fetch_goadmin_maps

MAP_WAREHOUSE_IDS = [
    "AE1DUB002",
    "AR1BUE002",
    "AU1BRI003",
    "ES1LAS001",
    "GT1GUA001",
    "HN1COM002",
    "MY1SEL001",
    "PA1ARR001",
    "TR1ISTA02",
]


class StockInventoryView(views.APIView):
    """List stock inventory rows generated by the PySpark transformation."""

    permission_classes = []

    # ------------------------------------------------------------------
    # Elasticsearch path (primary)
    # ------------------------------------------------------------------
    @staticmethod
    def _es_list(request):
        if ES_CLIENT is None:
            return None

        region_q = request.query_params.get("region", "").strip()
        region_list = [r.strip() for r in region_q.split(",") if r.strip()]
        country_iso3_raw = request.query_params.get("country_iso3") or ""
        country_iso3_list = [c.strip().upper() for c in country_iso3_raw.split(",") if c.strip()]
        product_category_q = request.query_params.get("product_category", "").strip()
        item_name_q = request.query_params.get("item_name", "").strip()
        warehouse_ids_raw = request.query_params.get("warehouse_ids", "").strip()
        warehouse_ids = [w.strip() for w in warehouse_ids_raw.split(",") if w.strip()]
        sort_field = request.query_params.get("sort", "")
        sort_order = request.query_params.get("order", "desc")

        try:
            page = max(int(request.query_params.get("page", 1)), 1)
        except Exception:
            page = 1
        try:
            page_size = int(request.query_params.get("page_size", 50))
        except Exception:
            page_size = 50
        page_size = min(max(page_size, 1), 1000)

        filters = []
        if region_list:
            filters.append({"terms": {"region": region_list}})
        if country_iso3_list:
            filters.append({"terms": {"country_iso3": country_iso3_list}})
        if product_category_q:
            filters.append({"term": {"product_category": product_category_q}})
        if item_name_q:
            filters.append({"term": {"item_name.raw": item_name_q}})
        if warehouse_ids:
            filters.append({"terms": {"warehouse_id": warehouse_ids}})
        else:
            filters.append({"terms": {"warehouse_id": MAP_WAREHOUSE_IDS}})

        body = {
            "query": {"bool": {"filter": filters}} if filters else {"match_all": {}},
            "from": (page - 1) * page_size,
            "size": page_size,
        }

        allowed_sorts = {
            "warehouse_id",
            "warehouse",
            "warehouse_country",
            "region",
            "product_category",
            "item_name",
            "quantity",
            "unit_measurement",
        }
        if sort_field in allowed_sorts:
            es_sort_field = sort_field + ".raw" if sort_field in ("warehouse", "warehouse_country", "item_name") else sort_field
            body["sort"] = [{es_sort_field: {"order": sort_order.lower() if sort_order.lower() in ("asc", "desc") else "desc"}}]

        try:
            resp = ES_CLIENT.search(index=STOCK_INVENTORY_INDEX_NAME, body=body)
        except Exception:
            return None

        hits = resp.get("hits", {})
        total_hits = hits.get("total", {}).get("value", 0) if isinstance(hits.get("total"), dict) else hits.get("total", 0)
        rows = []
        for hit in hits.get("hits", []):
            src = hit["_source"]
            qty = src.get("quantity")
            rows.append(
                {
                    "id": str(src.get("id", hit["_id"])),
                    "warehouse_id": src.get("warehouse_id"),
                    "warehouse": src.get("warehouse"),
                    "warehouse_country": src.get("warehouse_country"),
                    "country": src.get("country"),
                    "country_iso3": src.get("country_iso3"),
                    "region": src.get("region"),
                    "product_category": src.get("product_category"),
                    "item_name": src.get("item_name"),
                    "quantity": str(qty) if qty is not None else None,
                    "unit_measurement": src.get("unit_measurement"),
                    "catalogue_link": src.get("catalogue_link"),
                }
            )

        return Response({"results": rows, "total": total_hits, "page": page, "page_size": page_size})

    # ------------------------------------------------------------------
    # Database fallback path
    # ------------------------------------------------------------------
    @staticmethod
    def _db_list(request):
        region_q = request.query_params.get("region", "").strip()
        region_list = [r.strip() for r in region_q.split(",") if r.strip()]
        country_iso3_raw = request.query_params.get("country_iso3") or ""
        country_iso3_list = [c.strip().upper() for c in country_iso3_raw.split(",") if c.strip()]
        product_category_q = request.query_params.get("product_category", "").strip()
        item_name_q = request.query_params.get("item_name", "").strip()
        warehouse_ids_raw = request.query_params.get("warehouse_ids", "").strip()
        warehouse_ids = [w.strip() for w in warehouse_ids_raw.split(",") if w.strip()]
        sort_field = request.query_params.get("sort", "")
        sort_order = request.query_params.get("order", "desc")

        try:
            page = max(int(request.query_params.get("page", 1)), 1)
        except Exception:
            page = 1
        try:
            page_size = int(request.query_params.get("page_size", 50))
        except Exception:
            page_size = 50
        page_size = min(max(page_size, 1), 1000)

        queryset = StockInventory.objects.all()

        if region_list:
            queryset = queryset.filter(region__in=region_list)
        if product_category_q:
            queryset = queryset.filter(product_category__iexact=product_category_q)
        if item_name_q:
            queryset = queryset.filter(item_name__iexact=item_name_q)
        if warehouse_ids:
            queryset = queryset.filter(warehouse_id__in=warehouse_ids)
        else:
            queryset = queryset.filter(warehouse_id__in=MAP_WAREHOUSE_IDS)

        allowed_sorts = {
            "warehouse_id": "warehouse_id",
            "warehouse": "warehouse",
            "warehouse_country": "warehouse_country",
            "region": "region",
            "product_category": "product_category",
            "item_name": "item_name",
            "quantity": "quantity",
            "unit_measurement": "unit_measurement",
        }
        sort_db_field = allowed_sorts.get(sort_field)
        if sort_db_field:
            if sort_order.lower() == "asc":
                queryset = queryset.order_by(sort_db_field)
            else:
                queryset = queryset.order_by(f"-{sort_db_field}")

        try:
            iso2_to_iso3, iso3_to_country_name, _ = fetch_goadmin_maps()
        except Exception:
            iso2_to_iso3, iso3_to_country_name = {}, {}

        rows = []
        for stock in queryset.iterator():
            country_iso3 = derive_country_iso3(stock.warehouse_id, iso2_to_iso3, "")
            if country_iso3_list and country_iso3 not in country_iso3_list:
                continue

            country_name = iso3_to_country_name.get(country_iso3, "") if country_iso3 else stock.warehouse_country
            rows.append(
                {
                    "id": str(stock.pk),
                    "warehouse_id": stock.warehouse_id,
                    "warehouse": stock.warehouse,
                    "warehouse_country": stock.warehouse_country,
                    "country": country_name,
                    "country_iso3": country_iso3,
                    "region": stock.region,
                    "product_category": stock.product_category,
                    "item_name": stock.item_name,
                    "quantity": str(stock.quantity) if stock.quantity is not None else None,
                    "unit_measurement": stock.unit_measurement,
                    "catalogue_link": stock.catalogue_link,
                }
            )

        total_hits = len(rows)
        start_idx = (page - 1) * page_size
        end_idx = start_idx + page_size
        paginated_rows = rows[start_idx:end_idx]

        return Response(
            {
                "results": paginated_rows,
                "total": total_hits,
                "page": page,
                "page_size": page_size,
            }
        )

    def get(self, request):
        if request.query_params.get("distinct") == "1":
            return self._distinct_options(request)
        es_response = self._es_list(request)
        if es_response is not None:
            return es_response
        return self._db_list(request)

    @staticmethod
    def _distinct_options(request):
        # Return distinct filter options, optionally filtered by query params
        qs = StockInventory.objects.all()

        region_q = request.query_params.get("region", "").strip()
        region_list = [r.strip() for r in region_q.split(",") if r.strip()]
        country_iso3_raw = request.query_params.get("country_iso3") or ""
        country_iso3_list = [c.strip().upper() for c in country_iso3_raw.split(",") if c.strip()]
        product_category_q = request.query_params.get("product_category", "").strip()

        if region_list:
            qs = qs.filter(region__in=region_list)
        if product_category_q:
            qs = qs.filter(product_category__iexact=product_category_q)

        # If caller requested filtering by country iso3, we need to derive iso3
        # from warehouse_id using goadmin maps, because `country_iso3` is not
        # stored on the StockInventory model.
        try:
            iso2_to_iso3, _, _ = fetch_goadmin_maps()
        except Exception:
            iso2_to_iso3 = {}

        regions = set()
        countries = set()
        item_groups = set()
        item_names = set()

        for stock in qs.iterator():
            # derive country iso3 from warehouse id
            country_iso3 = derive_country_iso3(getattr(stock, 'warehouse_id', ''), iso2_to_iso3, "")
            if country_iso3_list and country_iso3 not in country_iso3_list:
                continue

            if stock.region:
                regions.add(stock.region)
            if stock.warehouse_country:
                countries.add(stock.warehouse_country)
            if stock.product_category:
                item_groups.add(stock.product_category)
            if stock.item_name:
                item_names.add(stock.item_name)

        return Response(
            {
                "regions": sorted([r for r in regions if r]),
                "countries": sorted([c for c in countries if c]),
                "item_groups": sorted([g for g in item_groups if g]),
                "item_names": sorted([n for n in item_names if n]),
            }
        )


class AggregatedStockInventoryView(views.APIView):
    """Return stock inventory aggregated by country for map bubbles."""

    permission_classes = []

    # ------------------------------------------------------------------
    # Elasticsearch path (primary)
    # ------------------------------------------------------------------
    @staticmethod
    def _es_aggregated(request):
        if ES_CLIENT is None:
            return None

        region_q = request.query_params.get("region", "").strip()
        region_list = [r.strip() for r in region_q.split(",") if r.strip()]
        country_iso3_raw = request.query_params.get("country_iso3") or ""
        country_iso3_list = [c.strip().upper() for c in country_iso3_raw.split(",") if c.strip()]
        product_category_q = request.query_params.get("product_category", "").strip()
        item_name_q = request.query_params.get("item_name", "").strip()
        warehouse_ids_raw = request.query_params.get("warehouse_ids", "").strip()
        warehouse_ids = [w.strip() for w in warehouse_ids_raw.split(",") if w.strip()]

        filters = []
        if region_list:
            filters.append({"terms": {"region": region_list}})
        if country_iso3_list:
            filters.append({"terms": {"country_iso3": country_iso3_list}})
        if product_category_q:
            filters.append({"term": {"product_category": product_category_q}})
        if item_name_q:
            filters.append({"term": {"item_name.raw": item_name_q}})
        if warehouse_ids:
            filters.append({"terms": {"warehouse_id": warehouse_ids}})

        body = {
            "size": 0,
            "query": {"bool": {"filter": filters}} if filters else {"match_all": {}},
            "aggs": {
                "by_country": {
                    "terms": {"field": "country_iso3", "size": 300},
                    "aggs": {
                        "total_quantity": {"sum": {"field": "quantity"}},
                        "warehouse_count": {"cardinality": {"field": "warehouse_id"}},
                        "country_name": {"terms": {"field": "country.raw", "size": 1}},
                        "region_name": {"terms": {"field": "region", "size": 1}},
                    },
                }
            },
        }

        try:
            resp = ES_CLIENT.search(index=STOCK_INVENTORY_INDEX_NAME, body=body)
        except Exception:
            return None

        buckets = resp.get("aggregations", {}).get("by_country", {}).get("buckets", [])
        results = []
        for bucket in buckets:
            iso3 = bucket["key"]
            country_buckets = bucket.get("country_name", {}).get("buckets", [])
            country_name = country_buckets[0]["key"] if country_buckets else ""
            region_buckets = bucket.get("region_name", {}).get("buckets", [])
            region_name = region_buckets[0]["key"] if region_buckets else ""

            results.append(
                {
                    "country_iso3": iso3,
                    "country": country_name,
                    "region": region_name,
                    "total_quantity": str(bucket.get("total_quantity", {}).get("value", 0)),
                    "warehouse_count": bucket.get("warehouse_count", {}).get("value", 0),
                }
            )

        return Response({"results": results})

    # ------------------------------------------------------------------
    # Database fallback path
    # ------------------------------------------------------------------
    @staticmethod
    def _db_aggregated(request):
        region_q = request.query_params.get("region", "").strip()
        region_list = [r.strip() for r in region_q.split(",") if r.strip()]
        country_iso3_raw = request.query_params.get("country_iso3") or ""
        country_iso3_list = [c.strip().upper() for c in country_iso3_raw.split(",") if c.strip()]
        product_category_q = request.query_params.get("product_category", "").strip()
        item_name_q = request.query_params.get("item_name", "").strip()
        warehouse_ids_raw = request.query_params.get("warehouse_ids", "").strip()
        warehouse_ids = [w.strip() for w in warehouse_ids_raw.split(",") if w.strip()]

        queryset = StockInventory.objects.all()
        if region_list:
            queryset = queryset.filter(region__in=region_list)
        if product_category_q:
            queryset = queryset.filter(product_category__iexact=product_category_q)
        if item_name_q:
            queryset = queryset.filter(item_name__iexact=item_name_q)
        if warehouse_ids:
            queryset = queryset.filter(warehouse_id__in=warehouse_ids)

        try:
            iso2_to_iso3, iso3_to_country_name, iso3_to_region_name = fetch_goadmin_maps()
        except Exception:
            iso2_to_iso3, iso3_to_country_name, iso3_to_region_name = {}, {}, {}

        totals_by_country = {}
        country_names = {}
        regions = {}
        warehouse_sets = {}

        for stock in queryset.iterator():
            country_iso3 = derive_country_iso3(stock.warehouse_id, iso2_to_iso3, "")
            if not country_iso3:
                continue

            if country_iso3_list and country_iso3 not in country_iso3_list:
                continue

            totals_by_country[country_iso3] = totals_by_country.get(country_iso3, Decimal(0)) + (stock.quantity or Decimal(0))
            country_names[country_iso3] = iso3_to_country_name.get(country_iso3, stock.warehouse_country or "")
            regions[country_iso3] = stock.region or iso3_to_region_name.get(country_iso3, "")

            if country_iso3 not in warehouse_sets:
                warehouse_sets[country_iso3] = set()
            warehouse_sets[country_iso3].add(stock.warehouse_id)

        results = []
        for iso3, total in totals_by_country.items():
            region_name = regions.get(iso3, "")
            if region_list and region_name and region_name.lower() not in [r.lower() for r in region_list]:
                continue

            results.append(
                {
                    "country_iso3": iso3,
                    "country": country_names.get(iso3, ""),
                    "region": region_name,
                    "total_quantity": format(total, "f"),
                    "warehouse_count": len(warehouse_sets.get(iso3, set())),
                }
            )

        return Response({"results": results})

    def get(self, request):
        es_response = self._es_aggregated(request)
        if es_response is not None:
            return es_response
        return self._db_aggregated(request)


class StockInventorySummaryView(views.APIView):
    """Return summary statistics for stock inventory."""

    permission_classes = []

    def get(self, request):
        try:
            low_stock_threshold = int(request.query_params.get("low_stock_threshold", 100))
        except (ValueError, TypeError):
            low_stock_threshold = 100

        qs = StockInventory.objects.all()
        total = qs.count()

        by_item_group = list(
            qs.values("product_category").annotate(count=Count("id"), total_quantity=Sum("quantity")).order_by("product_category")
        )

        low_stock_count = qs.filter(quantity__lte=low_stock_threshold).count()

        return Response(
            {
                "total": total,
                "by_item_group": [
                    {
                        "product_category": row["product_category"],
                        "count": row["count"],
                        "total_quantity": str(row["total_quantity"]) if row["total_quantity"] is not None else "0",
                    }
                    for row in by_item_group
                ],
                "low_stock": {
                    "threshold": low_stock_threshold,
                    "count": low_stock_count,
                },
            }
        )
