name: Flake8 check.

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  check:
    name: Flake8 check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Flake8 check
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          # NOTE: this needs to be the same as the job name
          checkName: 'Flake8 check'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
