{{- if .Values.playwright.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "ifrcgo-helm.fullname" . }}-playwright
  labels:
    app: {{ template "ifrcgo-helm.name" . }}
    component: playwright-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.playwright.containerPort }}
      targetPort: {{ .Values.playwright.containerPort }}
      nodePort: null
  selector:
    app: {{ template "ifrcgo-helm.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-playwright

{{- end }}
